-- Entity Behaviors
return {
	-- Doctor
    Doctor_attack = require 'src.entities.units.behaviors.npc.attack',
    Doctor_fall   = require 'src.entities.units.behaviors.npc.fall',
    Doctor_guard  = require 'src.entities.units.behaviors.npc.guard',
    Doctor_idle   = require 'src.entities.units.behaviors.npc.idle',
    Doctor_run    = require 'src.entities.units.behaviors.npc.run',
    Doctor_talk   = require 'src.entities.units.behaviors.npc.talk',
    Doctor_walk   = require 'src.entities.units.behaviors.npc.walk',
    -- Double
    Double_attack = require 'src.entities.units.behaviors.npc.attack',
    Double_fall   = require 'src.entities.units.behaviors.npc.fall',
    Double_guard  = require 'src.entities.units.behaviors.npc.guard',
    Double_idle   = require 'src.entities.units.behaviors.npc.idle',
    Double_run    = require 'src.entities.units.behaviors.npc.run',
    Double_talk   = require 'src.entities.units.behaviors.npc.talk',
    Double_walk   = require 'src.entities.units.behaviors.npc.walk',
    -- captain
    Captain_attack = require 'src.entities.units.behaviors.npc.attack',
    Captain_fall   = require 'src.entities.units.behaviors.npc.fall',
    Captain_guard  = require 'src.entities.units.behaviors.npc.guard',
    Captain_idle   = require 'src.entities.units.behaviors.npc.idle',
    Captain_run    = require 'src.entities.units.behaviors.npc.run',
    Captain_talk   = require 'src.entities.units.behaviors.npc.talk',
    Captain_walk   = require 'src.entities.units.behaviors.npc.walk',
    -- ensign
    Ensign_attack = require 'src.entities.units.behaviors.npc.attack',
    Ensign_fall   = require 'src.entities.units.behaviors.npc.fall',
    Ensign_guard  = require 'src.entities.units.behaviors.npc.guard',
    Ensign_idle   = require 'src.entities.units.behaviors.npc.idle',
    Ensign_run    = require 'src.entities.units.behaviors.npc.run',
    Ensign_talk   = require 'src.entities.units.behaviors.npc.talk',
    Ensign_walk   = require 'src.entities.units.behaviors.npc.walk',
    -- engineer
    Engineer_attack = require 'src.entities.units.behaviors.npc.attack',
    Engineer_fall   = require 'src.entities.units.behaviors.npc.fall',
    Engineer_guard  = require 'src.entities.units.behaviors.npc.guard',
    Engineer_idle   = require 'src.entities.units.behaviors.npc.idle',
    Engineer_run    = require 'src.entities.units.behaviors.npc.run',
    Engineer_talk   = require 'src.entities.units.behaviors.npc.talk',
    Engineer_walk   = require 'src.entities.units.behaviors.npc.walk',
    -- player
    Player_idle    = require 'src.entities.units.behaviors.player.idle',
    Player_die     = require 'src.entities.units.behaviors.player.die',
    Player_crouch  = require 'src.entities.units.behaviors.player.crouch',
    Player_standup = require 'src.entities.units.behaviors.player.standup',
    Player_jump    = require 'src.entities.units.behaviors.player.jump',
    Player_fall    = require 'src.entities.units.behaviors.player.fall',
    Player_run     = require 'src.entities.units.behaviors.player.run',
    Player_slide   = require 'src.entities.units.behaviors.player.slide',
    -- executioner
    Executioner_attack = require 'src.entities.units.behaviors.enemy.attack',
    Executioner_die    = require 'src.entities.units.behaviors.enemy.die',
    Executioner_fall   = require 'src.entities.units.behaviors.enemy.fall',
    Executioner_hurt   = require 'src.entities.units.behaviors.enemy.hurt',
    Executioner_idle   = require 'src.entities.units.behaviors.enemy.idle',
    Executioner_jump   = require 'src.entities.units.behaviors.enemy.jump',
    Executioner_run    = require 'src.entities.units.behaviors.enemy.run',
    Executioner_slide  = require 'src.entities.units.behaviors.enemy.slide',
    -- ghoul
    Ghoul_attack = require 'src.entities.units.behaviors.enemy.attack',
    Ghoul_die    = require 'src.entities.units.behaviors.enemy.die',
    Ghoul_fall   = require 'src.entities.units.behaviors.enemy.fall',
    Ghoul_hurt   = require 'src.entities.units.behaviors.enemy.hurt',
    Ghoul_idle   = require 'src.entities.units.behaviors.enemy.idle',
    Ghoul_jump   = require 'src.entities.units.behaviors.enemy.jump',
    Ghoul_run    = require 'src.entities.units.behaviors.enemy.run',
    Ghoul_slide  = require 'src.entities.units.behaviors.enemy.slide',
    -- dark mage
    DarkMage_attack = require 'src.entities.units.behaviors.enemy.attack',
    DarkMage_die    = require 'src.entities.units.behaviors.enemy.die',
    DarkMage_fall   = require 'src.entities.units.behaviors.enemy.fall',
    DarkMage_hurt   = require 'src.entities.units.behaviors.enemy.hurt',
    DarkMage_idle   = require 'src.entities.units.behaviors.enemy.idle',
    DarkMage_jump   = require 'src.entities.units.behaviors.enemy.jump',
    DarkMage_run    = require 'src.entities.units.behaviors.enemy.run',
    DarkMage_slide  = require 'src.entities.units.behaviors.enemy.slide',
    -- boss
    Boss_attack = require 'src.entities.units.behaviors.enemy.attack',
    Boss_die    = require 'src.entities.units.behaviors.enemy.die',
    Boss_fall   = require 'src.entities.units.behaviors.enemy.fall',
    Boss_hurt   = require 'src.entities.units.behaviors.enemy.hurt',
    Boss_idle   = require 'src.entities.units.behaviors.enemy.idle',
    Boss_jump   = require 'src.entities.units.behaviors.enemy.jump',
    Boss_run    = require 'src.entities.units.behaviors.enemy.run',
    Boss_slide  = require 'src.entities.units.behaviors.enemy.slide',
}