return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.3.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 30,
  height = 20,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 11,
  nextobjectid = 9,
  properties = {},
  tilesets = {
    {
      name = "tiles_spaceship",
      firstgid = 1,
      filename = "../tiles/tiles_spaceship.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 16,
      image = "../tiles/tiles_spaceship.png",
      imagewidth = 256,
      imageheight = 224,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 224,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      id = 1,
      name = "Background",
      x = 0,
      y = 0,
      width = 30,
      height = 20,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJy9lesKwyAMhX3n3e9jm2vp7rgN+rY7BQNZUCvV9seHqDWnSTxtoZQqLCUYgxkbDwOgwQRM2ZgSz4C3Z4/nembzWMqA7gjMW87ohBr59qhXUk/3rCt7pTPqXsDVU0djoWcXYAlWGXQf4BmoI2cDtmCXQdc4Ymi73rxTc7cqceaYSdc4dGtbgxu4B8531eU58/6t7doLfFt0fR6P1eX929t8Py265PGUOvP+ndT/HZfnaF16PPab1BWKTR536aX0PrZeIV/0pe26azTWmWNXgX66fJEL6WnD8pS+yN1XOZf/YfLFkHerL34JczM/"
    },
    {
      type = "tilelayer",
      id = 3,
      name = "Decorative (BG)",
      x = 0,
      y = 0,
      width = 30,
      height = 20,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo4B4MA+I5wDxXCh7PhAvoIO9yPbNgbIX0sFeZLt2IrmD1mARkt0wf9PD3oEK51EwCkbBKBhuAADUQRKl"
    },
    {
      type = "tilelayer",
      id = 4,
      name = "Walls",
      x = 0,
      y = 0,
      width = 30,
      height = 20,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt1FtOwkAYhuHZA8oWOEQUIxIV4crWggEXo4lywQY0kUXggYOwpK6Fd5I2+RnazsTijTjJk5mGtB8fM0Wp/RwhCjiwrOW1Ocef36esw5TcQxQta3ltzjfwMIhmufYzcvP2vcME7/gwnn/7i3117ie+Ep6fldtDF/1oluvAse804dkrS67LubD1Ncc3lg65+myY58JXm7nx7yIFCbkzzLFwyNX3DiMPeBb3yO/mGXzltk9ZuaPII54ScvV+tnCNNjrK/f0132OZ+4qXjFy9nyWUUUFVbZ73n+aO8Wbpe4Yj1HC8g756j8z9CdR23xPUcYqrHfR1uS/u28A5mjn7uvy/yr4XuMzZ93/8zbEGfQ6v4w=="
    },
    {
      type = "tilelayer",
      id = 5,
      name = "Platforms",
      x = 0,
      y = 0,
      width = 30,
      height = 20,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt080KQEAUhuGzZUM2lFyhf1fkahQRey7GW8bOguQsNF89ZTO9jZpNREpFMSoEWBEpqdGYrid6o91y79Z2bfcPXR+J6L+jUI53rN09Z7u2+8VSZHCU5SjgKrtahx4j5of/7835BQMm8/10d87v5fwuuQ=="
    },
    {
      type = "tilelayer",
      id = 6,
      name = "Decorative (FG)",
      x = 0,
      y = 0,
      width = 30,
      height = 20,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGwUABXiT2eiDeAMUbcahBB1uRMCMQM0ExM5I4NnP4kNibgHgzFG/BoQYdbEPCLEDMCsVsSOLEmDNcAQBgpg0R"
    },
    {
      type = "tilelayer",
      id = 7,
      name = "Foreground",
      x = 0,
      y = 0,
      width = 30,
      height = 20,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMArIA6FAHAbE4UTgCCraGwfEUUAcjQPHINFJVLY3HogTCOBEKtubDMQpRKhLp7K9qUCcRoS6TCLVjSQAABrDEAw="
    },
    {
      type = "objectgroup",
      id = 9,
      name = "Environment",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 256,
          width = 464,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 16,
          width = 16,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 16,
          width = 416,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 16,
          width = 16,
          height = 144,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 144,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 8,
      name = "Units",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 1,
          name = "Doctor",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 176,
          width = 80,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "Doctor",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 176,
          width = 80,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 10,
      name = "Events",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 8,
          name = "PlayerEnter",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 128,
          width = 80,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
