return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.3.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 30,
  height = 20,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 26,
  nextobjectid = 246,
  properties = {},
  tilesets = {
    {
      name = "strangemountains01",
      firstgid = 1,
      filename = "tiles/strangemountains01.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 64,
      image = "tiles/strangemountains01.png",
      imagewidth = 1024,
      imageheight = 1024,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 4096,
      tiles = {
        {
          id = 1678,
          objectGroup = {
            type = "objectgroup",
            id = 3,
            name = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            draworder = "index",
            properties = {},
            objects = {
              {
                id = 2,
                name = "",
                type = "",
                shape = "rectangle",
                x = 0,
                y = 0,
                width = 16,
                height = 16,
                rotation = 0,
                visible = true,
                properties = {}
              }
            }
          }
        }
      }
    },
    {
      name = "strangemountains02",
      firstgid = 4097,
      filename = "tiles/strangemountains02.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 64,
      image = "tiles/strangemountains02.png",
      imagewidth = 1024,
      imageheight = 1024,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 4096,
      tiles = {}
    },
    {
      name = "background",
      firstgid = 8193,
      filename = "tiles/background.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 32,
      image = "tiles/background.png",
      imagewidth = 512,
      imageheight = 512,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 1024,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      id = 21,
      name = "Background",
      x = 0,
      y = 0,
      width = 30,
      height = 20,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHl0+OPEAwAwOFbb7aNZdvesm1u2Ta3bJtbts0t3NWFq1Putuqqyzbe5/073g/P59+n37nsAQHnucBFAgniEpcJ5gpXucZ1QrjBTUIJI5wIIrnFbe5wl3vc5wEPieIRj3lCNE95xnNieMFLXvGaN7zlHe/5wEc+8ZkvfOUb3/nBT37xmz/8JVaOgIB/iE0c4hKP+CQgIYlITBKSkozkpCAlqUhNGtKSjvRkICOZyEwWspKNHOQkF7nJQ17ykZ8CFKQQhSlCUYpRnBKUpBSlKUNZylGeClSkEpWpQlWqUZ0a1KQWtalDXepRnwY0pBGNaUJTmtGcFrSkFa1pQ1va0Z4OdKQTnelCV7rRnR70pBe96UNf+tGfAQxkEIMZwlCGMZwRjGQUoxnDWMYxnglMZBKTmcJUpjGdGcxkFrOZw1zmMZ8FLGQRi1nCUpaxnBWsZBWrWcNa1rGeDWxkE5vZwla2sZ0d7GQXu9nDXvaxnwMc5BCHOcJRjnGcE5zkFKc5w1nOcZ4LXCSQIC5xmWCucJVrXCeEG9wklDDCiSCSW9zmDne5x30e8JAoHvGYJ0TzlGc8J4YXvOQVr3nDW97xng985BOf+cJXvvGdH/zkF7/5w19i5fQvsYlDXOIRnwQkJBGJSUJSkpGcFKQkFalJQ1rSkZ4MZCQTmclCVrKRg5zkIjd5yEs+8lOAghSiMEUoSjGKU4KSlKI0ZShLOcpTgYpUojJVqEo1qlODmtSiNnWoSz3q04CGNKIxTWhKM5rTgpa0ojVtaEs72tOBjnSiM13oSje604Oe9KI3fehLP/ozgIEMYjBDGMowhjOCkYxiNGMYyzjGM4GJTGIyU5jKNKYzg5nMYjZzmMs85rOAhSxiMUtYyjKWs4KVrGI1a1jLOtazgY1sYjNb2Mo2trODnexiN3vYyz72c4CDHOIwRzjKMY5zgpOc4jRnOMs5znOBiwQSxCUuE8wVrnKN64Rwg5uEEkY4EURyi9vc4S73uM8DHhLFIx7zhGie8oznxPCCl7ziNW94yzve84GPfOIzX/jKN77zg5/84jd/+Mt/zf+TfwGhD6ty"
    },
    {
      type = "tilelayer",
      id = 3,
      name = "Sharp Cliffs",
      x = 0,
      y = 0,
      width = 30,
      height = 20,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAG11dduE2kYBuBf9BZIjEvo7XwvYhVKeuI0OACyiwT3AaGnOi7A0pHgNpDoJZRUCB3EffDMwUiRFWs3WfFKj2zZM9/r39NC+H/pT4QwwCBDDDNCjt+ZpzXh/hMe84iHPGCxnfmNIRQoUuISl/nARz7xmS985Rvf+cEdFptJ+04xzQzveM8V/uEq17jODW5yi9sspneJH7qUZDKEeM3R8YvXPGvu71hz1JtIh7CRJCnSZCjPNr9tOzvYyS52s4eFJF5rVkcHnXTRTQ/lOWz+EY7Sy1/8zTEWkrg3p2OUPAWKlCjPNfOvc4Ob3OI2d1hIot6xmhDGdUwwyRTTzPCOWTM/8JFPfOYLX/nGd36wkO6ot8o5lMg4viRJkSZDLZtTIWxhK9vYzg52sovd7CHq/q/504bNerPmd9BJF930cJBDzNcdd8ztjj/7t9eTNoiumZzZo+QpUKTEsuoQlrOClaxiNWtYyzqqWM8GqqmhUqL/Nzamd1zHBJNMMc0MdWbsZR/7OUA9DTTSRDMttNJGO5US/b+xKveFRK3jS5IUaTL0mXGaM5zlHOe5wEX6GWCQIYYZoVJO+iLWrDero4NOuuimh4dmPOIxT3jKM57zgpeM8YrXvOEtlRJ1nqKPAb05HaPkKVCkxDLX2HJWsJJVrGYNa1lHFevZQDU1VMrc3jobjeuYYJIpppmhzoy97GM/B6ingUaaaKaFVtpoZ7784V4wtzdac2KT40uSFGky9JlxmjOc5RznucBF+hlgkCGGGWG+HLeOE2WyOjropItuevBMD57twTM+/LRP5Jn3z3nBS6L73Ste84a3xLmSCb2zbK4NvXfte69MTscoeQoUKXGJuC9+rXc+NNBIE9F52UIrbbSTJcplne/ZpPcXBZTVsw=="
    },
    {
      type = "tilelayer",
      id = 14,
      name = "Decoratives (BG)",
      x = 0,
      y = 0,
      width = 30,
      height = 20,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAFjYBgFoyEwGgKjITAaAqMhMBoCoyFA2xBQYcQ0XxYoJgfEMFoeixpMXaSJpADNjAbiGCCOBeI4LHQ8UIzaAAAl1gR1"
    },
    {
      type = "tilelayer",
      id = 12,
      name = "Cliffs",
      x = 0,
      y = 0,
      width = 30,
      height = 20,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAG91WlLG0Ecx/ExJhbBHBoVvOjz9l3UAwvm8CTW63n7LtIDrOawRTGeb0XweqJJTGLRd+P3JztlEVM2ge4fPszsZmZ+u7PJJmuMybZhgjkSDhnzJmDOuhACpzxVkFGt5Gq8dDptgPa6w5xd4RIceipdszvXrtus1XgZd9owA2+xyH0vwWtpDab9peN/0f3pOr/iGxJM1l7vYq/FXHdOhA2sM7+BuS5jzmkvcIkP5Ig714695/M/8Fo2U3larxwwJk5eP36hE0GEoM/dmWnO2bED9AfhtWyu1kuSncI88xderDHJ8RRmoX2wrca2UzY37NzvXcfr+/Wd9X9gB9oH2/6m307ZvUuQWwkYU0Uf/ncFCRDlR8mOwY+y+1wmT8827VOunqt++yn2Nu3D/tq91HPVb79AZtHH3By5eRRQhF+VJUjPtoKqz7kR9jmKGPyq5/slr4Iq7lBDHQ24z8/wTkkgiRTSmEWGi13GW/pDGMYIRjGG10q5Ed7nUcTQiz7E0Q/3+W3WyCGPAorYwT5rlLBBfxmfsIJVrGEdGbzje/seqgXWbqaHMd08c/3P3TLPtmX6FVSh9+oD6zzilH4JBzjEEY5xgn18Zr0vTu4W79c8Cg6973Vu0/HTOZ4m/yNumK9rsNnKrSHurKd78VJP0qV38A=="
    },
    {
      type = "tilelayer",
      id = 11,
      name = "Castle",
      x = 0,
      y = 0,
      width = 30,
      height = 20,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAFjYBgFoyEwGgKjITAaAqMhMBoCoyEwGgLUDAEACWAAAQ=="
    },
    {
      type = "tilelayer",
      id = 6,
      name = "Decoratives (MG)",
      x = 0,
      y = 0,
      width = 30,
      height = 20,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHt0TcOAkEMhWHXUC/LrpCAgnQgYgMUpAMRG6AgHYjYk27BfwC7ZKSV5klfY8seySPi4y/g5gJBSiSDEFlEiKElT72AotHXZqxanR0NNNFCGx1o6VLvoW/0tRmrNmXHDHMssMQKWtbUN9gafW3Gqp3ZccEVN9zxwL8TpPlfhMgiQgyfZF+glBMpo4IqanCRAe8MMcIYE7jIjnf2OOCIE1zkyTsvvPHBFz7JvsAPrOUdag=="
    },
    {
      type = "tilelayer",
      id = 1,
      name = "Platforms",
      x = 0,
      y = 0,
      width = 30,
      height = 20,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAFjYBgFoyEwGgKjITAaAqMhMBoCoyEwGgLUDAEACWAAAQ=="
    },
    {
      type = "tilelayer",
      id = 7,
      name = "Foreground",
      x = 0,
      y = 0,
      width = 30,
      height = 20,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHt0MsJgDAURNG312IszW8/gjag0W60CH97bwEGxUBWM3A2eYSBMVO0gBbQAlpAC2iBkAWy5P/vlr9datbDl4Xb+nDPA3p9XW/vBZ0lKtRoECMDPSMcJsyIkY2eHQdOXPiSGzooD7Q="
    },
    {
      type = "objectgroup",
      id = 9,
      name = "Environment",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 272,
          width = 432,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 115,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 64,
          width = 224,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 116,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 64,
          width = 16,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
