return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.3.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 60,
  height = 120,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 14,
  nextobjectid = 190,
  properties = {},
  tilesets = {
    {
      name = "strangemountains01",
      firstgid = 1,
      filename = "tiles/strangemountains01.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 64,
      image = "tiles/strangemountains01.png",
      imagewidth = 1024,
      imageheight = 1024,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 4096,
      tiles = {
        {
          id = 1678,
          objectGroup = {
            type = "objectgroup",
            id = 3,
            name = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            draworder = "index",
            properties = {},
            objects = {
              {
                id = 2,
                name = "",
                type = "",
                shape = "rectangle",
                x = 0,
                y = 0,
                width = 16,
                height = 16,
                rotation = 0,
                visible = true,
                properties = {}
              }
            }
          }
        }
      }
    },
    {
      name = "background",
      firstgid = 4097,
      filename = "tiles/background.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 32,
      image = "tiles/background.png",
      imagewidth = 512,
      imageheight = 512,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 1024,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      id = 1,
      name = "Background",
      x = 0,
      y = 0,
      width = 60,
      height = 120,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHt2nXsVfX/wHHsDkIUFQRJUeluQZTu7pbublBKurtDQbq7u7tLQqVLAaV+D/5gc+zrxn5zh82dPx4759ydz57vcz6ve+/u3X327QgRnuPZcBveh3AOwudB+DoQvg48xdeBSNqRicI7ROVd3iMa7/MBHxKdGHxETP6N97Gg+8msOzkpSEkqUpOGtKQjPRnISCYyk4VYfExs4hCXeMQnAZ+QkE/5jM9JRGKSkJSg+4U0C1OEohSjOCUoSSlKU4aylKM8FfiCrGTjS7LzFV+Tg5zkIjd5yEs+8lOAggTdb6jZiMY0oSnNaE4LWtKK1rShLe1oT0UqUZkqVKUa31CdGtSkFrWpQ13qUZ8GBN3vp9mfAQxkEIMZwlCGMZwRjGQUoxlDBzryLd/Ric50oSvd+J7u9KAnvehNH/oSdH+25hzmMo/5LGAhi1jMEpayjOWsYCVjGcd4JjCRSfzAj0xmCj8xlWlMZwYzmUXQ/d2ae9jLPvZzgIMc4jBHOMoxjnOCk6xiNWtYyzrWs4GNbGIzW9jKNrazg53sIuj+dc0bRI3ofYib9m9x+2+P3bF/l3vc5wERnPuz7SlOc4az/MKv/MY5znOBi1ziMle4yjWC7key7sg8q/0cj677vb899oH9D4lODD4iJg/Pf/R3j7YvevwlXuYVXuU1XucN3uQt3iYiQfcfrTPc/u//X3hfwvvyv57X4VyEcxHEXDxsBNH5p3l+2v1/Wtd/7fGnfZ+D7gfde3xegu4H3Xta15vY61USkpKM5KQgJalITRrSko70ZCAjmchMFh5f/5MeB93Pb60FKEghClOEohSjOCUoSSlKU4aylKM8FXjS63v8vKD79ay1Pg1oSCMa04SmNKM5LWhJK1rThra0oz2PX8eTHgfd722tfehLP/ozgIEMYjBDGMowhjOCkYxiNGN40ut7/Lyg+zOsdSazmM0c5jKP+SxgIYtYzBKWsozlrGAlj1/Hkx4H3d9hrTvZxW72sJd97OcABznEYY5wlGMc5wQnedLre/y8oPtXrPUq17jODR59x3HT/i1u/+2xO/bvco/7PODhdzuPX8eTHgfd/7e+W3nS63v8vKfdf3w94fHT/TwV3v/w/j/8LBDOQTgH4Rz8954Hz/ztuf28/Rd4kZd4mVd4ldd4nTd4k7d4m4hEIjJReIeovMt7RON9PuBDohODj4hJ0P1Ymh8TmzjEJR7xScAnJORTPuNzEpGYJCQlGclJQUpSkZo0pCUd6clARjKRmSwE3f9CMyvZ+JLsfMXX5CAnuchNHvKSj/wUoCCFKEwRilKM4pSgJKUoTRnKUo7yVCDofkXNSlSmClWpxjdUpwY1qUVt6lCXetSnAQ1pRGOa0JRmNKcFLWlFa9rQlna0J+h+B82OfMt3dKIzXehKN76nOz3oSS9604e+9KM/AxjIIAYzhKEMYzgjGMkoRjOGoPtjNccxnglMZBI/8COTmcJPTGUa05nBTGYxmznMZR7zWcBCFrGYJSxlGctZwUqC7q/SXM0a1rKO9WxgI5vYzBa2so3t7GAnu9jNHvayj/0c4CCHOMwRjnKM45zgJEH3f9Y8xWnOcJZf+JXfOMd5LnCRS1zmCle5xnVu8Dt/cJNb3OZP/uIOd7nHfR7wb/8G5En6zzz8boLneJ4X+P/+BiOKv32HR9+PPPwNSDTe559+AxJ0P5a1fExs4hCXeMQnAZ+QkE/5jM9JRGKSkJRkJCcFKUlFatKQlnSkJwMZyURmshB0/wvNrGTjS7LzFV+Tg5zkIjd5yEs+8lOAghSiMEUoSjGKU4KSlKI0ZShLOcpTgaD7FTUrUZkqVKUa31CdGtSkFrWpQ13qUZ8GNKQRjWlCU5rRnBa0pBWtaUNb2tGeoPsdNDvyLd/Ric50oSvd+J7u9KAnvehNH/rSj/4MYCCDGMwQhjKM4YxgJKMYzRiC7o/VHMd4JjCRSfzAj0xmCj8xlWlMZwYzmcVs5jCXecxnAQtZxGKWsJRlLGcFKwm6v0pzNWtYyzrWs4GNbGIzW9jKNrazg53sYjd72Ms+9nOAgxziMEc4yjGOc4KTBN3/WfMUpznDWX7hV37jHOe5wEUucZkrXOUa17nB7/zBTW5xmz/5izvc5R73eUCESH6DaRtk/xnNZ3mO53mBF3mJl3mFV3mN13mDN3mLt4lIJCIThXeIyru8RzTe5wM+JDox+IiYBN2PpfkxsYlDXOIRnwR8QkI+5TM+JxGJSUJSkpGcFKQkFalJQ1rSkZ4MZCQTmclC0P0vNLOSjS/Jzld8TQ5ykovc5CEv+chPAQpSiMIUoSjFKE4JSlKK0pShLOUoTwWC7lfUrERlqlCVanxDdWpQk1rUpg51qUd9GtCQRjSmCU1pRnNa0JJWtKYNbWlHe4Lud9DsyLd8Ryc604WudON7utODnvSiN33oSz/6M4CBDGIwQxjKMIYzgpGMYjRjCLo/VnMc45nARCbxAz8ymSn8xFSmMZ0ZzGQWs5nDXOYxnwUsZBGLWcJSlrGcFawk6P4qzdWsYS3rWM8GNrKJzWxhK9vYzg52sovd7GEv+9jPAQ5yiMMc4SjHOM4JThJ0/2fNU5zmDGf5hV/5jXOc5wIXucRlrnCVa1znBr/zBze5xW3+5C/ucJd73OcBESJ7/7UNsv+M5rM8x/O8wIu8xMu8wqu8xuu8wZu8xdtEJBKRicI7ROVd3iMa7/MBHxKdGHxETILux9L8mNjEIS7xiE8CPiEhn/IZn5OIxCQhKclITgpSkorUpCEt6UhPBjKSicxkIej+F5pZycaXZOcrviYHOclFbvKQl3zkpwAFKURhilCUYhSnBCUpRWnKUJZylKcCQfcralaiMlWoSjW+oTo1qEktalOHutSjPg1oSCMa04SmNKM5LWhJK1rThra0oz1B9ztoduRbvqMTnelCV7rxPd3pQU960Zs+9KUf/RnAQAYxmCEMZRjDGcFIRjGaMQTdH6s5jvFMYCKT+IEfmcwUfmIq05jODGYyi9nMYS7zmM8CFrKIxSxhKctYzgpWEnR/leZq1rCWdaxnAxvZxGa2sJVtbGcHO9nFbvawl33s5wAHOcRhjnCUYxznBCcJuv+z5ilOc4az/MKv/MY5znOBi1ziMle4yjWuc4Pf+YOb3OI2f/IXd7jLPe7zgAhRvP/aBtl/eJ2h8B6EMxDOQDgD4QyEMxDOQDgD4QyEMxDOQDgD4QyEMxDOQDgD4QyEMxDOQDgD4QyEMxDOQDgD4QyEMxDOQDgD4QyEMxDOQDgD4QyEMxDOQDgD4QyEMxDOQDgD/90Z+D+xt4uh"
    },
    {
      type = "tilelayer",
      id = 3,
      name = "Decoratives (BG)",
      x = 0,
      y = 0,
      width = 60,
      height = 120,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtmOlOU1EURq+ijwNUKUMHiC8EFCnQCXJeiEEB6QQ5L4QjY0Hj2uI1J40kxn/sfDtZufSmP/qtfUayTCUDMiADMiADMiADMvCvBub54gKUoAwVqMIiLIG32iJQA5rQgjZ0YBt2wFudEKgLPejDAIZwCmfgra4JdAO3MII7uIfv8AO81fwz5i+UoAwVqMIiLIG32iJTA5rQgjZ0YBt2wFudkKkLPejDAIZwCmfgpSafZ9kUTEMBZqAIs1CCMlSgCh5qmRwrsAo1WIc6bEATWtCGDnioXXLswT4cwCEcwTH0oA8DGIKHOifHR/gEn+EbXEDhBXsTzxHcwT14qMkJ5i9MQwFmoAg18pZ4lqECVfBQy+RYgVWowTrUYQM2oQVt6ICH2iXHHuzDARzCERzDAj3u8xzAELxUiVxlsN6+Z55CeD2RhQbv6Hmg94ExELzkbZKrBbY2275rmd+Sr8s7eh7ofWAMuMnbI1cfuuS0dZm8Ed7c8PeriSwWYBq89PeWXCO4Ia+ty/TW8kZ6G+ltpLduslrP5pi382DrVL5WrZGRuRuZu5G56yrvFX29hiK9nYU5SMfxlLO81l/LWocN2IR3Np6Bc2bkvOmmv2lPj8h5DB9gjYzcHyL3iMh9wk3etKcX5LyEK8jXZG9jOe1p8SXzF+aAu0PkDhG5S/zq7RTz20OlPf2zNnO+YiwHxnJgLAfLyfPJ1hd++1ewu5/1NM9p98BLYK0KrFWBtSrs/c7L88kWe03G+fjh7sdczfegIu9mwdv5kbOEnaEe7n7kzfegOu/sHpivVU+2oY/8cNt30/XK6/kxjZ+uV+R1dxdKs9rf6R6UniHHv+flc74mp2OZtTh6yTeeI1+Ta8ldiL3Wbd7xNdnb+XG8v3YPMjhfuLsLjWe1z2vkNDg/ursL/S2vvfP2P+bHcubvPf6POc+mpwzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIwP8Z+Ambv+W7"
    },
    {
      type = "tilelayer",
      id = 4,
      name = "Castle",
      x = 0,
      y = 0,
      width = 60,
      height = 120,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHNms92XMdxxhFZWeUdkmMmW0vkACCIJAs8iiWvLZEXAEHaWcwL5BkCUTnZWRIvAIqMs5hHsaSs5YgElTjJIr/f5f2QYuPOAJAJynPOx+qurq6ur6v/zRDfvbO2tv+TtbX7YBfsgdT3bQPH4AQ8AetgA2yC22AL3AHqZ/QN7CNSV74c608pf/HO2uJzsHbB51+w9fOzP1tbew+8D26CW2AG1sEG2ASX+XxHDCf4fAKOwDFIXX7iFBjr92AX7IF9cB8cgAfgOZCTMlg2N/K9C9ePr8D3l/D5CHwM7oJ7oAO7YA/sg8t85PsB439YIBdh/OtgA2yC2+AIvXk7AeEVrh3t9qm8n1GvdinfhOv74L2frB1++87a4WfgI/CeEp168n/InBxid/gb+HwGPgdfgMegB0fgGJyAy3zC17WcWJVb4Esgr7pWE6/SfCv/C3TY9kAp1N8G+jCftV/aPobT++D38KncomfNH7IODpmbw3/C1yGYNb6evrv28z+g/2/wP+B/waqPfB3fGPUlHoLE6Nq1PeOY78T+YCzfKbq0LeOpn038uRfuwvUm+A/4VG7RP0Z/D9wC2RuJw3FeAPfaNj7/Fvwd+Huw6iPfHpsO6Eu4BpVy1Z/lbtS5DjzTHC98ldpU2C7nY2TKB2M/94q6DSB314F81KVex1EvjOd3Rd56lzGB+fkV+DX4B7DqI1+5hI8xy9f6SWnrR90RMmeaMSSP4ZzY9CPMvTZbo9S3frWTr1K+6Zd6+OauOMLGudNn5D24dsD95Jr+LW3/BlZ95Ot51YHEaEzb4HvaahyWY5P4U1fKK/WOckX8qHsKUlfar9VlrNwV1k/B4FNZ4Jwa76/Q/Rqs+shXX/E/o5/9heUWw3joe5BypHGnHJ+Rs9GXde3MUcqRVXeAjXrn/JOx7D3RC3TZuy8pk5+dfxWUfwtWfZzXIDE9RJexHfMBddssXwTGHmxW9deX8ynvLZBxq842fZ0yppwct4NT5Zl7knh32L877N8d9u/OKr5f4edr8ClwXHye4RecnX8NvuF8dB+5zxxP+ynethun89e2h1P1b3nkcTZmdNGHk3VjXadPdPG5DUfO5x3O5x3O55V8f0r/G+Aevhxrg/2/CW6DQ+quJfXy0L/vkn1s74OMV6VxaZv8Wj4A6qdg31Yff+r3aM+ZVXPboQ84p3Y4pwae3L+X4vt4jGcPnvvgPvgdPr8a40kMSs/XJyDjVRm7qbVpW+ZBLg+oL9NlDo4dD/jerbklP/N2HfNGW8l1jU/ym3PrGJ4n4AnImMrwqLInhg4oA+sV8aHOXMsxuioTx7DOnMtXmMvL8iboKT8Gke065j16ab63iGMGTuH5EnwPrFfUN/ZzxhfySHlKpr9tz7DdanymPXzhM3Ct/Mp5MeTUvGrP22zBe3Rh3i77yTj36O85s/HnzCW4DeRSkdhcq5aN3fboLYvwznpNPVL7lCMTx3fwPQKjfk597vkyjjEnL3Pz+gE63qCX+k5Z50KOiXNKjuO8dn+4LtUbk31iY7nW1cc2NsrWRl34us42wWg/8JOvfYBre1jjn1C/C1++Py0qn4vKPf2+J25huQL/GedMJh8z2oLY9RP28k175JRd+LrOPNNG24GffHvje4VhD2ct873xSnz1Gw6tnGqbYS+m2tr+qbtvU14m9fkSPkrvn77wK3zn9B9yzneqBd8jr8TV3Bv36HvOWGIYkzNh+D5ifHtAaZsyiG3qU/I29ubYfdO2p3/rd50+/SvM6TPs39SxnbMG5nxnnPM9ec5vA3N5XPbTEcd4Fsr9jK85MQ65noL6DlFv7FP9bGuhrZxdpykfjD6si9rH70Y9OmA8A986lvov0H8OPgOX5apdh++yfvQ/jC1f204YV1nfIda1q/3ULYO2wnNd3lujzJzaVvt6Pld+rue8e+U6zsWaZzX7eM6dNGcfX4q34/hmc4xPgWMLY9kGnmPPQfsOcX3WfsvOvB47x6jQn1An/wcgOqXzWOdSvjnPwvvn6Iz3n8FN5uB9wG9fA+dvV7w7HHPm2OAemFkH5kKk3r5D+rHN+B5SVl4W8am982q+o1Oqr3Ppe2MGOhDelsFwN3EvzbmX5ryvBr6fXcDX2C/KT32HPGcsUWO03JW4nYPsV23NoTbpGzml2/x/P+fu30e0fQrG9T7cTV/A83MAz4EvvHfWlnyM8Yfmx74VPfXZiOzR1JWu3Vq33E3onCf14Nz9+yF6vqdm3ob3F3fTnLtp/u3I970VfN0b7XloHMJ5eArMxR5Qqk9upiQxDrH2o0xdKd9at9xP6MreHc5oY+wZG8yT3xk6MOT/KmeWvtrzcPQ17C3Lcj0duXavxjnjnfmY4j6lc79O6atu1f079f7i3Jm3e3jJch6+67fnYeUrv9xJlntg3pNvc3bMXBiv5Rp3W77s26Ndb+Yk99M23Nr8P0bX7uFVfI2rnoeV7zZj5U5K/OZIGzkrPcflugXSd5nURztHB/SLb2W73uSbe+gh3Nr8X+Ue1pf5m4EOrLqTwkG+3dhPGRir6zv1KTmjXdQ5kn/m0LZ2vRlj7qFPGOMRyN2L/ZXel8a3DA9pk0NF4lWaT2N1vpxzdT246G7rsAni27q+HgB1rre0fa1vUOvfUP93QD/fW5d+X87wG0zFnzb3qEjduXCejMF1rbRtao4S55SMP9vMsTFkvaXN/Ma/Osv8brr2N6Dn7hGs6QXn9NnvHcvel/G5LH59V8Te2IT17ONurMdGOaUjvuFukUctT51FsTGGF+AU6Nc7GN8L+i/47rDgu8OC7w6LZedU9PYVNfb4xN/QFpsqw1cb86FUp6zoS31mGVv3p39PcAD2qd8H/r+56/YlcD/AYw7Hs++C9s3vk7TteKahW3A/Le4CvhsuPgLhtUzqRyTWxN6h64GyYkZdhO825Zzf8aF9D4j3NQx6dCe0+fuq+7XayN//+/L/1eE0Z5zXvgtyNi84J3bka67htwbPs9/tWMNX4ltjr3HUMjEMfO8gReqRsU29yh77I6BNhxTq5K9O/vo0z/0rm4Fv7iLW+4K1MfA116zfNdbx2e92vJ8vzXdZ/DP8TeEh+mNiCr8HjZ36/wTmKzZKOeovOstPio1+smf7cT3nLmLt7jDmDj52/vLdtbW/AtyfC95Ww+92fE+4NN9l8SeuSOMTW8B8pK60vgE2gWuyG9EjY2dZfer6zfq2/JQ281lhvjvwCJ58N9qhr1jUM/kya9k9nXGXxZ/2yG6Mtx9l6pHqWXPDeVTnKO1KbbKuY1Ol+awY8o3uQ3hyLu9gKxbfAb4bDb/b8d1oyC3fjVZ+EocxpBxpvlKOrHG15dj09PM8mo1o7aJfJeE2rGu47mzAj7U87J8OCYbviazlc98TWNMrP20sbd0zt9VN1Y09+lquOvXL2mIX+QhbuHp27czA1N38GL7t94TP/gi+t+lrjt1TiSMxr5La5iyz/0Hpb1vbt6O91fVwMcc5m+E9nNtVsn9f+73uZ2T2PfA+uFmyvE55A2yCdpy2bnzGnPjlbnzLkP53sLHf1ihdJ2lr+/a0ndPB1xzLzzxPgTX+2u/Qv4TPR+BjcBfks0thD+yDq8ZvbL4vhOUWbdzOl1Av/wdgao+syqN5noJrgLfk8Du03H4DOKfnn1spnyPKx+AEGO9V4vfeCofINtY9+NV34oORszyTb+c5/ZW5Y6fy+AjbKfT0E3VdS/P3/lM+LyifgpdgKv4aR1ueMbZQn/jbWF37vkufgC/BU5B+6Wuu49vyB2Aqh+q+XoIb6Dt8g8nfZQvloejf0C4b4yr6NtZTYsi7P2+szthGhHvd45/Q9mgJ6DfcP/Lr8S205e2R33nO/S7LvTRv+fo3tFfhtcy2jbW+sVy/8uoLwjvyOfF/RfvXSzBynN/Qxyu+Q3nsP6f/ud8puZfO8ZX/Mg5X0RvrDCT+yPvoDoBnlJyWwb7C9uwRz2W+C53xk1PLtx/b6XvuNx3PLfm1n6vwWmU7cGT8XZDzKlzTL7yU5v1L4D6XV21z/4uqc39Y30TKs3Lv4Ibu7Kzme9Pw/6RTnBPLHyuZ/yGOI6SxyqP1mfg9I3M+Ozf2tU1ZMaXLXVD59nAFw/jtWX1d+XUdGusLcArMxzK+2spFrtpa7kad5WCZDv2wtpPrY3xoq76D+9S7OrzbmH5oPRzym4vfCVtfs5GLtsbnGhjjHM6zlCP70a7OoW+FXeBcRfp9LPlFnjur30O3jC9xLjhfF8S9mAFiW7Rx/9A6/obcyXcbGLtrIqh/QxAu7nHba9sRdXMauU4ZnmKO7bmzut5NbeyswwVrbPEC0Pda+Ho/ifCP3HuXdxnwbxnDZaqN2IZ9ELmLr/DF/txZXe+mli9rbMHcLRhvgY+Bc2vzQ+uJ/SHxmR/mc4D3lW3H8Kx/y6guNrUtPMnNsEaI9ezc7uBL3K+d1a7lnNVt7Ptw3AO7oBPXsJ5zF8kncN2ewrf+LSNjn7XXtnpG5Hcj4h32tFzBkO+ps7rlK78K4nlj+9f4RT/K1JXyrX9DYMzmLeugtj1HH/g7in21Decb1Dvq4NxZ3fK9znpiXCY9x2rbC2I+Ldxsm2FTIdcevbZydn5Wvauvk1/ru3Jpy7eJ09hbvfXKz7VQcWPk25PLzA9l52BO33NndRvTddZr3FNl4nuNW2zUB4Wftq+9O57B76Kz+jr5tb59Q3YrIL+pdte5baLwnWM78M0b8w/wdU1vvsqvvjy7Xjur25ius94Tr28MYbkF8Q3nzC7t3BHDbyTmVb1r3XvL/TlDBt5Jlp0H3jBz31rlvSXfs/8b5/9L59fJr/XtvZt1uUzeLG+Nk5GLOnO8NfaXX/r7/+Lyy3dP7yC5d68wlL/Bj/837ru6jelt1u/xWzr52kmu5HQXbj3ylPjMnXGra3kl/8e0n4DcSxvYboLb+qF/e1a/TX7Lxqp8Ldf3hNzl3PJyXZt/c2/7iPke9bxJ4Tv/KW03bHfufuT8hv+MeIT53QZtLp8Tq4hd7h3zb+5t60ccU8+bdLQf7qSBM74z5o8pw8PvEKLNZdo72kTNf9pGvvP67hzt5x15la82PybPjJ2YH8qVmJ6P8Dy2LfXIKZ1cwLy+O0fdoP9T5Ov5670T/sq2rq5rbNRtvuJ79v9N62PdOXj+J5Zf4xf9KOt69fuP8xCbald1eXPkfGrfWebXOcma+jEl8//amjXWZWeWtvXOSd/wjGzfWfJ1TmZI4Vw5ztFYjz4yfi8j1/ExZbdsTltbY2jPrKfFZ71zEt8MLh0I3/adJV/bYt9Tdpyu6NIWubuiLTZTEr+H9D1cB+7HnEmWDy7h07eTtubMual3TuZqA32PTfiqd43Y51Pg7/czgU7Y3iHtE53SOvG+NhcZI1K7lCOrjlwdMvbhBlDvnWP8W6M0d90EXA++KeTru8Kc2a/eOfoTWTvha7+ZnADvyOHN4ZzEnvkf5iP1SHIyrHPb5d2Nkrfg2Tw8pix6sDlCu/jgvXdIrIe0HaoPnJu6F425L5CbOt+KvivSr9452nhvhe9FcoatkAt5GHxGV2U3tvWjTF15kY54D8nR4W2Q/Ctn9K178RF1492nzXyyJob1aP0FuA/Sz76WfZO5Ti7imXb7sc6GPn5PewLUtahxXrVMDg4PAHEdZtzIuhe/HuPeJAbzGZs3Kd3Pzt1L4Pp2/Qr1zqs629RZ9g1E/MP//zgncDj3W7LxnoLM2br9wVTcdS+m3XGNyXxG96akXPbACZCj5Tqe49pm3neBNsdAG9cSeRvq7qH42aDNfazUdh3oYyrmuhfTvjnaOl50b0puExd/x/Tq7wCRxuZ4xup4yVFkh71l90B02sl90FPWR+xi8wLdm4p5lR/Hcd9rI4fW1vVo7M7/KWj3pnFX9E3dNnX2d607f/uUp+wytvNzBMx9dG9Sut/krWz9Gp88bZ9RbiF/bZSu6XY+rNs3eseQS+bOfZ9yxnaMDiije9Nygxim9r9/T2J+jbflat38y8H8rTc2x9RF7fdyrMvZPkp14k1zWuXvH//iVdzyrnY11rbs+vTt41zsgcxJchlpv5Qj1b0Y+zim3Ou4u9SdC+drv2mrdm+63HKs9WfEbF2up8ByN+qq3SqdfNaB3Grs1Zfrq7ZdZ9lYA2OokK9t5iY2fbG/jE6+2rmP3zSP7/HtfjS+3JcXjWH8wYxyhXy3gX6zTq8qXRv2uY41y/t0OF8u4ljba/yVq+U7I1r9Veov4OpaVmZc98ZL4DxGF6ndfVDtbYvuKrmMzypXxf6QcVyPmRPfUNqnHrlKZ3y7IPkd3qX48P1lfmosljdGe33WNn20sdb2qXK+k9W21ket5y6qOu+mWrfcrdDJT5tN4nXcXZDx+c50Vo4uc6hPdc5Tm+vYVjllg//hO1m1M5bAMSr6pm6bfKuN5Sm76GJvnuu4ll+im1rT1c55MudVZ3kGlM6PUj+t3cHEdzL7eS4pM7cXSe0vskm7590esZjn6BL7sjWd9vCxX9VZlps+zWvkEeWWc9tPnu5L5mLgnZiWydv4NGd5h1Q7fVXIVVthftPmms6bfmpNtzG29Z7+ourleRFX7ROD8Zs3eUe3TMpRDsfIlO1XuVt+iM71uIU0ltpeY23LcnF9CstBtVNX645T68vKxmkejKkDrgm5W16GGW0i8afsfKXNNSPfL4Fr7iVIm3JZPOrjt5Wr+ly2bZ045HoHyLMfMTW/aeuwETOQmFKWn1yV8nUu9xjDvZp+ylXx6cs96ZoQlh1nVZ+0yacDu0vsj9Drz3j0mbjDY5U0bu3TJ9L5c1zX2OkIy9VX4puS+jUu52kfvAD6nrKd0vXY23+qzXWmX9v16VjKqflVb8zOzcnYT/v0CZ/Y6XcDGPMmmBp/Suf3h75AH44xZTulMw7naKqNv+FYu0Xb/dGn4+hb/sZrrPadjXrlE+q7QJtjoI19bBMtb+fHmKfGvw5dxq8y43xHHM69cK8t+y1LPj1QykmkbD5Sj856xks5Y163zLiRjp8xb1E+hat7Thj7CXV1sY+US0Xf1G2ruhl1Yf/IbuyT8VdJc7AOVtlMtbnmHNMz82AcP3bWXWvmVsgz6zfxRupDG6VrWtnCvtGFm/3VRVrO+Ncl4XzIOAPqGK5n3zjeRdf1W5a8wzWyxnAd5XBV7sJxD+wDzyrvXnNvLMvwkDbnxNzYV5nYLQfLdN3ou/a7Dp7xCZ8ht4x3eER85HvYp+b3Iq5yeDbGK9dToC4cLAerdGmLTGzXIdmnZ3zdY8b8EpjfLeKVv3EEs8LBsnxt8yyLTT/qUleu0mWM2FwHz/g0r7OR8/CWIDbvRfnK3xgqsD3LmWX5bgPfmVm7V5V741w5TgcS23VKx9kFfh/bB+Hbxi7HCve4qLqrlh3DPsrr5Fh994x3BI7BCfCOcz9fFPtD+2CXeXlAPbFHV/lM6bTvxn41prdZPr0EV+N0j7fnWluvfCwH3VhW9kD5NjnWsTaW8DWmisRZdfKtdctTdtHV/NcY3mbZt4ZrdTbCc8lyXY+rytqvam/b4vttcqxjeQZVvu7Lg5FDYmtjTv02a8McPx3to1dm/iK3sbHcjbLG8DbLxis/ZWJbFv8UD3X2zVkWf5W7ZedUrv0o3ybHOtYW4/vuSF7Ng7pwj0z81i13SJH2O5Tlal/lM5A2fctXvXe949UY3mbZOL2TzM86MN7Kp+UVjj12Iu2R7bzIVd1swu/b5JmxMuf7xOQ97NvL2IQc2jj7UR9erdRedEVabpHx37Y0n66vPRCZ2PqJONN2Vdn6ets8M97/AYJTgxo="
    },
    {
      type = "tilelayer",
      id = 5,
      name = "Decoratives (MG)",
      x = 0,
      y = 0,
      width = 60,
      height = 120,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtnMly1EYYgBUC5gVygMTjsU0mZUMVhpTNKQuPAQkz3jKUDVUYsp2yPUQOkOAN4hTLIZtNLiF5iRyy4AVcroLkQKiYVA7Zvi5LlX/GLWkkSxr1THfV5+kZqaX+/m5ppB65HccmGwEbgVaKwJHd0W1eoMyL8BK8HKN89D3GL/Hhrtqy52PU9x3KvAvvwfsxytfWIN1339f5xtnbNzjehm/hu5z7PvVkHMPaMn/h+Df8A//m3DeJ9q21z/e7JNo334a2djYCNgLtFAGTrp+SaBeTrp+S8DXp+ikJX5Oun5LwtduwEbARaI0IjO9xPmgNk+ZYFPY4ThcUoR1SGc8KDLeJ7zSeMzCbkW/9eF1Qn1Jjl+MdW8dvnHFM3baX8VyB1Yx8o4znqLHLq65vnHFMnW+hg+MXipBFijqes+76JlW3Mp4VGM7IN0r7KscDe5P9PprGcwZmM/KN2r7jCfsu47kCqxn5JtUv426nsJfjF4rQDqmMZwWG28S3HdrUOtoItFsEFjl/LcEt+Brq37dbPKyvjYCNgI2AjYCNgI2AjUBQBP7c7awFLU97WZQxyjTqcpFn/C65z/nd4PVmAs/8BdUz6hhW0LZMWBZ1DMsEp6A65q199z3hOPvhaXgGOqEg6CJfhG7ogWehBI2mrNp3Q/yGIPNePfdx3O6HE9T9JLwCr8IpKAsq5IdhBEbhNahC3lJJjLnKvFfPE7iehIvU/RJ8BB/DZZgWzJCfhTmYh09gAfKWqsJX5r3z8w/U+Uf4CX6GO7AMpqYF4SvzpvqE1XtD+Mp8WDlTl1eFr8yb6hNWb+ko82HlTF2+INpX5k31Cat3SfjKfFg5U5dXha/Mm+oTVu8F4SvzYeUaXe5dd6rrTXVN2uy0IXxlvtn1Smv/VeEr87r9qWtL05N0lHmdl3eNqVvm95k3VnB4l3P8HPitl9XnC6J9ZT6r/We9nw3hK/NZ1yOr/ZX4XdNLMu991mqvpY7/jymZbzVPz4cxjeO6vPeZfbURsBGwEbARsBGwETAzAp3ufVUXr0U3b6ZJcK0f8b8VKp1qYcctw9q/l/GdbmHnh7Trb27bKvM7uC63qO8AvzcegaPid8dO5scp1M2R08N7helpCs/zcEH4mu4UVP/P8PwcvmgR3z48+gNcHgYsC4pTXpdN4DMZ4DQgxofy6hBWrwLnVnWtoNI1XK+7viU+ey7kvDvIeXoIjonz9daW8vVXPrNfxqkCyvk+rg9c3yrvT0NQehPPt+DtnPv6Oaj/X4iSFvFcgls58U3qf4b9YrCJ52P4Iye+Sf3PsJ/vIH1/CI65x4Dfevbz7CNwmD44kEI/7A05x2VvurXHc7hOpeA7llPftOL8O75vGOw8FfE76ktcvzLYV/WDo/T75xvs+61wH3gB19cb9F0zvD9HPc67uc+X/Xnd8L4d5r+KXyu3sRrLKbtjN128FqG+jcNilNTyPp6J6oeDcCil56OUqxyvW6F9vTZOyiNsO+pZ+9MwAZNwBs7CQepyKIPjyXMOq2dSy9Wz9p/CNbgON+AmnMH1bAa+Xr9OyqfR7dzH8QH8Ar+C97xUo+V3st6we0zvZBtxy3qeI9y3jcIYMC/etmTK+My2ivt8MIfjPFyBqxrfZo/P6OK9yPG35HMM6taX6ms43oV7sK7xXeQaqpnjM7p4b+L6WPjKMRvd+tK3m/HUHuiFA5qx1U18GxmfSWuOQ128BzkPDIlzgRyz0a0vfUdwHIUxYF68banR8Zm05jjUxVu2Z32FdevLdeZwnIcrwLx4sZOc43CGvjYL6r63vu9F3YEu3l576o5j3fpyn2s43oV7wLx4sZOc41BdW3jO9X0v9g40BePEspt79x7oBebFc/qoaz9ETfVzHHrXU6qN00pxYjmC4yiMAfPiORPUbzJGHevnOKxwPlHXF0n06bTitZPt6uY49No4TjvspC5ZlPWb49BzzqIOWe7Db47DZt0nxHHfcL/Tb4vvdr/tBM1xqNrYhFRqcDwuist/2akD1w=="
    },
    {
      type = "tilelayer",
      id = 2,
      name = "Platforms",
      x = 0,
      y = 0,
      width = 60,
      height = 120,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHVnNtyFccVhnfAzkNwkAmSsH0RCVdOFeBingOCrCDhJBeR5CROYuBiP0acWIIqBOVcRBJOYpcFF/MeBqQqCXIVwDlWsC/y/aP9y814Zvb0zEjgrvr3nLpXr9Xr0Kt7RnrvG73e78Ey+AO4CuYP9KZXwWMwebA3HV77nuv/jvrvAdO4wflNIFrvg8Xc+RLX6uN5le0Dvd4DsIJsj8AE8tXhZY66YZu5mu3q0N7LOrMHe72LoKhMINPXVa4ieXRvGVlvlMhb1uZ53p8+2Lt2DGwe6F27Bu5jmxugbrE9163/otUbQVevROhrjLrjEfVfNHmn4P3NCP6r/PdFk62Mnxib/rr5b5HMMTa9HWELRX09r3uLQYyKlXeEtq+AY+Bb4DgYBWMF16pTVl9txsFr4HWwXyXGh2fhS7gIfgwugBmge1PgTTANqp65vo6i81PwM7AX5RB0DwPr5T72uRFho8u0vQFugphCjtlbAD+gr1McTwftzwTnIc0jJffDOsPOz0LjHPD4j7yEbYK6ZZu2D8BDEFNWqb8GLoHLg7ZXBsdhdI5STz4hPQnyEflTmU+N80z6lC6tz79w/VcQWzz/noiwCfXBuqH3BKyD25H9nqe+fOXcAPIX+U2Z78hHpEfD+jwWoVePy2XkvBIpq9o6RjyFl8+Biug0obXTuvp35WAvWQVroLpm9dPb8HingbxLtLkKToHTQfsqeY8E9fJcvT8Ys/z98HoeWRdaynuKfk7X6CvsV+e251FsCrvuc93P18lfV8l7dwgPrFMT1uLJyZbyNvE/yUHfPfruvQGfylkegFHOx4DOH4K/AV3XKVVjofaPDvQSHe9Db6MmTdXPl9D/8s98fQj6h8Gn8H8X3AOOk9LvGBgHM9SZBTo/AV4Fb3FdpwyT1zRG6DtmPeR2Ps7S/iJ4C5SVs/CsWHoY/o+AoyCMlX/mGbGkd53jMtB83rZ4ztK8Fc5THuem9Jfh8wa4WSFvVZ4Qxs0teNsGms/bFs9ZmrfCecr5RdM4Ld8bVn40hP95nivXkp63oGebGUa37nP7rMaTvY1emzgt32tTFDdX4UO5lmxa/lxnDGP7tMzs5yhWNo7T4k3x1GsirW1i1jeOm5O0Own2Qr8eG8vM3JcwBya+H3N0bL0ArzNAa5uy9U2VH8NDll9avxpD5cVex4xyrrnpBGhaHJuxpwR7SprQibHnKj9m3zaZBxp3j6HmJI+fcmDNVXXnpyJZphhD7VWpnwVQVGfYva7i6QT9w0cWt9Qn8TPFn1Pid5rn4QPquchmquzG9XyUTauE88LOnXq/Y4zXOOiiYGdZ3BKtBeQkjqZzBfKGfclmquwmrBueQzeBfnQ+3dXccZ4xewzv2HPvM0CumRJH04kh8oYyOMeQn4+D10CZv0O3UT69DJ/KN9qWRWggX5ZTixZyp8ifEr/TurSdY8jP5e/y/TJ/17wA/Sxe1KWvep6PimLpCP2FudxxrhVni+47z8OO5cP9+cF6qSpPzfO5CG3551WwBarytBVkXQVrIE+n6tqxVHsM3hOa4VxjPAXCXO4C13pWdN95nvqChz689HVelafqeb4sMV5aV9fxM8Y0i9P/gae6JXx36/e/8LuJjjZP8n6Q4zTX008APjkd3it6B6x+qTt0PWxfDe1HtmM7sd3Jl+XHRfu7k9yHn973GZ+6ZYy6+fiMbjYZu03oTXN85t13eC/fh9dpjEsfX+7nn4fX9tXQfmQ7thPbnexMfly0vwtv8p2o4jga1aiksuVFv1msKqlWelu+uwm2wDJ6UBy9WSHPKs/WKp4XddSUtzwtj/XbOzyk8JI+LODlbsE907rHM8m8AWTPw8pj6sF/VCGe1soLhhH1WN+i/wVkRf60qE2dfQzJbP8d4Tz08eNcy8dVwvlv587wX9tzTF5QRNVjrdi6yhiuROQZRfTsv1PIF/q45gj7+Dx9oa+oYnuOyQuKOvBYd2UvRX3k7zGmCWMbtSft+Mz8nebpxVx7rGcY71lwEcTkGjF9ue4cstJvVA5t3kQjNjdwvzrir9nccB05l0EWWznudbEf1e1nG54eDKC5XXm6cvRXQUxZpf4a0P6GaT7kPL/eV+5Qlj/E9Oe69iNfDzs6LmjPWHO78nTl6D8BMcXjrP0N09R6P5+jKncoyx9i+nPdWHlH0cEYGAdtivNe6dY61XEd/+IdVXIHxNB3vml7K2vrcS57nr8fxpf8s9hrzZvSrXTqcgk5L4MrgPiS+n7RcSIYE+ebtrei+roXq98wvpTRrHt/BN0qp9SeqcspZPf7OORJfb/O8YOXeskfQVld6/aTCLpd2bN4sk1fC+S9FOi67Ryfl9u6fTdC3jb2bB9zvqc8bwNsDuTl3WH/5GAdnOe17fUZZOS9c8r75/SHEfK2sWf7mPM953n+ziD0XcknH24rp9t/QX70OXgK/heRK7XR7yK2ugSugmsgLJKVsU/QQYIuEj3zMazX9PwOMtp/9N5K36/UKW30e48+FJM3gNatYfl4cG2Zw2dl53n/OAYNz22jnDsfyvtPU3mb5JOOydJzWP7L9Tp6xd4S7C7B/pLwedF53j+moaG5TWuiGeB8KO8//+TZv4DLrYE9+To8bhFblCOE4xeeK7esKlq/W8dhPX2HJpv23Bs+24vzcO3wdoW8zv9m4NvjF54rt6wqR5DLOg7r/YN2tuUu/TbsQ+eSU2BuT5ifsvekb3DM18tfw1v2XRG8Ve4Z5dvp+grzAXpM0Wfq5/LfGFt2u9ij5BQks7ACVsEaqKIFrz14bvy92G3i5XowL2T+i89yPyGWVvZdxdewZ+QwiSCZBck8D9h3qOxTvN5G3jugSblM+0tAe8EfoVvpl+uE+8kV0IRmnTbsUyRCKLftuqq9/O0p+Bw0KegwZaz6jFlf+/3S7yn4OA3OgCY067SZg7YgmYVHgLx66Hsl6cM+PKwfz5PhWg0dKt/pM2Z96VjxGdmj14HD+s4/n0A2YQ74mXy4yn8lZ6YP6p0eYvei6XkyXKuhw1TPrGPtQxMT9mU+CuWV/w6TV7FK+kU3WW4gvqvKInVff7mXvgZuch6WUMeM4zP5ZFiv63PJLJoT9DnMf9fRjfTbhf1hH33k7LM22h2/LwJb60rOQ9A/DLQm+xTcBf7OUfe0TiuzacWqtvHKciBviryp7PkUIF71sPXOy1longNak5V951g2D8uWBfjMco42zGHP6VNwC3qXwGVALNv3Ij9Wp6vYFvum2bmuVWTLgv1t526zX+KV5vH0M+itg9vgDnheZR5ZF3LyWr/opVa8quL9CrJeBuSwis+ao3r473MtitehbVu/6GV3viyaY+swfQYZJ5GPfRzZS4o/a53/3Irteh7ZnGMqNyBHUD64+7c1RXNsHabRpd6FZu9WQnp12u5FHc1PohvOUeg3JQdUvr/7tzVVc2wVX/iq3nVn71ZCelVt9OwQbQ4D713oqP0M72n4WPddjOfjRwPffczxSc6PscE+ttgfxlvV8yvIC+3svXuMvGdpcw5470JHrccF5XE+xr6LWRnIiA6+EqeJY/35lvKeQV5sJ/vuzPGqanzCZ0X7BuFznfvdT9G7OOXzef3PDeRFrq/E6TVkZRz6+T5ir8234xUxu9a6eol6+j6gqlS9i5Md5PVvu55EXuw3CWk/QdbHHcg7Bc9vAu+N6X3rCLzYN7Xn6OtRzu2b96mnPLDrgsw95M3mjJD2SfJebLEf3os51zeUKtaT9nqtjyn6s29qz9HXM5zbN71fv0Olu19sevd9fEi1qf96rpbOpCNBug3p0Wc/7Kvr84f0XVZWeIafZnNGWGcNnrjfZ85Kw/vDzj1XS2fSkfVkempPn/1hdNo8P8H4lpVH8IWfPvOtlmxvGei7izZlHrrotSd6xOdsD1D06LPfhm7btvYx05H9ad/9OLyGMWTYfrvb+2i7Eb0wHmAzfdepe5yDl6bF+YvlkY+FsXAUO1RsuUAfYQwZtt+e5ye0m0vQutyCZ3ygcXH+YnnsYyZ4Hdq25wlyBt+PPTrXULt1aN4e8OyYJtuJtZlYHsL6U+hVc6OK1mwuW/Axy/XF4J6fxRzRb5anyn+fQvPzgbyOabKdWJsp699jqHlBuVXROIZ+y3ul3TLK+Rho+50O/pvlqfLfJ8Qo5O+rE2ymz7cYKd9kpLquKh++XPX0y2ceQ80Lyq2KxjGUVy2lV5UZ+OtCv/PIS3xOFA/CeLXTy/P5vY+MGwM5pVeV6xztvzt3mv1OIutJoNb5ePUock6yvbb1+XDtK72ukV+sgpWIPMO85P0G/Wbzr+QN45WuY+ck22uVz4sP5eXhdwD58cGnspgiHqTXBeScB3MR8pqXvN+s0vcaUAn9d+dO3O8vvjm8vvhQXh5+B5AfH/SY7V+J2hby4mdas6aMfzq8h50ai/RR9I6BsZScWWnrvx/WkLcOv6HNKa7An/YkUvwrrdO+qg7jlq31VSfvv1Xt/Ez2qfnFR63fP4XmXVA037hd1TG0ucx/kZN76UoH8o7A1ytAJe+/O3erf2Wfml981Prd7w+K5ptqajtP0eWuzWX+i5zzYK4DecN8xnGhDk9hnaLvJovuhW2qzieR9yRQyfwXObmXTnQgbzi/s5/T+v3MDpfNfom/WcHHEmJJogv5bxfzbkZ48BPGwy5ymJB2k3PsOSFGJWor/W4D7TFpz897SU1jg2gyt2mOExLTFn3Rzu8fqn6XxXHuMH35+zzk3fVfrwP9P2C8l9Q0Noh35jW9Y++tSkbsR7T99wL5/cMuZRUtx7lzyOjv80J7W4e38L1Rvv+btGtSwrjl9qOSH7Rdk5he1XEJvq+Ca2AOGbG57JsO9lz25BuLMG6Zr9B3lIfKtvfKvr1G2KQPF/kXMbTVNxb2l3werT7yMoe+ozxUtt21fd+DpjCCHSkPOAZUHKOfErdYk9f6fnWn5bO/9pd8Hq1a7lNrMY/zNucPQJOyWKPdUeQT3LfldYwmB2r1zZ94KMqjJc8U/WovxePMHJhW+W+RPIofMTHkPP0JKrZpnTtmkePu2Td/S/R7FSzA8zTHWXARFJUR6gihX8TIaZqL0Ne43RM9zjXWLopZp5D3NOC9XuL7XR2t3zo2fB7+pkCRX8TwI3kl69GBnNKxi3zYayPf6/Jo/VbZcNif/SK8V3Z+FDny9lBW1/flw3V5cZuYo+2pyo5j6IV1m9jDKvIW8dJk7EJefG57Xsa2bgR+5Odtjovo1/ZQ18/nkbeIlyZjV8S77XkbWY/Dn3KLOuUQ9Zz/HuM83Jtqk59MlthznbELeQr5Cfm7j5wbwO9plFvUKWep5/x3mvNwb6pNfqI5qcieY3kK+cnzdwF+m+YXdfiIqYM9d772jel/v+ui331br+y3bPn+HEua2nOe3otw7XlFe5n3BvC5Y0lRfH4ReG/Cg+cV/89X/d9Xn/v9r+YK7bVoL0f/z3cUn24T85vwuR9tHiMXueTufov/n+8M99rE/P3gvUkf5M7Ze4AbyCdcB8uD8yb0YtrIz/SOK5yrZVdjQLZ1AnRdWBtle4iiq/lxC9RZx3TBh/xM77jyc/Us92Rbb4Gui+ZerUtvsQZfA6uA+Sn9E+i6r5Derxnn34Al+vZ+2r8599+k7VX8XKWPNcA3DSn7WLvvQ39eQ17H/XHaF9le1fOPkPVjoHWp93l+yzX/YyH7mzTFT+Xasu8ubdv2PAN97bPgz9n70G/XkFf2OAUugiLbK3p+k7ou79CnivdYsK8EO0ukd+faM9TvyrYnoIt8Wby6rj6A9oT1PvTvNd4hLcJL1Vps2PMdab/cF8a+Euws+Q50vwu+B94F4VxpnSumya7K4p2eKdcIY6FyDetXe8KzoGxfybztxZFxTxj37F3WGxx/Ca+/Au+AT4DfTWiu1LpjBiimya7K4p2e+f/L53MNyfB/YvKv6g=="
    },
    {
      type = "tilelayer",
      id = 7,
      name = "Foreground",
      x = 0,
      y = 0,
      width = 60,
      height = 120,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHt3EdsHNcZB/ABXCKJkgykqNhxu4ukqq1CUjkmSHKJE/dC361eLIkidYojI5GQxLaKrfJ0N9U76yWOAltGEtsq7r6bVKcKW350uACxoMVdkbveWc4H/CBImp19/7c7s7vvG0wUJZXMQDIDyQwkM5DMQDIDyQwkM5DMQDIDyQwUxgy8MSaK3uQttrCVbWznbd5hBzvZxW4CeyiWOifLeT7lMz7nC77kK77mG4qlpoyNoqnczwP8nAd5iId5hEcplnpalmd4lud4nhd4kZeo5mXiWG8Y95u8xRa2so3tvM077GAnu9hNYA9xrI+M+2M+4QxnOcd5PuUzPucLvuQrvuYbkir+GVgyIYqWsozlrGAlq1hNpvXH8Zlumb/tNpVEv0h/tn0y7ecABznEYY5wlEzrHwWYd7CxX5DpIpe4zBWuco0Oiq3KJ0bRdGYwk1nMZg6PUWy1RKalLGM5K1jJKlZTbLVPpv0c4CCHOMwRjlJsdUGmi1ziMle4yjU6KLYqv8/xywxmMovZzOEx4lSbS4Ye7RKZlrKM5axgJatYTRzqmM+R45zgJA000kR67ZNpPwc4yCEOc4SjxKGuy3WDm9yiky66Sa8LMl3kEpe5wlWu0UGm9Xe/p4dae8h0X9lu97jzzFzmMZ8FrKeWOjYw0vVfeT/iYz7hDGcZuPYw0s95u/01ythEMy05yPtjv7d+wk/5GZOYzMC1h9uNb6T/r0vGbnrozUHe38n2BL/nDzzJUwxcexjpTLfbX4VjsZIqFvYfl686ntewlnXUsJ5a6ohzDfW9Iv083hzzvEN9r0g/j/fEPO9Q3ytS5/EKx3YlVTk4xvN5fAz1vWKdfDUM/NzK5/jy8VzH5DvOCU7SwMDPrXyMoRCeY7ifWxsz+N5eCDlTY0j/3Er9e6Z/nsoy75wJUetsZjGTGUynnDJKmUamz5/tdrU+n+vY0P85ne3js93+2vio9SpXuMwlLnKBdtr4lmz3m+n2TXI205KnvEdkOcwhDnKA/exjL/W8S6bjz3a7bjl76M1T3lWyrGQFy1nGUpawmEW8QrY5crX9eyVReI073f8cWWYzi5nMYDrllFHKNO50/4XyOOv/Ud8azLUSxy9XuMwlLnKBdtr4lkIZ93DHcUSWwxziIAfYzz72Us+7DPd5CuXxq2RZyQqWs4ylLGExi3iFQhnvcMcxR5bZzGImM5hOOWWUMo3hPk/y+DufgUm+e09mClP5oWrgellyrU5yrc4P9T4cqect5mt1Bpuj5FqdwWYlnv/Wdt/o+kyuH2V5F42yvKWjKG/7RL8TieeZJ/tR75W1fhTlXSzrolGUt0zW0lGUt916dFsO16SzP8Kye0S9fuRe+q5fzaRs2+oxrZlsW4jbeK0ir1nUd/3qaCjHYuSYjMozWCswJ61xnxPn2sg597vSKwr6J0FPIVhnD9aeg/XYYI0yWLcL1rJC3PPWy7q3P2+pvHpGQR8l6C0E6+3BGnSwLhusVQbrd7HP2yZre3/eMnn1yYLeUdBPCXoMwbp7sBYdrM8Ga5axz+u7cFTW36/SBw16g0G/LOghBX2VoNcQrL8Ha9LBOm3s8/qtEy3uz6v3G/RDgx5h0DcLeklBfyXoOQTr8MHadOzz1su6tz+vfnfQAw76okGvMOifBT2loM8S9B6C9fjY522Ttb0/rx5/0PcOesFBfzToGQZ9tKC3FPRbgh5EwebN5lqOX42NWn+J6xqCXn/Q/w56wkGfNOgdBv20oMcU9F0KNm8213KMlXUMruUIrm8Iev5BHzzoDQf90qCHGPTVgl5TXvLqa7dGOax/jYlaT+H6leCajuA6h6D3H/TDgx5x0DcNeolBfy0vefXwc5r3dVk3ksMpTXadzEAyA8kMJDOQwQz8Z1zU+m8y2LQoNvmbrH8dRXmL4kUroBDp16sU0NByMpT0e8vk5EkKaKfp95YpoKHlZCjp95bJyZMU0E7T7y0z0kObNM41dkxhKnEtaxTVfrdXDzX+J2V8iqd5Jsu8m9yvZHNM7lmSmoctMm5lG9uzzHta1g9jlveMjGc5x/ks807QJ5sYs17ZJNfmT2YKU0kqmYFkBpIZKPQZsG4bi3rd2v5GhjtY6/KxqFT/ppAH+6H1kNN8wPvDXBtJ9W/ylfde/Yp7uJu7MuxdbJZxE3/hz0Pk3Wyfm26z31T/Jl95U78r7vdd7AEe5CEe5hEeZbD70/xWzt/w6yHyDpUj3/2bJ+Tp+13xLM/xAi/yEtW8zGD3p5kg53hKhpl3qPnIxf+nflfskG0nu9hNYA+D3Z/mtHPqB7w/AufWXGRK9pnMQFxmYI3vFmtZRw3rqaWODRRbHZfpBCdpoJEmmmmh2OqGTDe5RSdddNNDL6laODaq3kALvSwc5++00MvCtPWxDveCu84NbnKLTrropode8l1zrTnNYz4LqKCSKhbSMe7/15ZUyVhHMz1UyVhHMz1UDcjrO9F39zF43P3R5jKP+SyggkrsLzKH31uvWRv6ExtHeI1ojUxrWUcN66mljg2kyhira2mim0oZa2mim8oBefses1qWV1nDWtZRw3rsJzJ3kffL99Z7cv6TUyOc97hMJzhJA4000UwLqfK6VBtrdSNdVMi4nka6qEjLe1SWYxznBCdpwOMjcxZ5n0SOjRGru1ybezf3cC8/YgxjGUcJfXVDppvcopMuuumhl1R5L1Z7faqNubqTBTLW0EAnC9LydshynRvc5BYeF5mryPsjckxEzgN5r/8BigHhUg=="
    },
    {
      type = "objectgroup",
      id = 6,
      name = "Environment",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 160,
          width = 352,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 512,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 16,
          width = 16,
          height = 144,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 208,
          width = 272,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 48,
          width = 304,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 464,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 400,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 288,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 176,
          width = 32,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 304,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 384,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 176,
          width = 16,
          height = 320,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 496,
          width = 320,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 544,
          width = 16,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 592,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 528,
          width = 192,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 432,
          width = 16,
          height = 384,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 672,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 816,
          width = 288,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 832,
          width = 16,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 992,
          width = 192,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 1008,
          width = 16,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 1248,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 1136,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 1408,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 928,
          y = 1264,
          width = 16,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 1520,
          width = 16,
          height = 400,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 1488,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 1504,
          width = 32,
          height = 176,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 1168,
          width = 192,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 544,
          y = 1600,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 1632,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 1536,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 1680,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "",
          type = "",
          shape = "rectangle",
          x = 816,
          y = 1760,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 1344,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 1296,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 416,
          width = 16,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 480,
          width = 32,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 1904,
          width = 304,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 93,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 1872,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 1824,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 98,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 1360,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 99,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 1552,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 1488,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1504,
          width = 16,
          height = 416,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 102,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 1792,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 103,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 1872,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 104,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 1872,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 105,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 1696,
          width = 160,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 109,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 1248,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 110,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 864,
          width = 16,
          height = 496,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 113,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 1200,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 115,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 688,
          width = 48,
          height = 352,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 117,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 1072,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 118,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 944,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 119,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 304,
          width = 16,
          height = 464,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 120,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 768,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 122,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 848,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 123,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 512,
          width = 16,
          height = 352,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 128,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 672,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 135,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 1104,
          width = 160,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 150,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 320,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 153,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 1280,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 155,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 1488,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 157,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 1360,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 162,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 1120,
          width = 16,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 163,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 176,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 164,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 64,
          width = 16,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 166,
          name = "",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 224,
          width = 16,
          height = 208,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 168,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 704,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 170,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 1216,
          width = 48,
          height = 272,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 171,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 1040,
          width = 32,
          height = 176,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 173,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 784,
          width = 32,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 174,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 1680,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 176,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 1664,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 177,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 1360,
          width = 16,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 12,
      name = "Spikes",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 80,
          name = "",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 576,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 432,
          width = 16,
          height = 144,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "W"
          }
        },
        {
          id = 82,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 624,
          width = 16,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "W"
          }
        },
        {
          id = 83,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 1392,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 95,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 1664,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 1680,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 116,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 1536,
          width = 16,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "W"
          }
        },
        {
          id = 125,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 1152,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 136,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 1104,
          width = 16,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "E"
          }
        },
        {
          id = 137,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 1120,
          width = 16,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "W"
          }
        },
        {
          id = 141,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 528,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "S"
          }
        },
        {
          id = 142,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 528,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "S"
          }
        },
        {
          id = 158,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 1344,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 160,
          name = "",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 1424,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "S"
          }
        },
        {
          id = 161,
          name = "",
          type = "",
          shape = "rectangle",
          x = 912,
          y = 1264,
          width = 16,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "W"
          }
        },
        {
          id = 167,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 752,
          width = 16,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "E"
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 13,
      name = "Checkpoint",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 127,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 131,
          name = "",
          type = "",
          shape = "rectangle",
          x = 816,
          y = 1824,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 132,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 768,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 8,
      name = "MovingPlatform",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 848,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "castle"
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 9,
      name = "Units",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 71,
          name = "Executioner",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 112,
          width = 130.5,
          height = 88.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "Ghoul",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 672,
          width = 76.5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "DarkMage",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 896,
          width = 92,
          height = 93,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "DarkMage",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 1696,
          width = 92,
          height = 93,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 111,
          name = "Ghoul",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 1456,
          width = 76.5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 129,
          name = "Ghoul",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 1168,
          width = 76.5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 130,
          name = "Ghoul",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 736,
          width = 76.5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 133,
          name = "Ghoul",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 368,
          width = 76.5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 145,
          name = "Ghoul",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 1312,
          width = 76.5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 149,
          name = "Ensign",
          type = "",
          shape = "rectangle",
          x = 816,
          y = 1824,
          width = 80,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["title"] = "Ensign Victor"
          }
        },
        {
          id = 172,
          name = "Ghoul",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 912,
          width = 76.5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 183,
          name = "Ghoul",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 1248,
          width = 76.5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 187,
          name = "Ghoul",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 1520,
          width = 76.5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 189,
          name = "Ghoul",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 1216,
          width = 76.5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 11,
      name = "MovingPillar",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 74,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 16,
          width = 32,
          height = 144,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "castle"
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 10,
      name = "Events",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 72,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "bullets",
            ["value"] = "sm"
          }
        },
        {
          id = 73,
          name = "Translate",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 240,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 256,
            ["Goal.y"] = -40,
            ["Target"] = 74,
            ["delay"] = 2,
            ["once"] = false
          }
        },
        {
          id = 75,
          name = "Teleport",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 80,
          width = 16,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["exit"] = "left",
            ["map"] = "mount01",
            ["method"] = "door",
            ["onTouch"] = true,
            ["section"] = "A"
          }
        },
        {
          id = 77,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 832,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 480,
            ["Goal.y"] = 1112,
            ["Target"] = 34,
            ["auto"] = true,
            ["delay"] = 2,
            ["delayIn"] = 2,
            ["delayOut"] = 2,
            ["pause"] = 2
          }
        },
        {
          id = 78,
          name = "Teleport",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 416,
          width = 16,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["exit"] = "left",
            ["map"] = "mount01",
            ["method"] = "door",
            ["onTouch"] = true,
            ["section"] = "B"
          }
        },
        {
          id = 89,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 896,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "bullets",
            ["value"] = "sm"
          }
        },
        {
          id = 108,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 912,
          y = 1856,
          width = 32,
          height = 32,
          rotation = 90,
          visible = true,
          properties = {
            ["category"] = "stat",
            ["name"] = "health",
            ["value"] = "md"
          }
        },
        {
          id = 112,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 1200,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "shells",
            ["value"] = "sm"
          }
        },
        {
          id = 124,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 624,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "shells",
            ["value"] = "sm"
          }
        },
        {
          id = 126,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 1440,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "shells",
            ["value"] = "md"
          }
        },
        {
          id = 138,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 1136,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "stat",
            ["name"] = "health",
            ["value"] = "sm"
          }
        },
        {
          id = 143,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 1632,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "bullets",
            ["value"] = "md"
          }
        },
        {
          id = 147,
          name = "Cutscene",
          type = "",
          shape = "rectangle",
          x = 672,
          y = 1888,
          width = 192,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["checkpoint"] = 131,
            ["quest"] = 3,
            ["require"] = 2,
            ["scene"] = "cut03"
          }
        },
        {
          id = 148,
          name = "Cutscene",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 1808,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["checkpoint"] = 131,
            ["quest"] = 3,
            ["require"] = 2,
            ["scene"] = "cut03"
          }
        },
        {
          id = 151,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "bullets",
            ["value"] = "md"
          }
        },
        {
          id = 154,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 1232,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "shells",
            ["value"] = "sm"
          }
        },
        {
          id = 165,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "stat",
            ["name"] = "health",
            ["value"] = "sm"
          }
        },
        {
          id = 179,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 336,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "bullets",
            ["value"] = "sm"
          }
        },
        {
          id = 180,
          name = "Translate",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 80,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 256,
            ["Goal.y"] = 88,
            ["Target"] = 74,
            ["delay"] = 1,
            ["once"] = false
          }
        },
        {
          id = 181,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "stat",
            ["name"] = "health",
            ["value"] = "md"
          }
        },
        {
          id = 184,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 1632,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "bullets",
            ["value"] = "md"
          }
        },
        {
          id = 185,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 1632,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "bullets",
            ["value"] = "md"
          }
        }
      }
    }
  }
}
