return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.3.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 100,
  height = 60,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 17,
  nextobjectid = 136,
  properties = {},
  tilesets = {
    {
      name = "strangemountains01",
      firstgid = 1,
      filename = "tiles/strangemountains01.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 64,
      image = "tiles/strangemountains01.png",
      imagewidth = 1024,
      imageheight = 1024,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 4096,
      tiles = {
        {
          id = 1678,
          objectGroup = {
            type = "objectgroup",
            id = 3,
            name = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            draworder = "index",
            properties = {},
            objects = {
              {
                id = 2,
                name = "",
                type = "",
                shape = "rectangle",
                x = 0,
                y = 0,
                width = 16,
                height = 16,
                rotation = 0,
                visible = true,
                properties = {}
              }
            }
          }
        }
      }
    },
    {
      name = "strangemountains02",
      firstgid = 4097,
      filename = "tiles/strangemountains02.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 64,
      image = "tiles/strangemountains02.png",
      imagewidth = 1024,
      imageheight = 1024,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 4096,
      tiles = {}
    },
    {
      name = "background",
      firstgid = 8193,
      filename = "tiles/background.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 32,
      image = "tiles/background.png",
      imagewidth = 512,
      imageheight = 512,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 1024,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      id = 2,
      name = "Background",
      x = 0,
      y = 0,
      width = 100,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHt22WQFHcaB2AS4u4uWNzdBbeQoMHd3d3d3QnuHtzd3d0Pd02ABLuHD1u1RS2TY++YGW758FT39H963rd/7/ZQXVNUiR2rTpVbRI84sWL1pBe9uZPYkbZX9xOSiMQkISnJSE4KUpKK1PxEGn7mF9KSjvRkICOZ+JXMZCEr2chODnKSi9zk4dqebvT1rTKLq31Od70zmMksIs8i4rrzOp6P/BSgIIUoTBGKUozilKAkpShNGcpSjvJUoCKVqEwVqlKN6tSgJrWoTR0i+oju9laax3bXu4Od7CKqedR1vB71aUBDGtGYJjSlGc1pQUta0Zo2tKUd7elARzrRmS50pRu/0Z0e9KQXvYnuHCLOu1XmcdG1XuIyV4gVN+p59LHWl370ZwADGcRghjCUYQxnBCP5nVGMZgxjGcd4JjCRSUxmClOZxnRmMJNZROQa3e2tMI8XZf8SL/MKrxKHqO6P2TKZw1zmMZ8FLGQRi1nCUpaxnBWsZBWrWcNa1rGeDWxkE5vZwla2ce09G905RJx3K8wjqtwj+r92+y8Z7WYPe9nHfg5wkEMc5ghHOcZxTnCSU5zmDM+Y+bOctX+O85GOXbAf1T17bT83+vr/bR5Rze4emd7LfdzPAzzIQzzMIzzKYzzOEzxJRJYRc3ku0rHr3bMR50R3+/82j+vlcHVOUbne+0N1/PY8ov536PY8rv9cGtV30D/lFdU5t++P62d8I/dlVNn+0zyutx4xk+uth/r4jeQSqvf+L+cR6rz/qX6oMr6Rurfn8b/5nrmRzAO99/Y8bs/jn75XbtZ6oL/LcFm7z7PD/TzAgzzEwzzCozzG4zzBkzzF0zzDszzH87zAi7zEy7zCq8ThDiIyvsv+3dzDvQSzfrhkHqiPN2XyFm/zDu/yHu/zAR/yER/zCZ/yGZ/zBV/yFV/zDd/yHd/zAz8Sl3jEJwGv8TpvEMz6gXIIl7UUMklJKlLzE2n4mV9ISzrSk4GMZOJXMpOFrGQjOznISS5yk4eEJCIxSUhKMpITzPrhknmgPorIpCjFKE4JSlKK0pShLOUoTwUqUonKVKEq1ahODWpSi9rUIS/5yE8BClKIwgSzfqAcwmWtiUya0ozmtKAlrWhNG9rSjvZ0oCOd6EwXutKN3+hOD3rSi97UpR71aUBDGtGYYNYPl8wD9TFYJkMYyjCGM4KR/M4oRjOGsYxjPBOYyCQmM4WpTGM6M5jJLPrQl370ZwADGUQw6wfKIVzWFslkMUtYyjKWs4KVrGI1a1jLOtazgY1sYjNb2Mo2trODnexiNnOYyzzms4CFBLN+uGQeqI+DMjnEYY5wlGMc5wQnOcVpzvAHf3KWc5znL/7mAhe5xGWucPW333/Z7mYPe9nHfg4QzPqBcgiHtej8jvSUfJ8m8u9Iz3v9Atf7HekOa3cSm7u4m+j+jvXf1A+HzAP18IZc3uQt3uYd3uU93ucDPuQjPuYTPuUzPucLvuQrvuYbvuU7vucHfiQu8YhPAl7jdYJdP1AW4bCWXCYpSEkqUvMTafiZX0hLOtKTgYxk4lcyk4WsZCM7OchJLnKTh4QkIjFJSEoygl0/HDIP1ENhmRShKMUoTglKUorSlKEs5ShPBSpSicpUoSrVqE4NalKL2tQhL/nITwEKUohg1w+URTisNZZJE5rSjOa0oCWtaE0b2tKO9nSgI53oTBe60o3f6E4PetKL3tSlHvVpQEMaEez64ZD5f9LDENkMZRjDGcFIfmcUoxnDWMYxnglMZBKTmcJUpjGdGcxkFn3oSz/6M4CBDGIwwar/n2QRDu9ZLJMlLGUZy1nBSlaxmjWsZR3r2cBGNrGZLWxlG9vZwU52MZs5zGUe81nAQhYRrPrhkHWgHg7I4iCHOMwRjnKM45zgJKc4zRn+4E/Oco7z/MXfXOAil7jMFWLF8/xhu5s97GUf+wl2/UBZhMPavbK6j/t5gAd5iId5hEd5jMd5gid5iqd5hmd5jud5gRd5iZd5hVeJwx3cSWzu4m7uIdj1wyHzQD28IZM3eYu3eYd3eY/3+YAP+YiP+YRP+YzP+YIv+Yqv+YZv+Y7v+YEfiUs84pOA13idYNcPlEU4rCWXSQpSkorU/EQafuYX0pKO9GQgI5n4lcxkISvZyE4OcpKL3OQhIYlITBKSkoxg1w+HzAP1UFgmRShKMYpTgpKUojRlKEs5ylOBilSiMlWoSjWqU4Oa1KI2dchLPvJTgIIUItj1A2URDmuNZdKEpjSjOS1oSSta04a2tKM9HehIJzrTha504ze604Oe9KI3dalHfRrQkEYEu344ZB6oh0EyGcwQhjKM4YxgJL8zitGMYSzjGM8EJjKJyUxhKtOYzgxmMos+9KUf/RnAQIJdP1AW4bC2UCaLWMwSlrKM5axgJatYzRrWso71bGAjm9jMFrayje3sYCe7mM0c5jKP+Swg2PXDIfNAPRyQyUEOcZgjHOUYxznBSU5xmjP8wZ+c5Rzn+Yu/ucBFLnGZK8SK7/nDdjd72Ms+9hPs+oGyCIe1e2V1H/fzAA/yEA/zCI/yGI/zBE/yFE/zDM/yHM/zAi/yEi/zCq8Shzu4k9jcxd3cQ7Drh0PmgXp4QyZv8hZv8w7v8h7v8wEf8hEf8wmf8hmf8wVf8hVf8w3f8h3f8wM/Epd4xCcBr/E6wa4fKItQriWVRTKSk4KUpCI1P5GGn/mFtKQjPRnISCZ+JTNZyEo2spODnOQiN3lISCISk4RQ1Q9l5oFqF5RJIQpThKIUozglKEkpSlOGspSjPBWoSCUqU4WqVKM6NahJLWpTh7zkIz8FCFX9QJmEcq2hTBrRmCY0pRnNaUFLWtGaNrSlHe3pQEc60ZkudKUbv9GdHvSkF72pSz3q04BQ1Q9l5oFqD5DJQAYxmCEMZRjDGcFIfmcUoxnDWMYxnglMZBKTmcJUpjGdGcxkFn3oSz/6E6r6gTIJ5dp8mSxgIYtYzBKWsozlrGAlq1jNGtayjvVsYCOb2MwWtrKN7exgJ7uYzRzmMo9Q1Q9l5oFq75PJfg5wkEMc5ghHOcZxTnCSU5zmDH/wJ2c5x3n+4m8ucJFLXOYKsRJ4/rDdzR72Eqr6gTIJ5drVXGKiUGYeqHZMnMXVaw6USSjXru0tpswnlJnfSO3b8wif/9MZU2Zx7XfCjfy93uz3xqQZRL7Wm51rdD8/co8xaT+6ed3s82LSDCJf683ONbqfH7nHmLQf3bxu9nkxaQaRr/Vm5xrdz4/cY0zaj25eN/u8mDSDyNd6s3ON7udH7jEm7f8byIAbmg=="
    },
    {
      type = "tilelayer",
      id = 8,
      name = "Sharp Cliffs",
      x = 0,
      y = 0,
      width = 100,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHt2uduE1kYxvEjQRJI75APS70USCE9oUsQXuBSSGyT3stq6d+23gISpJCe0IIEiQMfVtp6C/t/WR9z5HW8MSRSBp0j/ZjJeOLYz+PxjI8xxg+fgE/AJ+AT8An4BHwCPgGfgE/AJ+AT8An4BHwCPgGfgE/AJ+AT8An4BHwCPgGfgE/AJ+AT8An4BHwCPgGfgE/AJ+AT8An4BHwCPoG9nsBE+adHOHHIRC+jAm/KTZTbopdRgU97+bXdTIDc42OcHi7hMNboYByXcNj3Ec9ot1c4FuJjjB4u4hBe08EYLuKQ7yOe0W6v8P4UH6P0cAHleEUHo7iAct9HPKPdXpmgj+9LzbHfMEIP51GGl3QwgvMo833sdg3x+39TZqI/0MXvGKaHzW9M9AGuY5gezqEUp8vM41OI/6Jf2ZUE1ujjR7r4A0P0EaWH+xAM0cNZlGA/XezzfexKB+6dTvN+NQPtQm3Qwz1cw3SJif5daqK/4GmpefwE7u/69Z1PIOuwMQdg+1inh7toi/XxF138jHa6uOX72PkCktxjPp9BbB/v6OEOrsb6+JMufsJpujjl+0iS3s5uaqCLRqePt/TwHa7AdpTD+9l+utiHlTJjVmN29pH4e9MEeuiiF33oxwAGwbnc/Mr7mHahnpZw/kAR24vBOT5QY6LMCNeSwtyPMAckE2BuQvg8LHwGE6775Q2+9Em1cs3TgmY0oRENqEcdapHqb0TIWM0kEWZbCB1oxy200EMruO4K1BinC64lhbkfYQ5IxrEG5oaEOSIZx9oO9FFM3kUoRAHykYdc5CAb31Z8We8LhcmPnyAVMkYXr8HcjzAHJGN4DeaGhDkiGUMnz7ML3ehBL9Idq/qejmUsYRELmMccZsExYzh2DMfQZ428ImOWOB6WsYJVPEeQxihdvAJzP8IckIziFZgbEuaIZBSz5D+HeehrcBHpjkHyHkA/+tCLHnSjC53Y7nvXVn+7gT4KOIcUogjFKEGQxghdvARzP8IckIzgJZgbEuaIZATZPM8c5EJfg/lId7SSdwua0YRGNKAedaiFPUe454l0/k4Pj6uJ/JvRglacRRCGXg/qGKaLF2DuR5gDkmG8QCk9nANzRVLL86xDPfQ12Ijc4n9/f7v/FpN3EQpRgHzkIRc5yIbbx1brM5yr+Twe5/79BR5XH/n3YwCD4Fo4EEOvB3UM0cVzcF0oXIvIEHjPFY5z4bUlPB/p5Hl2oRv6GuxFfZp9rJLhCpaxhEUsYB5zmIV2wPygME8om9DsE2kXej1lud3M85isFXpYxfOA9KHXgzoG6YLPTcK1unB9KIPgPCi89wrHu/Aak1nyn8M89DW4iHT7GCTDAfSjD73oQTe6oF0o5geFeUKJbtGH7SexF+1Ht9k+7H66/PhE9/g/A/TRSw8D4L1L9OHaOTuuTYTzofAeLBz3ks3rLge5yEM+0u2jlVxa0IwmNKIB9aiDdqGYHxTmCWUDdlvicob9XO4x0sRnw2bY39H99LkFZfTTxXKsDztnx/WicI0inBeF92KpJX9XXawPzp1CxmmPdo6vDoQQRgQ2X+YHhXlCWYfdls7S7WaQXoLWhxtmNY+f+QjhGl64bhTNm/Oj5CdojN2mt/N6N9vtpJL38ipUowZnMO10odkxPyjME8o7p48I2126n8vtwN1u193nGIT1Kc0F+v3CM8xiDmGyjuA2rsRcZdmGu7iH+3iAh3iEVKOD+wzp/SKC28jiWONvxPNlflCYJ5S3Sfrg8Xw8j9ucky0Tu9GfUz2mvXhbJseFfa86yHot6sBz0ePdPIP2YbvQPtaxgSg28R4fkGpMkj9zS4Y5JsNck2HO6aOaWCfaSyo2a7tP2OmRxxnvVNd1X13q+T1IY5LcpzR7zGAWc+hCVinfAeEgEo+PI2w7imM4jhM4iVQjg/t8QgfMwZpJTMVEyEyPE5dmrnnr0tKfLc3bXkvpUrNPti1ofWRUGJOJLBxANnJRgEIU4Qw58/nZ8Dna8HnaXEUbrkFwHTdwE/83+G5Cv6MwGciMmSHPRbpawjKq+TlZtpp5Ksl+J2h9VJJ3FapRg1o0ognNaMFtcmN+yTDPZJhvMndwF/dwHw/wEI+QalSRdQh8h2cqUYVq1CCfv2NfA5prsmzt9mRLtyd73Oi2oPXRQQ4hhBFBJ3rRh34M4Bl5zWIO83iHdWwgik28xwekGtpFJtrZrwMhhBGB+xoIf0Yfbke2B7tM9Zj2+m3aR+I4yFwX308YvqcwfF9h+N7CHMFRHMNxnMBJpBqZnM/1GHlK/pOYwjRmYIcek5qtfY3r0r72beaJt9nt7tL+ni6/plFDxmfA93eG7/EMc+KG7/VMG65BcB03cBPbHRnsm4ksHEj4vbDTh3Zhc9btuu72Ydfd/ew+X8Pxsd08P2c/ey3H/yE0lahCNbRzd6TK2HZjl2GnH7cTvQ/fh5vqf9fttVw7+XcghDAicMdWfWgHmr/L7mvz132U/Vk7ce/br39KIPFaTv9/m37+zIY7bMbu693N2d5ul+5+dpsu7fZ/ANwFBAc="
    },
    {
      type = "tilelayer",
      id = 6,
      name = "Decoratives (BG)",
      x = 0,
      y = 0,
      width = 100,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHt3EdS3FAUQFFBYVgEYLJJgw7bAUywiR502A45gxkQ9kSwPeiwAu4C9JhIdLlK91fdyXv1W+hoTpJ4FFBAAQUUUEABBRRQ4H8RmOxLkimaphn6RrM0R/O0QMM0QqP0lcZonCboL/0jTz4CG1j+oJ+0SVu0TTu0S3u0RMu0Qt9pldZonRb6k2SRPPkInGF6Thd0SVd0TTd0S79pnw7okI7omE7olPb4Fr/8Hvl8jJx+5c7vkZOkP6OAAgoooIACCiiggAIKKKCAAgoooIACCiiggAIKKKCAAgoooIACCiiggAIKKKCAAgoooIACCiiggAIKKKCAAgoooIACCijQa4HuQPoTW8zb1An26becZhWofkn/hRLzMlWCffotp1kFmoF3jXmdGsE+63M/uj8zwv/xoFmao3kqynkKvO+ZP9BjsP9Mn038t2ibdmiXinK6gXeLeZs6wf4zfS7xv6JruqFbKsqpDqa/aYl5mSrBPv1WPtNn/F/old7oDxXlNAPvGvM6NYJ9UXx6/Z5Pgfc98wd6DPa9/juL8rxu4N1i3qZOsC+KT6/fszqU/sQS8zJVgn36LadZBZqBd415nRrBPutzvV8MgXcRzzxp"
    },
    {
      type = "tilelayer",
      id = 4,
      name = "Castle",
      x = 0,
      y = 0,
      width = 100,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtnGtTFEcUhieQ/A3NovkKaLyAl6r5JQlg8hXvF0Cr9pckC5qvSLxG0Kr5JYlg8tWYeIskVuV5Jxw9aWd3WXYGsceueunL9vZOn7fPOX0bzg4kyY8bODKQtNbBMpgFys8OEoOwPCxbGkgengKjA8kE8QT5iSdgdBAUlG2mzsXBJLkEnvN8fw0kTYF8OgN4rnQOJD2Eyz3W76Hp0qqepb/nwB/0+SjyXwF/gzmgPH1uHQUqW3HlYdl1uDgJRpA98QT5id/BCHwUlW2mzm/If+9g0jzI8xkfY8h0HDAeUp4h7UUQx3qs30vbZdW9Bw/oQ4K8NRY1/v4HxlSLfrT+gYv74DI4JhSUhd8tyj/+JJkYhqdpsAgeg2E4KypbRH7XwRIQH9KLZYDepoyVnrgoS15VtzMOD/RPulHIR5FMqyq7gcw9ppH9SXAKqFx6sRU7VbUMy2x/Bh5mwdx75MNskWLPR5h+hU7gizLsX1amDHZSW93sVVW64Nv1fPg0Q0Q+PIOXbA8+5CpYp1C2NdbAmMv7uELsZbSdac+B/a6Vkc/5OFEDLjTGxuHhffsPk71i40O2amxjbiHdWHbPGatuqF9mr7rpRz8yMBm3iz0f4kB58aH6iqGiKVslHbGx8wDf3s8z7dTvmr2STW4nL5X38/yd2tVnng/J3qDyXXCwG3wOGoD1UMocPL0SKR/MIRPWVglrqx3BR8jNVzzX12ACTAKtAVn7pMdj5YPBaDag0zjeLv0wW2W8fAcH34MWmAfoccraNH0d6XpwBj5mwRzYSXyMYceEn+HgF/AQrAL8XMo+QfogUj6205/L3rSD6YNihkbzLvFp+DgMDgHGTcq4SRk3KXs26RXQj85+SN8t0pN+nt/ak71pB8+H0i/Bn4D9zjz9gjR+pIk/afbzLB/id01+Pu6nH9ZOAz6G2sDzYXphfIgL9ty115t8AeoWTH4+7kcG1o5s1VQbeD6MB8XCTXRCa8KPfLxdL5fBh2zVQhsYHzccB9IT8SFforXgN+BbEHPgTCFhD1vrrMrnV6v8xlobhHyIgzsb3IgTrc+vgR9AzGGcycx2rT9kr9pBNk2cSPYG+Q3xItTFXpW9/rgJv2Ew/yF71Q6qc2ODC81vbZ5r3NTFXpW9/njagY8GfHSaX4kPs1uK1dYzoPsMdbFXr+jrOmAfohT/8WWBfTf9kK3qNL8SHwbxobYOAN1nkJ7UwZ+XrR+s394JxodsVaf5lbiQ3AXxobZ09+U8MB/3TuORFZSpH3a/J7zLw52E4js/lBfV9fdKdA8Jft7ssUUm/ne6s5377bJX7SB9kH4I/l6J+Y9lOGEvMfqwnesP2at28HwMc7bBPbqUu42p+Q/ulTS5V9KMnRCz7d3ifuRgbTfgo9v8Sr5DwPalT4DdKyVuYts+8sFaQPIsgw/Zqk7zK/EQ/o75lyU+u17weVj/Q8/b2O0Wd+vnLmS9GxQFa1u2qt38SlwJYRB/dVl7qO8mq25xKKcwb+eqYbny1vYqsl1rA3ElhEH8nQB1WHuo7yarbnEop6K8zlWLgrWt8d8N4ffF30f9eLvPbrIM5dRL3towHegUyz4JVkfro7rpxyP6rHm+3n/ZC3QGZzK0uBf5h3WtjQbtDnXBAp8LVs/WR78y1+J9kDRsO7a8ONgDtEd0F5idNhla3E+/rY1J2p/qgjU+F6yerY/0jDZW+nmWnf5dcSB7cA/w7kvGXkVm8is7lg1a6BF6Lt7BqY3Nksyv0l/eecnYZ8rYq6iMj1V+x8b/ZmPp1Di2VM94Deh88Dj5WIP4eEQf2ZvI2KPI2KuojA/J1jBPugj2uY9nkP8s4O5Vwt2rhLtX0QbxsefTJGFvImOPIuN9vsr48PL38i5KcxbV4qyxdRaIiyXGidlT7iZGG+TH2dPOjA/0o1m237D2vNw9N0Vp5nutW+Ac0N6ut6evI+ZDZz28f56xP5SxPyT/URkfXu4NfvcAenkQHALK79+A0pzRtm6D88DrBnfbE+62Rxs0dk/DwynA3l1mHbUxXWYsORsmSZ+Dh/PgAlA4Q9kw6RHA3ZIW931aF4DXDd79SHj3I9rgbZXvZJk8WFviwDBP+hZyvw3uAAXxMU36JNDnOj/XfHcd+6TzfQsPKIs1eFvl+2gyLDOWjAULz5D7c/ACmK0KY9Ye6Qq4D/Q9uMhjpWMMRbZK/SyTB2trEi6YL70JBz7Df4BDQLqhoFicKBa4O5n/nxLsVP6OGrYqzStG+mcfPmMUjACtBa2bJsMyY/HBHLbwnMP0xvt48XEE+ft31I7XiA9xUfV68Cl8mOyNe8XcY8iD9/Hiw99/4T21hLlu+l/NOP96f661YJXrQemHfPQQCANntfm9Hu/jxcc4QEfy90011409eH++CB9CmTbKtyU+hKkCue6nTPA+foH8DMCH5PfvY+dC/fP+fFo+pAsf+o6X8WbTuoPLmiLnQ3IOIV0QvI/Xb2m+y9qoFndL1F/vz4fhQtisjHupp30Z7q3nfKwRG/ZprgukN0VBe7vsHdTibon67/ciepHvVuqajrxExvPIXzgNF2eA5cM6q9Rlfd4s4irGMr8XsRUZ9/Id05HD8DDk0CBt8HWsTOdlOresQxhlzVH1uYdxNolMhakAVu5j1bG8P4uKnZMn+Iuqzz1CPhaQtcc8+RD6XHzwrlp+vm/n+rHzga/M99kXK/LjxoVik/kacvZ2iTOOhH31hL3c5CK4BFRH9eVrZK/srDZ2PphL5vvs3ea5Xq5bTTeQ6xBYBZMbmCLm3Cl/J03zYenDT0D1zLeLj71A95BiD6Pwob2rqua5njtxIPl7aP/kGTB9kT7w7kFex8rkP+pmrzTuvOyqSM8j14UA2j/ROx6mL5p7jW3UsbJH5OvCh9mr7eBjFbmubQHSj7r4j38BgDmDoA=="
    },
    {
      type = "tilelayer",
      id = 1,
      name = "Cliffs",
      x = 0,
      y = 0,
      width = 100,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtnAlX00oYhnvZd1nU39NjgQKyCejv6fEibUEWcfk9XEQoyO7ye+7z1n6eMU7SVtY7N3N8TtIkpOn7Zma++SYxk0nLXSnQ0ZLJdEIXlGEV0nJ3Coyjfx4m4BCOIC13p8AK+hehBN2tmUwPpOVuFcjjwQRMQtpe3a0X+vYiPpSgDGl7db/8SNuru/fjgHpRgUOYgrTcrALv2jKZ9/AB4orbZsUdk26/PQXcOnJ73xrmN43+9eN3jbHMwwzMwhzMw1fqxTf4nlA/OtnXBd0Jx4Sp3vX/qmU0V3nFsgjrsAGbsAUP2zOZR/AY4koeHyZgMvUjTqKGt++huYqN6w75fASfa8s5xnrzkFSK+JDWjySFmt93gOaV2jj7M/oaZ2w7h2eQVNL6kaROc/v2WzLZTmLVLtA427yYZX0O5qFeKeFhOW2v6snU0H7yUNk8mivvoTG2+bHB503YgnPwlV08+FjjMPXDJ1HsNsVSiqPGQbHUBEzCFFTQUnoesz6D9vJE9WMTf7bgTUx71UI/31qjO6HPj72o//EOxVKKo1ZAsVQJyrAKXWgpPXvAVz/iZHvC8TnoxT+RlsYVUCz1CfbhACrgxlOqG+aFlqfUjzOIa6v0zTY2T/1o3Ac7so02px06oBM0r9cNPdALfWB+zKi9grk697yNzZXjlSdpaVyBUfQeg3HIg+b1jtHRPNBSn8U66xuw2YDG5oly7mlpXIFl9H8FxFM/x3/S/nXNlzWtg7ad4MMpnEGj+RLleEMqFjvuoYFiIGlxDhdwCV9A+SQ3v/SM4xZgEZYgqeyh+yfYBxv/ad676gPLz/KC5QmcwgD9dDP5km6uLaRisWMbOlj8M8j6EAzDCEgfyy8px/QGtuEtvIOk0obe7dABnaDxn+pC1QeWqid9aKptinkV7y7xfc/hBSQVjc9DGw9a7Kg+1uIf5ZEU95zAKZw5S61fwCV8ga+QVEbRdwzGIQ8a/2k8rn7YfLC2a53tGg++w4f38KGOH/re0MaD0Vh0Cl+QpMo06zMwCwPwAAZhCIZhBB5CUlnmZK9gBV6i79+wDKt8ro7L+XvN8YlV1r+w7yt8g++QVLrwNLT2KhqL5hDA0H27DhsgTyzvqjzfAizCEjRadtH3I+zBRMePZ3V65UMN+TPC9ofwCB5DUlF7NQkhlWgsKi+Q5xde85vliZvH2Obz2ya8MM1W0LgIJSjDKqzDJizAIizBc3gBvvJPzYMSy9D6j2gs2oMZ8sRF7YiwscEWOgzSbwzBMIzU6UNcTffR+AAqcAhHcAJnNc5ZXsAlxBWLCStcR3D9Bzq7sWi0bujzMb/bxgZuLOzGvXHa3cR2iwkt/3UT33EX59SY2YqNDdx6Yet9tPf9oLGBGwu7ca+d5zaWFhOOcj1T3CuhFI2ZrdjYwFc/pvndMzALczAP57RRbtxr57mNZZGLVO6qGqcF5IfaKSs2NrA6EbdU3y5PonGvnec2lgd4UQF5Emr+Su2VckHqz/kXSz87+/FkAB7c8b0pT0LLX9n9bGMrjctybPQhLwZgBh9mYe4a/HDnDu05rEbjBLtm+w0hLSfQVmMrjc3458XyS8ppWOx7VQ3cuUN7DqvROMGu+arXcJ/+XuNzPctUAo2tjtA6xwX6sPzSKcdoDu+6irU7ypfNcl71TcqPJZVQn0/U71Lcq/5jAi2U65PUcVy3F9Lc2h3leOX5PNei/FhSyXPdIdYP/eZqHUEHi1fMixz7ovxpP64xteZYPsE+HEDFQeNs+WE5GeWOk0qR461OJx33X9ynHJbFkIpXJvksWP2NP+3HNaZug3bogE7Q+NrG2HrGRH6corPNiblzYFEvzc/Q8iW6f5TD6kQHazfKfBY59kWxflw5rGaKjanXOK/ljfWsidon+WDzU8oBPADlAWwOTM9YR700P0N9/iqPvtYeH6KZQKbfcO/feXSy2LSeNy/RV3MfpvtTTj7t+KDthjzSM0FVn2pL9fXVZx+4zuqSz/1co+ZlQi6q/8hRJccyinv/6r612LSeJlY/ejm5dJfWbr1wt9m+6NKeD5IPPaC5Ms1jhlxU/80DJPvpja1bvqQ6h8tGi3vrxUO7nFdzURvk0TXfIWxdS81/5EHzVCLqRVV7vs/mLKdqXmheJtRiOV5rq3L8UB/yRHO3A1qCvFioo0sLGrfCKWi+Q9i6lpr/cOepzB955Fs33ybxONTSyf3XBd0gH1h4kR8ao8+yVM5Ezz1vw2WCJ0/QNQdJxZ2nMn/kkW+9xHbNL8qrUIvleDUmVPus9lq+RGF3tX5YrCU9htg4rB1XKJoXdIv8MY+0XXOJwrZpflFehVrIURQugLmNAv1DwXyQzD4s1tJ4oZF3MEPV7aZ+F/1AgWd5CuSPCvQPBY0V5IP54i7VZrmxlp6Zq/cO5k1dd2jnVV/rFl89idYP+aH5QsX/6tupUz/nC91zpevNK6C+1i3ReqJ6IT/c+qH1PjbO4sUcuPOF7rnS9asrsEBbxTNvBfKsBbQuTFAPFFfKExfLe6yrrrRlssRa2Xm4+hWkZ/ApoLxvB+TxwjyZYv0pqH4cs+9EqC/BB8Yi2cEYP3Y5Ru9gunlBe49wgbZu0TPOducO9d6h3jm0OcQ51i1f47v2ELcp52s5xh601DPQbv1Qe9Uv8Id5kSxj9SzvmWV9WrRwTCu4eUF7j3Abbd9CtLhzh3rvUO8c2hziJuuWr4n+Xcifi+ht8yI5fqiPPnxifJjdBN5Tzvr0sPzVKJ7YM0OqVxYzP0XfadD9786PKJ92BL7vtW2+7wt1m+pIBTQvwj8v0+ilZxyS3tl4iQ/K7yoXU4Yc57Jn7JRfX8OH16D7350fUT5NcyM6Po5QtY/7XdZmxemh7ei8w/99sUMObMd3HsvlKxcjT9xzHeGB+86Ju6+Rdd/3hbzNbbPinj/hnt8pQTHGjxL1pwzKxag+NaJzo8eErL3vt5mWq+i4BhoLRrVy+wI9c+3GUe7cahk/fH8fPV8zn33XfJ+3Wawpndz3NH2a+bZV+DvrV22ODll/6UvcvkBzrW4c5c6tqm5YnHwaabea8cA99j5r77s2izXdZ9P1nqZPM98295mDXv5Oz7u7emhdMZNipzEYB/f5a/v/GKqxceuPcb3WB0B/e1X+BYbIVY0="
    },
    {
      type = "tilelayer",
      id = 3,
      name = "Decoratives (MG)",
      x = 0,
      y = 0,
      width = 100,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtmkuK3EAMhs10HpfItiC5RUMukUC2hnlcIYvAXCKBbGuTQC6RSyQH8DoXmMVUE1z+FjbTmrZklZGh6Y+ySvr1q7qnGdx1cYUD4UA4EA5YOPD50B0t6kSN8xx4uIp5nOdURIUD6zowvJzykafV7Yh6yNsp0q/cv5pqkKfV7ShBG3k7RfqVOQOyfuWnK1AP+emd7UZknEGyh46oh+xBm5aGhHmQtepJ8g7QRpbkaC22R89kD31QD9mDNi0NGfMga9WT5OUMyJIcrcUOmAfZQx8Z2sgetGlp6NEzWaueJG+CNrIkR2uxnAHZQx/UQ/agTUtDxhkka9WT5KUesiRHa7EJ8yB76GOANrIHbVoaevRM1qonyUs9ZEmO1mIz5kH20AdnQPagTUvDgHmQtepJ8mZoI0tyaMd+7LovH8pLUqfEd2Xf7JVeT8vkaXU7SpgHeTtFU+W3V133rry+lVl8Fc6jxJ/2zV495kGeDTZe7DEPsrGM2XLXZRY35fW3zOKPcB4l/rRv9mKf5Nlg48WMeZCNZZiWY59kUxELxQbMg7wQvovlhJ7JHprL0Eb2oE1LQ4+eyVr1JHkHaCNLcrQWm9Ez2UMf/L1H9qBNSwPPHVmrniQvzwdZkqO1WJ47soc+Ej67ZA/atDTw3JG16knylhkcx3jyuLbH99Jnvch1cUMoz8Adx/LkcW2P7zx35JZ6fYNnLFvSPaeV5448F+t17dOO5uHVY4mu78bzKOe2XuS6GGDqAP/Okk1FRLHqQI/fQOQaEGDqQMY8yKYiolh1IGEe5BoQYOpAj3mQTUVEsepAxjzINSDA1IEB8yCbiohi1QH+35VcAwKqA7/wfEZdXBn4HUVeuUykO9OBhO8r8pnbI2xlB8oMjmNK8rgW77YOcAZkWxWXV7svz4/t4eL/wcmt9fZ7J/NozfclvYfD0p3nrf978bx9seu/A2vPI3y9zIH3K38+LlMTu08O3MdM4iCEA+FAOBAOhAPhgLEDt6XenXHNKLfswI9y6+fy7V3ceQT/tF27"
    },
    {
      type = "tilelayer",
      id = 5,
      name = "Platforms",
      x = 0,
      y = 0,
      width = 100,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtm09vVFUYxo+tKH4F/kyBmTa6sC2JQAIuWOpXAG1HpiW6kJaNJsCiS/EzGCEUiC6kJSom4GJ2gp8B2kQKO6Es1EQ3/h7atzmcztw7nTtzZ9p7TvLM/Xfm3HufZ8573vc9Z5zbHuXvAef+AbH0BwNHB507BmLpDwZuD7qT/fEk8SnEwPmoR89/CKNoMAbGweGoR8/1eDbgTj4Hq+AF6PkDFfwBbqHBAlgEt6MePf81nEODGTALzkc9eq7HKBqMgXFwOOqRqMc+YrM9YO86DrA9CCpgGIyArOXZa4wfYBW8AFnb28nf/wi+T4HT66iy/QRMgWlwFsSSHwPfrPNdImYeAj9zfAdcBzfATdCJ8i1tX4lxeSqVD+H7EZiAq0nwF/vKMa2AJ+ApSCv7qVMCQ8Ds3SH2y8Ds3hJtL0c90qjcuG6/3yNwphxTBQyDEZBWPob3CTAJzN6dYb8GzO6VXkcvcAAUoZThbQpMg7MtcBhyYv1D52sZ2wrbLuKx9LgOboCbYKvF+od9z/qHHcft1hjQb3oFPAFPgez22x7eYT+t+Pbd+lrad+L1xgzMSwNs8zAYAbLbn3r4LEWPEt8fAlasr9lx3GZn4Ds0+D5FB7uLP37onPU130fqRGxo94vb5gz8QA6cfLgjH+4W2deckfW1GnqajxRjw+YcdvLK5/B/DsyAWWBzRte8vlVBK/m/7fhunXzWIrT1LhpozogcrCMH68jBbio2nrTju21qLJ5IZOBPcq6aM2KOwjFH4Zij2FRsPJHvlhSL+/G5cpTNYnbV8+uWOY7j06u0Y7McNsthszYVG0/kuyXF4n58rhxls5hd9fy6ymHG8elV2m+hwwJgTI+lTxjwY8I+eaRCP8YSdmMZxJKdgRV4VI48Swnj9CxtFfm7yl91IkYI84pF5jTLuyt/1akYIY4hWZRY+66f3z2IzToE5NNbjjcpv+uvZ1hC10YxQ3guxgrJmvn5XfnyZ0ANWI43Kb8brmdoFDOE52KskKyHrs7D/09AaxLaGdvNt7rC95OK2cWkOvFadgbMt1pO0cNyJ2YTw7yHfxztWjZdrI8ktWK5E7OJft5DNtI/jnZtbT1CuzalXX/3PXQ4Ao6CY8D395K0LcI1cWE25SH7hkdNfCfZF/lVtk3yd7+grs97yKeufwkee88gu+b7fBWOh0FRbJm4MJuyj3ysYT/7oZ8k+6J8rdZH2TbkOOlY3KuYH3GH419AmfbsGWTXfJ+viPONFwbd1ePg3wF39S64IDQ4d5zzYT07py1r0qvMUVWZF6nafFXI/SrX/HrN9teUK+bnRbg/Af6D03vgotDg3AnOh/XsnLb8T0A6VJmrEtbmqwZdnZx8ndx8nRx9/TnXxrx6zfaLqUT33hreHX1B/8msM2dVZ+6qzhxWvXt3jC37DFwKuB5jXBoH/Cez/hhdKuxrjcNoUM9vI+53ngHTZQYNZgX4L6PDFJgGrZS0GLOVNrZjnWst8rOVdzM9FtBiEdBH6jXu02qMY3H/Vu65XetehpevPQ3+8PY79U7SQ7DxY557CGav0u4zQd3JLjxX2n3zvr7rDece8J6/5/Cu0sPGD72n+scK0PrtMn0mKb5rN+bPm88s9/sNHu4D6aE+0u3yvtc/7rH/sn8Q82n9tjCNJs1yVUWxV74m3dZD7fv940f49+PCpHn7otirN/ld7gZvgbzKr/SNu8SJyoUwrm/E7sQl1WbPUAR7Ze+etx66L37vy3id/rIRuzPWV+2Zwm2R9PiA3+mHOfaPkOtWjoukx1docbkP9dB/oAU/h499m6NPzbWi4Xatcx8tHgR67IGHvaAEhtY58ecftOYkab1JJ7jQf6A1TyjYf52J6+dmdrgeu3cxngO/nIKD00DzGY3mO7TmJGm9id9W3I8MRAYiA5GByEBkYOcxYL6b/DfB1sRpzYh8W9+PC88l5Rx3HlP5vJH5bvLfBFsTpzUj8m3DdST+uaScYz5Pn99d/gcBqmOM"
    },
    {
      type = "tilelayer",
      id = 7,
      name = "Foreground",
      x = 0,
      y = 0,
      width = 100,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHt3Ed0XFcZB/C7xDWwoSVO2Ue9uNvaQwKsIeGxj9Utl7itwjkEG1hSEh57rFEddzurcIgJS8pJ30cadZc4Nr8hGp8hGsv2oBkpo/ud87P6zLz/N/PuvW/8XgixYgIxgZhATCAmEBP4qiQwuCWEDEMMM8IosVYngUnZ55himhlmibU6CdRvDaGBRppopoVYq5NAp+y76KaHXvqItToJDMo+wxDDjDBKrJVJYPKJkA7SST2TW32N10Faj/EiNYanhXvz85BjimlmmGU91PWNoeNvvEultjenBxm6aEDWqed/2kUDxu7UfCot3L+eBb8XGmmimRbWQ72uD7/kNGcq1JMpPRiiGxmnnvepfVHaTSPmUam5bVrI2+so6F3w+6GHXvpYD/U9Pfg+L/BihfoxrQfDyDZtwj4oNS6kPTRhTptaZ6SFvAdln0EPg78LI4yyHmqTHmxmC1sr1I8ZPZBp6nmeNmM8SI3RaS/NWF+k1nxpIe9J2eeYYhp/H2ZZD3V9g/GDd/k7ldhmWaae32kfLRibU/OltI8WrPVS6++0Evcdb3NpAnN6MEY/rczpwRj9tDKnF2OxH0uDq9B35vVgnIO0Ma8H4xykjXm9GI/9qFD6S292QQ+yDNDOgh5kGaCdBb3Ixn4sDS5+JyYQE1hzCby2KZxacw+qwg/or5tDeIdHrV9sCuF1qlFv12A/vuV427f5Dt/lSZ5iG/na4P2cjY/xns47enG9Sv344hHGf2MCMYF8Av/YEMI/+Rf/JlZMICYQE1grCWzbGMLTPMOzPEe5NfG1ECbJMcU0M8wyR6yHJ/CS/F/mpyT8jHKrznhTTwONNNFMC63EengCb8j/Tf5Iyp8otw7IvJMuuumhlz76qdU67b2QM/yKX/Mb1sK2npX5IBmGGGaEUcao1XpB/i/yA37Ij1gL2zoh80lyNZx9qZy3yH8rT/B1vkGp36v29+rs6+pp+D/2edV+zF+V+zvteMyZBxyTadsQkvx2jPs4T9vGL74+oA+ddMV+rGqbWxf7cVYfBsnEflSlH9YQiXlrYq6UGJ+TOfK96F/sx4Q+TJKL/ahKP6zrEmuJxPw1MWdKZmnRi77FftR5z6CeBhppopkWWmkj1solYK2dWN8l1hSJeWwyQ7Ne9C7244C8O+mimx566aOfg8RauQQc/0ia9KCHYaZp0ouexX6clfcgGYYYZoRRxhgn1uMlsNzxp3nHoBr1oJshpmjUi+7FfkzIe5IcU0wzwyxzzFOr9Zpt+3kVt884Hsxz88emki4y5LDWSMxvk3zOdd7jrKeBRppopoVW2qjVelsv/lLFfhRyrNeDTgaZxPovseZICj+PH6ubQJ0eHOAsE1iTJ9aBsR/acMz6+TgnOMkpyqn3jAvv8wEf8qD61Hj+vB68wp/5lOf14pXYj/9Gdln+V7jKNd6inHrSuPAU23iaj/TkYz5Zpjfl3E+t/80d+X/OXe7le1HmePJjPfgJL/Eyz/AszxHr0RPYI/+97GM/HZRTv5f7H3iDN8n3I9bjJ3BM/sc5wUlOUU69J//3+YAP+YiP+YRYyyewa0vo2M0eLsv/Cle5xlvEqm4CtzeHjs+4w03P31vxOVzdBnzp3i7qwyW8Njp2OK69c40c23aO+pJr/jjPLTi3Kjifp+brnPnUeS7k51UrXO1ec9vZwU52sZs97GUf+/mm/w9e+L/irhuw5Jo/zj0MzncLzrGq+bqhDze5VYF+DMj6EIc5wlFe5RjHOcFJisu1HJZc88f5oME5iMF5bzVf243dO9i5gmP4b93W78jK+hznucBFLnGZK1zlGsXl+hpLrvnjHN3gvNDgXMSaqQHP/0Mc5ghHydchuR3mCMvVo+57im9jQdY3KMwXbvv8M+7wOXe5R3FlZO46G/9zzZ8xX4+TpVYqK//iseLiYj/O6cN5LjykH+Xse9rNEbZTmC/s8vlu9rCXfeynuHIyn8L1Nu5f82fO5/MsUCu1IP/iseL2Yj/y23dMJsc5wckv5VPY/nL2PQNu6xCHOcJRXmW5+yt1zR/XFwjOaQ/Oo66Zavf8Lx4rdhW9Hgpr86uyukapKmffk3Vb5zjPBS5yictcodT9lbrmj2s+BNcZCM5tr5kakH/xWHG0qB+FtfldGd2jVJWz7yl1O/nvFe8jrYOCddD9KnXNnzF9GCdbQ/3I2uZSORSOldwP5AGflLPvecBNhRsey01ucRvHCe7XfwAbFB62"
    },
    {
      type = "objectgroup",
      id = 9,
      name = "Environment",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 928,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 816,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1312,
          y = 160,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1216,
          y = 256,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1344,
          y = 176,
          width = 48,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1392,
          y = 336,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1328,
          y = 544,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1232,
          y = 608,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1280,
          y = 624,
          width = 320,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1584,
          y = 0,
          width = 16,
          height = 624,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1536,
          y = 448,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1536,
          y = 240,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1440,
          y = 832,
          width = 160,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1344,
          y = 864,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1232,
          y = 832,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 848,
          width = 16,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 928,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1104,
          y = 768,
          width = 16,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1008,
          y = 656,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 752,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1040,
          y = 672,
          width = 16,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1008,
          y = 464,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 992,
          y = 384,
          width = 16,
          height = 272,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 816,
          y = 352,
          width = 240,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 0,
          width = 48,
          height = 208,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 208,
          width = 208,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 368,
          width = 480,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 0,
          width = 624,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 160,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 176,
          width = 32,
          height = 208,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 304,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 16,
          width = 16,
          height = 944,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 272,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 496,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 496,
          width = 208,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 512,
          width = 16,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 512,
          width = 16,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 592,
          width = 384,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 320,
          width = 16,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 544,
          width = 176,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 592,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 944,
          width = 544,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 608,
          width = 160,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 624,
          width = 16,
          height = 176,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 384,
          width = 16,
          height = 368,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 608,
          width = 32,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 832,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 976,
          y = 768,
          width = 16,
          height = 176,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 752,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 83,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 848,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 736,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 123,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1376,
          y = 560,
          width = 16,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 125,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1584,
          y = 672,
          width = 16,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 14,
      name = "MovingPlatform",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 144,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "castle"
          }
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 736,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "mountains"
          }
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1104,
          y = 512,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "mountains"
          }
        },
        {
          id = 86,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 928,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "boss"
          }
        },
        {
          id = 87,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 928,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "boss"
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 16,
      name = "MovingPillar",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 102,
          name = "",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 656,
          width = 32,
          height = 144,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "castle"
          }
        },
        {
          id = 133,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 704,
          width = 32,
          height = 144,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "castle"
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 15,
      name = "Checkpoint",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 71,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 864,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "",
          type = "",
          shape = "rectangle",
          x = 848,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 121,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1504,
          y = 768,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 11,
      name = "Spikes",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 16,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 224,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 576,
          width = 224,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 864,
          width = 16,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 656,
          width = 16,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "W"
          }
        },
        {
          id = 109,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1440,
          y = 608,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "N"
          }
        },
        {
          id = 110,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1568,
          y = 512,
          width = 16,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "W"
          }
        },
        {
          id = 116,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1136,
          y = 912,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "N"
          }
        },
        {
          id = 117,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1232,
          y = 848,
          width = 16,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "W"
          }
        },
        {
          id = 118,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 800,
          width = 16,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "E"
          }
        },
        {
          id = 120,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 672,
          width = 16,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "E"
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 12,
      name = "Units",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 33,
          name = "DarkMage",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 112,
          width = 92,
          height = 93,
          rotation = 90,
          visible = true,
          properties = {}
        },
        {
          id = 85,
          name = "Boss",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 720,
          width = 132,
          height = 125,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 108,
          name = "Ghoul",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 128,
          width = 76.5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 112,
          name = "DarkMage",
          type = "",
          shape = "rectangle",
          x = 1312,
          y = 160,
          width = 92,
          height = 93,
          rotation = 90,
          visible = true,
          properties = {}
        },
        {
          id = 115,
          name = "Captain",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 864,
          width = 80,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["title"] = "Captain Jenny"
          }
        },
        {
          id = 122,
          name = "Executioner",
          type = "",
          shape = "rectangle",
          x = 1312,
          y = 448,
          width = 130.5,
          height = 88.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 128,
          name = "Ghoul",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 240,
          width = 76.5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 129,
          name = "Ghoul",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 464,
          width = 76.5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 130,
          name = "Ghoul",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 464,
          width = 76.5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 13,
      name = "Events",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {
        ["exit"] = "right",
        ["map"] = "mount01",
        ["method"] = "door",
        ["onTouch"] = true,
        ["section"] = "A"
      },
      objects = {
        {
          id = 43,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 128,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 192,
            ["Goal.y"] = 504,
            ["Target"] = 44,
            ["auto"] = true,
            ["delay"] = 2,
            ["delayIn"] = 3,
            ["delayOut"] = 3,
            ["pause"] = 2
          }
        },
        {
          id = 56,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 1104,
          y = 496,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 1168,
            ["Goal.y"] = 136,
            ["Target"] = 59,
            ["auto"] = true,
            ["delay"] = 2,
            ["delayIn"] = 3,
            ["delayOut"] = 3,
            ["pause"] = 2
          }
        },
        {
          id = 57,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 720,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 800,
            ["Goal.y"] = 600,
            ["Target"] = 58,
            ["auto"] = true,
            ["delay"] = 2,
            ["delayIn"] = 3,
            ["delayOut"] = 3,
            ["pause"] = 2
          }
        },
        {
          id = 89,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 912,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 280,
            ["Goal.y"] = 760,
            ["Target"] = 86,
            ["auto"] = true,
            ["delay"] = 1,
            ["delayIn"] = 3,
            ["delayOut"] = 3,
            ["pause"] = 1
          }
        },
        {
          id = 90,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 912,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 376,
            ["Goal.y"] = 760,
            ["Target"] = 87,
            ["delay"] = 1,
            ["delayIn"] = 3,
            ["delayOut"] = 3,
            ["pause"] = 1,
            ["replay"] = true
          }
        },
        {
          id = 91,
          name = "Translate",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 848,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 448,
            ["Goal.y"] = 872,
            ["Target"] = 102,
            ["affects"] = "Player",
            ["delay"] = 2,
            ["once"] = true
          }
        },
        {
          id = 93,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 672,
          y = 544,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "item",
            ["name"] = "health",
            ["value"] = "md"
          }
        },
        {
          id = 96,
          name = "Teleport",
          type = "",
          shape = "rectangle",
          x = 1568,
          y = 752,
          width = 16,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["exit"] = "right",
            ["map"] = "mount01",
            ["method"] = "door",
            ["onTouch"] = true,
            ["section"] = "A"
          }
        },
        {
          id = 103,
          name = "Translate",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 880,
          width = 16,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 448,
            ["Goal.y"] = 728,
            ["Target"] = 102,
            ["affects"] = "Player",
            ["delay"] = 2,
            ["once"] = true
          }
        },
        {
          id = 104,
          name = "Translate",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 784,
          width = 16,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 448,
            ["Goal.y"] = 728,
            ["Target"] = 102,
            ["affects"] = "Player",
            ["delay"] = 2,
            ["once"] = true
          }
        },
        {
          id = 113,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 688,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "shells",
            ["value"] = "md"
          }
        },
        {
          id = 114,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 784,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "bullets",
            ["value"] = "md"
          }
        },
        {
          id = 126,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 80,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "stat",
            ["name"] = "health",
            ["value"] = "md"
          }
        },
        {
          id = 127,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 816,
          y = 80,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "shells",
            ["value"] = "sm"
          }
        },
        {
          id = 131,
          name = "Cutscene",
          type = "",
          shape = "rectangle",
          x = 688,
          y = 928,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["checkpoint"] = 71,
            ["quest"] = 6,
            ["require"] = 5,
            ["scene"] = "cut06"
          }
        },
        {
          id = 132,
          name = "Translate",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 880,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 656,
            ["Goal.y"] = 872,
            ["Target"] = 133,
            ["affects"] = "Player",
            ["delay"] = 1,
            ["once"] = true
          }
        },
        {
          id = 134,
          name = "Translate",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 784,
          width = 16,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 656,
            ["Goal.y"] = 776,
            ["Target"] = 133,
            ["affects"] = "Player",
            ["delay"] = 1.5,
            ["once"] = true
          }
        },
        {
          id = 135,
          name = "Translate",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 880,
          width = 16,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 656,
            ["Goal.y"] = 776,
            ["Target"] = 133,
            ["affects"] = "Player",
            ["delay"] = 1.5,
            ["once"] = true
          }
        }
      }
    }
  }
}
