return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.3.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 100,
  height = 60,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 17,
  nextobjectid = 116,
  properties = {},
  tilesets = {
    {
      name = "strangemountains01",
      firstgid = 1,
      filename = "tiles/strangemountains01.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 64,
      image = "tiles/strangemountains01.png",
      imagewidth = 1024,
      imageheight = 1024,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 4096,
      tiles = {
        {
          id = 1678,
          objectGroup = {
            type = "objectgroup",
            id = 3,
            name = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            draworder = "index",
            properties = {},
            objects = {
              {
                id = 2,
                name = "",
                type = "",
                shape = "rectangle",
                x = 0,
                y = 0,
                width = 16,
                height = 16,
                rotation = 0,
                visible = true,
                properties = {}
              }
            }
          }
        }
      }
    },
    {
      name = "strangemountains02",
      firstgid = 4097,
      filename = "tiles/strangemountains02.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 64,
      image = "tiles/strangemountains02.png",
      imagewidth = 1024,
      imageheight = 1024,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 4096,
      tiles = {}
    },
    {
      name = "background",
      firstgid = 8193,
      filename = "tiles/background.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 32,
      image = "tiles/background.png",
      imagewidth = 512,
      imageheight = 512,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 1024,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      id = 2,
      name = "Background",
      x = 0,
      y = 0,
      width = 100,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt2XfUz3UbB3Cys6KErNtWJJFS9ojKJiujbMqWlhEyojKiKHtm05CRkbJTNpXRsEvDKLM8L+c8zlFP9/ndqvP78ty/P17nc5/fH/d1fd7X+ZzzPed6Jl6cns9cI8ZExYkzlnGM5zriXXZeVJoylKUc91OeCjzAgzxERSpRmSpUpRrVqUFNHqYWtalDXerxCPVpQEMa8SiP/UVPV3oGnfGVWKrfZSznw2ju05gmNKUZzWlBS1rRmsd5gja0pR3t6UBHOtGZJ+nCUzx9MSue5Tm60o3u9OB5esayeezR716+4uto7tOL3rxAH/rSj/68yAAG8hIv8wqDGMwQhvIqwxjOa7zOCEbyBm8yitGEerP/r/M4r9ff+J0LxMn61/eZwEQmMZkpTOUtpjGdGcxkFrOZw1zm8Tbv8C7vMZ/3WcBCFrGYD1jCn99sbJhHBtlnJBOZyUJUNPNYwUd8zEpWsZo1rGUd6/mEDXzKZ2xkE5vZwla2sZ0d7ORzvuBLdrGbP7/Z2DCPK7nPN3zLPvZzgIMc4jBH+I7vOcoP/MhP/MwxjnOCm808Lb/6+xSnL/vtnL//6s1G5vG/31h//i2hnBKRmCRcT1KSkZwUpOQGUpGaGy/L9tIM0l32W3RvNjKPmM/pr/zT//tvn0FnHZlH7JhHTGcSdP6xZR6h3knQuUfmcW2cQWcdmUdkHlfzGXTWkXlce/NIrM8kXE9SkpGcFKTkBlKRmhu5iTTcTFrSkZ5byEBGMpGZLEQR97JM4pOAhCQinPWDzjom8ujzVm4jL/m4nfzcQQHupCCFuIvC3M09FOFe7qMoxShOCUpSiqxkIzs5yEkuchPO+kFnHRPh2COVjgp2j3WpftBZx0Q49kiNo4LdY12qH3TWMRGOPVKvqGD3WJfqB511TIRjjzQhKtg91qX6QWcdE+HYI62ICnaPdal+0FnHxJXukU7yS9Qf90hnOBsV/R7pm6h/b4/1T+oHnXUof2ePdBNpsv5xj5SeW7JGv0eKe3GXdHEHTHwSZP37e6x/Uj/ovEPJrcc83Mpt5CUft5OfOyjAnRSkEHdRmLu5hyLcy30UpRjFKUFJSpGVbGQnBznJRbjrB513KBX0+AAP8hAVqURlqlCValSnBjV5mFrUpg51qccj1KcBDWnEozxGacpQlnLcT3nCXT/ovENpqcdWtOZxnqANbWlHezrQkU505km68BRPX7wjz/IcXelGd3rwPD1pTBOa0ozmtCDc9YPOO5T+enyRAQzkJV7mFQYxmCEM5VWGMZzXeJ0RjOQN3mQUoxnDWMYxnl705gX60Jd+hLt+0HnH1HS9zmAms5jNHOYyj7d5h3d5j/m8zwIWsojFfMASlrKM5XzIBCYyiclMYSpvMY1w1Q8655hap9f1fMIGPuUzNrKJzWxhK9vYzg528jlf8CW72M0e9vIVX7OCj/iYlaxiNWtYS7jqB51zKIf0eJgjfMf3HOUHfuQnfuYYxznBSX7hV05xmjOc5Rzn+Y3fuUCcbL7/nd+yj/0c4CDhrh903qEk0mtiknA9SUlGclKQkhtIRWpu5CbScDNpSUd6biEDGclEZrIQRVyuIx7xSUBCwl0/6LxDya3HPNzKbeQlH7eTnzsowJ0UpBB3UZi7uYci3Mt9FKUYxSlBSUqRlWxkJwc5yUW46weddygV9PgAD/IQFalEZapQlWpUpwY1eZha1KYOdanHI9SnAQ1pxKM8RmnKUJZy3E95wl0/6LxDaanHVrTmcZ6gDW1pR3s60JFOdOZJuvAUT1+8I8/yHF3pRnd68Dw9aUwTmtKM5rQg3PWDzjuU/np8kQEM5CVe5hUGMZghDOVVhjGc13idEYzkDd5kFKMZw1jGMZ5e9OYF+tCXfoS7ftB5h/KWHqcxnRnMZBazmcNc5vE27/Au7zGf91nAQhaxmA9YwlKWsZwPmcBEJjGZKUwl3PWDzjuUNXpcyzrW8wkb+JTP2MgmNrOFrWxjOzvYyed8wZfsYjd72MtXfM0KPuJjVrKK1YS7ftB5h3JIj4c5wnd8z1F+4Ed+4meOcZwTnOQXfuUUpznDWc5xnt/4nQvEye773/kt+9jPAQ4S7vpB5x1KIr0mJgnXk5RkJCcFKbmBVKTmRm4iDTeTlnSk5xYykJFMZCYLUcTlOuIRnwQkJNz1g847lNx6zMOt3EZe8nE7+bmDAtxJQQpxF4W5m3sowr3cR1GKUZwSlKQUWclGdnKQk1yEu37QeUfnfr2VpwIP8CAPUZFKVKYKValGdWpQk4epRW3qUJd6PEJ9GtCQRjzKY5SmDGUpR1D1g849Os311oKWtKI1j/MEbWhLO9rTgY50ojNP0oWnePriHXmW5+hKN7rTg+fpSWOa0JRmBFU/6Nyj01dv/ejPiwxgIC/xMq8wiMEMYSivMozhvMbrjGAkb/AmoxjNGMYyjvH0ojcv0Ieg6gede3Sm6G0qbzGN6cxgJrOYzRzmMo+3eYd3eY/5vM8CFrKIxXzAEpayjOV8yAQmMonJBFU/6Nyjs0pvq1nDWtaxnk/YwKd8xkY2sZktbGUb29nBTj7nC75kF7vZw16+4mtW8BEfs5Kg6gede3QO6O0ghzjMEb7je47yAz/yEz9zjOOc4CS/8CunOM0ZznKO8/zG71wgTg7f/85v2cd+gqofdO7R2fffbGKboHOPzOPamUdsnE/QuUfey7U3j6Aziswjds0gMo+rV9C5R+YRmcfVLOjcI/OIzONqFnTukXlE5nE1+w/IgBua"
    },
    {
      type = "tilelayer",
      id = 8,
      name = "Sharp Cliffs",
      x = 0,
      y = 0,
      width = 100,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt2WdTU1kAxvEzo4BSU24KL+wfRZrUgNJmFI/6USRFegd31v5u61dwRinSwQYzq0Z94czWr7D/Q+5drtdAEoRo3PPM/GYkhpTz5JQbhNDR0dHR0dHR0dHR0dHR0dHR0dHR0dHR0dHR0dHR0dHR0dHR0dHR+Tpy02/7d0DEO1GOTb+I83/xTpTji73A/1k2bX1M0UMHgtiggyl0IKj7yFqYC/9lkh7aEcBLOphEOwK6j6yl09bHBD20wY8XdDCBNvh1H1kLe4b4wRAnf8c4PbTCh+d0MI5W+HQfWcumT8R/pIs/MEYPb4+J+D1cwRg9XICBCp94eBZf+vV+69mgj5/o4k+M0kecHu5CYpQezsOLw3RxSPdx4JllvZqD6kJ5Qw93cBmzXhH/xxDxX/HYEA8fGbqPg05BUIgjwe0+XtPDbXSZffxNF7+gmy6u6z6yklL/dh+v6OEWLpl9/EUXP6OCLs7qPg48DXTRaOvjN3r4HhePJX5WiljPDtPFId3HgaefLgYwiCEMY0T1gw+sY6oL5bGX/cOr+8hW5hhrpygiCKMb17HmE2LdpLP/cXYQS9IL+8jDMuaLC2544PWnfuyvKTd9QnKtJcv9QnbiJjZRHuBncF0sN/G5z9PCNUEzQmhCIxpQjzrUprhmiJkd7EbNkybGP4RmtOB8jvUxRRdca8kgHXRgChsI0kEHprCxD314GG83XChDKUpQjCIU4rvyz3ueJVfy/SWXMkkXLxGgg3ZM4iUCdNCOSfTwPnvRh34MuDJ/nnXOPGtYxQqWsYRFLGDe2JozgrkjQntc80vcQqww/qtYwzqe5lgfE3TxAn46aMMEXsBPD22YwDzjv4BFV+IzuLyHPkYY72EMYRAD6EcfetFjpL927ZQG+ijjjOWCGx54A6l/72vKOF08h48OWjGO5/DRQyvGUcj7LEKxO/EZLHVn/jwtjHczQmhScwENqgPUodb4eC+w9uhMnqOf19XE+IfQjBacz5E+1sw1YYwunsGggwsYwzMY9HABY6jlfdah3p34DDaqbjyZPZ+H8XbDhTKUogTFKEKhkXyPdj6OdY6y2P9vidc1yPgPYRgjie+7ciJuc10dpYun4FwoOYtI9j/JmiuZ55LPlhxV+wfvsxd97sRncEB1k2Ef6+qaAKtYwTKWsIgFzO9wZrKfZS1RG/vti7wmyxo9rONpjvTRbPYxQhdcM0nO6pLzoeRMItkHJWuvZL7LEbV/MP4LWHQnPoPLe+hjhPEaxhAGMYB+9KE3xTk22TWgs5eooxP7ffd98A4g6jw4QA/DYO2S6jbrO23OJpL9ULIGy2G1f/D+ijyJNaoEpZ7M+2hhXJoRUtcIaEQD6lGX4poiVT/2OdIUZP8Ibl+v5EofVoboYtXsw/pOm/Oi5Iwi2RflkNo/GHu7OrOPJtWZN/Pn7GZ+hRFBFDF38u9B9sLezUgw8bj7O2LZS3Vw63pKcoaXnBulGm/2R1nq0Gj+n8LnXaTbSSVzrwrVqME5zKbRRSbzI9nvH+igHUBmAttr1RPMYwGsFWreixu4aLqELtzGHdzFPdzHgxS9hHnMiHpcxHADBZ7E2pJOH9Y+ke78sH7OyiDuY/KD22vVUdSiDrwX9dkVTxxdKK/xBnG8xTu8T9HHNON/nft0I4yIqcaT3vdT1jjb+9mtlzlzf8+lTDPuM2rs1VqLeSygV3Vk0BGOGp/Oj+PcdgIncQqnccbY/bnyeMxH3q2/UYhpzJhinsQ8sUu2l+90lrLOU8luy7U+8sqZHyjAERSiGGVwwY1zjDPXz4LraMH1tLiELlyGxBVcxbUUfagcMrb+hifykG+aY8yW6WpFnSVQ7dmam5+MbTp7ea73Ucl4V6EaNahFI5oQQjNuMGY96EUfbuE27uAu7uE+HqToo4qxjqCC+1WiCtWoQantM5Ds+s65NzjZe8nlPsK8/wiiiKEHAxjEEIbxhPGaxwIW8Qqv8QZxvMU7vE/Rh+pC7VXd3C+MCKKIGR9/BnZbj9Jh9ZCLfTij+nDmqI91DEUoRgmO4wRO4hRO40yK78nzA4k58pjxn8YMZtV6ZesxVL7zWpXJvPlW+nCmhjE+h1rUoR4N6MJlSFzBVVzL4O8Wedw3HwU44vi9qGPNsX9v5exjp16+1T72M9ZZroLxr0QVqn2Jzu3ZbYyd82Cn7nQfqWOd5boZ/zAiiCKWZh/JvkPcaY7Y17kv8mZzIM6znHX9WRj8+H679ZFqrUp2+7+4sSBJ"
    },
    {
      type = "tilelayer",
      id = 6,
      name = "Decoratives (BG)",
      x = 0,
      y = 0,
      width = 100,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt0TdSA1EQANGFwhwC4ZFwgcx18EbCBTLXwXsEAeZO+EDmBDS5fkRJC6hfVSfzk92ZKJIkSZL0W0z0RNEkTVGSUjRNMzRLczRECRqmERqlMRqnD/rsifsv/o91drlBm5SnAm3RNu3QLi3QIi3RMq3QKq1936s3iuZ74/6L/+OMnZ7TBV3SFV3TDVXplvbpgA7piI7phE6/78Ut9rzHr3LnPSRJkiRJkiRJkiRJkiRJkiRJkiRJkvRHNftaz2vM69QIvKs9cv2t52nmGcoG3tUelcC+i8xLVI7hHslEFKVommZoNtH5b4jLU2Df98wf6DGGe+TZf4G2aJt2uugezcC+a8zr1IjhHpfs/4qu6YaqXXSP3EDreZp5hrKB93Z6Zv8v9Epv9N5F96gE9l1kXqJyDPfoZk+Bfd8zf6BH79FRzcC+a8zr1PAeHZUbbD1PM89QNvCu9qgE9l1kXqKy99APfAERzzxp"
    },
    {
      type = "tilelayer",
      id = 4,
      name = "Castle",
      x = 0,
      y = 0,
      width = 100,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztXNtSG0cQ3czKv5EEk7wKHGMMAVftlyQil1cECEi4VelLEjmOXwEDhphLlb4kNjh+xVg2lzh2VU5rp0vNeHYlIe0Cs3TVKe0OC9qds92np2eGkvK8JxrfKq/yHtgG5gE6n/fx6X/abratKu/FBNCvvAI+CzgvHAH9PmBpa+WaX3zP+xU4xr2dKa9MwHkwB+C+ggXAa8MW27z+MqyE550G3uCZR9CvO8B/wAJA53jmyogftu2IdrNtBVwUgT70JT4LOC+8BvrQr7a2Vq55hf7/yvfK9/wGH0Po02EA70Mw0mb/jl4DPp6BB7zjHvqW3sWyCbxTFTxH5QP6fBdYBEaVvc32+yYOP/MKefT3OLAMHAJ53962jP5bAVYB4oL8Ypu4UOBCXf2+vYgNh3GKfMPKR5pYU+cxjr4vAhMAnQ9fME5dJ5sDD4j/3sIl8sGx6Ex9yonEv/AJ6EwVsa162f2WlDWLV2nzIYFbos8quKj2QkMeAe/1vbpqeOfqz7hzRfgw23Bc5+PHDHBBdhX0w8bHWphL1Y/JN7bFfbpsHK+a+Ucn39EOH0N+Q0eYF4pbFKvIR5iTPUc1neNVM/3o5Dva4YP6nkHnn4ODL4AvgR6Acisa1y05yscwvXPAiH81+DC5+Q739T1QAMbC+wxoXPfAVT5a1I9OvqNdPtbE8W/g4HegAjz0634cYBwafHR0PNjq+KOT77gIH6QjhL/BwXPgBbDv13Uu2AX2HOUjTT0f0zHHBjNObeFzEr9zHxgE8N4EeG8CvDfBIrDkKB82S4qPhzrm2GD6yClQA0p+eHwCQEdITzq6l+toSfFB+dHtCEgu2C+YD+LiOKz1el/7XXrIa2RJxqsfIiD5YB5q+nhdjwlv+Oh+vPojAlLLmYNJzQlpCY0FfwJ+dpyPOTzffDjOSlzPKT86iIDJB3GwqRo+QuPzP4HHjvOR5vgjLr/ivLcmcKJ5IWQlXnV7/LFuqfe1kl9xrYp4GBR5LnOTlXjV7fHH2xg+muVXclxOoL/1ToXrGbISr7pdT7xr6a9W8ys5F0jn9LcGAFrPQD5y4x/t81GK4aNZfrUmtOMszHnra19m/GzMfZB10z+i1vIUo9b8RFwr15XQOqSa0DjXLc16e7P6lW1dCesH+7Drlub4o1n9ivnIgwf4StAPsH70ox0+1tF9XAdrVgtPs34l9QPxKzgCeA0pPsvFGz5SrV/VLP3N+gJOyis3fLTMB89zx31HXH7FOmIacZWVsQdZt/jgedW474irX7GOmEZcZWVsTtbNePW8CR9x+VWUfxzc+Mel5FcM1hM+p/FR1vzjpa4T0f4XrqGmnV8xWE/4nMdH/yDXepWBOXPioFfn+FviPUw7v2KwnvA5j4+yUm/f0nr5DFjxveoy0GoMaxdx+VUU6L62M6Tp1E+klxPgoQiMJ8hHXH4VBfKpYaPe/sDhukldP/CM/eChD8gnyIfMo6L03JZzyTmzRWDJcT56c553pLzqa+BQJRuv4vpd4q3yKutAKdy/663iPeF4uucwH6Tjb8AB85FPiItW/YOBfK+yAUyHe6rPxdOPDvNBcz1PwMMqsKLqz5sYH7K/KfcdgF/eAwZz4fk3GnR8DB6eAjO0t134xijph8OaTv00CR4mgKLYJ5kEHz26r3u0j0yDhxlgNhd+5xTa8jjuA07AwyYwC0jfWMQ1Sw7zIWOVbE8jXm2g358Cm4KPcRwXc+HP7+p819w3uOcwHzJWyfYk4xXbO/T7MflCrhGrTND+/x1gV++/cXWfGpstVpEl5R8l8Z4P3IJ+AIO3Qt8gm9I8TGnw/n/eo+bqPjW2O+CB99hTfOb2pPig9XK2Oi77jdR44oP/TwnvUXN1nxqb5IPOkx4P0ho32zzHmvYbqfHEh1z/8gFwdZ8am9Tzw4THg2Nao29b+KjpdT1S44kPuf5l1GEdZ5N6vqyRJB9c4zWN9VtqPNUT5fqXLJjU83GNuD6l37kIF7SG6kRrh62Oy/otNZ6M8t2srC0hk/qR10jCN6guM6j9Q9Zv71Cum7NrPBnVdrOytoRM1iKSilOmj5yqRt1kknQi1zg3r9kPa1fly+6ntCyNeQ/TR+775+doZR1FXsNtPBeVBUtj3sOm5xK2ertsz9L6kjTmPUw+TC231dt5jdyWCufOszBXSyZz3aT54L4+MOLSNPp8BpilNS6070E11sid6vU+WfEPmesmzQev99k34tKGaug4+cNfKryO24iPLKwtIZO5bhrxytQO3iPI/kL+cKbCn3HbowzGKzpOI16Z2sF7BNlfKH4N+efXWL/MEB+y1p40HxdZ75O19bv/A4A5g6A="
    },
    {
      type = "tilelayer",
      id = 1,
      name = "Cliffs",
      x = 0,
      y = 0,
      width = 100,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztnIlWGksQhseZAfe4JXkeTqKIxAUTk+fx3GtEISpme54sKqKoaJbnuX8xXaFoZyPhSk7bdc4XEIFo/1R3baPjWBuUZV3HGQYjYBdU3EH/RPfb8lj/RVAADXBm9RiobWP9y2AHjHqOM+YN+ieytggNCmDJs/vV32Bl6LADdj27X/0NJvWw+9XgrQ4NTkEDFK0e/7u99x3nA/joRz9H+oi1wZv0EWt/ZvNDwe0CbhfBClgFa6AEvsMvfoCfMf4xjO+NgNGY51hLZ1tKj9e4LYM9sA8OQA08zDjOI/A4E/0ei9ChAJasHn9sR0oPzusa+PoMnKvbNTxWSohjy9Y/+m51rPmpyrPP/Q5XeKwF1hM0sf7RPztxndwwdBhReTZrsYr7a6CU4pzewfN3rR59sW3owXUPyrFZj318fQBqoBWhyRc876uiYfXoySiWojgqr2KpAlgCRXCq1rNJMZbX8Y8D6FMDhxH7lYtz3lOMxpz51m4bxVIUR22rWGoH7IIKGFHrOZYJ948oe4LnPwXjfoC19Eax1DE4AXXyiaHueIp8Q57ll9DhKmavIuPc3OrRu/nYczJud19vFIyBcTAhzo4V2q/AWsIac27OmlhLb/NY7wW3u6/X1OJb+prYo/0KHKRYY9bE1q96sy2s/2u3u69Ha/9G3VbpvtLjgvYryj96qJeYVr/i2PHID2IgWosWuAY34Jsf1JNkfWkdPAcvwMZQ/PsfYd2P3Xa+8Sv/o753VWlyTlrg9gJcggeZ3uolpuXnHDv6mU78M437M2AWzKn14foScQjegnfgfYIePtY7A7KA87/2fuV1/GRC7VkU81K8u4H/7yV4lRDLFgzMBzl2pDOW4x+Oey7AJfmMuCWuwQ34RrXYBD3msb4LIO91973pHGYdeO/a84J49z1+ng/gY4rcwrR8UI9Fi1gb2pKJZdxfAau0j4ApMA1mwCyYAw8TakxbeKPXYBv8g/X9F2yBCuflbtDjK6rZhG/43nfwA/xM0MPEeqIeiz51OtDndg/sK0247kp1vufgBdjoYZ7gC9b3KzgChWzQ+x73Am1Ynzk8/hA8Ao+z8e9nYj1Rj0VJB0/jjR9oIusYb8G735jt2MYal8EO2AUVsAcOwHPwAmyAl+BVhB6flQYm1hP1WJQ+s9JHiIqay+TcoAamsbfNgFkwl3CGSDvBGtfBKWiAM3ABrhQtcA1uYnyDY0Kuf5lkeiyq+wbR9Du5gYyFZdx7l8YxIde/TLG82G9YD903iAn8zpOZIDeQsbCMe+/SOCacB0WD/GNb6MG5QZh/LOP3XgGrYA2UQEuLe+/SuJ7YjtMM0uNE6MG5QZh/dMVcfqCJHvfepcl6oqn1K9qvqBY0FuEjzCT+mYQmD8DUgD+bJs9fcW5VjPER0uKBl74unsZk75DnsNLGCSbmg2ycW1Vi/IPrS1TTSFsXTzLZO+Q5rLRxgon5IOXnNMvEudVZjH9wfYl7eP0y3neoXkZ609l0k6CFqfOJ9HvlVf7Btb6486PfWpDxunJNsaTihDgzeT6x7SMiXuG1D/OR3z3Hv6geyzE4AXWVXzMNpQfXZJJiaOnTphnVsOS8+JIbEOYfv3uOu6rHkgFZMKzyazljQnpwf7Cl9cB0Leu+mfUSMqphyf2YriPejcjVZQ2rF+Ocuup26sZU36f9SfanqAYwpeoAcsZa13I4Y169RJrcjxuqpxp6fojPr+zdJhn3Pnjdn4FlocO5gDSimaD24+r2Qs0FNXkGAl9Pqr6MyUb+H3t+iM9vTcSmSfZrhk1o0NT0aCbA80GTal6IemXNO67V3LWR//Pah/kH10vaPVwRayXFQ7IXdQyeud39R+kfYdqsqJ4uv6aotNg32D/k/EeUfxCkCfVuOdaaVf3COHOzeE/gg0y2+xyhNS3hsXXVm9pX/alFRUEhX7NIPUawZOj5QcY13lEv2j/YRygv5FiL+4U3MZo8wXo+BfNgAeS1ta+BQ9WbulS9qXJIL5GoqtdxX9FUk/MfPM8Z5h+kyZTbXTOZwYOzPeaJcu25LyitHtJLJM7V67ivaKrdDDmb16AFcD5sxp0jMta68tNdg2mtN8M5sDkDpgE+/5vVmHOE9iwZa6WZKbSWzlzN58P8JOwMoX4hz2XJfqG1P7Mnmh66n7Aeuo9MeJ25LNkvtNZfQ+y6uQ5KAGu9yXHlLR9Rsede0J/KIdbKlcBAf3iDjWcXZaxfpFxO5Yw8l34R9G9zyEVy0xF6yDl6rgvydYRRvUD9usPi0O2/5bB+j/ZHqvlyjXHMD2agpX/QftXup2fauXoOuXqu5YXrIefouS7I1xFG9QL16w4rQ7f/lsPhPdKDTPZFovL1iSA/zB2AWoQecmaKZ4bk9TfPsK7L6vMv+yNUTzvz42de7pPJvkhUHrLsBzMOcddscH23IWr5PGNHMXMVOrxRn3/ZH+HeiNWjY7xnxa0J1vnTKaiDsPfgWj7VYhpa3i+vtaW6etz/Y/Xo3rOi5k/wmf+0A8oRenBvlWoxywnaWj3ijdeSZjOrfpAL6msiz4JWRK+czgLSNOz190kPjjX16zTD1ixq5oDPVe7R6f4hz4LpiF45nQXkG/L6zfuoB8ea+nWaYWuWNHMwngnm3fU1WVOx0wLIa/PX/PcY2rGx14mTadaxH3r8B1JBWj0="
    },
    {
      type = "tilelayer",
      id = 3,
      name = "Decoratives (MG)",
      x = 0,
      y = 0,
      width = 100,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt2k1KA0EQhuFmxkwu4Tagtwh4iQhuA/5cwYWQSyi4daPgJbyEHmDWXsCFHSTGRW2GTE2/Vn8PNPQiEyr5KtXJkJRERGQKt21alq5B9r4a5SFSQj+z9wTk2rysO3tPsOjsfWTkPMi1eXnq7D0BuTYv5JnQd/Y+MvJMINfmhTwTasyDPBPIveKF3IPks80LOQ9ybV7IM4FcmxfyTCCfbV7IM4FcmxfyTKgxD/JMIPfKznlKd6u8hlyz+rnOtJjbewLy2XbSpHSa10PO4n5gHvnx2+tM67m9JyDPq8ucxVVeHzmL94F55MdvrzORX/N/mFdjI79m8tnmhTyjyb3ihTyvavx8kHuQ/N3PC7kHyb3ihdyD5LPNC7kHcwZLax8ZuQf72T6Dv/vIIvTgcaD/LkbowYtAeUTwOHEeNf6vmIx85taIfE+jRuTfCDXSvGLRvGLRvGIh34OtEfkeLM3rBO+P5hWLvl+xRLgHG0mkPDZN6QoOF+Ge+M5bgDwiadvxnuvzaLznqtWYecjhzpQHykZ5iIiIyMSu87opXYT8es7rpXQRzr4B+URduw=="
    },
    {
      type = "tilelayer",
      id = 5,
      name = "Platforms",
      x = 0,
      y = 0,
      width = 100,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztm0tPE1EUxy93+ikECsojuhBKIpCgCz6HiIAFogtp2UgCLPggRggFogtpia9EXPBBeCTy2EnLQk104/86vfR0nOkMM9NOZc4v+af1dmjGc3rPPefcO0L8H/yQQvyUUd8FoxkyhBg2or4LRrNjiNGo74GpMM/+iJw++KAfSkED7I/IOZditAiVoAvJ/oiabfggDxWgHfZH5MzBBxkoC82zPyKnDz7oh1LQAPujJm2ozW5ArWV1QjehbqgH6g2hdjtvwfoBlaCLFvZHLR7B3g+hsbImoSloGpqBZrmWbigvy/ZOombugD7g3x+hDWgT2grJH6/w3atcl7uyD3sfQI9hqwnouzR7TCfQKXTmwR/tuCYJdZB4dwvqInHvEN99xP7wjP79Dhpmj6kb6oF6PdhwXPkTmiDx7gmUJnEvmYC/oM5E/f8vzUAX7DYNzUCzPn6Hen4o0gG/izH9sQFtQls+bGiN73p+MP5Qv+kT6BQ6M8y4fZvojod1gMZ3PT8Yf+SUDxCbe6DehBm3nxI9c/GHzq80eq4x4fEaPnjjMV+l64dCzzWaI4VRGzLuvDX74SIFFfBe7RnpuUZzJK4NG8Nz2H8OykBZSO8ZrRP76/Wd8636cxf2V3tGGdg/C83bzIMguRtzNb5JMXpu7lGIArRj4w+au9WqxelYq8t11nFen6pBzBKIWSJrMwdo7larFqdjYy7X0fEpXp/+YRt+yJtrOtMkcM+vuThEzDjiuBEKukceBGudzvgjbYRTI/C+UTjkAvZ3KbyGBIf2d2lO76W/S88zqH08u5rBOsa1Qm1of5fm+l76u9bzDHY1g3WMawV3crDRe2meSfCztuvcatXl77gX3xh0buWW7+q4qGOZNbZxXAsPL/WHjos6llljG8e1atKG/5jiN9+9B7sPQkPQsKzO9+JOjuRa+0QHDrlTZzmv0q+18t0XFrvbfb4AHRvVcc3uTFZcYtkxybXaiNoT9rmT6tcmE5XXq7BQtqnOI9TZxk/K7onquGZ3JitOsWzREGsj0C8p1j5Di0o2YyPSeUy9pqSYzEIFSO9XWW1fwmf0Oqf3UdskSpZgz/vQb9h0F1pSshm7L53H1Gu/6YfJvClzv8oQewUoD21DRXxGr3N6H7VNrhtFcy6oZzL3slAGmoOivq+4sGyxtT6DMoDxY1npX/axTxqK9oteP9TcoOeFGWfW62Af7Q+9fmCO7AWpceLE1zr5Y9lct/+uH6q+yRl85jpKlD/0+qGg/f2umNV3zcADMj928Z7295XiVt81A3R+vLPUhUH37Rl/fMHcUHW8mhvwzWXtXeJ6LzIua2+jUnsXa/iDz0g0F+yP5qBdVvfwEd9WMKdWor6vRqPPizidQ/f6PGFQxsu9ff2sM+r6lUwM/aHPizidQ/fyPCHDMAzDMNcXeta3VTo/O2g3xj3H8KFnfcek87ODdmNx6jn+AS1CUeo="
    },
    {
      type = "tilelayer",
      id = 7,
      name = "Foreground",
      x = 0,
      y = 0,
      width = 100,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt10ly2lAYReE3NK1XgoUaPM48iXcCovUi0u0E1MIiTJydgGg9zskgS/B7lHVP1Td/9d+BSsYopZRSSimllFJKvX/bpvn0G69w/RZlzHd2+IGf+KVNnPeZDb7gK560h/NabNBGB13t4bxtg+8HXvGnoT2UUkoppVQ9+tbi373l+hXqfy9ssdUeSimllHqHdnfG7FHhgCNOOONy5/p19avXMOYBHvrwESBE1HD9uvo15OYjxBhjgilmmGsP6y25+QoJUmTIUaDUHtbbcfM9Kt3+Juo1+X7Aa7p+ifrXkB1GiLXHTbRkhxUS7XET7dhhj0p73ES9Nt8PeOjDR4AQEQZt1y+sV0PuPUKMMSaYYoY5FtrDakvuvUKCFBlyFCix1h5W23HvPSoccMQJZ1xw1R5W63X4fsBDHz4ChIgw6Lh+oVJKKaWUUkop9bFL+PdOkSFHgRJrbPRfbr2Kmx9wxAlnXHDFm/awntc1pg8fAUJEGOCx6/p19Svm5mNMMMUMcyzwrD2sl3DzFBlyFCixxkZ7WK/i5gccccIZF1zxpj2s593z/YCPACEiDPB47/p19Svm5mNMMMUMcyzwrD2sl3DzFBlyFCixxkZ7WO8vTPF1GA=="
    },
    {
      type = "objectgroup",
      id = 9,
      name = "Environment",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 928,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 816,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1312,
          y = 160,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1216,
          y = 256,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1344,
          y = 176,
          width = 48,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1392,
          y = 336,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1328,
          y = 544,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1232,
          y = 608,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1360,
          y = 624,
          width = 224,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1584,
          y = 0,
          width = 16,
          height = 624,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1536,
          y = 448,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1536,
          y = 240,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1440,
          y = 832,
          width = 160,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1344,
          y = 864,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1232,
          y = 832,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 848,
          width = 16,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 928,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1104,
          y = 768,
          width = 16,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1008,
          y = 656,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 752,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1040,
          y = 672,
          width = 16,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1008,
          y = 464,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 992,
          y = 384,
          width = 16,
          height = 272,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 816,
          y = 352,
          width = 240,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 0,
          width = 48,
          height = 208,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 208,
          width = 208,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 368,
          width = 480,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 0,
          width = 624,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 160,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 176,
          width = 32,
          height = 208,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 304,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 16,
          width = 16,
          height = 944,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 272,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 496,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 496,
          width = 208,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 512,
          width = 16,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 512,
          width = 16,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 592,
          width = 384,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 320,
          width = 16,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 544,
          width = 176,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 592,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 944,
          width = 544,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 608,
          width = 160,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 624,
          width = 16,
          height = 176,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 384,
          width = 16,
          height = 368,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 608,
          width = 16,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 832,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 976,
          y = 768,
          width = 16,
          height = 176,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 752,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 83,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 848,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 736,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 14,
      name = "MovingPlatform",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 144,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "castle"
          }
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 736,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "mountains"
          }
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1104,
          y = 512,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "mountains"
          }
        },
        {
          id = 86,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 704,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "boss"
          }
        },
        {
          id = 87,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 928,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "boss"
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 16,
      name = "MovingPillar",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 102,
          name = "",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 656,
          width = 32,
          height = 144,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "castle"
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 15,
      name = "Checkpoint",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 71,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 864,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "",
          type = "",
          shape = "rectangle",
          x = 848,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 11,
      name = "Spikes",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 16,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 224,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 576,
          width = 224,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 864,
          width = 16,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 656,
          width = 16,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "W"
          }
        },
        {
          id = 109,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1440,
          y = 608,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 110,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1568,
          y = 512,
          width = 16,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "W"
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 12,
      name = "Units",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 33,
          name = "DarkMage",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 112,
          width = 92,
          height = 93,
          rotation = 90,
          visible = true,
          properties = {}
        },
        {
          id = 85,
          name = "Boss",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 720,
          width = 132,
          height = 125,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 108,
          name = "Ghoul",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 128,
          width = 76.5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 112,
          name = "DarkMage",
          type = "",
          shape = "rectangle",
          x = 1312,
          y = 160,
          width = 92,
          height = 93,
          rotation = 90,
          visible = true,
          properties = {}
        },
        {
          id = 115,
          name = "Captain",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 864,
          width = 80,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 13,
      name = "Events",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {
        ["exit"] = "right",
        ["map"] = "mount01",
        ["method"] = "door",
        ["onTouch"] = true,
        ["section"] = "A"
      },
      objects = {
        {
          id = 43,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 128,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 192,
            ["Goal.y"] = 504,
            ["Target"] = 44,
            ["auto"] = true,
            ["delay"] = 2,
            ["delayIn"] = 3,
            ["delayOut"] = 3,
            ["pause"] = 2
          }
        },
        {
          id = 56,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 1104,
          y = 496,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 1168,
            ["Goal.y"] = 136,
            ["Target"] = 59,
            ["auto"] = true,
            ["delay"] = 2,
            ["delayIn"] = 3,
            ["delayOut"] = 3,
            ["pause"] = 2
          }
        },
        {
          id = 57,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 720,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 800,
            ["Goal.y"] = 600,
            ["Target"] = 58,
            ["auto"] = true,
            ["delay"] = 2,
            ["delayIn"] = 3,
            ["delayOut"] = 3,
            ["pause"] = 2
          }
        },
        {
          id = 89,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 912,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 272,
            ["Goal.y"] = 920,
            ["Target"] = 86,
            ["auto"] = true,
            ["delay"] = 2,
            ["delayIn"] = 3,
            ["delayOut"] = 3,
            ["pause"] = 2
          }
        },
        {
          id = 90,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 912,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 384,
            ["Goal.y"] = 712,
            ["Target"] = 87,
            ["auto"] = true,
            ["delay"] = 2,
            ["delayIn"] = 3,
            ["delayOut"] = 3,
            ["pause"] = 2
          }
        },
        {
          id = 91,
          name = "Translate",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 880,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 448,
            ["Goal.y"] = 872,
            ["Target"] = 102,
            ["affects"] = "Player",
            ["delay"] = 2,
            ["once"] = false
          }
        },
        {
          id = 93,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 672,
          y = 544,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "item",
            ["name"] = "health",
            ["value"] = "md"
          }
        },
        {
          id = 96,
          name = "Teleport",
          type = "",
          shape = "rectangle",
          x = 1584,
          y = 752,
          width = 16,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["exit"] = "left",
            ["map"] = "mount03",
            ["method"] = "door",
            ["onTouch"] = true,
            ["section"] = "A"
          }
        },
        {
          id = 103,
          name = "Translate",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 880,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 448,
            ["Goal.y"] = 728,
            ["Target"] = 102,
            ["affects"] = "Player",
            ["delay"] = 2,
            ["once"] = false
          }
        },
        {
          id = 104,
          name = "Translate",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 784,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 448,
            ["Goal.y"] = 728,
            ["Target"] = 102,
            ["affects"] = "Player",
            ["delay"] = 2,
            ["once"] = true
          }
        },
        {
          id = 113,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 688,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "shells",
            ["value"] = "md"
          }
        },
        {
          id = 114,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 784,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "bullets",
            ["value"] = "md"
          }
        }
      }
    }
  }
}
