return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.3.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 60,
  height = 120,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 14,
  nextobjectid = 169,
  properties = {},
  tilesets = {
    {
      name = "strangemountains01",
      firstgid = 1,
      filename = "tiles/strangemountains01.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 64,
      image = "tiles/strangemountains01.png",
      imagewidth = 1024,
      imageheight = 1024,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 4096,
      tiles = {
        {
          id = 1678,
          objectGroup = {
            type = "objectgroup",
            id = 3,
            name = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            draworder = "index",
            properties = {},
            objects = {
              {
                id = 2,
                name = "",
                type = "",
                shape = "rectangle",
                x = 0,
                y = 0,
                width = 16,
                height = 16,
                rotation = 0,
                visible = true,
                properties = {}
              }
            }
          }
        }
      }
    },
    {
      name = "background",
      firstgid = 4097,
      filename = "tiles/background.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 32,
      image = "tiles/background.png",
      imagewidth = 512,
      imageheight = 512,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 1024,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      id = 1,
      name = "Background",
      x = 0,
      y = 0,
      width = 60,
      height = 120,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHt2nXsVfX/wHHsDkIUFQRJUeluQZTu7pbublBKurtDQbq7u7tLQqVLAaV+D/5gc+zrxn5zh82dPx4759ydz57vcz6ve+/u3X327QgRnuPZcBveh3AOwudB+DoQvg48xdeBSNqRicI7ROVd3iMa7/MBHxKdGHxETP6N97Gg+8msOzkpSEkqUpOGtKQjPRnISCYyk4VYfExs4hCXeMQnAZ+QkE/5jM9JRGKSkJSg+4U0C1OEohSjOCUoSSlKU4aylKM8FfiCrGTjS7LzFV+Tg5zkIjd5yEs+8lOAggTdb6jZiMY0oSnNaE4LWtKK1rShLe1oT0UqUZkqVKUa31CdGtSkFrWpQ13qUZ8GBN3vp9mfAQxkEIMZwlCGMZwRjGQUoxlDBzryLd/Ric50oSvd+J7u9KAnvehNH/oSdH+25hzmMo/5LGAhi1jMEpayjOWsYCVjGcd4JjCRSfzAj0xmCj8xlWlMZwYzmUXQ/d2ae9jLPvZzgIMc4jBHOMoxjnOCk6xiNWtYyzrWs4GNbGIzW9jKNrazg53sIuj+dc0bRI3ofYib9m9x+2+P3bF/l3vc5wERnPuz7SlOc4az/MKv/MY5znOBi1ziMle4yjWC7key7sg8q/0cj677vb899oH9D4lODD4iJg/Pf/R3j7YvevwlXuYVXuU1XucN3uQt3iYiQfcfrTPc/u//X3hfwvvyv57X4VyEcxHEXDxsBNH5p3l+2v1/Wtd/7fGnfZ+D7gfde3xegu4H3Xta15vY61USkpKM5KQgJalITRrSko70ZCAjmchMFh5f/5MeB93Pb60FKEghClOEohSjOCUoSSlKU4aylKM8FXjS63v8vKD79ay1Pg1oSCMa04SmNKM5LWhJK1rThra0oz2PX8eTHgfd722tfehLP/ozgIEMYjBDGMowhjOCkYxiNGN40ut7/Lyg+zOsdSazmM0c5jKP+SxgIYtYzBKWsozlrGAlj1/Hkx4H3d9hrTvZxW72sJd97OcABznEYY5wlGMc5wQnedLre/y8oPtXrPUq17jODR59x3HT/i1u/+2xO/bvco/7PODhdzuPX8eTHgfd/7e+W3nS63v8vKfdf3w94fHT/TwV3v/w/j/8LBDOQTgH4Rz8954Hz/ztuf28/Rd4kZd4mVd4ldd4nTd4k7d4m4hEIjJReIeovMt7RON9PuBDohODj4hJ0P1Ymh8TmzjEJR7xScAnJORTPuNzEpGYJCQlGclJQUpSkZo0pCUd6clARjKRmSwE3f9CMyvZ+JLsfMXX5CAnuchNHvKSj/wUoCCFKEwRilKM4pSgJKUoTRnKUo7yVCDofkXNSlSmClWpxjdUpwY1qUVt6lCXetSnAQ1pRGOa0JRmNKcFLWlFa9rQlna0J+h+B82OfMt3dKIzXehKN76nOz3oSS9604e+9KM/AxjIIAYzhKEMYzgjGMkoRjOGoPtjNccxnglMZBI/8COTmcJPTGUa05nBTGYxmznMZR7zWcBCFrGYJSxlGctZwUqC7q/SXM0a1rKO9WxgI5vYzBa2so3t7GAnu9jNHvayj/0c4CCHOMwRjnKM45zgJEH3f9Y8xWnOcJZf+JXfOMd5LnCRS1zmCle5xnVu8Dt/cJNb3OZP/uIOd7nHfR7wb/8G5En6zzz8boLneJ4X+P/+BiOKv32HR9+PPPwNSDTe559+AxJ0P5a1fExs4hCXeMQnAZ+QkE/5jM9JRGKSkJRkJCcFKUlFatKQlnSkJwMZyURmshB0/wvNrGTjS7LzFV+Tg5zkIjd5yEs+8lOAghSiMEUoSjGKU4KSlKI0ZShLOcpTgaD7FTUrUZkqVKUa31CdGtSkFrWpQ13qUZ8GNKQRjWlCU5rRnBa0pBWtaUNb2tGeoPsdNDvyLd/Ric50oSvd+J7u9KAnvehNH/rSj/4MYCCDGMwQhjKM4YxgJKMYzRiC7o/VHMd4JjCRSfzAj0xmCj8xlWlMZwYzmcVs5jCXecxnAQtZxGKWsJRlLGcFKwm6v0pzNWtYyzrWs4GNbGIzW9jKNrazg53sYjd72Ms+9nOAgxziMEc4yjGOc4KTBN3/WfMUpznDWX7hV37jHOe5wEUucZkrXOUa17nB7/zBTW5xmz/5izvc5R73eUCESH6DaRtk/xnNZ3mO53mBF3mJl3mFV3mN13mDN3mLt4lIJCIThXeIyru8RzTe5wM+JDox+IiYBN2PpfkxsYlDXOIRnwR8QkI+5TM+JxGJSUJSkpGcFKQkFalJQ1rSkZ4MZCQTmclC0P0vNLOSjS/Jzld8TQ5ykovc5CEv+chPAQpSiMIUoSjFKE4JSlKK0pShLOUoTwWC7lfUrERlqlCVanxDdWpQk1rUpg51qUd9GtCQRjSmCU1pRnNa0JJWtKYNbWlHe4Lud9DsyLd8Ryc604WudON7utODnvSiN33oSz/6M4CBDGIwQxjKMIYzgpGMYjRjCLo/VnMc45nARCbxAz8ymSn8xFSmMZ0ZzGQWs5nDXOYxnwUsZBGLWcJSlrGcFawk6P4qzdWsYS3rWM8GNrKJzWxhK9vYzg52sovd7GEv+9jPAQ5yiMMc4SjHOM4JThJ0/2fNU5zmDGf5hV/5jXOc5wIXucRlrnCVa1znBr/zBze5xW3+5C/ucJd73OcBESJ7/7UNsv+M5rM8x/O8wIu8xMu8wqu8xuu8wZu8xdtEJBKRicI7ROVd3iMa7/MBHxKdGHxETILux9L8mNjEIS7xiE8CPiEhn/IZn5OIxCQhKclITgpSkorUpCEt6UhPBjKSicxkIej+F5pZycaXZOcrviYHOclFbvKQl3zkpwAFKURhilCUYhSnBCUpRWnKUJZylKcCQfcralaiMlWoSjW+oTo1qEktalOHutSjPg1oSCMa04SmNKM5LWhJK1rThra0oz1B9ztoduRbvqMTnelCV7rxPd3pQU960Zs+9KUf/RnAQAYxmCEMZRjDGcFIRjGaMQTdH6s5jvFMYCKT+IEfmcwUfmIq05jODGYyi9nMYS7zmM8CFrKIxSxhKctYzgpWEnR/leZq1rCWdaxnAxvZxGa2sJVtbGcHO9nFbvawl33s5wAHOcRhjnCUYxznBCcJuv+z5ilOc4az/MKv/MY5znOBi1ziMle4yjWuc4Pf+YOb3OI2f/IXd7jLPe7zgAhRvP/aBtl/eJ2h8B6EMxDOQDgD4QyEMxDOQDgD4QyEMxDOQDgD4QyEMxDOQDgD4QyEMxDOQDgD4QyEMxDOQDgD4QyEMxDOQDgD4QyEMxDOQDgD4QyEMxDOQDgD4QyEMxDOQDgD/90Z+D+xt4uh"
    },
    {
      type = "tilelayer",
      id = 3,
      name = "Decoratives (BG)",
      x = 0,
      y = 0,
      width = 60,
      height = 120,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtmOlOU1EURq+ijwNUKUMHiC8EFCnQCXJeiEEB6QQ5L4QjY0Hj2uI1J40kxn/sfDtZufSmP/qtfUayTCUDMiADMiADMiADMvCvBub54gKUoAwVqMIiLIG32iJQA5rQgjZ0YBt2wFudEKgLPejDAIZwCmfgra4JdAO3MII7uIfv8AO81fwz5i+UoAwVqMIiLIG32iJTA5rQgjZ0YBt2wFudkKkLPejDAIZwCmfgpSafZ9kUTEMBZqAIs1CCMlSgCh5qmRwrsAo1WIc6bEATWtCGDnioXXLswT4cwCEcwTH0oA8DGIKHOifHR/gEn+EbXEDhBXsTzxHcwT14qMkJ5i9MQwFmoAg18pZ4lqECVfBQy+RYgVWowTrUYQM2oQVt6ICH2iXHHuzDARzCERzDAj3u8xzAELxUiVxlsN6+Z55CeD2RhQbv6Hmg94ExELzkbZKrBbY2275rmd+Sr8s7eh7ofWAMuMnbI1cfuuS0dZm8Ed7c8PeriSwWYBq89PeWXCO4Ia+ty/TW8kZ6G+ltpLduslrP5pi382DrVL5WrZGRuRuZu5G56yrvFX29hiK9nYU5SMfxlLO81l/LWocN2IR3Np6Bc2bkvOmmv2lPj8h5DB9gjYzcHyL3iMh9wk3etKcX5LyEK8jXZG9jOe1p8SXzF+aAu0PkDhG5S/zq7RTz20OlPf2zNnO+YiwHxnJgLAfLyfPJ1hd++1ewu5/1NM9p98BLYK0KrFWBtSrs/c7L88kWe03G+fjh7sdczfegIu9mwdv5kbOEnaEe7n7kzfegOu/sHpivVU+2oY/8cNt30/XK6/kxjZ+uV+R1dxdKs9rf6R6UniHHv+flc74mp2OZtTh6yTeeI1+Ta8ldiL3Wbd7xNdnb+XG8v3YPMjhfuLsLjWe1z2vkNDg/ursL/S2vvfP2P+bHcubvPf6POc+mpwzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIwP8Z+Ambv+W7"
    },
    {
      type = "tilelayer",
      id = 4,
      name = "Castle",
      x = 0,
      y = 0,
      width = 60,
      height = 120,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHNms92XMdxxhFZWeUdkmMmW0vkACCIJAs8iiWvLZEXAEHaWcwL5BkCUTnZWRIvAIqMs5hHsaSs5YgElTjJIr/f5f2QYuPOAJAJynPOx+qurq6ur6v/zRDfvbO2tv+TtbX7YBfsgdT3bQPH4AQ8AetgA2yC22AL3AHqZ/QN7CNSV74c608pf/HO2uJzsHbB51+w9fOzP1tbew+8D26CW2AG1sEG2ASX+XxHDCf4fAKOwDFIXX7iFBjr92AX7IF9cB8cgAfgOZCTMlg2N/K9C9ePr8D3l/D5CHwM7oJ7oAO7YA/sg8t85PsB439YIBdh/OtgA2yC2+AIvXk7AeEVrh3t9qm8n1GvdinfhOv74L2frB1++87a4WfgI/CeEp168n/InBxid/gb+HwGPgdfgMegB0fgGJyAy3zC17WcWJVb4Esgr7pWE6/SfCv/C3TY9kAp1N8G+jCftV/aPobT++D38KncomfNH7IODpmbw3/C1yGYNb6evrv28z+g/2/wP+B/waqPfB3fGPUlHoLE6Nq1PeOY78T+YCzfKbq0LeOpn038uRfuwvUm+A/4VG7RP0Z/D9wC2RuJw3FeAPfaNj7/Fvwd+Huw6iPfHpsO6Eu4BpVy1Z/lbtS5DjzTHC98ldpU2C7nY2TKB2M/94q6DSB314F81KVex1EvjOd3Rd56lzGB+fkV+DX4B7DqI1+5hI8xy9f6SWnrR90RMmeaMSSP4ZzY9CPMvTZbo9S3frWTr1K+6Zd6+OauOMLGudNn5D24dsD95Jr+LW3/BlZ95Ot51YHEaEzb4HvaahyWY5P4U1fKK/WOckX8qHsKUlfar9VlrNwV1k/B4FNZ4Jwa76/Q/Rqs+shXX/E/o5/9heUWw3joe5BypHGnHJ+Rs9GXde3MUcqRVXeAjXrn/JOx7D3RC3TZuy8pk5+dfxWUfwtWfZzXIDE9RJexHfMBddssXwTGHmxW9deX8ynvLZBxq842fZ0yppwct4NT5Zl7knh32L877N8d9u/OKr5f4edr8ClwXHye4RecnX8NvuF8dB+5zxxP+ynethun89e2h1P1b3nkcTZmdNGHk3VjXadPdPG5DUfO5x3O5x3O55V8f0r/G+Aevhxrg/2/CW6DQ+quJfXy0L/vkn1s74OMV6VxaZv8Wj4A6qdg31Yff+r3aM+ZVXPboQ84p3Y4pwae3L+X4vt4jGcPnvvgPvgdPr8a40kMSs/XJyDjVRm7qbVpW+ZBLg+oL9NlDo4dD/jerbklP/N2HfNGW8l1jU/ym3PrGJ4n4AnImMrwqLInhg4oA+sV8aHOXMsxuioTx7DOnMtXmMvL8iboKT8Gke065j16ab63iGMGTuH5EnwPrFfUN/ZzxhfySHlKpr9tz7DdanymPXzhM3Ct/Mp5MeTUvGrP22zBe3Rh3i77yTj36O85s/HnzCW4DeRSkdhcq5aN3fboLYvwznpNPVL7lCMTx3fwPQKjfk597vkyjjEnL3Pz+gE63qCX+k5Z50KOiXNKjuO8dn+4LtUbk31iY7nW1cc2NsrWRl34us42wWg/8JOvfYBre1jjn1C/C1++Py0qn4vKPf2+J25huQL/GedMJh8z2oLY9RP28k175JRd+LrOPNNG24GffHvje4VhD2ct873xSnz1Gw6tnGqbYS+m2tr+qbtvU14m9fkSPkrvn77wK3zn9B9yzneqBd8jr8TV3Bv36HvOWGIYkzNh+D5ifHtAaZsyiG3qU/I29ubYfdO2p3/rd50+/SvM6TPs39SxnbMG5nxnnPM9ec5vA3N5XPbTEcd4Fsr9jK85MQ65noL6DlFv7FP9bGuhrZxdpykfjD6si9rH70Y9OmA8A986lvov0H8OPgOX5apdh++yfvQ/jC1f204YV1nfIda1q/3ULYO2wnNd3lujzJzaVvt6Pld+rue8e+U6zsWaZzX7eM6dNGcfX4q34/hmc4xPgWMLY9kGnmPPQfsOcX3WfsvOvB47x6jQn1An/wcgOqXzWOdSvjnPwvvn6Iz3n8FN5uB9wG9fA+dvV7w7HHPm2OAemFkH5kKk3r5D+rHN+B5SVl4W8am982q+o1Oqr3Ppe2MGOhDelsFwN3EvzbmX5ryvBr6fXcDX2C/KT32HPGcsUWO03JW4nYPsV23NoTbpGzml2/x/P+fu30e0fQrG9T7cTV/A83MAz4EvvHfWlnyM8Yfmx74VPfXZiOzR1JWu3Vq33E3onCf14Nz9+yF6vqdm3ob3F3fTnLtp/u3I970VfN0b7XloHMJ5eArMxR5Qqk9upiQxDrH2o0xdKd9at9xP6MreHc5oY+wZG8yT3xk6MOT/KmeWvtrzcPQ17C3Lcj0duXavxjnjnfmY4j6lc79O6atu1f079f7i3Jm3e3jJch6+67fnYeUrv9xJlntg3pNvc3bMXBiv5Rp3W77s26Ndb+Yk99M23Nr8P0bX7uFVfI2rnoeV7zZj5U5K/OZIGzkrPcflugXSd5nURztHB/SLb2W73uSbe+gh3Nr8X+Ue1pf5m4EOrLqTwkG+3dhPGRir6zv1KTmjXdQ5kn/m0LZ2vRlj7qFPGOMRyN2L/ZXel8a3DA9pk0NF4lWaT2N1vpxzdT246G7rsAni27q+HgB1rre0fa1vUOvfUP93QD/fW5d+X87wG0zFnzb3qEjduXCejMF1rbRtao4S55SMP9vMsTFkvaXN/Ma/Osv8brr2N6Dn7hGs6QXn9NnvHcvel/G5LH59V8Te2IT17ONurMdGOaUjvuFukUctT51FsTGGF+AU6Nc7GN8L+i/47rDgu8OC7w6LZedU9PYVNfb4xN/QFpsqw1cb86FUp6zoS31mGVv3p39PcAD2qd8H/r+56/YlcD/AYw7Hs++C9s3vk7TteKahW3A/Le4CvhsuPgLhtUzqRyTWxN6h64GyYkZdhO825Zzf8aF9D4j3NQx6dCe0+fuq+7XayN//+/L/1eE0Z5zXvgtyNi84J3bka67htwbPs9/tWMNX4ltjr3HUMjEMfO8gReqRsU29yh77I6BNhxTq5K9O/vo0z/0rm4Fv7iLW+4K1MfA116zfNdbx2e92vJ8vzXdZ/DP8TeEh+mNiCr8HjZ36/wTmKzZKOeovOstPio1+smf7cT3nLmLt7jDmDj52/vLdtbW/AtyfC95Ww+92fE+4NN9l8SeuSOMTW8B8pK60vgE2gWuyG9EjY2dZfer6zfq2/JQ281lhvjvwCJ58N9qhr1jUM/kya9k9nXGXxZ/2yG6Mtx9l6pHqWXPDeVTnKO1KbbKuY1Ol+awY8o3uQ3hyLu9gKxbfAb4bDb/b8d1oyC3fjVZ+EocxpBxpvlKOrHG15dj09PM8mo1o7aJfJeE2rGu47mzAj7U87J8OCYbviazlc98TWNMrP20sbd0zt9VN1Y09+lquOvXL2mIX+QhbuHp27czA1N38GL7t94TP/gi+t+lrjt1TiSMxr5La5iyz/0Hpb1vbt6O91fVwMcc5m+E9nNtVsn9f+73uZ2T2PfA+uFmyvE55A2yCdpy2bnzGnPjlbnzLkP53sLHf1ihdJ2lr+/a0ndPB1xzLzzxPgTX+2u/Qv4TPR+BjcBfks0thD+yDq8ZvbL4vhOUWbdzOl1Av/wdgao+syqN5noJrgLfk8Du03H4DOKfnn1spnyPKx+AEGO9V4vfeCofINtY9+NV34oORszyTb+c5/ZW5Y6fy+AjbKfT0E3VdS/P3/lM+LyifgpdgKv4aR1ueMbZQn/jbWF37vkufgC/BU5B+6Wuu49vyB2Aqh+q+XoIb6Dt8g8nfZQvloejf0C4b4yr6NtZTYsi7P2+szthGhHvd45/Q9mgJ6DfcP/Lr8S205e2R33nO/S7LvTRv+fo3tFfhtcy2jbW+sVy/8uoLwjvyOfF/RfvXSzBynN/Qxyu+Q3nsP6f/ud8puZfO8ZX/Mg5X0RvrDCT+yPvoDoBnlJyWwb7C9uwRz2W+C53xk1PLtx/b6XvuNx3PLfm1n6vwWmU7cGT8XZDzKlzTL7yU5v1L4D6XV21z/4uqc39Y30TKs3Lv4Ibu7Kzme9Pw/6RTnBPLHyuZ/yGOI6SxyqP1mfg9I3M+Ozf2tU1ZMaXLXVD59nAFw/jtWX1d+XUdGusLcArMxzK+2spFrtpa7kad5WCZDv2wtpPrY3xoq76D+9S7OrzbmH5oPRzym4vfCVtfs5GLtsbnGhjjHM6zlCP70a7OoW+FXeBcRfp9LPlFnjur30O3jC9xLjhfF8S9mAFiW7Rx/9A6/obcyXcbGLtrIqh/QxAu7nHba9sRdXMauU4ZnmKO7bmzut5NbeyswwVrbPEC0Pda+Ho/ifCP3HuXdxnwbxnDZaqN2IZ9ELmLr/DF/txZXe+mli9rbMHcLRhvgY+Bc2vzQ+uJ/SHxmR/mc4D3lW3H8Kx/y6guNrUtPMnNsEaI9ezc7uBL3K+d1a7lnNVt7Ptw3AO7oBPXsJ5zF8kncN2ewrf+LSNjn7XXtnpG5Hcj4h32tFzBkO+ps7rlK78K4nlj+9f4RT/K1JXyrX9DYMzmLeugtj1HH/g7in21Decb1Dvq4NxZ3fK9znpiXCY9x2rbC2I+Ldxsm2FTIdcevbZydn5Wvauvk1/ru3Jpy7eJ09hbvfXKz7VQcWPk25PLzA9l52BO33NndRvTddZr3FNl4nuNW2zUB4Wftq+9O57B76Kz+jr5tb59Q3YrIL+pdte5baLwnWM78M0b8w/wdU1vvsqvvjy7Xjur25ius94Tr28MYbkF8Q3nzC7t3BHDbyTmVb1r3XvL/TlDBt5Jlp0H3jBz31rlvSXfs/8b5/9L59fJr/XtvZt1uUzeLG+Nk5GLOnO8NfaXX/r7/+Lyy3dP7yC5d68wlL/Bj/837ru6jelt1u/xWzr52kmu5HQXbj3ylPjMnXGra3kl/8e0n4DcSxvYboLb+qF/e1a/TX7Lxqp8Ldf3hNzl3PJyXZt/c2/7iPke9bxJ4Tv/KW03bHfufuT8hv+MeIT53QZtLp8Tq4hd7h3zb+5t60ccU8+bdLQf7qSBM74z5o8pw8PvEKLNZdo72kTNf9pGvvP67hzt5x15la82PybPjJ2YH8qVmJ6P8Dy2LfXIKZ1cwLy+O0fdoP9T5Ov5670T/sq2rq5rbNRtvuJ79v9N62PdOXj+J5Zf4xf9KOt69fuP8xCbald1eXPkfGrfWebXOcma+jEl8//amjXWZWeWtvXOSd/wjGzfWfJ1TmZI4Vw5ztFYjz4yfi8j1/ExZbdsTltbY2jPrKfFZ71zEt8MLh0I3/adJV/bYt9Tdpyu6NIWubuiLTZTEr+H9D1cB+7HnEmWDy7h07eTtubMual3TuZqA32PTfiqd43Y51Pg7/czgU7Y3iHtE53SOvG+NhcZI1K7lCOrjlwdMvbhBlDvnWP8W6M0d90EXA++KeTru8Kc2a/eOfoTWTvha7+ZnADvyOHN4ZzEnvkf5iP1SHIyrHPb5d2Nkrfg2Tw8pix6sDlCu/jgvXdIrIe0HaoPnJu6F425L5CbOt+KvivSr9452nhvhe9FcoatkAt5GHxGV2U3tvWjTF15kY54D8nR4W2Q/Ctn9K178RF1492nzXyyJob1aP0FuA/Sz76WfZO5Ti7imXb7sc6GPn5PewLUtahxXrVMDg4PAHEdZtzIuhe/HuPeJAbzGZs3Kd3Pzt1L4Pp2/Qr1zqs629RZ9g1E/MP//zgncDj3W7LxnoLM2br9wVTcdS+m3XGNyXxG96akXPbACZCj5Tqe49pm3neBNsdAG9cSeRvq7qH42aDNfazUdh3oYyrmuhfTvjnaOl50b0puExd/x/Tq7wCRxuZ4xup4yVFkh71l90B02sl90FPWR+xi8wLdm4p5lR/Hcd9rI4fW1vVo7M7/KWj3pnFX9E3dNnX2d607f/uUp+wytvNzBMx9dG9Sut/krWz9Gp88bZ9RbiF/bZSu6XY+rNs3eseQS+bOfZ9yxnaMDiije9Nygxim9r9/T2J+jbflat38y8H8rTc2x9RF7fdyrMvZPkp14k1zWuXvH//iVdzyrnY11rbs+vTt41zsgcxJchlpv5Qj1b0Y+zim3Ou4u9SdC+drv2mrdm+63HKs9WfEbF2up8ByN+qq3SqdfNaB3Grs1Zfrq7ZdZ9lYA2OokK9t5iY2fbG/jE6+2rmP3zSP7/HtfjS+3JcXjWH8wYxyhXy3gX6zTq8qXRv2uY41y/t0OF8u4ljba/yVq+U7I1r9Veov4OpaVmZc98ZL4DxGF6ndfVDtbYvuKrmMzypXxf6QcVyPmRPfUNqnHrlKZ3y7IPkd3qX48P1lfmosljdGe33WNn20sdb2qXK+k9W21ket5y6qOu+mWrfcrdDJT5tN4nXcXZDx+c50Vo4uc6hPdc5Tm+vYVjllg//hO1m1M5bAMSr6pm6bfKuN5Sm76GJvnuu4ll+im1rT1c55MudVZ3kGlM6PUj+t3cHEdzL7eS4pM7cXSe0vskm7590esZjn6BL7sjWd9vCxX9VZlps+zWvkEeWWc9tPnu5L5mLgnZiWydv4NGd5h1Q7fVXIVVthftPmms6bfmpNtzG29Z7+ourleRFX7ROD8Zs3eUe3TMpRDsfIlO1XuVt+iM71uIU0ltpeY23LcnF9CstBtVNX645T68vKxmkejKkDrgm5W16GGW0i8afsfKXNNSPfL4Fr7iVIm3JZPOrjt5Wr+ly2bZ045HoHyLMfMTW/aeuwETOQmFKWn1yV8nUu9xjDvZp+ylXx6cs96ZoQlh1nVZ+0yacDu0vsj9Drz3j0mbjDY5U0bu3TJ9L5c1zX2OkIy9VX4puS+jUu52kfvAD6nrKd0vXY23+qzXWmX9v16VjKqflVb8zOzcnYT/v0CZ/Y6XcDGPMmmBp/Suf3h75AH44xZTulMw7naKqNv+FYu0Xb/dGn4+hb/sZrrPadjXrlE+q7QJtjoI19bBMtb+fHmKfGvw5dxq8y43xHHM69cK8t+y1LPj1QykmkbD5Sj856xks5Y163zLiRjp8xb1E+hat7Thj7CXV1sY+US0Xf1G2ruhl1Yf/IbuyT8VdJc7AOVtlMtbnmHNMz82AcP3bWXWvmVsgz6zfxRupDG6VrWtnCvtGFm/3VRVrO+Ncl4XzIOAPqGK5n3zjeRdf1W5a8wzWyxnAd5XBV7sJxD+wDzyrvXnNvLMvwkDbnxNzYV5nYLQfLdN3ou/a7Dp7xCZ8ht4x3eER85HvYp+b3Iq5yeDbGK9dToC4cLAerdGmLTGzXIdmnZ3zdY8b8EpjfLeKVv3EEs8LBsnxt8yyLTT/qUleu0mWM2FwHz/g0r7OR8/CWIDbvRfnK3xgqsD3LmWX5bgPfmVm7V5V741w5TgcS23VKx9kFfh/bB+Hbxi7HCve4qLqrlh3DPsrr5Fh994x3BI7BCfCOcz9fFPtD+2CXeXlAPbFHV/lM6bTvxn41prdZPr0EV+N0j7fnWluvfCwH3VhW9kD5NjnWsTaW8DWmisRZdfKtdctTdtHV/NcY3mbZt4ZrdTbCc8lyXY+rytqvam/b4vttcqxjeQZVvu7Lg5FDYmtjTv02a8McPx3to1dm/iK3sbHcjbLG8DbLxis/ZWJbFv8UD3X2zVkWf5W7ZedUrv0o3ybHOtYW4/vuSF7Ng7pwj0z81i13SJH2O5Tlal/lM5A2fctXvXe949UY3mbZOL2TzM86MN7Kp+UVjj12Iu2R7bzIVd1swu/b5JmxMuf7xOQ97NvL2IQc2jj7UR9erdRedEVabpHx37Y0n66vPRCZ2PqJONN2Vdn6ets8M97/AYJTgxo="
    },
    {
      type = "tilelayer",
      id = 5,
      name = "Decoratives (MG)",
      x = 0,
      y = 0,
      width = 60,
      height = 120,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtnMlyE0cYgCcEzAvkAIll2SZK2VCFIWVzysJjQIIkLxFlQxWGbKdsD5EDJHiDKMVyyGaTS0heIocseAGXqiA5EComlUO2r8szld/SrPJMe2bUXfVJrVn7+7tnNNMatWWZZCJgIpCnCBzZnSebVpcPd22ddj7nvt83+W61z9+np57Mn5Ofkalfv+iYeSYCJgImAumOwAtcg7wIL8HLOb8eUTXxDo7vwnvwfgf4foPjbfgWvusA379w/Bv+gX87wDfdZxdTOhMBE4GwEZjYY30QdlmzXGsECnssqweK0AmpjGcFqh3iO4PnLMxp8m3ur/NrU6rvcqJr8/iNqx9zGc8VWNXkG6U/R/VdXrV94+rHLHRx/EIRdKSo/XXrtm9cZSvjWYGqJt8o9ascD+yN9/toBs9ZmNPkG7V+J2L2XcZzBVY1+cbVLtvdTmEvxy8UoRNSGc8KVDvEtxPq1DiaCHRaBBY5fy3BLfgamj93WjyMr4mAiYCJgImAiYCJgImAXwT+3G2t+c1Pel6UPsokynKRZ/wu2c/53eD9ZsLP/EXtw0rCWec2o/Zh6SxbEvtKW/3ue8Ky9sPT8Ax0Q0HQQ74IvdAHz0IJwiZd9dsQvyHIvFPOfRy3++EEZT8Jr8CrcArKggr5KozCGLwGNUhbKok+V5l3ynkC15NwkbJfgo/gY7gMM4JZ8nMwDwvwCdQhbakmfGXeOT//QJl/hJ/gZ7gDy5DVVBe+Mp9Vn6ByN4SvzAetl9X5NeEr81n1CSq3dJT5oPWyOr8u6lfms+oTVO6S8JX5oPWyOr8mfGU+qz5B5a4LX5kPWi/sfOe6U11vqmvSnU4N4SvzO12upPZfE74y77Y/dW2Z9SQdZd7Ny7nGdJvnNc3pKzi8yzp+DryW0zW9LupX5nXtX/d+GsJX5nWXQ9f+Svyu6SSZd6bl7b3U9f8xJfN583R86NM47pZ3ppl3EwETARMBEwETAROBbEag276v6uG9aOezaeJf6kf8t0KlUzl23DTc+noZ35kcOz+kXn+z61aZ38F1Oae+Q/zeeASOit8duxkfp9A0Rk4fnxVZT9N4nocLwjfrTn7l/wzPz+GLnPgO4DHo4/LQZ55fnNI6bxKfKR+nIdE/lFaHoHIVOLeqawWVruF63fYtMe25gPPuMOfpETgmztebW0rXq3xmv4xTBZTzfVwf2L41Pp8Gv/Qmnm/B2yn39XJQ/1+IkhbxXIJbKfGN6z/DXjHYwPMx/JES37j+M+zlO0zbH4Fj9jHgtZyZrj8Ch2mDQwm0w/6Ac5x+0809nsN1OgHf8ZT6JhXn3/F9I8PO0xG/o77E9asM+6p2cJR2/3zItp+H+8ALuL4e0nct4+056nHey32+bM/rGW/bQf6r+OW5jlVfTtnuu+nhvQjNdRwUo7jmD/BM1CAchEMJPR+lXGV/3Qr169RxXB5B21HP2p+GSZiCM3AWDlKWQxqOJ8c5qJxxzVfP2n8K1+A63ICbcAbXsxp8nXYdl0/Y7dzH8QH8Ar+C87xU2PW3s1zVPqa3s41213U8R7lvG4NxYFy8lpSV/pmWgntMmMdxAa7AVRffne6fcYv3Isffkscx6La8VF/D8S7cg3UX30WuoXayf8Yt3hu4Pha+ss/GbXnp20t/ah/0wwGXvtUNfMP0zyQ1xqFbvIc5D4yIc4Hss3FbXvqO4jgG48C4eC0pbP9MUmMcusVb1mdzgd2Wl8vM47gAV4Bx8dpOcozDWdraHKj73ua2F3UHbvF26tPtOHZbXu5zDce7cA8YF6/tJMc4VNcWjnNz22t7By4rthPLXu7d+6AfGBfPGqCsgxA1NY9x6FxPqTpOKrUTy1Ecx2AcGBfPmqR8U22UsXmMwwrnE3V9EUebTipe29mu2xiHTh23Uw/bKYuOdb3GOHScdZRB5z68xjjcqfuEdtwb9nf6bfHd7rUdvzEOVR1nIZVC9sdFcfkP3j35sA=="
    },
    {
      type = "tilelayer",
      id = 2,
      name = "Platforms",
      x = 0,
      y = 0,
      width = 60,
      height = 120,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHdnFtzFMcVxzdg50NwkQkS2H6IhCu3CvAwnwOCrCDhJA/RykmcxMDDfow4sYAqBOU8RBJOYpcFD/M9DEhVCPIUwLlWsB/y+4/2v9Ua5tazu8h2V/13bt2nz+lz6dM9I733jU7n92AF/AFcBd19nbk18ATM7O/Mhde+5/q/o/57wDRucH4TiNb7YDl3foVr9bFXZXtfp/MQrCLbYzCNfE14WaRu2GaxYbsmtMdZZ2F/p3MBFJVpZPqqylUkj+6tIOuNEnnL2uzl/bn9nWtHwNa+zrVr4D62uQmaFttz0/pftnoT6OqVCH1NUfdYRP0vm7yz8P5mBP9V/vtlk62Mnxib/qr5b5HMMTa9HWELRX3t1b3lIEbFyjtB21fAEfAtcBRMgqmCa9Upq682x8Br4HXwokqMDy/Al3AB/BicB/NA92bBm2AOVD1zfR1F56fgZ2Ac5QB0DwLr5T72uRlhoyu0vQFugphCjtlZAj+gr5McTwXtTwfnIc1DJffDOnXnZ6BxFnj8J17CNkHTsk3bh+ARiClr1F8HF8GlftvL/WMdncPUk09IT4J8RP5U5lPHeCZ9SpfW51+4/iuILZ5/j0fYhPpg3dB5CjbA7ch+z1FfvnK2D/mL/KbMd+Qj0qNhfR6J0KvH5RJyXo6UVW0dI57By+dARXTa0NppXf27ur+TrIF1UF2z+ulteLzTQt4rtLkKToJTQfsqeQ8F9fJcvd8fs/z98LqLrEtDynuSfk416CvsV+e250lsCrvucd3L18lfV8l7t4YH1qkJa/HkxJDytvE/yUHfHfruvAGfylkegknOp4DOH4G/AV03KVVjofaP93USHe9Db7MhTdXPl9D/8s98rXlEMfVT+L8L7gHHSel3ChwD89RZADo/Dl4Fb3HdpNTJaxoT9B2zHnI7HxdofwG8BcrKj+BZMfUg/B8Ch0EYK//MM2JJ5zrHFaD5fNjiOUvzVjhPeZzb0l+BzxvgZoW80m9ZCePmA+ptA83nwxbPWZq3wnnK+UXbOC3fqyvSb1Xp8ly5lvT8AHq2mao2Mc/ssxpP9jY6w8Rp+d4wRXFzDT6Ua8mm5c9NxjC2T8vMfo5iZes4Ld4UT70mUu52HDQtjpsztDkBxqFf82KZmfsS5sDE92OOjq3n4XUeKHcri6lVfgwPWX5p/WoMlRd7HTPJueammLHMy+HYjD0l2FNrefN0y66r/Jh926QLNO4eQ81JWhsKGkfNVWVjWdZneH+WMdRelfpZAuGzpuejiqfT9A8fWdxS38TPFH9Oid9pnpcPqOcim6myG9fzUTatEs4LO3ea/U4xXsfAKAp2lsUt0VpCTuJoulggb9iXbKbKbsK64Tl0E+hH59OjmjvOMWZP4B177nwGyDVT4mg6XSNvKINzDPm54uZroMzfodsqn16BT+Ubw5ZlaCBfllOLFnKnyJ8Sv9OmtJ1jyM/l7/L7Mn/XvAD9LF40pa96no+KYukE/YW53FGuFWeL7jvPw47lw71uf71Ulafm+VyGtvzzKngAHoKysoqsa2AdlNUpuu9Yqj0G7wnNc64xngVhLneeaz0ruu88T33AQw9eejqvylP1PF+uMF5aVzfxM8Y0i9P/gaemJXx36/e/8LuFjrZO8H6Q4xzXc08BPjkX3it6B6x+qVu7HravhvYj27Gd2O7ky/Ljov3dGe7DT+f7jE/TMkXdfHxGN1uM3Rb05jjuevcd3sv34XUa49LDl3v55+G1fTW0H9mO7cR2JzuTHxft78KbfCeqOI5GNSqpbHnRbxarSqqV3pbvboEHYAU9KI7erJBnjWfrFc+LOmrLW56Wx/rtHR5SeEkfFfByt+Cead3jmWTeBLLnuvKEevAfVYinjfKCOqIe61v0v4SsyJ8WtWmyjyGZ7b8TnIc+fpRr+bhKOP/t3Kn/tT3H5AVFVD3Wiq1rjOFqRJ5RRM/+O4t8oY9rjrCPd+kLfUUV23NMXlDUgcd6VPZS1Ef+HmOaMLZRe9KOz8zfaZ5ezLXHep7xXgAXQEyuEdOX6y4iK/1G5dDmTTRicwP3qyP+ms0N15FzBWSxleO4i/2oaT/b8PSwD83tytOVo78KYsoa9deB9jdM8xHn+fW+coey/CGmP9e1H/m67ui4oD1jze3K05Wj/wTEFI+z9jdMU+v9fI6q3KEsf4jpz3Vj5Z1EB1PgGBimOO+Vbq1THTfwL95RJXdADH3nm7a3srYe57Ln+fthfMk/i73WvCndSqcuF5HzErgMiC+p7xcdp4Mxcb5peyuqr3ux+g3jSxnNpvcn0K1ySu2ZuoTv45An9f0mxw9e6iR/BGV1rdtPIuiOyp7Fk236WiDvxUDXw87xebmt23cj5B3Gnu1jzveU522Crb68vDvsneivg/O8Dnt9Ghl575zy/jn9YYS8w9izfcz5nvM8f2cQ+q7kkw8PK6fbf0F+xHcFKe830/9F5ErD6HcZW70CroJrICySlbFP0EGCLhI98zGs1/b8DjLaf/TeSt+vNCnD6PcefSgmbwKtW8Pycf/aMofPys7z/nEEGp7bJjl3PpT3n7bytsknHZOl57D8l+sN9Iq9Jdhdgv0l4fOi87x/zEFDc5vWRPPA+VDef/7Js38Bl1t9e/J1eHxAbFGOEI5feK7csqpo/W4dh/X0HZps2nNv+Gwc5+Ha4e0KeZ3/zcO3xy88V25ZVQ4hl3Uc1vsH7WzLo/TbsA+dS06BuT1hfsrek77BMV8vfw1v2XdF8Fa5Z5Rvp+vLzAfoMUWfqZ/Lf2Ns2e1ij5JTkMzCKlgD66CKFrx24Ln192K3iZcbwbyQ+S8+y/2EWFrZdxVfdc/IYRJBMguSuQvYd6jsU7zeRt47oE25RPuLQHvBH6Fb6ZfrhPvJZdCGZpM27FMkQii37bqqvfztGfgc1BXPG+HaBR2mjFWPMetpv1/6PQkfp8BpUEez7fNFaAuSWXgMyKtr3ytJH/bhur49b4RrF3SofKfHmPWkY8VnZI9eB9b1nX8+jWzCIvAz+XCV/0rOTB/UO1Vj96K5zNi8/nInfQ3c5FwFHaY6WsfahyYmvJD5KJRX/lsnr2KV9ItustxAfLctoY4Zx135ZFuaTdpJZtWbps86/91AN9LvKOwP++ghZ4+10WD8vghsrQnvTeocgP5BoDXZp+Au8HeOuqd1WplNK1bFxKsqfpA3Rd5U9nwSEK9k6yMvZ6B5FmhNVvadY9k8LFsW4DPLOYZhDntOn4Fb0LsILgFi2Qsv8mN1uoZtsW+anetaRbYs2N927rb7JV5pHk8/g94GuA3ugL0qXWRdyslr/aKXXfGqaJ6t4/sysl4C5LCKz5qjOvjvnhbF69C2rV/0smu+LJpn6xg/jYwzyMc+juwlxZ+1zt+zYrvuIptzTOUG5AjKBwd/WyMGi+bZOsbRpd6FZu9W8vTq2o7jueYn0Q3nKPSbkgMq34/+25o8j/iq3nVn71Zi6B2gzUHgvQsdtZ/hPQ0fm76L8Xz8uO+7Tzg+zfkxNtjDFnt5GWKuLyMvtLP37jHynqHNWeC9Cx21HheUt/oY+y5mtS8jOnguThPHet0h5T2NvNhO9t2Z41XT8SraN8i39bufondxWr/k9b/Ylxe5novT68jKOPTyfcRem2/HK2J2o3X1Ferp+4CqUvUuTnaQ17/tegZ5sd8kpP0UWZ+MQN5ZeH4TeG9M71sn4MW+qT1HX09ybt+8Tz3lgaMuyNxB3mzOCGmfIO/FFnvhvZhzfUOpYj1pr9f6mKU/+6b2HH09z7l90/v1O1RG94tND97Hh1Tb+q/zEulMOrKepF/TpM9e2Neozx/Rd1lZ5Rl+ms0ZYZ11eOJ+jzkrDe/XnTsvkc6ko1BPpkmfvTo6wzw/3retIhqP4Qs/3fWtlmxvBei7i2FKF7roNCui+RQ56atHn71h6A7b1j5mOrI97bsfhdcwhtTtt7u9j9jHwG5E0zEBm+m5TtPjYn/cmtYP6zl/sTz2MdeZxA4VW87TRxhD6vbb3d7HvN1chN6llnzjA62L8xfLE/qYiF6Htu15mpyhbUfONdx+A7q3gWOabCfWZkyrzXEWG9PcqKI1m8sD+Fjg+kJwz89ijuh3kKfKf59B93PgmCbbibWZsv49hpoXlFsVjWPot7xXGpRJzqfAsN/p4L+DPFX+63iFzfT4FiPlm4x00GnJyYcvlzzI3fYYal5QblU0jqG8ai69qszD2yj020Ve4nMimooJjle63qtyHxk3+3JKryrXOdp/d+60+51B1hN9eUUhjFePI+ck2+uwPh+ufaXXdfKLNbAakWeYl7zfoN/B/Ct5Ha90Hjsn2V6rfF58KC8PvwPIj88Txh+/SsSD9LqEnF2wGCGvecn7zRp9rwMX+mm9BvnFN02l/Cg+lJeH3wHkxwc9ZvtXovIAefExrVlTxj8tp7z7yTJ95N+pqAZjqRg1KMP474cN5B10VHES2pxiCvyl8JniX2lFs0aPGLdsre/Kof/6XtVR9qn5xUet3z+F5l1QNN9U0fKz0OYy/0VO7qWrI5B3Ar5eAS6h//pe1VH2qfnFR63f/f6gaL6pouVn6HJgc5n/ImcXLI5A3jCfUX+ODTHzetF3k0X3LE/dcQZ5TwCVzH+Rk3vp9Ajkzc/vjg07vb3YX+JvVvCxBD4SXch/RzHvZoT7P2E8HEUOE9Juc449D+Yj6XcbPATa8/NeUtvYIH4Y18E3I6Yt+qKd3z9sw39sG+Qd+K/Xgf4fMN5LahsbxAvzWmIb8v6V/14gv38Yy3tdfcf1g8jo7xFDeTfgLf/eKKR5k3ZtSj5uicakdAxiYlds347rZ+Hb3yPav9aRlT3xsXxjkY9b4jv0HeWhsu1x2fcVaF8F10DoX+yJD/WNhe0nn0dLvrzMoe8oD5Vtj9q+70FT8Jpoi3MV+9czYhfr8Ubfr+603P1r+8nn0apV1O82/T/s87CbUv3VcoN2h/EXYQIo7zkCVByjyX+G+uZPPBTl0eoj36/m4ir/LZJH8SMmhpxDPkHFOta5fZj8dqzf/HXhdwnMwcMCuNDnRTyEZYI6QugXMXKa1jL0NW73RI/zMLft4rsnkfcU4L1e4jajPK7RbxMbPke9WVDkFzH8SF7Jerg/rtKxi3zYayPfG/VRc1+VDYf92S/Ce0Xnh6GZt4Wievl78uGmvOTbNr1WjK6y46Z0wnptbQFbS0bNS8iXz1eQ+UbfvnxvmOMy+rUtxPh4F3ljeDlAP8rTtPa+B+6D8Nzrcj/zcZt6Mfmz+1E+KIR7U8PkJzOR9nyGvpWnhf+jMDz3utz/v9BH59DKzZvkF+5njvpCuDfVpH2Z7WhOirFn/udHSn8pcTSB93QenAfwk8JXyr5ZSnxNy54xVqmAPGkZT+O8jz1HrX35ny4p9pQSG5MpjpPgKMDeUuwuZV80Zf5My57hCym2uieyahzRb+O5Ypzj/iJoa564CmLs+UXwNUwfnpcdQxUvfa7Yugli4vMwvLyItp6XHUMVL33u97+eK7SXo//ni09m+y7HOX6dyhPkIZccfC/k/+dLzM2+D3rrayYvuXP2HuAGcgnXwUr/fNx6lZ8Ry5/LJYjr2X7HOGyLtZH2wrPykH4egG2g83EX+Rlz9XO5xAL3lE+Mw7Y092pdeos1OPtYg/ehf4p4Z9ZmXH7NGP8GXKHvq+Aa+Dfw36SNK36u0cc64JuGFD0P3of+vEJex/tjtKuyuap6HyHrx+A+NDbBFvgt1/yPhexv0hQ/yWGyuEluU9lPzHjbnuehr30W/Dl7H/rtCnllh+SStWvyono3aefyDn2qeI8F+0qws0R6D7+JGpVtT0PX8eq6+gDaE9b70L9X5HvL8NxkHda03iIyMu4J9pVgZ8l3oP9d8D3wLgjnSutcMU32VRbv9Ex5BvntYF2lXMP61Z7wAijbV9rRxHh+GffBe4g3OP8lPP4KvAM+AV5Xaa48z/U8UEy7AMrinZ55XZbPNSTF/wEWTtkq"
    },
    {
      type = "tilelayer",
      id = 7,
      name = "Foreground",
      x = 0,
      y = 0,
      width = 60,
      height = 120,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHt3FdsHMcdB+AF3CRRkoH0Xt5FUtVWIakAaQ6SvKTbacy71YslseghsSwjkZDEvY/fTaqRaqxAYlmBLSOJe7ffTapThS0fHRI4HCTdnXg87B53gA/Wkbtz85u73TvOf71RlLZ0BtIZSGcgnYF0BtIZSGcgnYF0BtIZSGcgHjPwwIwoepCHeJhHeJTHeJwneJKneJpnCDxLubQ3ZXmLt3mHd3mP9/mAD/mIcmlfmBlFX+RLfJmv8FW+xtf5Bt+kXNqvZLmTu/g1v+G3/I7fU88fSGJ7wLgf5CEe5hEe5TEe5wme5Cme5hkCz5LE9opxv8prvM4bvMlbvM07vMt7vM8HfMhHpK38Z2DNnChayzrWs4GNbGIz+bZ7Z+e7Zem221URfSv72fbItJd97OcAbbRzkHzb8zHMe6Wxn5TpFKc5w1nOcZ4Byq1Vz42i+SxgIYtYzBJuo9zaGpnWso71bGAjm9hMubU9Mu1lH/s5QBvtHKTc2kmZTnGaM5zlHOcZoNxa9a2OXxawkEUsZgm3kaS2uyL3aNfItJZ1rGcDG9nEZpLQDvkcOcwRjtJBJ11ktz0y7WUf+zlAG+0cJAntglwXucRlBhlimOx2UqZTnOYMZznHeQbIt/3d39O51h7y7avQ7W53nlnKMpazgkaaaGY7xW7/lfcVXuU1XucNMtceiv2c1+qvU8YuuumZgryf8vfWp/kMn+VzfJ7MtYdrja/YvxuScZgRRqcg709k+yk/4+f8gl+SufZQ7EzX6q/GsVhLHSvHj8t7HM9b2Mo2GmikiWaS3HJ9r8g+j3cnPG+u7xXZ5/GRhOfN9b1i4jxe49iupW4KjvFSHh+5vldsk6+BzM+tUo6vFM91SL7DHOEoHWR+bpViDHF4jsl+bu3M43t7HHJOjCH7c2vi5/n+93iBeZfMiXoXs4iFLGA+1VRRyTzyff5Ct2vy+dzM9vHP6UL3L3T787Oj3nOc5QynOcVJ+unjYwrtN9/tu+TspqdEedtlaeMA+9nHXvbQSgvPke/4C91uWM4RRkuUd5MsG9nAetaxljWsZhV3U2iOqdr+WEUUdnC9/S+RZTGLWMgC5lNNFZXM43r7j8t+1v+jsTWY8xWOX85yhtOc4iT99PExcRn3ZMfRLksbB9jPPvayh1ZaeI7JPk9c9t8ky0Y2sJ51rGUNq1nF3cRlvJMdxxJZFrOIhSxgPtVUUck8Jvs86f7Jn4HM9bL0Wp30Wp2kv6PL+VqdK7026bU6V5qVZP6s79bp9ZncMs3yrppmeSunUd7+uf5OJJlnnsJH3SpryzTKu1rWVTHOW+w16SpZK2Oct9A16Vzv8H7r0X1TuCad6/kn+/sW9chWxq5fzafZttc+vflsG8dtvFaR1ywau351OjTHYuSYjKrJ1cxJb65t4v5759rIOfeTplYU1E+CmkKwzh6sPQfrscEaZbBuF6xlhbjnyTW+Fllbx/NWyqtmFNRRgtpCsN4erEEH67LBWmWwfpf4vH2y9o/nrZJXnSyoHQX1lKDGEKy7B2vRwfpssGaZ+Ly+C0dV4/UqddCgNhjUy4IaUlBXCWoNwfp7sCYdrNMmPq+/daLV43nVfoN6aFAjDOpmQS0pqK8ENYdgHT5Ym0583hZZW8fzqncHNeCgLhrUCoP6WVBTCuosQe0hWI9PfN4+WfvH86rxB3XvoBYc1EeDmmFQRwtqS0G9JahBJD5vpP1gZtR7B65rCGr9Qf07qAkHddKgdhjU04IaU1B3KYu8M2WdgWs5gusbgpp/UAcPasNBvTSoIQZ1taDWVJK86tq9XoYpa/+aEfUex/UrwTUdwXUOQe0/qIcHNeKgbhrUEoP6WpiyQWR0rIbfm/Gw6P+8X9adFL3jtMN0BtIZSGcgnYGCZuA/s6Lef1PQTgne+G+y/nUa5U3wSxXLoWdfrxLLQRZxUNn3lili17HsKvveMrEcZBEHlX1vmSJ2Hcuusu8tE8tBxmBQanv16l31UzmUXe5Xsjsh9ywpxjyckPXlaZR3jjrZ3GlSKyvG+yPtI52BdAbSGSjnGbjf2v5OyjljZraJ+k3mz+L275eth5zgJV6c5NrIRP1mqjPOUKe4hZu5iRu5gXyed7eMu/gLf86Rd7c+d12j34n6TT7Pe73bjN1z5rhxvsAxnuef/IPsPq92f5of2/ZH/PAK+2T3ca3Hparf7DTO+9jBvfyJP5I9tqvdn2aObWdTcYV9svuIw+M7jPP7fI/v8h2+TfbYrnZ/mhPOqS/x4jQ6t2bPTfo4nYFizMAW/3/2VrbRQCNNNLOdcmuHZTrCUTropItueii3dlGmS1xmkCGGGWGUibZyZlS/nR5GWTnLY3oYZWXW+tiAz+kLXOQSlxlkiGFGGKXUbak1p2UsZwU11FLHSgZm/f/akjoZm+lmhDoZm+lmhLqMvL4TfXIfg9vdH20py1jOCmqoRX+RObxq22Ft6D52FnmNaItMW9lGA4000cx2Jpox1jfRxTC1MjbRxTC1GXnH9tksyz1sYSvbaKAR/UTmLvJ+uWo7JucLHC9y3sMyHeEoHXTSRTc9TDSvS72x1ncyRI2MjXQyRE1W3oOyHOIwRzhKB/aPzFnkfRI5NorWbnBt7o3cxM3cwgxmMosKxtpFmS5xmUGGGGaEUSaa92K916femOsHWSFjAx0MsiIr74AsF7jIJS5jv8hcRd4fkWMich4oefsfdvTomw=="
    },
    {
      type = "objectgroup",
      id = 6,
      name = "Environment",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 160,
          width = 352,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 512,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 16,
          width = 16,
          height = 144,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 208,
          width = 272,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 48,
          width = 304,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 464,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 400,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 288,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 176,
          width = 32,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 304,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 384,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 176,
          width = 16,
          height = 320,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 496,
          width = 320,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 544,
          width = 16,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 592,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 528,
          width = 192,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 432,
          width = 16,
          height = 384,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 672,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 816,
          width = 288,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 832,
          width = 16,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 992,
          width = 192,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 1008,
          width = 16,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 1248,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 1136,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 1408,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 928,
          y = 1264,
          width = 16,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 1520,
          width = 16,
          height = 384,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 1504,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 1504,
          width = 16,
          height = 176,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 1168,
          width = 192,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 544,
          y = 1600,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 1632,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 1536,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 1680,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "",
          type = "",
          shape = "rectangle",
          x = 816,
          y = 1760,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 1344,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 1296,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 416,
          width = 16,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 480,
          width = 32,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 1904,
          width = 304,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 93,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 1872,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 1824,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 98,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 1360,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 99,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 1552,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 1488,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1344,
          width = 16,
          height = 576,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 102,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 1792,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 103,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 1872,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 104,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 1872,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 105,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 1680,
          width = 272,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 109,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 1248,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 110,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 864,
          width = 16,
          height = 480,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 113,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 1200,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 115,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 688,
          width = 32,
          height = 800,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 117,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 1056,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 118,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 928,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 119,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 304,
          width = 16,
          height = 640,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 120,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 768,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 122,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 848,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 123,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 512,
          width = 16,
          height = 352,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 128,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 672,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 135,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 1104,
          width = 160,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 150,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 320,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 153,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 1280,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 155,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 1488,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 157,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 1360,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 162,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 1120,
          width = 16,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 163,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 176,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 164,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 64,
          width = 16,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 166,
          name = "",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 224,
          width = 16,
          height = 208,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 168,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 704,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 12,
      name = "Spikes",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 80,
          name = "",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 576,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 432,
          width = 16,
          height = 144,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "W"
          }
        },
        {
          id = 82,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 624,
          width = 16,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "W"
          }
        },
        {
          id = 83,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 1392,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 95,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 1664,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 1664,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 116,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 1552,
          width = 16,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "W"
          }
        },
        {
          id = 125,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 1152,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 136,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 1104,
          width = 16,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "E"
          }
        },
        {
          id = 137,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 1120,
          width = 16,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "W"
          }
        },
        {
          id = 141,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 528,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "S"
          }
        },
        {
          id = 142,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 528,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "S"
          }
        },
        {
          id = 158,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 1344,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 160,
          name = "",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 1424,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "S"
          }
        },
        {
          id = 161,
          name = "",
          type = "",
          shape = "rectangle",
          x = 912,
          y = 1264,
          width = 16,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "W"
          }
        },
        {
          id = 167,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 752,
          width = 16,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "E"
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 13,
      name = "Checkpoint",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 127,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 131,
          name = "",
          type = "",
          shape = "rectangle",
          x = 816,
          y = 1824,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 132,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 768,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 8,
      name = "MovingPlatform",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 848,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "castle"
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 9,
      name = "Units",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 71,
          name = "Executioner",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 112,
          width = 130.5,
          height = 88.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "Ghoul",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 672,
          width = 76.5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "DarkMage",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 896,
          width = 92,
          height = 93,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "DarkMage",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 1696,
          width = 92,
          height = 93,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 111,
          name = "Ghoul",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 1456,
          width = 76.5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 129,
          name = "Ghoul",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 1168,
          width = 76.5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 130,
          name = "Ghoul",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 736,
          width = 76.5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 133,
          name = "Ghoul",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 368,
          width = 76.5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 145,
          name = "Ghoul",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 1312,
          width = 76.5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 149,
          name = "Ensign",
          type = "",
          shape = "rectangle",
          x = 816,
          y = 1824,
          width = 80,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["title"] = "Ensign Victor"
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 11,
      name = "MovingPillar",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 74,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 16,
          width = 32,
          height = 144,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "castle"
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 10,
      name = "Events",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 72,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "bullets",
            ["value"] = "sm"
          }
        },
        {
          id = 73,
          name = "Translate",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 240,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 320,
            ["Goal.y"] = -40,
            ["Target"] = 74,
            ["delay"] = 1,
            ["once"] = true
          }
        },
        {
          id = 75,
          name = "Teleport",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 80,
          width = 16,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["exit"] = "left",
            ["map"] = "mount01",
            ["method"] = "door",
            ["onTouch"] = true,
            ["section"] = "A"
          }
        },
        {
          id = 77,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 832,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 480,
            ["Goal.y"] = 1112,
            ["Target"] = 34,
            ["auto"] = true,
            ["delay"] = 2,
            ["delayIn"] = 2,
            ["delayOut"] = 2,
            ["pause"] = 2
          }
        },
        {
          id = 78,
          name = "Teleport",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 416,
          width = 16,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["exit"] = "left",
            ["map"] = "mount01",
            ["method"] = "door",
            ["onTouch"] = true,
            ["section"] = "B"
          }
        },
        {
          id = 89,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 896,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "bullets",
            ["value"] = "sm"
          }
        },
        {
          id = 108,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 928,
          y = 1856,
          width = 32,
          height = 32,
          rotation = 90,
          visible = true,
          properties = {
            ["category"] = "stat",
            ["name"] = "health",
            ["value"] = "md"
          }
        },
        {
          id = 112,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 1200,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "bullets",
            ["value"] = "sm"
          }
        },
        {
          id = 124,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 624,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "bullets",
            ["value"] = "md"
          }
        },
        {
          id = 126,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 1456,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "shells",
            ["value"] = "md"
          }
        },
        {
          id = 138,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 1136,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "health",
            ["value"] = "sm"
          }
        },
        {
          id = 143,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 1632,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "bullets",
            ["value"] = "md"
          }
        },
        {
          id = 147,
          name = "Cutscene",
          type = "",
          shape = "rectangle",
          x = 672,
          y = 1888,
          width = 192,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["checkpoint"] = 131,
            ["quest"] = 3,
            ["require"] = 2,
            ["scene"] = "cut03"
          }
        },
        {
          id = 148,
          name = "Cutscene",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 1808,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["checkpoint"] = 131,
            ["quest"] = 3,
            ["require"] = 2,
            ["scene"] = "cut03"
          }
        },
        {
          id = 151,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "bullets",
            ["value"] = "md"
          }
        },
        {
          id = 154,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 1232,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "shells",
            ["value"] = "sm"
          }
        },
        {
          id = 165,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "stat",
            ["name"] = "health",
            ["value"] = "sm"
          }
        }
      }
    }
  }
}
