return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.3.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 60,
  height = 120,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 14,
  nextobjectid = 133,
  properties = {},
  tilesets = {
    {
      name = "strangemountains01",
      firstgid = 1,
      filename = "tiles/strangemountains01.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 64,
      image = "tiles/strangemountains01.png",
      imagewidth = 1024,
      imageheight = 1024,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 4096,
      tiles = {
        {
          id = 1678,
          objectGroup = {
            type = "objectgroup",
            id = 3,
            name = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            draworder = "index",
            properties = {},
            objects = {
              {
                id = 2,
                name = "",
                type = "",
                shape = "rectangle",
                x = 0,
                y = 0,
                width = 16,
                height = 16,
                rotation = 0,
                visible = true,
                properties = {}
              }
            }
          }
        }
      }
    },
    {
      name = "background",
      firstgid = 4097,
      filename = "tiles/background.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 32,
      image = "tiles/background.png",
      imagewidth = 512,
      imageheight = 512,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 1024,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      id = 1,
      name = "Background",
      x = 0,
      y = 0,
      width = 60,
      height = 120,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHt2nXsVfX/wHHsDkIUFQRJUeluQZTu7pbublBKurtDQbq7u7tLQqVLAaV+D/5gc+zrxn5zh82dPx4759ydz57vcz6ve+/u3X327QgRnuPZcBveh3AOwudB+DoQvg48xdeBSNqRicI7ROVd3iMa7/MBHxKdGHxETP6N97Gg+8msOzkpSEkqUpOGtKQjPRnISCYyk4VYfExs4hCXeMQnAZ+QkE/5jM9JRGKSkJSg+4U0C1OEohSjOCUoSSlKU4aylKM8FfiCrGTjS7LzFV+Tg5zkIjd5yEs+8lOAggTdb6jZiMY0oSnNaE4LWtKK1rShLe1oT0UqUZkqVKUa31CdGtSkFrWpQ13qUZ8GBN3vp9mfAQxkEIMZwlCGMZwRjGQUoxlDBzryLd/Ric50oSvd+J7u9KAnvehNH/oSdH+25hzmMo/5LGAhi1jMEpayjOWsYCVjGcd4JjCRSfzAj0xmCj8xlWlMZwYzmUXQ/d2ae9jLPvZzgIMc4jBHOMoxjnOCk6xiNWtYyzrWs4GNbGIzW9jKNrazg53sIuj+dc0bRI3ofYib9m9x+2+P3bF/l3vc5wERnPuz7SlOc4az/MKv/MY5znOBi1ziMle4yjWC7key7sg8q/0cj677vb899oH9D4lODD4iJg/Pf/R3j7YvevwlXuYVXuU1XucN3uQt3iYiQfcfrTPc/u//X3hfwvvyv57X4VyEcxHEXDxsBNH5p3l+2v1/Wtd/7fGnfZ+D7gfde3xegu4H3Xta15vY61USkpKM5KQgJalITRrSko70ZCAjmchMFh5f/5MeB93Pb60FKEghClOEohSjOCUoSSlKU4aylKM8FXjS63v8vKD79ay1Pg1oSCMa04SmNKM5LWhJK1rThra0oz2PX8eTHgfd722tfehLP/ozgIEMYjBDGMowhjOCkYxiNGN40ut7/Lyg+zOsdSazmM0c5jKP+SxgIYtYzBKWsozlrGAlj1/Hkx4H3d9hrTvZxW72sJd97OcABznEYY5wlGMc5wQnedLre/y8oPtXrPUq17jODR59x3HT/i1u/+2xO/bvco/7PODhdzuPX8eTHgfd/7e+W3nS63v8vKfdf3w94fHT/TwV3v/w/j/8LBDOQTgH4Rz8954Hz/ztuf28/Rd4kZd4mVd4ldd4nTd4k7d4m4hEIjJReIeovMt7RON9PuBDohODj4hJ0P1Ymh8TmzjEJR7xScAnJORTPuNzEpGYJCQlGclJQUpSkZo0pCUd6clARjKRmSwE3f9CMyvZ+JLsfMXX5CAnuchNHvKSj/wUoCCFKEwRilKM4pSgJKUoTRnKUo7yVCDofkXNSlSmClWpxjdUpwY1qUVt6lCXetSnAQ1pRGOa0JRmNKcFLWlFa9rQlna0J+h+B82OfMt3dKIzXehKN76nOz3oSS9604e+9KM/AxjIIAYzhKEMYzgjGMkoRjOGoPtjNccxnglMZBI/8COTmcJPTGUa05nBTGYxmznMZR7zWcBCFrGYJSxlGctZwUqC7q/SXM0a1rKO9WxgI5vYzBa2so3t7GAnu9jNHvayj/0c4CCHOMwRjnKM45zgJEH3f9Y8xWnOcJZf+JXfOMd5LnCRS1zmCle5xnVu8Dt/cJNb3OZP/uIOd7nHfR7wb/8G5En6zzz8boLneJ4X+P/+BiOKv32HR9+PPPwNSDTe559+AxJ0P5a1fExs4hCXeMQnAZ+QkE/5jM9JRGKSkJRkJCcFKUlFatKQlnSkJwMZyURmshB0/wvNrGTjS7LzFV+Tg5zkIjd5yEs+8lOAghSiMEUoSjGKU4KSlKI0ZShLOcpTgaD7FTUrUZkqVKUa31CdGtSkFrWpQ13qUZ8GNKQRjWlCU5rRnBa0pBWtaUNb2tGeoPsdNDvyLd/Ric50oSvd+J7u9KAnvehNH/rSj/4MYCCDGMwQhjKM4YxgJKMYzRiC7o/VHMd4JjCRSfzAj0xmCj8xlWlMZwYzmcVs5jCXecxnAQtZxGKWsJRlLGcFKwm6v0pzNWtYyzrWs4GNbGIzW9jKNrazg53sYjd72Ms+9nOAgxziMEc4yjGOc4KTBN3/WfMUpznDWX7hV37jHOe5wEUucZkrXOUa17nB7/zBTW5xmz/5izvc5R73eUCESH6DaRtk/xnNZ3mO53mBF3mJl3mFV3mN13mDN3mLt4lIJCIThXeIyru8RzTe5wM+JDox+IiYBN2PpfkxsYlDXOIRnwR8QkI+5TM+JxGJSUJSkpGcFKQkFalJQ1rSkZ4MZCQTmclC0P0vNLOSjS/Jzld8TQ5ykovc5CEv+chPAQpSiMIUoSjFKE4JSlKK0pShLOUoTwWC7lfUrERlqlCVanxDdWpQk1rUpg51qUd9GtCQRjSmCU1pRnNa0JJWtKYNbWlHe4Lud9DsyLd8Ryc604WudON7utODnvSiN33oSz/6M4CBDGIwQxjKMIYzgpGMYjRjCLo/VnMc45nARCbxAz8ymSn8xFSmMZ0ZzGQWs5nDXOYxnwUsZBGLWcJSlrGcFawk6P4qzdWsYS3rWM8GNrKJzWxhK9vYzg52sovd7GEv+9jPAQ5yiMMc4SjHOM4JThJ0/2fNU5zmDGf5hV/5jXOc5wIXucRlrnCVa1znBr/zBze5xW3+5C/ucJd73OcBESJ7/7UNsv+M5rM8x/O8wIu8xMu8wqu8xuu8wZu8xdtEJBKRicI7ROVd3iMa7/MBHxKdGHxETILux9L8mNjEIS7xiE8CPiEhn/IZn5OIxCQhKclITgpSkorUpCEt6UhPBjKSicxkIej+F5pZycaXZOcrviYHOclFbvKQl3zkpwAFKURhilCUYhSnBCUpRWnKUJZylKcCQfcralaiMlWoSjW+oTo1qEktalOHutSjPg1oSCMa04SmNKM5LWhJK1rThra0oz1B9ztoduRbvqMTnelCV7rxPd3pQU960Zs+9KUf/RnAQAYxmCEMZRjDGcFIRjGaMQTdH6s5jvFMYCKT+IEfmcwUfmIq05jODGYyi9nMYS7zmM8CFrKIxSxhKctYzgpWEnR/leZq1rCWdaxnAxvZxGa2sJVtbGcHO9nFbvawl33s5wAHOcRhjnCUYxznBCcJuv+z5ilOc4az/MKv/MY5znOBi1ziMle4yjWuc4Pf+YOb3OI2f/IXd7jLPe7zgAhRvP/aBtl/eJ2h8B6EMxDOQDgD4QyEMxDOQDgD4QyEMxDOQDgD4QyEMxDOQDgD4QyEMxDOQDgD4QyEMxDOQDgD4QyEMxDOQDgD4QyEMxDOQDgD4QyEMxDOQDgD4QyEMxDOQDgD/90Z+D+xt4uh"
    },
    {
      type = "tilelayer",
      id = 3,
      name = "Decoratives (BG)",
      x = 0,
      y = 0,
      width = 60,
      height = 120,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtmOlOU1EURq+ijwNUKUMHiC8EFCnQCXJeiEEB6QQ5L4QjY0Hj2uI1J40kxn/sfDtZufSmP/qtfUayTCUDMiADMiADMiADMvCvBub54gKUoAwVqMIiLIG32iJQA5rQgjZ0YBt2wFudEKgLPejDAIZwCmfgra4JdAO3MII7uIfv8AO81fwz5i+UoAwVqMIiLIG32iJTA5rQgjZ0YBt2wFudkKkLPejDAIZwCmfgpSafZ9kUTEMBZqAIs1CCMlSgCh5qmRwrsAo1WIc6bEATWtCGDnioXXLswT4cwCEcwTH0oA8DGIKHOifHR/gEn+EbXEDhBXsTzxHcwT14qMkJ5i9MQwFmoAg18pZ4lqECVfBQy+RYgVWowTrUYQM2oQVt6ICH2iXHHuzDARzCERzDAj3u8xzAELxUiVxlsN6+Z55CeD2RhQbv6Hmg94ExELzkbZKrBbY2275rmd+Sr8s7eh7ofWAMuMnbI1cfuuS0dZm8Ed7c8PeriSwWYBq89PeWXCO4Ia+ty/TW8kZ6G+ltpLduslrP5pi382DrVL5WrZGRuRuZu5G56yrvFX29hiK9nYU5SMfxlLO81l/LWocN2IR3Np6Bc2bkvOmmv2lPj8h5DB9gjYzcHyL3iMh9wk3etKcX5LyEK8jXZG9jOe1p8SXzF+aAu0PkDhG5S/zq7RTz20OlPf2zNnO+YiwHxnJgLAfLyfPJ1hd++1ewu5/1NM9p98BLYK0KrFWBtSrs/c7L88kWe03G+fjh7sdczfegIu9mwdv5kbOEnaEe7n7kzfegOu/sHpivVU+2oY/8cNt30/XK6/kxjZ+uV+R1dxdKs9rf6R6UniHHv+flc74mp2OZtTh6yTeeI1+Ta8ldiL3Wbd7xNdnb+XG8v3YPMjhfuLsLjWe1z2vkNDg/ursL/S2vvfP2P+bHcubvPf6POc+mpwzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIwP8Z+Ambv+W7"
    },
    {
      type = "tilelayer",
      id = 4,
      name = "Castle",
      x = 0,
      y = 0,
      width = 60,
      height = 120,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHNmst2XMd1hhFJeY0kpjM1RTUAgswIj2LJY+tyABBERv0maVFZmZmSDgCKdDLoR7HkjCWLBJXLKN93WD9SLJxuNCA05F7r5961a1fV/mvXrRv88Z2NjYN3NzYegT2wD1I+sA6cgFPwDGyCLbAN7oMd8ABon9A2sI1IWfm6lJ+jf/XOxvxLsHHJ59/w9fObv9nYuAveB/fAB2ACNsEW2AarfH4khlP6fAaOwQlIWX7iDBjrT2AP7IMD8AgcgsfgJZCTMlg0N/L9FK6fXIHv7+HzMfgEfAo+Ax3YA/vgAKzyke+HjP9RBbkI498EW2Ab3AfH2M3bKQivcO2ot03N+wXl2i/6Pbi+D+6+uzH7/p2N2VPwMbirxKad/M+Ykxl+sz/A5yn4EnwFvgY9OAYn4BSs8glf13JiVe6Ab4C86rWaeJXmW/nfoMO3B0qh/T6wD/NZt0vdJ3B6H/wAn5pb7Kz5GetgxtzM/oW+ZuB/39uY/RH8M/gn8Py9jd9++e7G9ClYla/jG+Ok4KiK0bVrvXVK860Uj4v+oLKlbhFP+9mmrXvhU7jeA3+BT80t9q+xfwY+ANkbcn4F3GOeOUdI+pgzb/NV+fa064CxCNegUq72q94Vm+vAM63mK299algv5xNk9MPSzr2ibQvI3XUgH20p1+NoF8bzJ3D3Pc4t8BUcye2c3K7E1flwPcslfIxZvpZPq7q+2I6ROdOMIXkM58RmP8Lc67NTpH3br37yVco37VIO39wVx/g4d/b5MVw/AayDOWt/zn6/El/Pqw4kRmN6CH5q4jCW+CT+lJXySrlDrxE+2p6DlJW2a20ZK3eF5TNge/T5B3DMOuZsuxJf+0r/E/ozJ0K9heOJvsiUlcadcvqMnFAnLOtnrqJH1rbD4uucf15074lewJe9PWfPD3c4Z/vKfJ3XIDEdYcvYxvKYcmK1vAyuDeuXtbcv51PeOyDj1jbr7OuMvl6XMbt3N3Z7bB38OMfmnwLuqzn32Mp8v6Wv78AXwHHp8xy/4+z8Nfgz56P7yH3m2aj/GGfrjdP5a+vtu+3fsfSrx4wt9tz9ln/Nnv0H8Efa/Tv4D3DVz69ocwcwX8O4W/S3De6DGXbXkjHIYwJ8lxzg+whYbmFc+ia/6odA+xhs39rTp3bvgpxZ5uRfwb13Nqa8Qaa8Taby/f6djV3lKp/wZT8M4+7D8wA8An9irG9LPIlB6fn6DHToLeI3tjatyzzI5THlRbbMQe4C37sd/MjLlHU8ZR1PWcdTOT69Bt8fC98TeJ6CZyBjKsOjln3hqwy6YotMH5bNtRxjq2XmfVhnzuUbDPzUt0EPP/Iy5Zya8h6bwnPgC+9dea/yyTic7wOnM3i+Bj+BSbFF1m/sxCqP6GMyba3z/Nlp+kx94oDPwLXmV50XU/Iy/Qv4AXxf+N69Bt/PiMNzZutvmUtwH8ilRmJzraobu/Wxq4vwznpNOVL/6JHhC5/hO0mxD/w8X8oYU/Iy5d6d8n6ccu9OV8lp7SPHxDkmyzhv3R+uS+3GZJv4qNdl7fGNj7L10Ra+rrNtUPwHfvK1DZh25PQz0O7hmtMyvaefn4hbqNeg/4xzLpOPCXVB/PoRf/mmPnLML3xdZ55pxXfgJ9/e+N5gdA8v41jX2W84tHKsboK/GKtr26ecN0jKY9I+X8NH6f3TV/wqvlPa/qw1bdyl7yljiWHMI+Q+YxpbpHWWg/imPCbv42+O3Tdtfdq3/fpdqX+DKW2mNV98p6yBKd8VpnxXmPJdYVrn7zK9I45yFpqzc77mxDjkegbqd4h2Yx9rZ10LfeV8gox+WPqwLOo2fjfqsQHjGfjWY2n/CjvfBVf+np956Oi7Wj/2P4wtX+tOGVdZv0Ms61e307YI+grPdXnvFJk5ta5u63e/mp/5zbtXrmUuNq5zVjuObzbHyBva8Y3lIfAcewnad4jrs2636Mzr8au5qNufUJf/48qm3Xms51K+Oc/C+7fYrvO+dMyJYwPO+SEPE2zmQqiL9h3SF7vxHaErV0X61N95Nd+xKbXXc+l7YwI6EN7qYPRu4t21m/Xbyo7+e3BZfup3yEvGEnWM6vYVm3OQ/aqvObQubSPHbNv/38+F+/cJdV+Ast5H76Zl70tjvG5+bFujpzwpyB5NWenarcvq3YjNedIOLty/H2Hne2rm7crvS/dGex4ah3AengNzsQ+U2pObMUmMQ6x9kSkr5VuX1fsRW7V3hzPaGHvGBtPkd4INXPkutq/2PCx9DXtLXa5nhWv3Zpxz3pmPMe5jNvfrmL22Lbt/x95fV3lfyrc9D2u+8sudpN4D8558m7MT5sJ41eu4W33Vt0e73owx99NDctzm/2ts7XfE9pxK2b6Mqz4Pa74Pqc+dlPjNkT5yVnqOy3UHpO0iaR/tHB3SLn0r2/VmjLmH+H192ub/KvewfZm/CejAsjspHOTblXbKwFhd3ymPyQn1op4j+WcOrWvXmzHmHvqcMZ6A3L34X+l9aXyLcESdHGokXqX5NFbnyznX1oPL7rYOnyB9W7avx0Bbvd5y/8bX8p/BfwLa+d5a+X05of9gLP7UuUdFys6F8zTEhl1p3dgcJc4xmf6sM8fG0K637Lnal99NN/4R9LwtBGv6/Pd39+qi3wLSx6L42xjjb2zCcvZxV8rxUY7ZiG+4W+RR62NnUXyM4xU4A/brHUzfc9rP+e6w8t+RbCvq2NMn/Q118all+OpjPpTalDX6qjxRx9f96d/2DsEB5UfAv5u7Tl8D9wM8pnA8/y5o202wBajb9UzDNud+mvPdcOW/I9mPSKyJvbNfoKwxoSzC9yF6zu/0oX8PiPctDHZsp9T5+6r7tfaRv39Lvo+E05Rx3vouyNk855zYla+55rvvBt+Bz/8eyhqe595ZJOnzPP469jqOWo//A9qJlCPjm3Ite/yPgT4dUmiTvzb526d57t/4DHxzF7He56yNga+5fgr4DrzB3bvy35Em+ItF8ae+lUe08fwKv8eln/hp/y9gvuKj7IpfbPo/q3zsJ3u2L+s5dxFrd5cxd+lj9+/4vfjvAffnlf6OlPgWxZ+4IuO/Q1zmI2WlZffXNnBNdgU9Mn7q2lO236xv9efUmc8a5rsDT+DJd6Nd2op5fSavspZd4xl3Ufypj+xKvH2RKUdqZ80N51E9R6lX6pN1HZ9ams8aQ76xfQRPzuVdfMX8R8Bv73N+e5/z2/tcPvz2vvSTOIwheqT5ih5Zx9Xq8elp53k0KWj9Yl8m4Tasa7jubsGPtTzsnw4Jhu+JrOULv0Pz3Xfpp42lLXvmtraxsrHHXuu1TfuiuvhFPsEXrp5duxMwdjd/Dd/2e8LTn8H3Pm3NsXsqcSTmZVLfnGW2P6zaW9e27ahvbT1czHHOZngP53Yt2b9v/W3lN2T2Lngf3KuyvIm+BbZBO05bNj5jTvxyN75FSPsH+Nhup0jXSeratj11F2zwNcfyM89jYI2/9Tv07+HzMfgEfAry2UPZBwfgqvEbm+8Lod6ijdv5Etrl/xiM7ZFleTTPY3AN5Hdouf0BcE5Pv7RQfY7RT8ApMN6rxO+9FQ6Rbaz78Kvfifn/lfJMvp3ntFfmjh3L4xN8x9DTTtTrWpo/+E/1eYV+Bl6DsfjrOFp9wthCe+JvY3Xt+y59Br4Bz0Hapa25Tt/qH4KxHGr7bgHuYO/oG4z+LltRHlT/D+2iMa5ib2M9I4a8+/PG6oytINzrPf45dU8WgHbD/SO/nr6Fvrw98jvPhd9luZemLV//D+1VeC3ybWOt31iuX3n1FcI78iXxf0v9dwtQOE7v2McbvoNe2k9pf+F3Su6lC3zlv4jDVezGOgGJP/IRtkPgGSWnRbCtsD57xHOZ70Ln/OTU8u1LPW0v/KbjuSW/9nMVXst8B46MvwdyXoVr2oWX0rx/A9zn8qrr3P+itrk/LG8j5Vlz7+CG7fys5nvT8HfSMc6J5edK5n+I4xhprPJo+0z8npE5n50b21qnrDFmy11Q8+3hCobx27N6Xfl1HRrrK3AGzMcivvrKRa76qnfFph4ssmEf1nZyfUIf+mrv4D72rg7vNqbrlsMhv7n4nbDta1K46Gt8roES53CeRY/si189h74V9oBzFen3seQXeeGsvottEV/inHO+zol7PgHENm/jvm6Z/obcyfchMHbXRIsT6k6B37Hc4/X/LfB79TFtzGnkJnrhO6WvC2d1fTe1sbMO56yx+StA27Xw9X4S4X+ZrP9vgWc+sQ37IHIPW/jS14Wzur6bWr6ssTlzNz8G9DFwbn2uWw6vI+IzP8znAO8r61KOjK3+vwXu2fAkN8MaIdbzc7uDL3G/dVa7lnNWt7EfwHEf7IFOrGE95y6ST+C6jR7ZFVv9fws8n+szwvWtH/EOe1quYMj32Fnd8qXtwDFycoN8jUv0RaaslG9dVu+Lbez/FryEk8geN8fhfMd2lMGFs7rlu85yYlwkPccW1cU+waeG89TD7RWQs/tk2bt6nfzavhPzmLxPnMY+Vlfz6/CpcafwhfNUzmcAXUzp68JZ3ca0znId95hOfG/lLj7ag4qfvm+9O17A77Kzep382r59Q3ZLIL+xete5daLiO8V34Js35v/A1zXtGd4D65FvndVtTOss98TrG0OotyC+4ZzZo547YviNxLxqd617b7k/J8jAO0ndeeANM/WtVb235Dtwz1m9Tn5t3967xr8Mxpdz57Rw0d8c75T28ksf++jy8x1yCOQl9+4N3ui078iz7+o2ptssf8Zv6eRrN7mSkzxy7pg747a+5ZX8L3t79rRvz+rb5LdorJqvev2e6Cl3oOXlujb/1lWY1m9P+E5/Rf0dffT9hfMb/hPiEeb3IWhz+ZJYa9T5j73HR9Rvz9LvcCcNnOk7Y/6SMnz9DiHaXKY+ss5/bIXvtH57dvQFph15la8+vyTPjJ2Yj+Ra5dLz2LqXlU19zCYXMK3fnsU22P8a+Xr+eu+Ev7Ita+saH23bb/ie/71ps5Sdg5d/Zfk1ftEXWa9Xv/84D/Gp/Wpb3hw5n9p3lvl1TrKmfknJ/L+1Zo31sjOrbROekd7hyTnzMuxf52RC38K5cpzjUo49su1/WXmTPsbqF81p62sM7Zn1fKTPxDZIuHQgfNt3lvm1Lm16dMfpKlvqIveW1MVnTNLvjLazTeB+zJmkfrhCn87HWLt6nrbw6ekrfK1zjZjnL4C/309EGc/6Dt02sSktE+9bc1GPo67fMhu5mjH2bAvo651j/DtFmrtuCWwz1s77OnVZO+HrW2QiJ8A7cnhzOCfxZ/6H+Ug5kpwM69x6eXdF8hY8n4ev0UUPtgv0Sx+n8GR9zaibaQ8yRz22D4Exq7eIf2TaWXbevLfC9zI5wVfIhTwMscRWy67U9UWmrLzMxm8uM97zM87aWWJVTmgrvHc/B09AXb9ITzvrzbHr5DKeqbct62xo4/e0Z1Uc6Ve5aOxV7ORgdgiIa5ZxW/ktY3wHWvtNl93Pr8Br4Pp2/QrtB8VmnTbrzQXxD3//cR7gcOG35G38zkDma9P24KZjv05/ctkHp0CO6gfgFXhUpHXmfQ/ocwL0cS2Rt6HsHko/W9S5j5X6bgL7uE58N93mIXHx/5je/D/AEtu2ZSC/5Ciyw1/dPRCbfnIf7Ojyi198XmG76div05/r0did/zPQ7kfjrtE3Zeu02d617vwdoI/5XSe+m25jfPJ0/ifoLeSvj9I13c6HZdvG7t4+ppy5c99Hv+nYr9Of/5/E/Bpvy9Wy+ZeD+dtsfE4oi7rd61KWs22U2sR14rvpNnWsre769O3jXOyDzElyGWm76JHaXpU2W0i533Ts1+mv5ViXXxCzZbmeAfWu2Gq/ZbYT2rkuzPN14rvpNsYa1BzU5WuduYlPX/mvYpOvfu7jm479Ov0ZfzBBryHfh+AnYs46vap0bdjmAFwnvptuU8dfc1V/UNDar1J2D7uWlYndveH55TzGdltyWexH8HU9Zk58Q+mfcuQym3thDyS/w7uUPnx/+VvNOnnmO1k9xjK+uYtqH++muqzeLbHJT5/tkss99IzPd6ZzPbablPlOVvdZx27cNfqmbJ18ax/1Mb/Y4m+e63HVX2Nb55o+HPlONmFczyVl1udlUv/LfFLveeeZZZ5jC+/bWNMZK1Ke7kvmYuCdmBbJ+8RuzvIOqf3sq4Zc9RXmN3Wu6X1gDOte0+EZmRiM37zJO7ZFUo5yyFmmbruau/oRNvftDnILWddn/NuWxmkejKkD3h1yV1+EzEPit6zufKXONSPfb4B3kXs1dcrb5pnxNolDrg+APPsCzxGRci07fMQEtJzlJ1elfJ1L9697Ne2UGX8dsmM878Cxvs2nZ4nxGHvNIVwWSePWP20inT/n0bV8VqBe9zMWy03ZesaS11h/rjPn33rj7Ur8zoF7TuRsDR/n5hS77fRPm/CJn/W2PwDy1e48iLFYbspmHK8WjHGPGD6g7hEw7r7EL3/jNVbbGqv1ymeU94A+J0Cf1Fnf8nZ+5K3vJjgFN8VtrJ+MX8v4/cjYzr1wry36LUs+Pah5Rc9vWZZjm6BnvOhK4fxl/HXIjBvpmBnnA/QzxnfPiZv4LaujH+E4wnEjtYuMvw7pOnJMz8zDMn7GsexaM7dC7s6/8bWwD32UrmllC9vGFm72oy1SPeOvS8J5xjgD6jFcz75xvIvW9VuWvMM1so5hHXq4KvfguA88ZzyrvHvNvbEswhF1zom5sa0ysasHi2xd6btutw6e6RM+Q24Zb3ZMfOR7OCfN72Vc5fCixCvXM6AtHNSDZbbURSa2dUj26Tlf95gxvwbmd4d45W8cwaTioC5f604rv77YtAfLbBkjPuvgmT7N66RwHt4SxOi9KF/5G0MNfM9zpi7fh8A3ZtbuVeV+mSvH6UBiW6d0nD3g97EDEL5t7HKs4R4Xte2qumPYRrlOjnXfPeMdgxNwCnxnuJ8vi/3INvhlXh5TTuyx1XzGbPp3pV0d023qZytwNU73eHuuteWaj3rQFV3ZA+VtcqzH2lrA15hqJM7aJt+6rD7mF1ud/zqG29R9a7hWJwWeS+r1elym67+svq1L37fJsR7LM6jm6748LBwSWxtzyvdZG+b4efGPXZn5i3yIj3pXZB3DberGKz9lYlsU/xgPbbbNWZb+au7qzqlc+yJvk2M91g7j++5IXs2DtnCPTPyW1TukSP0DdLnaVvkCpM6+5avdu97x6hhuUzdO7yTzswmMt+bT8grHHj+R+sh2XuSqbTLS723yzFiZ8wNi8h727WVsQg5tnH2xh1cr9RddJdVbZPzblubT9bUPIhNbPxJn6q4q275um2fG+z9GTXj8"
    },
    {
      type = "tilelayer",
      id = 5,
      name = "Decoratives (MG)",
      x = 0,
      y = 0,
      width = 60,
      height = 120,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtnMluFEcYgDsEzAvkAInHYxtZskHCdmRzysJjQMLMeJElGyQM2U5keYgcIMEbyBLLIZtNLiF5iRyy4A3LEiSHJMJEOWThK9Gl/LRreqZ7pnu6pqukz1Putb6/ume6/26V57niIuAi0E4RGNrfTjZ7XT7e9+y0C23u+33A91n79vvvhefbzynMyPVvWHTcPBcBFwEXgWxH4BWuQV6F1+D1Nr8eUT1xCcf34QP4MAe+3+B4F76F73Lg+zeO/8C/8F8OfLP97eJa5yLgIlBvBCYPeB/Vu6xbbm8ECgc8rwuKkIdSwrMMlZz4zuE5Dwsp+QbzdWHHlMpdTnY8PX+blcdcw3MdNlLyjZLPUbnL675vs/KYhQ7OXyhCGiVqvm7b921W20p4lqGSkm+U/lWORw429/doDs95WEjJN2r/TjbZdw3PddhIybdZx2Xc7RQOcv5CEfJQSniWoZIT3zz0qXN0EchbBFb4/lqFO/A1BP/PWzycr4uAi4CLgIuAi4CLgItAWAT+2u9ths1Pel6UHGUSbbnMO35X/Pf8bvF5O+F3/qLmsJJwTnObUXNYabYtiX1lrX8PPed5h+FFeAk6oSDool6EbuiBqCWt/t0RzxBkXbf3EOftYTiFw2l4A96EM1ASlKlXYAzGIaulT+RcZV239xSup+EyDlfgE/gUrsKcYJ76AizCEmS1TAlfWdffzz/Q9h/hJ/gZ7sEa2FqWha+s2+pTq907wlfWa61n6/wp4SvrtvrUard0lPVa69k6f1n0r6zb6lOr3X3CV9ZrrWfr/CnhK+u2+tRq97LwlfVa69U7X193qutNdU3a6rIjfGW91e1Kav9TwlfWTftT15a2F+ko6yYvfY1pmldtms4VHN/nnTwP1ZZLa/qy6F9ZT2v/ae9nR/jKelg7gu+1DfMO2MsgS3AZOa+V9T6ea+oi63qa6TP4XttFXN8K+AaXMW2nFdP6Ov4/p2S9FW1JY5/kNE7q/ci6nuY+XQRcBFwEXARcBFwE7IxAJ/dVBeiCInRDj4+dRuGtPoNbCcpQgTEY9wlf0865V3Gbg3lYgEVY8rHTyPMGee42BMP+87cJ8RzuHm5rsA4bsAlbPrb6zuJ3AS4KT+3Syfg4BeiCInRDj49exrbPz/D8HL4w+EoX5WtD6cdjIMTlN+b9Dn+ELKM8K5b4TuMxE+IySJ5kCIZFvsTUjwuW+N7A9WaIr8nN5mkPcH0Yw3eEPM8onAjke7IWi+A7+7p96n3+KOUdPN+F9zLuG8UpbNkVPFfhTkZ8k86b7uL5GP7MiG/SedMRzvlROBHj3A87bty8xiNwnGNwsMHj0HQf2Mu1cxbLeVxnG/Q13QdOZNS3GX2g7gMV8l7wEf+/bbHzbMhv8hpeCnkv+CX/f2WxrzoOTM8I1XR1H2i6F1TzbC6mZ4TKp4SvQhXZxzYfz09tzH/ncFXnrzqm5f2+PJ63LT+2pbnyVa6FHPWxci35vtX6WMYoyXo/70QNwFE4ltD7UcpV9bEu8jzW09L6nMZxBs7COThKu46JtiXVDu2c1ParbfcGjjfhFtyGs7ieS8FXH9fV2pXU9Ac4PoRf4FfQ70sltT+53Vbm7rTnGPdt46Dy5YyLt6fYkp/Z0/AqExZxXIJrcN3g2+r8jCneK5x/q1XOQdPyUn0Txy24D9sG3xXul1qZnzHFexfXx8JX5mxMy0vfbvLHPdALRwy55F1868nPJDXGoSneI/zejfq/78pF5mxMy0vfMRzHYQIYF29PqTc/k9QYh6Z4y/4MNti0vFxmEccluAaMixe7yDEO5znW1HPQRxA89qLuwBRv3Z+m89i0vNznJo5bcB8YFy92kWMcqmsL7Rw89mLvwLBinFh2c+/eA73AuHheP20dgKglOMahvp5SfZxUiRPLMRzHYQIYF8+bpn0zMdoYHOOwzPeJur5oxjGdVLwa2a5pjEPdx3H6oZG2pLFutTEOtXMabUhzH9XGOGzVfUIc9x3/N/2u+G2vtp2wMQ5VH9tQ+hrMvZscnwAQExRN"
    },
    {
      type = "tilelayer",
      id = 2,
      name = "Platforms",
      x = 0,
      y = 0,
      width = 60,
      height = 120,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHlnEtzHUcZhg8O4UfEt2BJTrJAUopbxfJifkec2MKSAiyQFCBAbC3OzyAQ2a6y5AoLJCVUJRXbi/kf8UVVkg0bbJMqoEiy4HlHeg99RnOfORZOuuo909P3r79Lf9090nvf6vX+ANbAH8FVsHSkN7sJHoOp53qz4bvTXP73lH8PuI114jeA2nofrKbiV3hXH4cVdo/0eg/ABrQ9ApPQV2Usi5QN6yxWrFel7VGWmX+u11sAWWESmp5VurLoUdoatK7n0JtX51lOtzw/yzTUGfs4vJ34BvG3SH/rzNuzUvYbp7/PoCyvsn5eAU3CLvSeoO5J8CL4LjgFxsB4xrvK5JV3HdUbVcDf6T0B9xr2MU89YQH8BFwEc0Bp58EFMAuK8lzez7co33XAD0oC/l5vuoVMrjG2dXCjwRjxM3vLwG34eTanrWM56VXmBv+ttwSWW9CqfnYZg/zJhw3GskmdLeA2VkraeIP84+AosE5Yj/R0PK1TE+RtQOcm2GpJr9ff0w3asS6NUbfKuvY+434TnAPWFeuLno6ndUe6duLbzAd4EbQJlxnrSgNa1ed56l0A18EZMAOK2rrDuJsG+BvB3wj+Rk3bUL1bjPE2aBKuUO8q2AGXQNncHaNMXhDvywL6G6G/UVm5ovwz9DNToa+8Nu5DwxgydpNn2dwV0VvGe+xzNAWmW9J7E1pvNaR3inrT4FWwI0Cz1vMH4CH4KxgnvUoomgvVf3SkF2EvItbeqEp7eWW+YDxflozpGPmyq58x/jvgLri3D/P3L+SLz+NgApwGL4Gqa3EZvZwtRKwHEetBK3ptV99i/HnhDWiRXT3K+I+B40D20jZTtGqtuM7Ta3BeW03TOXeIlsByS3rXGKf2+zcK6BV/80JoNyXTXovzyrdND/tr0pb0rSyIv0WBeU/8LPFZOmyZKarTNG8Re9XGTkvf2gTZTfQq8bMk09LhKnPYtE/118ZOa2yyp6cY8xiQ73YaVA2ymyo7RR3Z6lHzt62dtj29yFjngHy3PJtapMePqcdaMeCv5jBrf1l3PtPz3tZO15HnIj22/YTmyHOoNelnzIGgeZzff+bNZ5q2rHf309ROd2VPJ6HTdkvj3IE2tb0O0uGDIE0yUyQ36bp+b2qnx5G7CdBFsN1SW2O0qbYfBLRl9SGZKZKbrDpKa2qn5xnTQgf0vkkb1uF/QMMaEG/rzKV8OO+LZTvHVR9k2c+mdnqNca53QO8qbbBODM5amuiJfDjvi2U758ECyNL3R+gP81vbn95ljA9Ali31XKfzstLlT8uXZr+WBMmyeFvkp+6V/N/vKrTdA1eBQpHsbUAr+lPbn7YtLTuTC88czIOwjn1pjVO0eqxFfqrKpoP31NdoYw0Uyd4S9MpO/2t/ftJtZb2Hd7e+/9060tumne1p7gd5zvI++wSw95wN07LugN1H2VhDXbX8SGctJ9vQqnmTjOSFKcoznt6PCsqk62a1iZxsM3fbtDd0141+zoZp6bZOBv2W2eVQVy0n0lnLSRX9Z4yJ354eR9E7PIuhIy4qUzXP9CIL8WNQtZ7LSXe3wQ6wfNwgnhc2ydsqyM+q13Rs6bY812/vjSFmLPHDjLHcyUhzW3fJE833wW4gK85PP5nTxIdNpxe9Y0/jJcD6HReVK8vzXH/IGJahFfoz2ys7x1A/oln0at04QfwksI6fIi4dVwjXv72U8l/LM+t3XF46v4Tn+ipj2aStjZbted04D33pc2nrOHwarH/5IxvOsTyzfsfDOfXePNddyUuV3pnT2mfSts+s363o9Vx3JS9V6EUHa591zCMTC/v6UNc3CMeEviZrg9trKy9h20Vx61FRmTDPdkG2IfTPX2L8dcIm5bU2rNHOOqjjR9bpJ13WepROz3u3XdCZceif/7QmvZ5n09tGVvLGmpVel17vUyf2ZTqrzSpp9nslL77P1NPxMeKSn5dB1v6uSh9ZZTzPWXlZaXOMbx5Yh7PKVE3Tuil58d5CT8fniEt+dLaTtb9TH6yJUdW+XK4uf69Dq2XQbTR9nqAt+ZSzQEH7umvgY/Ar8Gsg/ncVzNtPa6z1XcmzaLBMay+nIL9Q/rD2a6zz29iz7WWQZHbwY96+W4PeNvKc3tPJz7sPtJdT4I404o40ug3gxfYmWOqI3rPQOAO4Z49fq0FvG3lO7+ns5/mbA+7Ao8tgBYh+PxVvG77CP+JeM+Z+M/5PDV+pDX9XkdMrwHoa0iBamfsIHkTwIlKen2G5pvHb0Mi9dcz9dfxpDXrb8Dfcv0lPw/DJ/rtpDvO6iK9A42VwCbzbkN4mPoJtsvgchn/zfhO+Im8Rchchf1GY3zZ+FhpnwBnwWg16d7AtWiPGGJ/9yTBe5hvcoZ7WXdniMPyYNiXTof6G+V3F6+6R/A3CHOO1PxnG83wDj/cYdJnHTtPzc9qzLHept2EfimuPVJdm1WNsyfdTjK32t4UrrAfwMYafsdpSkP6OSpb3etj7lU/WhGbGWvr9VNhPOm5b6fREf9FZ0qPbHeuu+9CTfWdkmpegnfOGKMzPi99E529B823QJFym/iWgs2D5j+Iv7xHp0coI6eWcIjLN+FuVv8+SviF/pd8maS7sV4V3WfAwZq76zFlf/qP4e4axzICzI6R3kbZNMz5c5fsk8cM6XMZf+1XhXRY8lL/TZ8764rHsM7QnvmRZe23yJ6HRNKudKrZLdCb8YHwzFeRfftUrz/fil8EN4grwMNbTPMYejHwtUn8Kpllx2a4yPZatEn/hTeIbqF7TYB4zh0O+ZNP2qtYTzSor21WmxzfhjfjbhfwhH31olVyPxK8y/S8w3qNAe7LPwB3g7xy1R9uE7i3g8uFTtqqOvQrrpuPQG0Ov/Lzku1vkfCThddo9B7QnS3/nqO/Ci/RYsiwwzsTnaDNA5DmGt1qbepcBduxQQpEeS5YF61ybAWKvtI5rn5Z8Z3z7kOgVDXl6bP7ClyF7lbXOls3FCrReBpcAvO59dYj0aj3OkmvzF74MrZdZ62wZvWeh0zrMU3v8Qw1Zci3fAB9hoHMeYNY667y8J/wUXxMdhs+Ff7+R10aX6ZMZ6xP8jfEBBzrXpj/0dXDOgrzI/ziU4PX4ETKd52dO4wtOgTYDXIFe7HKyd8Ae9KzDZXr8AmWPgpNAd9t+pu8n0u8+o9C9xSsgHTagdxNwFhyl8zgb7i+1pPcstJ6HpxeA1zfpcJkev85Yz4ELYDZ4pu8n0u8+o9C9xc9BOixCJzRF0Bal85iDPnPRT6fXffd5BzZ6sKdeIV4WPE9l5erkS66nwHQGvU+g9XEH9HrcPhvTXesJ5j6UUb+PkW6ZvEc5+YJdB2juQXPyrVbYNnfzfdbofphWJ65vKBWu8LwKdNbr+9bz9GdZlUz6fY64ZdLn9XutdPeLTPeWADI9FHhvpL/2S8Qz8ch8En/dJn32hzqr8HI3Nb6iKg8Lym6Qtwm2UmV4T/SXNSsuajudZ79EPBOPQj65Tfrsp+uVvR9nvqqG0wVlHzEu9HToWy3JXhf3oqHcqM0n0ElfffrsVx27y02m+OH0uk+1MwWmg/Ykezp3P0VaaEPKztvTfW9SH54mQW3aJiAz/XTZsvfFYHxlZYvy1U7IB5UdQw5lWy6SF9qQsvP2dD/wckhuLvGO/9EobDSoZ79FvouD2gn5oPTrpFmeJ/EZXLbuE/s++MZddW/S7q2g77rtpcvbNmptkxym5c9+i3wXB+g5KM+kzTPWtt9xwN/Bmaj09wva/XK/b/rtewxNn7aNWtskh2Xyt0iZtCyr7zHGNg7afqeD3Ax8Velv6GNVpfGj56uWLC+3Ab2hLO/wrjDH2LrgL3M58FVlE27Sbt19kmU2S173Rlv99xH0PQasE0kQXxWu87T+7qU0+52CXux+FNa+RF+XAX33w/S8uGW2irzmteF01oWh74bFV84tY84v440afoZ5EN6pqA/4e8Bvs82quib98jsebf7T/dsnfwgd+vv5v4Ewvsj7ElgGCuIr8drffJsH4Z2K2tuEXq+/eleg/T599um7nySU/HxUgV73b5/cfz//MjoUxuGhzqIH/6dkh/g09E4B5j8uGcogexW60ncqygx1xYW3oLOOLfy8Ar3ek7zI+M8wlhkADdv0v82cby8BvfMckrcx5gNdjikXo1+xx9j0SR9D66/auU6fRbZQsmm59PmFzis+o607wPcGfoZ7klnybR/SY07bZuUn+gudzElMfpyuU/f9BP2fBGHYZewPQF6QbFoufX6h84r0vUH4fxK8J7lGX7YP6fbh3wF7kugvdML3eLEDes/Tv85ywlBHlsN6in/AmP8EmgT084A9SfQXOqfAZAf0Wq/C8RXJcliu6zj28YA9kf6ukb6e4kmbvrGJg7+j+JB41+3XHRuyO7BZ4u8u0BmT1i2fJaX98Dp9MK+DO+e3/w/oxTYN1kjx12dMWrd8llTmhxfRj95E2OmIdS56FYwzj2398qL+ivI094+h1/4k/m2Efzt0bxTWv9HQVoR26zDlWXO/ATYBfkDE/mUk31nYbl1lvqwvp4iPgS50JuRJWVw8XgLL4AyYAZz/R2X1svLlK+hcMu1Hq6xptr5cpNwc6EJnssZSlGb9+oK9DPvxxt+vylfQuWTaj1bfd0m/B+6D8HvhNd7XQd2w2qCO+0CHk3MIfJNW3/xpDFl+tPrReeoJIH9Lfq7DLnWy/K0semQ/mtoQ96endRjfM2JvOrJv/rz2yc91yLLXx6ErrRdd0Ok+9ZQOn4FW9hYj++bPa5/5m8fbN6E3Ty/CMbeJS4e9N2rTTlFdr33m7zx8Xgh47bpFeuEyfmbJgvOKntLhLNkqqlM3zzb6GjQ2tVPpPpvKArIW5c13uo+279vQmyfLdduuIwth20vQu8Y46uwVJEvhHjyM5+3P7+/Lb1VZeoE+jgJ91yD4DGCMuM4Bsr5bCOnKi081kGfJUvg/CsN43v5c3/cpVJWl1+njHNB3DYLPAOSr6Bwg67uFvR6Kf7UmVR2DW4LeCDsazbNXpv/4ImA8MeOKOaOI8TvivDxoiKEldltP+4k81977Is8R62Q0zriRr/gUQN5i5C4+CSZAXh4yGiOrh0Yv/O3kDuVp86lJf14n6spzk76eVh3ZUvlotqE6z3T8HnHZzTVQxz4/rbE36Ue2VD6abajOMx33eeYu9D4AvoNAJ5P96WmeX6fwGHp0xuG9qe8gsLnJ/vStrxm9+M7JPYD2ocJ1sLYfHzVfpWfY8gO+BHa98//fYFrYGw3uzB7Qzw7YBYqPOkjPWKsP+BLzpMmfGIVsae1dBpwPx5xjDe5D/1zjzqzJvPyGef4tuELfV8E18E/gv0kblf3cpI8twPlwzDlWDL9jzrXiX4A8OmzvJ6hXZM+Kyn0MrZ+Ae7RxH2yD3/HO/1hI/iZN9hMfJjnXk69c1E/eOLPSLc+6L5uGRvQ5uQ/9XgG9kkPZ+wVQJHNZ5W5Qx+Ed+lTwGQvyFSFnkfgefhPVlWxP0i70JfZK92XjYAJwnxb/vcDfW2XMeWdVexTs/VYthzwNzkmRs+j7tP8D8EPA3+QPznG1VprnsmmSrzx7pzz5Gfi3g32VfA3zV/cp82ABPO3AvA/dQ/h/sLzDWPmfC0Nr5UXe54BsmuQrz94pz/emaV9D9P0X04nCVw=="
    },
    {
      type = "tilelayer",
      id = 7,
      name = "Foreground",
      x = 0,
      y = 0,
      width = 60,
      height = 120,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHt3FlsXOUVB/BPYrPjhErQnbaU99jZVSDbQzcq4KUFurfTdxL2NnseCsGoTdSWfT+8YycsKdljqU1IBUFt2Xd4xw5LCUm89edgS8jCnkk8mHs93yf9Ejm+9873P7MkPmcyKeWVK5ArkCuQK5ArkCuQK5ArkCuQK5ArUIwK3NqU0m3czh3cyV3czT3cy33czwM8SPAQZVzP2vdzPM8LvMhLvMwrvMprvM4bvMlbvE0Z19nNKX2RL/FlvsJX+Rpf5xy+wTf5Fufybc6jjOsn9n0Zl3MFP+Vn/Jxf8Et+xa/5Db+lwu8o47rVvm/jdu7gTu7ibu7hXu7jfh7gQYKHKON61r6f43le4EVe4mVe4VVe43Xe4E3e4m3yyhWotQI3Ta/1yKlx3L4Gyzs17rWcIlcgVyBXIFcgV6BcFfibn6er9R7KlWj83f5X3mq9h/GvUK7vnuXnrWq9h3IlGn+3P5a3Wu9h/Cvk7+YK5ArkCuQK5ArUtwLtLfW9XtGvduAE8y6YkbrmM4+5zGE2s2ijlZkUPXet+/tweur6Hx/wPu/xLofooZt3qPV6RT9uqyyP8xiP8ghb2EwnHTxM0XPUur8bZLme67iWa7iaq1jOMq6k1ut91sftb0mxgZO9nQWyzGcec5nDbGbRRiszOdnrF+W8jV7XNvFhi+cvH/A+7/Euh+ihm3coyr4nuo+tsjzOYzzKI2xhM5108DATvZ2inH+DLNdzHddyDVdzFctZxpUUZb8T3ccCWeYzj7nMYTazaKOVmUz0dvL5uQK5ArkCuQK5ArkCE69A9xca6+/kjgbLu6zB8rY2UN6eM/2cyMRfBcpxhU5ZOxoo73JZlxU4b7170m2ythY474n2pKs9q3r0o7tL3JPumJFSJ5upZTm2yzldtRxbxGPcV8l9lg7VmLeIGU5kT56LyXMyzaLaUpOuascU/ftea5PX3OPLrCjMT8JMIfTZQ+859GNDjzL07UIvK4qep9r+OmTtHM7bKq+ZUZijhNlC6LeHHnToy4ZeZejflT5vt6w9w3nb5DUnC7OjME8JM4bQdw+96NCfDT3L0uf1b+HUxtAyBw2zwTAvCzOkMFcJs4bQfw896dCnjeMHlvgXP+uk5cN5zX7DPDTMCMPcLMySwnwlzBxCHz70pkuft0PWzuG85t1hBhzmomFWGOZnYaYU5ixh9hD68aXP2y1rz3BeM/4w9w6z4DAfDTPDMEcLs6UwbwkziNLnHXoq/qg5dV2E9zWEWX+Yf4eZcJiThtlhmKeFGVOYu0yJvM2yNuG9HOH9DWHmH+bgYTYc5qVhhhjmamHWNCXy/qspdR3A+1fCezrC+xzC7D/Mw8OMOMxNwywxzNemRN5bZG0n5ZUrkCuQK5Ar8LlW4D/TUte/+Vw3MYk3/ldZ/9JAeSextPmmcgVyBXIFplwF6j3nKnqB6j3nGivvRp9XsqmBPrPkoKzPNFDeGeZkZzbIrGysx3j+81yBXIFcgVyBjytwi95+O41Sj5H5TZHzPqMfcpCneWqCvZGR+c1nnbfJ/yU6g9M5jVM5hVpud5OMG/kzf6qSd5NrbhznuiPzm1pu92SPGfrMmQP2+ST72cc/+QejrznW59Nc6thLuPhTzhl9jfG+nqz5Tbt93swGbuJG/sjovY31+TQzHDudlk85Z/Q1ivD1Rfb5Q37A9/ke32X03sb6fJqDXlOf5qkGem0dXZv8da5APSqwwv/PXskqVrOGtaxjPVNtbZNpOzvYyS52s4e9TLV1RKajHKOXPvoZYJCRtbQ5Vdazl0GWTvM1exlkaUuqjBw79Pthf09/xBGOcoxe+uhngEEme52v53QBF7KQRSxmCUs5PO3j95YskXEdexhgiYzr2MMASz6R17+Jjn+OwXd8Ztr5XMCFLGQRi3G9pIZjrg16QzfTXuce0QqZVrKK1axhLetYz8iyx8padtPPYhnXspt+Fn8i79A5v5flD6xgJatYzRpcJ6ld8ngZc+2X80kO1DnvNpm2s4Od7GI3e9jLyHK/VOy1sos+Fsm4hl30sWhU3r/L8gTb2M4OduL8pGbJ4yR5btRtneK9uadyGqdzBk00M40WhtYRmY5yjF766GeAQUaWx2LF/VOx50ovC2VczU56WTgq72FZPuIIRzmG85JaJY+P5DmRvA5M+vo/ZpU2dw=="
    },
    {
      type = "objectgroup",
      id = 6,
      name = "Environment",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 160,
          width = 352,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 512,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 16,
          width = 16,
          height = 144,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 208,
          width = 288,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 160,
          width = 16,
          height = 272,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 48,
          width = 256,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 464,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 400,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 288,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 176,
          width = 16,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 304,
          width = 160,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 384,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 176,
          width = 16,
          height = 320,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 496,
          width = 320,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 544,
          width = 16,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 64,
          width = 16,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 592,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 528,
          width = 176,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 432,
          width = 16,
          height = 400,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 704,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 832,
          width = 272,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 848,
          y = 848,
          width = 16,
          height = 144,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 992,
          width = 176,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 928,
          y = 1008,
          width = 16,
          height = 256,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 848,
          y = 1264,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 1120,
          width = 256,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 1360,
          width = 160,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 1280,
          width = 48,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 720,
          width = 16,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 1088,
          width = 16,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 944,
          y = 1376,
          width = 16,
          height = 528,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 1504,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 528,
          y = 1408,
          width = 240,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 1312,
          width = 16,
          height = 368,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 1168,
          width = 176,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 544,
          y = 1600,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 1632,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 1536,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 1680,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "",
          type = "",
          shape = "rectangle",
          x = 816,
          y = 1760,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 1328,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 1280,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 416,
          width = 16,
          height = 176,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 480,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 1904,
          width = 304,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 93,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 1872,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 1824,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 98,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 1360,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 99,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 1552,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 1488,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1344,
          width = 16,
          height = 576,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 102,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 1792,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 103,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 1872,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 104,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 1872,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 105,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 1680,
          width = 256,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 109,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 1248,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 110,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 864,
          width = 16,
          height = 480,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 113,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 1200,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 114,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 944,
          width = 16,
          height = 256,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 115,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 1216,
          width = 48,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 117,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 1056,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 118,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 928,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 119,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 304,
          width = 16,
          height = 640,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 120,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 768,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 122,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 848,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 123,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 512,
          width = 16,
          height = 352,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 128,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 672,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 12,
      name = "Spikes",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 80,
          name = "",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 576,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 432,
          width = 16,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "W"
          }
        },
        {
          id = 82,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 624,
          width = 16,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "W"
          }
        },
        {
          id = 83,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 1344,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 84,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 1392,
          width = 192,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 95,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 1664,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 1664,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 116,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 1552,
          width = 16,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "W"
          }
        },
        {
          id = 121,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 592,
          width = 16,
          height = 112,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "E"
          }
        },
        {
          id = 125,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 1152,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 13,
      name = "Checkpoint",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 127,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 131,
          name = "",
          type = "",
          shape = "rectangle",
          x = 848,
          y = 1680,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 132,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 768,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 8,
      name = "MovingPlatform",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 848,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "castle"
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 9,
      name = "Units",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 71,
          name = "Executioner",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 112,
          width = 130.5,
          height = 88.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "Ghoul",
          type = "",
          shape = "rectangle",
          x = 672,
          y = 800,
          width = 76.5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "DarkMage",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 896,
          width = 92,
          height = 93,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 96,
          name = "Executioner",
          type = "",
          shape = "rectangle",
          x = 784,
          y = 1808,
          width = 130.5,
          height = 88.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "DarkMage",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 1696,
          width = 92,
          height = 93,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 111,
          name = "Ghoul",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 1456,
          width = 76.5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 129,
          name = "Ghoul",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 1168,
          width = 76.5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 130,
          name = "Ghoul",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 736,
          width = 76.5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 11,
      name = "MovingPillar",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 74,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 16,
          width = 32,
          height = 144,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "castle"
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 10,
      name = "Events",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 72,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "shells",
            ["value"] = "md"
          }
        },
        {
          id = 73,
          name = "Translate",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 240,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 320,
            ["Goal.y"] = -40,
            ["Target"] = 74,
            ["delay"] = 1,
            ["once"] = true
          }
        },
        {
          id = 75,
          name = "Teleport",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 80,
          width = 16,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["exit"] = "left",
            ["map"] = "mount01",
            ["method"] = "door",
            ["onTouch"] = true,
            ["section"] = "A"
          }
        },
        {
          id = 77,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 832,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 480,
            ["Goal.y"] = 1112,
            ["Target"] = 34,
            ["auto"] = true,
            ["delay"] = 2,
            ["delayIn"] = 2,
            ["delayOut"] = 2,
            ["pause"] = 2
          }
        },
        {
          id = 78,
          name = "Teleport",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 416,
          width = 16,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["exit"] = "left",
            ["map"] = "mount01",
            ["method"] = "door",
            ["onTouch"] = true,
            ["section"] = "B"
          }
        },
        {
          id = 89,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "bullets",
            ["value"] = "md"
          }
        },
        {
          id = 90,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 240,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "bullets",
            ["value"] = "sm"
          }
        },
        {
          id = 108,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 1664,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "item",
            ["name"] = "health",
            ["value"] = "sm"
          }
        },
        {
          id = 112,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 1200,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "bullets",
            ["value"] = "md"
          }
        },
        {
          id = 124,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 624,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "item",
            ["name"] = "health",
            ["value"] = "sm"
          }
        },
        {
          id = 126,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 848,
          y = 1456,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "shells",
            ["value"] = "md"
          }
        }
      }
    }
  }
}
