return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.3.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 100,
  height = 60,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 17,
  nextobjectid = 131,
  properties = {},
  tilesets = {
    {
      name = "strangemountains01",
      firstgid = 1,
      filename = "tiles/strangemountains01.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 64,
      image = "tiles/strangemountains01.png",
      imagewidth = 1024,
      imageheight = 1024,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 4096,
      tiles = {
        {
          id = 1678,
          objectGroup = {
            type = "objectgroup",
            id = 3,
            name = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            draworder = "index",
            properties = {},
            objects = {
              {
                id = 2,
                name = "",
                type = "",
                shape = "rectangle",
                x = 0,
                y = 0,
                width = 16,
                height = 16,
                rotation = 0,
                visible = true,
                properties = {}
              }
            }
          }
        }
      }
    },
    {
      name = "strangemountains02",
      firstgid = 4097,
      filename = "tiles/strangemountains02.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 64,
      image = "tiles/strangemountains02.png",
      imagewidth = 1024,
      imageheight = 1024,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 4096,
      tiles = {}
    },
    {
      name = "background",
      firstgid = 8193,
      filename = "tiles/background.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 32,
      image = "tiles/background.png",
      imagewidth = 512,
      imageheight = 512,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 1024,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      id = 2,
      name = "Background",
      x = 0,
      y = 0,
      width = 100,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt2XfUz3UbB3Cys6KErNtWJJFS9ojKJiujbMqWlhEyojKiKHtm05CRkbJTNpXRsEvDKLM8L+c8zlFP9/ndqvP78ty/P17nc5/fH/d1fd7X+ZzzPed6Jl6cns9cI8ZExYkzlnGM5zriXXZeVJoylKUc91OeCjzAgzxERSpRmSpUpRrVqUFNHqYWtalDXerxCPVpQEMa8SiP/UVPV3oGnfGVWKrfZSznw2ju05gmNKUZzWlBS1rRmsd5gja0pR3t6UBHOtGZJ+nCUzx9MSue5Tm60o3u9OB5esayeezR716+4uto7tOL3rxAH/rSj/68yAAG8hIv8wqDGMwQhvIqwxjOa7zOCEbyBm8yitGEerP/r/M4r9ff+J0LxMn61/eZwEQmMZkpTOUtpjGdGcxkFrOZw1zm8Tbv8C7vMZ/3WcBCFrGYD1jCn99sbJhHBtlnJBOZyUJUNPNYwUd8zEpWsZo1rGUd6/mEDXzKZ2xkE5vZwla2sZ0d7ORzvuBLdrGbP7/Z2DCPK7nPN3zLPvZzgIMc4jBH+I7vOcoP/MhP/MwxjnOCm808Lb/6+xSnL/vtnL//6s1G5vG/31h//i2hnBKRmCRcT1KSkZwUpOQGUpGaGy/L9tIM0l32W3RvNjKPmM/pr/zT//tvn0FnHZlH7JhHTGcSdP6xZR6h3knQuUfmcW2cQWcdmUdkHlfzGXTWkXlce/NIrM8kXE9SkpGcFKTkBlKRmhu5iTTcTFrSkZ5byEBGMpGZLEQR97JM4pOAhCQinPWDzjom8ujzVm4jL/m4nfzcQQHupCCFuIvC3M09FOFe7qMoxShOCUpSiqxkIzs5yEkuchPO+kFnHRPh2COVjgp2j3WpftBZx0Q49kiNo4LdY12qH3TWMRGOPVKvqGD3WJfqB511TIRjjzQhKtg91qX6QWcdE+HYI62ICnaPdal+0FnHxJXukU7yS9Qf90hnOBsV/R7pm6h/b4/1T+oHnXUof2ePdBNpsv5xj5SeW7JGv0eKe3GXdHEHTHwSZP37e6x/Uj/ovEPJrcc83Mpt5CUft5OfOyjAnRSkEHdRmLu5hyLcy30UpRjFKUFJSpGVbGQnBznJRbjrB513KBX0+AAP8hAVqURlqlCValSnBjV5mFrUpg51qccj1KcBDWnEozxGacpQlnLcT3nCXT/ovENpqcdWtOZxnqANbWlHezrQkU505km68BRPX7wjz/IcXelGd3rwPD1pTBOa0ozmtCDc9YPOO5T+enyRAQzkJV7mFQYxmCEM5VWGMZzXeJ0RjOQN3mQUoxnDWMYxnl705gX60Jd+hLt+0HnH1HS9zmAms5jNHOYyj7d5h3d5j/m8zwIWsojFfMASlrKM5XzIBCYyiclMYSpvMY1w1Q8655hap9f1fMIGPuUzNrKJzWxhK9vYzg528jlf8CW72M0e9vIVX7OCj/iYlaxiNWtYS7jqB51zKIf0eJgjfMf3HOUHfuQnfuYYxznBSX7hV05xmjOc5Rzn+Y3fuUCcbL7/nd+yj/0c4CDhrh903qEk0mtiknA9SUlGclKQkhtIRWpu5CbScDNpSUd6biEDGclEZrIQRVyuIx7xSUBCwl0/6LxDya3HPNzKbeQlH7eTnzsowJ0UpBB3UZi7uYci3Mt9FKUYxSlBSUqRlWxkJwc5yUW46weddygV9PgAD/IQFalEZapQlWpUpwY1eZha1KYOdanHI9SnAQ1pxKM8RmnKUJZy3E95wl0/6LxDaanHVrTmcZ6gDW1pR3s60JFOdOZJuvAUT1+8I8/yHF3pRnd68Dw9aUwTmtKM5rQg3PWDzjuU/np8kQEM5CVe5hUGMZghDOVVhjGc13idEYzkDd5kFKMZw1jGMZ5e9OYF+tCXfoS7ftB5h/KWHqcxnRnMZBazmcNc5vE27/Au7zGf91nAQhaxmA9YwlKWsZwPmcBEJjGZKUwl3PWDzjuUNXpcyzrW8wkb+JTP2MgmNrOFrWxjOzvYyed8wZfsYjd72MtXfM0KPuJjVrKK1YS7ftB5h3JIj4c5wnd8z1F+4Ed+4meOcZwTnOQXfuUUpznDWc5xnt/4nQvEye773/kt+9jPAQ4S7vpB5x1KIr0mJgnXk5RkJCcFKbmBVKTmRm4iDTeTlnSk5xYykJFMZCYLUcTlOuIRnwQkJNz1g847lNx6zMOt3EZe8nE7+bmDAtxJQQpxF4W5m3sowr3cR1GKUZwSlKQUWclGdnKQk1yEu37QeUfnfr2VpwIP8CAPUZFKVKYKValGdWpQk4epRW3qUJd6PEJ9GtCQRjzKY5SmDGUpR1D1g849Os311oKWtKI1j/MEbWhLO9rTgY50ojNP0oWnePriHXmW5+hKN7rTg+fpSWOa0JRmBFU/6Nyj01dv/ejPiwxgIC/xMq8wiMEMYSivMozhvMbrjGAkb/AmoxjNGMYyjvH0ojcv0Ieg6gede3Sm6G0qbzGN6cxgJrOYzRzmMo+3eYd3eY/5vM8CFrKIxXzAEpayjOV8yAQmMonJBFU/6Nyjs0pvq1nDWtaxnk/YwKd8xkY2sZktbGUb29nBTj7nC75kF7vZw16+4mtW8BEfs5Kg6gede3QO6O0ghzjMEb7je47yAz/yEz9zjOOc4CS/8CunOM0ZznKO8/zG71wgTg7f/85v2cd+gqofdO7R2fffbGKboHOPzOPamUdsnE/QuUfey7U3j6Aziswjds0gMo+rV9C5R+YRmcfVLOjcI/OIzONqFnTukXlE5nE1+w/IgBua"
    },
    {
      type = "tilelayer",
      id = 8,
      name = "Sharp Cliffs",
      x = 0,
      y = 0,
      width = 100,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt2WdPVFkAxvGTKKD06cML634UaVIHlJYIHPSjCMNI7+BGKfpu61cwUYp0sEGiMOiLTbZ+hf0f5t7lcp3CKKDjnif5JYrDlPPcU+4ohI6Ojo6Ojo6Ojo6Ojo6Ojo6Ojo6Ojo6Ojo6Ojo6Ojo6Ojo6Ojo6Ojo7O1577XsuffSLchAJse0WYfws3oQBf7A3+z7Jt6WOCHhrhxxYdTKARft3HqYW58F/G6aEBPryhg3E0wKf7OLU0WfoYo4d6ePGaDsZQD6/u49TCniF+cIvLv2OUHurgwSs6GEUdPLqPU8u2R4R/pIs/MEIPexdEeAZtGKGHm3Cj0COeXMOXfr/ferbo4ye6+BPD9BGmh2lIDNPDDbhwli7O6D5OPPOsVwtQXSi79DCFVsy7RPgftwj/imdu8eSpW/dx0snwC3HOf9DHDj1MosXo42+6+AXtdHFX93EqyfUe9PGOHh6i2ejjL7r4GYV0cU33ceKppIsqSx9v6eEBbl2I/F3JYj07SxdnsOERYtOgc/zppYs+9GMAgxhS/eA31jHVhfLMxf4BBz93wuVN/NxfU+57hOQsKQu8QjbhPrbB/bDkHkxy7pfb+NzXqeXMU4MAqlGFSlSgHGUJzkQhxlhZiKITQXSgHXdRQw+1uJFifUzQBWdJ6aeDRkxgC346aMQEto6hDyfj7UA+8pCLHGQjC5n4vuDzXmclP/r8SaWM08Ub+OigAeN4Ax8dNGAcXXzObvSgF335yb/OplrTsY41rGIFy1jCont/zgjmjgh84pqf4xBijfFfxwY28SLF+hiji9fw0kE9xvAaXnqoxxgWGf8lLOdHrsHVT+hjiPEexAD60Yde9KAbXe6jr12xUkkfeewh+XDACZcv8e99TRmli1fw0EEdRvEKHnqowygy+ZxZyHZErsFcR/KvU8t41yCAajUXUKk6QDnK3JH9wb5PJPMavbyvasY/gBrU4kaK9LFhrAkjdPESbjq4iRG8hJsebmIEZXzOclQ4ItdglerGmdzrORlvB/KRh1zkIBtZyLT1EYvqaN7C+horvK9+xn8AgxiK3M+nRBzGujpMFy/AuVByFpHsf5I1VzLPJdeWHFb7B5+zGz2OyDXYp7pJso9Nxm4D61jDKlawjCUsGuPddkHIGewh2llq3jhPmazdLPOeTBv0sIkXKdJHjdHHEF1wzyQ5q0vOh5IziWQflKy9kvkuh9T+wfgvYdkRuQZXP6GPIcZrEAPoRx960YNuy/Uv6WEa4Rh9xOql09aJ9bHHPngnEHUe7KOHQbB2SfUz8zs7ziaS/VCyBstBtX/w+bKckTUqB7nO5PuoVfcECKAaVahEBcotfbTSwxR2EW/NsndjqubeMOA/fL9y/KN3chmgi3WjD/M7O86LkjOKZF+UA2r/YOytyo0+qlVnruRfs5351YEgOhFyHFzPLfQwiZ0E8yPevDEN+SPPe7wjdnop8e/fT0nO8JJzo1Tjzf4oc22qjH9TuN7FUTspYu4VowSluI55x+G1pZkeHuKdpY9k5ke0jk500E4gc76Dteo5FrEE1mQ178U93DI0owWTmMI0ZvAIjxP00sFzBtXzIoR7yHBG1hZz7G7RwwO8jdKHuU8cdX6Yfz+VQTzGpPsP1qrzKEM5+Czq2hXPbV0oO9hFGHt4jw8J+phl/O/ymHZ0IGgodR6s9/GY42ztJ14vC8b+nkqZZdzn1NirtRaLWEK36shNRzjv/nh+XORnl3AZV3AV37njv1Yaz/nUtf8drJjFnCHkjMwTK3O8Q66P54f9LGWep6L9LNX6SCtgfiAD55CJbOQhHw5cZ5y5fxbcRwvup0UzWtAKiTbcxp0Efaicce//H4VIQ7phgTFbpas1dZZAiXN/bn40tkfZy1O9jyLGuxglKEUZqlCNAGpwjzHrQjd68BCTmMI0ZvAIjxP0UcxYB1HI44pQjBKUItdyDUS7v7PvDXbWXlK5jw4+fxCdCKELfejHAAbxnPFaxBKW8Q472EUYe3iPDwn6UF2ovaqdx3UgiE6E3IevgXjr0VGYPaRiH/aoPuw572EdQxaykYOLuITLuIKr+C7B9+Tpvsgcecb4z2IO82q9svQYKIi9ViUzb76VPuwpZYyvowzlqEAlWtAKiTbcxp0k/t8ijcemIwPnbL/XaVtzzDGONm9i9fKt9nGcMc9yhYx/EYpR4ol0bk28MbbPg1jd6T4SxzzLtTP+HQiiE6Ej9hHtO8RYc8S6zn2RD5sCsZ/lzPvPTP/hx8XrI9FaFe3n/wLcBQQH"
    },
    {
      type = "tilelayer",
      id = 6,
      name = "Decoratives (BG)",
      x = 0,
      y = 0,
      width = 100,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt0TdSA1EQANGFwhwC4ZFwgcx18EbCBTLXwXsEAeZO+EDmBDS5fkRJC6hfVSfzk92ZKJIkSZL0W0z0RNEkTVGSUjRNMzRLczRECRqmERqlMRqnD/rsifsv/o91drlBm5SnAm3RNu3QLi3QIi3RMq3QKq1936s3iuZ74/6L/+OMnZ7TBV3SFV3TDVXplvbpgA7piI7phE6/78Ut9rzHr3LnPSRJkiRJkiRJkiRJkiRJkiRJkiRJkvRHNftaz2vM69QIvKs9cv2t52nmGcoG3tUelcC+i8xLVI7hHslEFKVommZoNtH5b4jLU2Df98wf6DGGe+TZf4G2aJt2uugezcC+a8zr1IjhHpfs/4qu6YaqXXSP3EDreZp5hrKB93Z6Zv8v9Epv9N5F96gE9l1kXqJyDPfoZk+Bfd8zf6BH79FRzcC+a8zr1PAeHZUbbD1PM89QNvCu9qgE9l1kXqKy99APfAERzzxp"
    },
    {
      type = "tilelayer",
      id = 4,
      name = "Castle",
      x = 0,
      y = 0,
      width = 100,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztXNtSG0cQ3czKv5EEk7wKHGMMAVftlyQil1cECEi4VelLEjmOXwEDhphLlb4kNjh+xVg2lzh2VU5rp0vNeHYlIe0Cs3TVKe0OC9qds92np2eGkvK8JxrfKq/yHtgG5gE6n/fx6X/abratKu/FBNCvvAI+CzgvHAH9PmBpa+WaX3zP+xU4xr2dKa9MwHkwB+C+ggXAa8MW27z+MqyE550G3uCZR9CvO8B/wAJA53jmyogftu2IdrNtBVwUgT70JT4LOC+8BvrQr7a2Vq55hf7/yvfK9/wGH0Po02EA70Mw0mb/jl4DPp6BB7zjHvqW3sWyCbxTFTxH5QP6fBdYBEaVvc32+yYOP/MKefT3OLAMHAJ53962jP5bAVYB4oL8Ypu4UOBCXf2+vYgNh3GKfMPKR5pYU+cxjr4vAhMAnQ9fME5dJ5sDD4j/3sIl8sGx6Ex9yonEv/AJ6EwVsa162f2WlDWLV2nzIYFbos8quKj2QkMeAe/1vbpqeOfqz7hzRfgw23Bc5+PHDHBBdhX0w8bHWphL1Y/JN7bFfbpsHK+a+Ucn39EOH0N+Q0eYF4pbFKvIR5iTPUc1neNVM/3o5Dva4YP6nkHnn4ODL4AvgR6Acisa1y05yscwvXPAiH81+DC5+Q739T1QAMbC+wxoXPfAVT5a1I9OvqNdPtbE8W/g4HegAjz0634cYBwafHR0PNjq+KOT77gIH6QjhL/BwXPgBbDv13Uu2AX2HOUjTT0f0zHHBjNObeFzEr9zHxgE8N4EeG8CvDfBIrDkKB82S4qPhzrm2GD6yClQA0p+eHwCQEdITzq6l+toSfFB+dHtCEgu2C+YD+LiOKz1el/7XXrIa2RJxqsfIiD5YB5q+nhdjwlv+Oh+vPojAlLLmYNJzQlpCY0FfwJ+dpyPOTzffDjOSlzPKT86iIDJB3GwqRo+QuPzP4HHjvOR5vgjLr/ivLcmcKJ5IWQlXnV7/LFuqfe1kl9xrYp4GBR5LnOTlXjV7fHH2xg+muVXclxOoL/1ToXrGbISr7pdT7xr6a9W8ys5F0jn9LcGAFrPQD5y4x/t81GK4aNZfrUmtOMszHnra19m/GzMfZB10z+i1vIUo9b8RFwr15XQOqSa0DjXLc16e7P6lW1dCesH+7Drlub4o1n9ivnIgwf4StAPsH70ox0+1tF9XAdrVgtPs34l9QPxKzgCeA0pPsvFGz5SrV/VLP3N+gJOyis3fLTMB89zx31HXH7FOmIacZWVsQdZt/jgedW474irX7GOmEZcZWVsTtbNePW8CR9x+VWUfxzc+Mel5FcM1hM+p/FR1vzjpa4T0f4XrqGmnV8xWE/4nMdH/yDXepWBOXPioFfn+FviPUw7v2KwnvA5j4+yUm/f0nr5DFjxveoy0GoMaxdx+VUU6L62M6Tp1E+klxPgoQiMJ8hHXH4VBfKpYaPe/sDhukldP/CM/eChD8gnyIfMo6L03JZzyTmzRWDJcT56c553pLzqa+BQJRuv4vpd4q3yKutAKdy/663iPeF4uucwH6Tjb8AB85FPiItW/YOBfK+yAUyHe6rPxdOPDvNBcz1PwMMqsKLqz5sYH7K/KfcdgF/eAwZz4fk3GnR8DB6eAjO0t134xijph8OaTv00CR4mgKLYJ5kEHz26r3u0j0yDhxlgNhd+5xTa8jjuA07AwyYwC0jfWMQ1Sw7zIWOVbE8jXm2g358Cm4KPcRwXc+HP7+p819w3uOcwHzJWyfYk4xXbO/T7MflCrhGrTND+/x1gV++/cXWfGpstVpEl5R8l8Z4P3IJ+AIO3Qt8gm9I8TGnw/n/eo+bqPjW2O+CB99hTfOb2pPig9XK2Oi77jdR44oP/TwnvUXN1nxqb5IPOkx4P0ho32zzHmvYbqfHEh1z/8gFwdZ8am9Tzw4THg2Nao29b+KjpdT1S44kPuf5l1GEdZ5N6vqyRJB9c4zWN9VtqPNUT5fqXLJjU83GNuD6l37kIF7SG6kRrh62Oy/otNZ6M8t2srC0hk/qR10jCN6guM6j9Q9Zv71Cum7NrPBnVdrOytoRM1iKSilOmj5yqRt1kknQi1zg3r9kPa1fly+6ntCyNeQ/TR+775+doZR1FXsNtPBeVBUtj3sOm5xK2ertsz9L6kjTmPUw+TC231dt5jdyWCufOszBXSyZz3aT54L4+MOLSNPp8BpilNS6070E11sid6vU+WfEPmesmzQev99k34tKGaug4+cNfKryO24iPLKwtIZO5bhrxytQO3iPI/kL+cKbCn3HbowzGKzpOI16Z2sF7BNlfKH4N+efXWL/MEB+y1p40HxdZ75O19bv/A4A5g6A="
    },
    {
      type = "tilelayer",
      id = 1,
      name = "Cliffs",
      x = 0,
      y = 0,
      width = 100,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztnIlWE0sQhodZ2JFNfZ4cBRIiS1D0eTj3IoEgi4o+jwsSAgkEXJ7n/pXpMpVmtkgu8TRd53wmxBih/6nu2gbHsdYvG3QdZwgMgx1Qcfv9Hd1vW8D650EB1MCZ1aOvtoX1L4NtMOI5zqjX7+/IWh4aFMCiZ/erv8HK0GEb7Hh2v/obTOph96v+WxUanIIaKFo9/nc78h3nA/jox79H+oi1/pv0EWu3s7mB8HEej3mwDFbAKiiBH/CLn+BXgn8M4e+GwUjCe6xls02lx2s8lsEe2AcH4BA8DBznEXgcxH9GHjoUwKLV49Z2rPTgvK6Gr8/AuXpcxWullDi2bP2j51bFmp+qPPvcb3OJ15pgLUUT6x+9sxPXyQ1Bh2GVZ7MWK3i+CkoZzultvH/H6tET24IeXPegHJv12MfXB+AQNGM0+YL3fVXUrB5dGcVSFEctqFiqABZBEZyq9axTjOW1/eMA+hyCtzH7lYtz3lOMJJz51m4axVIUR22pWGob7IAKGFbrORpE+0ecPcH7n4IxP8RadqNY6hs4AVXyiYHOeIp8Q57lF9DhMmGvIuPc3OrRvfnYcwK3s683AkbBGBgXZ8cy7VdgNWWNOTdnTaxltzms97zb2dera/EtfU3s0X4FDjKsMWti61fd2SbW/7Xb2dejtX+jHnfpudKjQfsV5R9d1EtMq19x7HjshzEQrUUTXIFr8N0P60myvrQGnoMXYH0g+fOPse7f3Fa+8Tv/o773rtLknLTAYwNcgAdBd/US0/Jzjh39oB3/TOH5NJgBs2p9uL5EvAXvwHtwlKKHj/UOwCDg/K+1X3ltPxlXexbFvBTvruP/ewlepcSyBQPzQY4d6Yzl+Ifjnga4IJ8Rj8QVuAbfqRaboscc1nceLHidfW86h1kH3rv2vDDePcL38wF8zJBbmJYP6rFoEWtDWzKxhOfLYIX2ETAJpsA0mAGz4GFKjWkTH/QabIF/sL7/gk1Q4bzcDXt8RTWb8B1/9wP8BL9S9DCxnqjHok+dNnTd7oF9pQnXXanO9xy8AOtdzBN8wfp+BcegMBj2vse8UBvWZxavPwSPwOPB5M8zsZ6ox6Kkg6fxxg81kXWMd+D9H8x2bGGNy2Ab7IAK2AMH4Dl4AdbBS/AqRo/PSgMT64l6LErXrPQRoqLmMjk3OART2NumwQyYTTlDpJ1gjavgFNTAGWiAS0UTXIHrBN/gmJDrXyaZHovqvkHU/XZuIGNhGffepXFMyPUvU2xB7Desh+4bxDh+5okgzA1kLCzj3rs0jgnnQNEg/9gSenBuEOUfS/i5l8EKWAUl0NTi3rs0rie24jSD9DgRenBuEOUfHTGXH2qix713abKeaGr9ivYrqgWNxvgIM4E/JqDJAzDZ52vT5Pkrzq2KCT5CWjzwstfFs5jsHfIcVtY4wcR8kI1zq0qCf3B9iWoaWeviaSZ7hzyHlTVOMDEfpPycZpk4tzpL8A+uL3EPr1fG+w7Vy0hvOpuuU7QwdT6Rfq4FlX9wrS/p/Oi1FmS8rlxTLKk4IclMnk9s+YiIV3jto3zkT8/xL6rH8g2cgKrKr5ma0oNrMmkxtPRp04xqWHJefNENifKPPz3HXdVjCcAgGFL5tZwxIT24P9jUemC6llXfzHoJGdWw5H5M9xHvxOTqsobVjXFOveu268ZU36f9SfanqAYwqeoAcsZa13IoMK9eIk3uxzXVU408P8T1K3u3aca9D173Z2BJ6HAuII1oJqj1unpsqLmgOs9A4OsJ1Zcx2cj/E88Pcf0eitg0zX7PsAkN6poe9RR4PmhCzQtRr6x+x7Wauzbyf177KP/gekmrhytirbR4iHtR+6rfQeyLR+p/5AfDPhWha7GserrcsywqLfYN9g85/xHnHwRpQr1bjrVmVL8wyVyssQcuVL+jIZ5fqN6H7FOxPvmY56zboqHnBxnXeEe8eP9gH6G8kGMt7hdeJ2jyBGv3NKX/KvtUrE855rnUzVST8x88zxnlH6TJpNtZM5nGizO3zBOvtLWtil4i2ZnqJ+q6mWrXA87GFWgCnA8bSeeIjLUu/Wz3YFrrznAObEyDKYDrf2M34RyhPUvGWllmCq1lM1fz+Sg/iTpDqF/Ic1myX2jtdvZE00P3E9ZD95Fxrz2XJfuF1npriF031kAJYK03CkEYV97wEVX32Av7UznEWrkS6Os3b7Dx7GKe5gmVJkXwTOWMPJfeCPu3OeQiuakYPeQcPdcF+T7CuF6gft9hceDm73JYu0f7I9V8ucY46ocz0NI/aL9q9dODVq6eQ66ea3rResg5eq4L8n2Ecb1A/b7DysDN3+Xw9h7pQSb7InH5+niYH+YOwGGMHnJmimeG5P03z7CuS+r6l/0Rqqed+ckzL/fJZF8kLg9Z8sMZh6R7Nri+WxO1fJ6xo5h5Fzq8Ude/7I9wb8Tq0Tbes5LWBOv86RRUQdRncC2fajE1Le+X99pSXT3p/7F6dO5ZcfMnuOY/bYNyjB7cW6VazFKKtlaPZOO1pNnMXT/MBfU1kWdBM6ZXTmcBaRr17++THhxr6vdpRq1Z3MwBn6vco9P9Q54FUzG9cjoLyDfk/Zv3UQ+ONfX7NKPWLG3mYCwI5931NVlVsdM8WNDmr/n3MbRiY68dJ9OsYy/0+A+GyFWN"
    },
    {
      type = "tilelayer",
      id = 3,
      name = "Decoratives (MG)",
      x = 0,
      y = 0,
      width = 100,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt2k1KA0EQhuFmxkwu4Tagtwh4iQhuA/5cwYWQSyi4daPgJbyEHmDWXsCFHSTGRW2GTE2/Vn8PNPQiEyr5KtXJkJRERGQKt21alq5B9r4a5SFSQj+z9wTk2rysO3tPsOjsfWTkPMi1eXnq7D0BuTYv5JnQd/Y+MvJMINfmhTwTasyDPBPIveKF3IPks80LOQ9ybV7IM4FcmxfyTCCfbV7IM4FcmxfyTKgxD/JMIPfKznlKd6u8hlyz+rnOtJjbewLy2XbSpHSa10PO4n5gHvnx2+tM67m9JyDPq8ucxVVeHzmL94F55MdvrzORX/N/mFdjI79m8tnmhTyjyb3ihTyvavx8kHuQ/N3PC7kHyb3ihdyD5LPNC7kHcwZLax8ZuQf72T6Dv/vIIvTgcaD/LkbowYtAeUTwOHEeNf6vmIx85taIfE+jRuTfCDXSvGLRvGLRvGIh34OtEfkeLM3rBO+P5hWLvl+xRLgHG0mkPDZN6QoOF+Ge+M5bgDwiadvxnuvzaLznqtWYecjhzpQHykZ5iIiIyMSu87opXYT8es7rpXQRzr4B+URduw=="
    },
    {
      type = "tilelayer",
      id = 5,
      name = "Platforms",
      x = 0,
      y = 0,
      width = 100,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztm0tPE1EUxy93+ikECsojuhBKIpCgCz6HiIAFogtp2UgCLPggRggFogtpia9EXPBBeCTy2EnLQk104/86vfR0nOkMM9NOZc4v+af1dmjGc3rPPefcO0L8H/yQQvyUUd8FoxkyhBg2or4LRrNjiNGo74GpMM/+iJw++KAfSkED7I/IOZditAiVoAvJ/oiabfggDxWgHfZH5MzBBxkoC82zPyKnDz7oh1LQAPujJm2ozW5ArWV1QjehbqgH6g2hdjtvwfoBlaCLFvZHLR7B3g+hsbImoSloGpqBZrmWbigvy/ZOombugD7g3x+hDWgT2grJH6/w3atcl7uyD3sfQI9hqwnouzR7TCfQKXTmwR/tuCYJdZB4dwvqInHvEN99xP7wjP79Dhpmj6kb6oF6PdhwXPkTmiDx7gmUJnEvmYC/oM5E/f8vzUAX7DYNzUCzPn6Hen4o0gG/izH9sQFtQls+bGiN73p+MP5Qv+kT6BQ6M8y4fZvojod1gMZ3PT8Yf+SUDxCbe6DehBm3nxI9c/GHzq80eq4x4fEaPnjjMV+l64dCzzWaI4VRGzLuvDX74SIFFfBe7RnpuUZzJK4NG8Nz2H8OykBZSO8ZrRP76/Wd8636cxf2V3tGGdg/C83bzIMguRtzNb5JMXpu7lGIArRj4w+au9WqxelYq8t11nFen6pBzBKIWSJrMwdo7larFqdjYy7X0fEpXp/+YRt+yJtrOtMkcM+vuThEzDjiuBEKukceBGudzvgjbYRTI/C+UTjkAvZ3KbyGBIf2d2lO76W/S88zqH08u5rBOsa1Qm1of5fm+l76u9bzDHY1g3WMawV3crDRe2meSfCztuvcatXl77gX3xh0buWW7+q4qGOZNbZxXAsPL/WHjos6llljG8e1atKG/5jiN9+9B7sPQkPQsKzO9+JOjuRa+0QHDrlTZzmv0q+18t0XFrvbfb4AHRvVcc3uTFZcYtkxybXaiNoT9rmT6tcmE5XXq7BQtqnOI9TZxk/K7onquGZ3JitOsWzREGsj0C8p1j5Di0o2YyPSeUy9pqSYzEIFSO9XWW1fwmf0Oqf3UdskSpZgz/vQb9h0F1pSshm7L53H1Gu/6YfJvClzv8oQewUoD21DRXxGr3N6H7VNrhtFcy6oZzL3slAGmoOivq+4sGyxtT6DMoDxY1npX/axTxqK9oteP9TcoOeFGWfW62Af7Q+9fmCO7AWpceLE1zr5Y9lct/+uH6q+yRl85jpKlD/0+qGg/f2umNV3zcADMj928Z7295XiVt81A3R+vLPUhUH37Rl/fMHcUHW8mhvwzWXtXeJ6LzIua2+jUnsXa/iDz0g0F+yP5qBdVvfwEd9WMKdWor6vRqPPizidQ/f6PGFQxsu9ff2sM+r6lUwM/aHPizidQ/fyPCHDMAzDMNcXeta3VTo/O2g3xj3H8KFnfcek87ODdmNx6jn+AS1CUeo="
    },
    {
      type = "tilelayer",
      id = 7,
      name = "Foreground",
      x = 0,
      y = 0,
      width = 100,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt3El0Ulccx/G7lCGk3XRy3psZUGPU7Fttu261t3sDGQgZzODKntNW2y47aG/3FTIAmRNX9lRrl7Y9DtW9gZAAztovESrJIcaQAPFx/+d8jifnkPByf+/d/72P+ITQpUuXLl26dL0u5SsTwo8BDGIIw2XFPqrSrTBjH8EcopjHgs6jaFVpE6IK1ahBLepsxT6q0i0XY+9GM1rQijadR9HKx9j7MYBBDGFY57FhFS4XygcXKhG28TW4DhRzk6JfKHq4+v/1jH0Ec4hiHgslkscVs2j8A1eRr/eIkIEfblSBsVac/4o5SdEnFL1b+TPyIDPB60Q1alCLuvJ8Hd3mqq/I4Wucwdk8ZTJHBgNoBmOsOO8Vc5GiPyh6tmIdpQYy8uA6EmQneL1oQSvaSiSP98ngAxzB0TzlESWDQTC2ivNdMQcp+oKiVyvWT4o1rRrMyIO5TXA9CTIUfJ8YwnCJ5GEhAyvKYMtTHvNkwJgqznPF3KPoB4oerVg3Kdayiv2FGsrsH+WLc1zyukpmmfx+sVAieVwx0T9wFX+a8pMHY6k4vxVzjqIPKHqzYr2kWMMq9hWKvZ4azshDV34rRgYBeGBHjAwC8MCOGFkEdB4FqzgZBNEOB+JkEEQ7HIiTRVDnUbBKkEEIXjiRIIMQvHAiQRYhnYcuXbpegzptEaeKfQyFrt+tQly2vvrrv7Swd7fk73gy65IB83jbJsQ7eBfvYSu2YXvqPpypTAjzGj7TuUwWVwqUhy5dul7UNZMQf+Fv/GMq9tHo0qVL14vabhZiB3ZiF3abc/9Zs1uECCOCOUQxjwXEtmzcMRu5jjH+x/EZJD5fRx4V9JtKVKEaNahFHey6F71SnWP8z+NnKPyyjjyaGHMX3GhGC1rRBo+B8zhjEo1n8Q2+xXd5+mxkrXWBMffBjwEMYgjDCBg4jyOM/1F8iI/w8SbJY5YxDyNi4LHPVmWMvw3leANvbpI8KpjrKlG1jjlPV/Y6YxHi7Ar3ZBwmIZP/Bvk3Dof5+ddN5OCCW+dR1LKn8rhADj74dR4FKfYQknWrZK0k6c8yhmQWnlQes+QQRkTnUZBiXyfZS0jWr5I1k1xAHVm0pfKosNI/UIVq1KAWdbDDsYbPFHStXuy1Jfs7yZ5Cso6V86gli9Z0/2C8XXCjGS1oRRs8aNd5bGhFyYM9t2SfJ9lbyChqyKIl3T8Ybx/8GMAghjCMAII6jzXXy+4/xbcs3geR7L0l+z05h2qyaE73D8Y7jAjmEMU8FhBD3MB5nOZ3+6KAv1/y/pPj+b0p6QZ7cMm+T7LXkO50/yijf6AK1ahBLepgh8PA/6/tEln8VoTzrZIMXPCBvbhk/yddqTx0Fb4qyKAJFzAL9uSySeexWD3sn3vRh36cyvFvHK7TF27gJm695HOKu/TzPWRwAr/iLvaQxQmdx2JNMv5TmMYMLuaYx1b6wjZsxw78Sya3cUd/hrSmesz4P8FTPEtmkWM/+YQMPsUxHMdO7MLuErtPu95qYPwP4hAOozHHPH5k3H/COZxP5aFr7dXD+PeiD/04lWMe1xn/G7iJW8n5CrdxR+eyatWXicYDaMAk4z+FaczgooH3W5u1HlpF4yM8xn3O3wf6HC5qjZPDhHXx2mjcZxZi/ya5t53tmT8BBBEy8L48XSOsp0Yxloe/q3Zyze3FPuxHPQ6gAQdxCIfxlu3F34pne+ZPDHEkSiCPe+RwHw/ykIeXse5AJ7rQjZPoQS/60L9snsz2zB87HHCWwPM09tK792H/Bvbw7/lZPyDEWI9gFGMYxwQmMYVpzCzLI9szfzxoh9dAeXg5/zvQiS50p66HDsatE12r5PGqc09mJfj6HtLrhYd4hMd4gqd4tux7sj3zJ4AgQgbKI2RZ2ivGU3mMkMMoxlbJI5e5x8kaYS/S64V6HEADDuIQDi9bR2R75k8McSQMlEfCsrRXPMzoFz2MSS/60L/COiuXucfLz+pAJ7rQjZPml79ftmf+2OGA00DP03Bal/aK+ozrIb03n2ZsZlbII5e5J8TPGsEoxjCOCUxiypz9/bI988eDdngNlIfXurRXdGfkkd6bP2Vsnq2QRy5zz0qVOUeyDxITGceS7Zk/AQQRMlAeIWv2cUjfK1mtcpl7Vqp7vN99PLAu3icQjzLe/z8bFB62"
    },
    {
      type = "objectgroup",
      id = 9,
      name = "Environment",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 928,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 816,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1312,
          y = 160,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1216,
          y = 256,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1344,
          y = 176,
          width = 48,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1392,
          y = 336,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1328,
          y = 544,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1232,
          y = 608,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1280,
          y = 624,
          width = 320,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1584,
          y = 0,
          width = 16,
          height = 624,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1536,
          y = 448,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1536,
          y = 240,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1440,
          y = 832,
          width = 160,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1344,
          y = 864,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1232,
          y = 832,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 848,
          width = 16,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 928,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1104,
          y = 768,
          width = 16,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1008,
          y = 656,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 752,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1040,
          y = 672,
          width = 16,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1008,
          y = 464,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 992,
          y = 384,
          width = 16,
          height = 272,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 816,
          y = 352,
          width = 240,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 0,
          width = 48,
          height = 208,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 208,
          width = 208,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 368,
          width = 480,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 0,
          width = 624,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 160,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 176,
          width = 32,
          height = 208,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 304,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 16,
          width = 16,
          height = 944,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 272,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 496,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 496,
          width = 208,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 512,
          width = 16,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 512,
          width = 16,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 592,
          width = 384,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 320,
          width = 16,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 544,
          width = 176,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 592,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 944,
          width = 544,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 608,
          width = 160,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 624,
          width = 16,
          height = 176,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 384,
          width = 16,
          height = 368,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 608,
          width = 16,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 832,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 976,
          y = 768,
          width = 16,
          height = 176,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 752,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 83,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 848,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 736,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 123,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1376,
          y = 560,
          width = 16,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 125,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1584,
          y = 672,
          width = 16,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 14,
      name = "MovingPlatform",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 144,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "castle"
          }
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 736,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "mountains"
          }
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1104,
          y = 512,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "mountains"
          }
        },
        {
          id = 86,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 928,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "boss"
          }
        },
        {
          id = 87,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 928,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "boss"
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 16,
      name = "MovingPillar",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 102,
          name = "",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 656,
          width = 32,
          height = 144,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "castle"
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 15,
      name = "Checkpoint",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 71,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 864,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "",
          type = "",
          shape = "rectangle",
          x = 848,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 121,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1504,
          y = 752,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 11,
      name = "Spikes",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 16,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 224,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 576,
          width = 224,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 864,
          width = 16,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 656,
          width = 16,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "W"
          }
        },
        {
          id = 109,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1440,
          y = 608,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "N"
          }
        },
        {
          id = 110,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1568,
          y = 512,
          width = 16,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "W"
          }
        },
        {
          id = 116,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1136,
          y = 912,
          width = 96,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "N"
          }
        },
        {
          id = 117,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1232,
          y = 848,
          width = 16,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "W"
          }
        },
        {
          id = 118,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 800,
          width = 16,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "E"
          }
        },
        {
          id = 120,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 672,
          width = 16,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "E"
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 12,
      name = "Units",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 33,
          name = "DarkMage",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 112,
          width = 92,
          height = 93,
          rotation = 90,
          visible = true,
          properties = {}
        },
        {
          id = 85,
          name = "Boss",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 720,
          width = 132,
          height = 125,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 108,
          name = "Ghoul",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 128,
          width = 76.5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 112,
          name = "DarkMage",
          type = "",
          shape = "rectangle",
          x = 1312,
          y = 160,
          width = 92,
          height = 93,
          rotation = 90,
          visible = true,
          properties = {}
        },
        {
          id = 115,
          name = "Captain",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 864,
          width = 80,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 122,
          name = "Executioner",
          type = "",
          shape = "rectangle",
          x = 1312,
          y = 448,
          width = 130.5,
          height = 88.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 128,
          name = "Ghoul",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 240,
          width = 76.5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 129,
          name = "Ghoul",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 464,
          width = 76.5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 130,
          name = "Ghoul",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 464,
          width = 76.5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 13,
      name = "Events",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {
        ["exit"] = "right",
        ["map"] = "mount01",
        ["method"] = "door",
        ["onTouch"] = true,
        ["section"] = "A"
      },
      objects = {
        {
          id = 43,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 128,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 192,
            ["Goal.y"] = 504,
            ["Target"] = 44,
            ["auto"] = true,
            ["delay"] = 2,
            ["delayIn"] = 3,
            ["delayOut"] = 3,
            ["pause"] = 2
          }
        },
        {
          id = 56,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 1104,
          y = 496,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 1168,
            ["Goal.y"] = 136,
            ["Target"] = 59,
            ["auto"] = true,
            ["delay"] = 2,
            ["delayIn"] = 3,
            ["delayOut"] = 3,
            ["pause"] = 2
          }
        },
        {
          id = 57,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 720,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 800,
            ["Goal.y"] = 600,
            ["Target"] = 58,
            ["auto"] = true,
            ["delay"] = 2,
            ["delayIn"] = 3,
            ["delayOut"] = 3,
            ["pause"] = 2
          }
        },
        {
          id = 89,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 912,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 280,
            ["Goal.y"] = 760,
            ["Target"] = 86,
            ["auto"] = true,
            ["delay"] = 1,
            ["delayIn"] = 3,
            ["delayOut"] = 3,
            ["pause"] = 1
          }
        },
        {
          id = 90,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 912,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 376,
            ["Goal.y"] = 760,
            ["Target"] = 87,
            ["delay"] = 1,
            ["delayIn"] = 3,
            ["delayOut"] = 3,
            ["pause"] = 1,
            ["replay"] = true
          }
        },
        {
          id = 91,
          name = "Translate",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 848,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 448,
            ["Goal.y"] = 872,
            ["Target"] = 102,
            ["affects"] = "Player",
            ["delay"] = 2,
            ["once"] = true
          }
        },
        {
          id = 93,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 672,
          y = 544,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "item",
            ["name"] = "health",
            ["value"] = "md"
          }
        },
        {
          id = 96,
          name = "Teleport",
          type = "",
          shape = "rectangle",
          x = 1584,
          y = 752,
          width = 16,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["exit"] = "left",
            ["map"] = "mount03",
            ["method"] = "door",
            ["onTouch"] = true,
            ["section"] = "A"
          }
        },
        {
          id = 103,
          name = "Translate",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 880,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 448,
            ["Goal.y"] = 728,
            ["Target"] = 102,
            ["affects"] = "Player",
            ["delay"] = 2,
            ["once"] = true
          }
        },
        {
          id = 104,
          name = "Translate",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 784,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 448,
            ["Goal.y"] = 728,
            ["Target"] = 102,
            ["affects"] = "Player",
            ["delay"] = 2,
            ["once"] = true
          }
        },
        {
          id = 113,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 496,
          y = 688,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "shells",
            ["value"] = "md"
          }
        },
        {
          id = 114,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 784,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "bullets",
            ["value"] = "md"
          }
        },
        {
          id = 126,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 80,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "stat",
            ["name"] = "health",
            ["value"] = "md"
          }
        },
        {
          id = 127,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 816,
          y = 80,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "shells",
            ["value"] = "sm"
          }
        }
      }
    }
  }
}
