return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.3.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 80,
  height = 80,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 21,
  nextobjectid = 71,
  properties = {},
  tilesets = {
    {
      name = "tiles_spaceship",
      firstgid = 1,
      filename = "tiles/tiles_spaceship.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 16,
      image = "tiles/tiles_spaceship.png",
      imagewidth = 256,
      imageheight = 224,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 224,
      tiles = {}
    },
    {
      name = "tiles_ui",
      firstgid = 225,
      filename = "tiles/tiles_ui.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 13,
      image = "tiles/tiles_ui.png",
      imagewidth = 208,
      imageheight = 128,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 104,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      id = 1,
      name = "Background",
      x = 0,
      y = 0,
      width = 80,
      height = 80,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtm9lu7DYMhvPO033H6Tlt0b1oUqB92uq/+IAfBLXaHk9mciFQEndaImlP8u7p6end23iLwcln4FL0f1YG8O1Mzt3Lj0rsPi0DeG/x+7v49lzGUX59XGR/UgYw0/NFwX9Zxs9l/FRGRsP5BWY0Z+xhz4/Fbh81P46w8Zui+9syfi/jh2CHbJItnF/gEXasyMQeYkfcPhSbV+St8nxf9P1T0SlbOL/AVT3i2/PORXuIm+C/FX+22C5eyeV59aCeZ3YmR/hqdm65c+jlnOlZaKDr8zInH31l++D3gDyjEVkztC6vxbflzhG3mvyvS8zIR9/dafy23DniJqhz90cZOs+qff78lI/ehz3Hb5ljw4iMGVqX90ux/dcyuG+CnJ0tdw57BMlDv5W5ap/rP3KODSM6Zmhdns7Fn2V43GqyRu4cOS7Lb38VPbXa5zatzHW24/uHzkY87zXZNZ9r9Ozjr9bIENT+yp1DXoy1ns9LGUfFj1wNlD+yf/S84ztxGYXyF5+RIbhy51wW+slvnh/A7QnJ1cBZ2fg+yyd64nftO7di61E8it9zGSvyid+179yKrVt56DnjO/ClxE75c1b+mXdu1tY96Ok54zswedPzDHP6kT3034MM3oHJ8YoTeZOYCRK3LbnxHuJV88Hjwj0kl4kHvKDv1+SdsS+7VvP2VnuJT00OeEGd1RrdmfuXYpfytt8bvztH2kZ/XdOd9SNH2rMiO+bta+acrL/WfeDcxX5kxb+jecjb6MH2a92ZmNe0jt8BeQfAxmvDo75R7O2HYsfYW/YWeVu+UXCft+h/7bx+R/x+ar/3jQL6mRhIrmo60Pu8WCu0npF9Bq380JBu4kF+k/2t74LQz9h9KTL9WxYy4v6MzB6t/NujD+s966wnaH0XxPee/Y6npgORwRroPFvnPJt4vmfzj2xFFtBtiz2B9L2UUfsuiO8uozenpgORwRrYkzOD55kQP+KG7lFZokcWMOOlJ5A+dGV0s/qPkpHJ9b34TLBbUHfSaVtz0SML2KIXDl0ZXQuX0Wd7vGdkuJm9a/RhK/62eFq4Ud+z94xRXqfb0oe5nNZc/mY1osdTw+8Rv5rs2X3VWHiwS1D7vT4Mvh6UvFgjRnhqNNhZw19zX3EihtglSM/R6sNG7dS7I7ReI6hLGfzPeOAFYifrsyHxy+5Yqw87y+5bjV+8YzoXL2XU+rC94sdZz86h79HT3FL8/P4Sj+yOgTsCEo9LeVb+jhV1QQeM+EddEw96a2CMB3TAiH/UNfGgtwbGeEAHjPhHXY/GAzrgo8Yr+h2/jatmUCugzXoD70+9zsDzGuBI7VzxI56xrDdQzPboT1fs24sHP3u1c1YfciOf9wbC3WJ/Gm1urfGTmgls8Yzgsjvtd5T5NfrTEXtXaYgfNRO4Ku/R+Ijfa/Vb7w/PZZxlP/HL6uNZNmV6t/6NH3EGjtRNckxmD3vEL9ZH8LcCt/6NX6yP+B33Z/1FDnzUR9a3BGWbvoX42SFfc1YE6T3dN+oiEBxr4Ky/yJnlO5PebdZ9ZGATeEHhtE+cgdCwBiIDmOU17/uRA/1rgD2bwQvqrGY+QZPhfC/mNc45ff+oHJd59pzf3vAFyL3Nzky0Gb9HaMVLXpMuren7kRPlb1nrmeNTD+LzjD7dn/g/NLqn+BLPTCZ7hjbyy6eXMpSLkRNptqyReSnyW99TpQPaWX3kNfi09nce7XNmoHEY9bZonS/Oo5yIX1kjk5oGzGRBm+FG9xQ7xijPHnqlay85bjcyqWlA7rLfWWidvzXPzh2xi7hMjvfhGX52b9b+Efk9mY73+YhsYhRj1vo7DMmFz/vwEX09mln7e/KER2attoF32hG5oiEOkV41ZfR/dunDV/RHve5LxK2ukVmrg+BX7K/Fz/eRL6h973fxid90oWV/Fm7lz/RFmbG2Od7nmay4p3gwHOd7yBSkl6LfhUdnVXNo2b8F2LMJ/KXYn/2fTc8Hj5XTal/rLG/Q7zq95tgS90fWmZ7srI/IgqYWk6zmtvoa5GWwF7+YN7zfjfK2xC/TI13xrEedrTUxib2K28k89jXwtOQL5/FjDnRe8gZyHUKHLaxXoOsRf+2sj8gmJtBin6BykfbZg+aeoJ7RSxnUp8y3Vq8Vz0GWI/w9y88E80znPezp/MjHmV6rliM8H95DbEZ84N7pjEHPnqD2a/WHHBH5WD8CJFZ+R9kT5HyO1B/4XlPc5PdzGas2u8+cwSy/jdQfl7Vqz1F8/o3B88ylxE796qpe95n4ZfmtV3+k32Wt2nMUn39j8FoXezPqnaDHuWYXPit2xA9a8pvLbM1bf1+OzDOh/Fn9ra9mN/Gr4e9x333m3PjZAS/o+1ksoM1w97rX8xm8oOpnKw7QtmjuDbfHb33E5BHjp3526299jxw/+R7zmtZel0UzUj9vvWbynI+Eih3jSD1vstu15Mj4/A/r2cAC"
    },
    {
      type = "tilelayer",
      id = 12,
      name = "Decoratives (BG)",
      x = 0,
      y = 0,
      width = 80,
      height = 80,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtmG1uhDAMRPf+Z+jn3qK3K26FxA/QKmOPl7AvEuqKkvH4OQkJtxsNAhC4CoGPJZG35Xpfrvj9uVxfy1XV3PpVPkNH8brlFhxD4zvEippbv8jmn4zidcvsZ1FZNap8ufWrfIaO4vW+6bfO3/hb1dz6VT5DR/G6jrdY97b8q3y59at8hs5MXivzfqSlvBceab7S/xlXuWpv1yXHOzLn7vy9lffC+bPqc+icv+611a3fV4X9SM7aRESHvqsmiq57bXXoO2qi1tq9tjr0HTUJfoquq5bhJ5pD31GT8OrSDe0zNUdNIj+X7pnY4QUCEIAABCAAAQjMSEA5p86Yp8sz+9wcWeWcmot4rd6vck51VY356yKLLgQgAAEIQGAOAh1noY4YFbQVnx17qY4YFfwUnx1noY4YFfwUnx1noY4YFfwUn8qYHfXaEWPU097zs/jc8849CEAAAhCAAAQgAAEIQOCfgPJd4xnszupzlnOR4rODufJdo2r8jeSn+FSYj+amfNcYjXH0/Eh+ik+F+ZHXo/sjORxpqPdHxp/iU2Gu5vKMfgqTEZ9u/REvjmc75pfD91k0rz6/3JyvPr/c/NCHAARyBEb2YLlI1+zNGp6rK3uwHD/2YDl+zN8cP3pDAAIQgEA/AfbuOea8+3P82Lvn+LF3z/Fj/ub40RsCVyLwC1TMVwE="
    },
    {
      type = "tilelayer",
      id = 15,
      name = "Walls",
      x = 0,
      y = 0,
      width = 80,
      height = 80,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtm1uOXTUQRXsOPKYQiCANaoh45otXQIDEVEACPpD4Bgl++QfyhMwACK9pMBZqS72ifbdsH9/b54bbdCyVatsul8vbdc+xTydHR4/KIwb+ewb+qRDeKHmz5INT7fitapPNEyVPNrT6lvpn/ZerVQsxK77HSh4vGWFfRw9ngLJ7r+T7kh9Kfizx8nZVfE7iQKtvqX/Wv8+7BvYYncse9nX0cMYlO63vRsnN7Kw6/DFnao2XZDv1bfw3pj9Tk8fgXPawr6OHMyDWdys7qn6vBP6YM7XGS7Kd+jb+y82qxWNwLnvY19HDGSDry/afquHnEvhjztQaL8l26tv4LzerFo/h3fJ8veT9U+34nWrLdfiaHJfpRmmt73ZZ3Cm5WwJ/zK95EZ931K/ng5eWf+XK2sXzb+YdJi58TAtnjBrD2pf2Rra7yIx/5craxfNv5h2mtfmYFs4YnY8Pq5O6Y9rOqt2nY/ndd/7NvCOJY3TOOVT+Hkb+Lb0jxV8r57z9UPl7GPmXa8935K75N/tslf9dZMZ/a99pQ+f6VOc58JFhYvRxM+8wjfMxLVwmG0VjZp+txLWtnvHfetfRhvb1zeyJj5t5h8n/kt0GeVXRmNln67a8YT/jv7XXtKHlD05m9sTHEQv5qrpj+tHe57iGbRTZK5aZZyu+t9Uz/uFFvskBzpnSnDXhZGZP3CcxOxeO6ZdWbue3FL6jVNdGkb1iyZLPVn4v+jaD4JM5aUfTP+MfXpZ8wcnMnrhP+ZU4Z47pl5bvz0/l49KflXCPKLhRsPfG3v3g1TJ6reT1kmslnJPkQ+vq9Sd/Pf/4G/mCk/RZ0x/lnsO14kOcM8f0S8v3F6fySelPS0b88XsZ3T8U96WSp0qeLrlcou+BzDvqn/WPv5EvOEn+WnsC18Qo7Zw5dhv5/rrkq5IZ/hjr/hyrX3GflDxT8mzJlRLyZaZfNu7TMePxN5oLTmb2BK7lH/F5HdMvLf6+LfmmZC3+FPdxyXMlz5e8UkK+aM6lftl4vI4Zj7+Rr+TE/ThOn6ovxYCN9iZ/i7y/qmujMGbJNznxQo1+seRqCfmisUv9M/7xN/IlbuF5G5+yXbLHZmRXbjbKzBjZkBMvFX65pJd/vf5RTPiHl9Fc+84/zhl5ftGZQueJ815m8++8r3Nf8c/m377mP+9+yb+l35k/l4ThPbX6LlJh/TpjLP3N1TmE99QXjT/WL/5ulNxsJA93BeeP8+L1skd6Z5KGy/9Nk+ffrcaq7lVbiz/nMnHDzf+2yfMvF5n33+SpVddz9CIVzz9fd+v+2+Ir2+TvIhXyj+dZ3rP0bOO5lly16vJ3kQr5Bxd+53VM/5K+qPkHL84ZmLMh33G5ezHGNfmMpg9fqjs+77k6k3/YpIYb1zwH8nfvnDk+7/zN5Ak2qZ23JeycOU7+5Id8731zkE3uJfVWHK2+pTn099uZkr59bWBsUrdizbalODNGjZ+5C+VeUs/5VW/1Lc0xy1/Gv1TXN7FWPK24Z7jI+RizdBfKvaTeiqPVt3Tf2hd/eVdrxettvTi51/T4W7oLsYepfW4wNtSlFddojn3x5zHM4Facutcs8Ze85l3I31NLe9rLv9Ech8Sfx3m7Ks6F9wmTG96uMXdK7pZsexeXv17+VdeDknMcMn/OxYMFnAKtl9w6612I30cr/5bmOBT+luJs8ce6ef+r7lh13ut+pmdc6lb+YeN+He+bv1b8/PsSYnPtsTnelT/lVO/fZ/i8wq38w8Zjcbxv/ogpNXGl9tgc78qfcur+0dGXv5X8WvJLCX9vzLkPMf+IKXXGTt05c7wrf9q3P4uz70r+KPm9hL93MyeaPabu2mNx/LDzT7+layUem2OPzfGu/Gnf/jb+/ip8nvOvuLtfHN53zhw7Z4535W/f+Ufs/L6ou84+8jy1xlAYnzbU6U/tnDnGL9rHuZ1j2ew7/4hjtK7sg8/U8kXBb9pQpz+1r98xftE+zu0cY7utdt+cH0bfeGQ/Wlf2wWdq+dm1ELOv33H6xV7a7RznmNm6+9a9cubv3XDhY8HZB5+pZb9rYS5fv+P0K/uZ3MgYqTOfa+bwNvG39I1H9iO/2cddgfu4tP/tKO2dB8ceJ9j7HbM2tOxncoO9T818rt037Zpj9P0FO/xTdz3qcztw2jsPjrF37f2OWRtaY2Zyg71M7XOC3TdtmiOLf9fADv/UXWcfvxu/U/qdDHvslp69Ppdz5jjXoDEzubH0W2FuxUqhjTlol87vL9hmztAunX2qj+6U2Gt9rWcv3/R8DrBz5rhcbRTZz+YGvkdaMVPcDv6XvvGQMz4WnH2qXyp5quTpksslfqbHXuvLZ28r95lH2jlzXF0bRbbJXy833H8PK+azFHKm5T/7VD8peabk2ZIrJX6nxF7r82cv61sr/2ZzQ2viWdL7m7RiPkshZ1r8ZZ/qxyX8nwDx18u/jGnN/CNWz1PH9Euzp2jvE2aNqbFzv45ZX8+vz40v2Z6UvFDyYsnVkl7+VdeDQv7drZbe93WPzfEDJysA32vWRC5fL/+In8k8FseEA+/4c519qh+X9P7NP/bEtPTs9bk8NsfEuYb2vfa5R9hjcbxGPO5DMWQu+3yOW/F6v2Of46y4lX+tWNTGc/ODwpzXwDqzrV00J/k3mptYUhOb2oU5V64Zp/8ue7zRrndg6wymePwZxJpTOx/Zl3XmJP/W0vK7ZiFOafbY95E9U7/4yzMYsTh/vbXKR/I0sm3Z5/ht6/K5ZpE/RGsZ3QXyDEYc9wo4f701aZ7ka2Tbss/x29blc80Cd9Jay6WS3l1A/GVpncF4V/LuluY5kXyNbIlJz+gct2t9n/xpL09KeneB5O922d4puVvi+ed7kjjzJfuzjn2LZ9+fFs6zDntY4a5WPF7t6XEJd4H8/5msIePy/HJ/LZx507LxNuy9bRb7mcXxauSVI4+F/OvdBbD1WBzTP9LkE3pkq75Zu5Yfj83xvvgj/3p3AWL0WBzTP9LkE3pkq75Zu5Yfj83xmvyt6Ys1jM5B5BN6ZCt/2Akv2TI/2jlzvOaa1/RF3Fpz7xxEPqFHtvKHnTBcpmbe1M6Z4zXXvKYv4teae+egXPvI1jkThsvUzJvaOXO85prX9EX84uikpHUOyrWPbJ0z4eReOX6thHlTO2eOa8hBFuIXR8clrXNQcjCylT/shZP7ayv9+5dyfRAF/sip1jkoORjZOmfCcJmaeVN7zjk+CLIaQRA/OdU6B+XaR7bOmXByT515UztnjhuhP2oyBuDROXNspo/gGRj4F6zz/OY="
    },
    {
      type = "tilelayer",
      id = 3,
      name = "Platforms",
      x = 0,
      y = 0,
      width = 80,
      height = 80,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtXNty1DAM3TdKYYaFF2CAL+TS7X5Bv47hzvII9GPQodXMqeKbnDibdO0ZYVmWHflYUXxZer3ZbC6IXgm/BNqJHUgfhT4LfRP6KRRLIb1rUW45Ftj4TOiv0IsF0aXYshdCOgh9Efp+y0sWTCG9lmNTG/GMJ0GLjifcyqOf3j7+k+RfhX4I/bqVhbKQXsuxwUbMcctnhMZZImP84FeamFeZ5lynfMuxbeXBa8AvFNcUM85Deh2/8fGvVWxai/+F4hr7nfIhve5/N/6nGGlc0zLnXKd8x2/c+q/j1+Mfv2OlPGLzG6Gxe4fX0kfL7wfWqC19XLqvSs+l1VT7oZdVFuQbYY6Xil/e+uNrAL+90BL97/jo5C3o+OUxSml0/FLo5Os6fnmMUhrAr38/Ugil6zp+aXxytf39zSGUru/4pfHJ1Xb8cgil6zt+aXxytYrfW1F8J/RwRfQgNziqP2s0rt/SL/Zv74U+CJ2vhB6LnZ4zFc9ZxKX0/ciBwx/RLUmhs/FUO69+qi97L9Ryv67vJNtzkELJ/TO3sTz60MS8ymzOOsxbvZIy2rP9c+M3hS9YH8iN26uf6s/aPzd+PP/Mp2y2ddYHbL0te/Vtey6zzeCBX+h7d7bZXHG7Gn4rjfam4RS+YH3APGJQ9OoPOiCBtR/4hX6vI9+JK2pWxYbww5xx/KjpGH1oYl5lNmcd5q1eSRnt2f7W7y/OVDhN4QvWB7j/EO/VD/WhMmt/a/w891Y7NTKTWx/IqBf/5izXD+rZf8G3xM+7VtyXDEB0rA/kmnn1U/1ZX26JX8oOW7cVAfDDbzQvhMbetU7dfic2IcHn5op//x9Y+I/ih/kMfc+mun+t6Qf7KH03rC8vzf+WYg9Pu84tZPA/TeCXYq/auBR7FCPkaht4G/9qzos85zV4ZklSG5eOH3yO45+eF5WeGXnPa0qwg85a8LPxLza+mF4r/1gLfvA/TcyrTHOuY/7U8bPxT/GyeUzv1PGDL3H8s7hpOaZ36vjF4pripnlM79Tx41jGvOKmOdcxf+r4xeKa4qZ5TO9U8fOcI6X23q1+A72VidsLtZof9Yua3HOOlNtfYy/tue8stXfJ+JWOoUQP4+z4lSAV1lkSfmdiovd3Hi327mGkwlLgF7qvS42jxOaa99cbl1rFnjBSYanXZsTTkv8zUoNf2MK4tNW7E3/ifDUdv3FYd/w6fuMQGNe6+9868POuHbCuKFk/jBv9+NZz+F/N2mEJa54SdOfAr8QOqwO7Wuy37HPGlhW/mvtAXrtP/a6tDT+9DzyXCfFSi7tB4FcTM3lOlZ96btln1f9YFuPnPBuviZmxM6ySfVhszDm5B78Ddcb8Es8OydSmrAe/uc/Gmw58os49+MHnQneI3f/KJmPO+Fdm0fG1vP6nFsMXNXX/UyTSeY9/Q3y8/tfj310MPfj1+HcXO5Q8+HHMYx7xb6q9wlrOXRRJD36x+Ie9n3fPF9NvsRfUsbbIPfjB50LxL2aXVx/9rO1b7sEvFv9i+Hn17zt+8CdNzKvM5qzDvNXj8n32v1j84/Ez79VH2/uMH3yoxz/2EN/6xRvPvPrqf1OuhfQMtTa/i9awpH+/ZFgzlHAMY36oeSNhHeZj+pBPuRaKrZGmluPvl/wDprSUmA=="
    },
    {
      type = "tilelayer",
      id = 4,
      name = "Decoratives (FG)",
      x = 0,
      y = 0,
      width = 80,
      height = 80,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtmntu2zAMxrvnf90Vpr16jQW98J5ddpEuPU4/YibAMnJqyWJsxZ8AQi9SIn82Aonx1dXT8h7dv05krFWJXr+Vn7JOja8JdnsnMtaqJCwUuX4rP2WdBOnFV/G3x3IPp/+tzPED/Hlo4FNkbOpj5B61CNS3Wnu1i4xNfYzcQ+MordW3UjuvHxlbKx+9zy36rXzbKr8Wz4BrkAAJLEtAzv8fIB8H+YQ6dxeaqgfzTZWEaD9DvgxygzpBfEkYmKLn7bbQ35kgb03bNq2OjI/pWRu210Eg8oy0jghjvNAzKvnV8SW/Om5qpfy0z7qMAPmV8aI2CZAACZDAaQLXmL4z4rVl/gXk5SCvUFubb+h/H+QHal+es7f6OV07P7Ut64ho8f5LvL5YBtbW6/n+Owz8MZKbf43BN4O8RW1tfqL/a5DfqH0R3VP2Vj+na+enthMURbT4/fc6YWrLQPxgGSfAfMM4G86QAAmQAAmQwLkJ1Hy/dm4f17xfgnNyNrQiYyxlBHaDes05cey/Vf+NqvbH9Ms8vhzthFBy/63ad9q2x/Qvh0h5JDtjUvIOi26JvtmGzRkEDrB97vtTyYnYHEku71OSNyl1V328h2GP3+/anI/kSnJ5n8i8Se/8pr4vUe8H+U19Aqf1op7P6V3PN3vp8Z2PJHciARIggX4I5O7S1nveuS2N43bCkL97W609OiIJ4vVkjKWMgN61tS6zpnYPBORO7r9/8Hf5yHt7LSPrYy7XoOtG+56wkf/+Qcb0t0h/jzC0qpLgjfqYyzWos6K3RPm6xKYr2JP3w7qHcICZ5CjJj/zqCMyz4vs3j9+S1nJGGDsDLelXL3snODp2BuolBvoZT+AOW4j487qMRZ/T46OL30G/ofbndRmP/G+wNLLc76k++9K1tqifELT/PdW72hZ52Jin3At31sC0mccyMNgkARIgARIgARIggQACcg/Yyn1P838tMeo3oWu/77WIOYJfC796WYP85j0p8pvHj9YkQALHBDTvKXXuP6Zji/+5cK9r1/G5cp9Pz63Z65jmvKX2OdGxnLeMe127jrfz56scK2uja6menXsEXQXW1A=="
    },
    {
      type = "tilelayer",
      id = 6,
      name = "Foreground",
      x = 0,
      y = 0,
      width = 80,
      height = 80,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHt3P9KxDAMwPG9pJ6onPPHKb7/C5jIFUKXdIXlOpzfQbHXzab94B/NLThNXAgggAACCCCAAAIIIIAAAggggAACCCCAAAIIIIDAsQXuZHv30k5Be9i4/bX5bdytsXSpdbyMOVsEZ7n5KO3JtOdrX3++SdtyefPfKpau08bLWP/a3jXei7TZaa8yluEXzW9jZsSS5f76lXhZc+q80fUuNz6Cm18yvtWvNb8NmxFL57Pxsua066z7Fxn4rAevn78b94JfWQy35rcPZ8TS+Wy8rDntOukjgAACCCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggggMB+AnU9RHa9xX47GxPZ1kPYugvtb323PmYH+0aJ6jtG1Ebsu/Oc6LYews44ojbCxvurfVsPYfdAbYTVoI8AAggggAAC/10gyhlvXUt/FHcvZxxRS38kv1JDP8umtJEvCkLn5eWM5IudePKYlzOSL/b78SQCCCCAwLEFojzBvmMqfXKH5d+ClyfU75j0M7nD0k5HondLs9yzjdxBQJzLyxOcxyZyB0/FzxP8JxlFAAEE8gV6zmCcvWL3tTMYZ6/YTu+sncE4e7X9yhksqiXj7NX2K9/V9v4Plx+iPFnH"
    },
    {
      type = "objectgroup",
      id = 9,
      name = "Environment",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 32,
          width = 32,
          height = 336,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 368,
          width = 736,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 560,
          width = 560,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 560,
          width = 16,
          height = 208,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 368,
          width = 384,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 800,
          width = 192,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 800,
          width = 32,
          height = 144,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 912,
          width = 176,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 624,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 32,
          width = 32,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 160,
          width = 320,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 32,
          width = 32,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 0,
          width = 400,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 32,
          width = 32,
          height = 336,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 384,
          width = 16,
          height = 208,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 592,
          width = 208,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 608,
          width = 32,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 800,
          width = 224,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 752,
          width = 288,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1072,
          y = 400,
          width = 16,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1088,
          y = 512,
          width = 176,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 528,
          width = 16,
          height = 752,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 1248,
          width = 544,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 1136,
          width = 16,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 1136,
          width = 288,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 960,
          width = 16,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 960,
          width = 224,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 560,
          width = 16,
          height = 416,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 912,
          width = 32,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 976,
          width = 288,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 1264,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 448,
          width = 80,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 14,
      name = "MovingPlatform",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 1248,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "spaceship"
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 13,
      name = "Units",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 52,
          name = "Doctor",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 288,
          width = 80,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "Doctor",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 1168,
          width = 80,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "Doctor",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 288,
          width = 80,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 11,
      name = "Events",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {
        ["Enabled"] = true
      },
      objects = {
        {
          id = 59,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 1232,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 1184,
            ["Goal.y"] = 808,
            ["Target"] = 57,
            ["delayIn"] = 3,
            ["delayOut"] = 3,
            ["pause"] = 1,
            ["replay"] = false
          }
        },
        {
          id = 64,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 736,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 1184,
            ["Goal.y"] = 808,
            ["Target"] = 57,
            ["delayIn"] = 3,
            ["delayOut"] = 3,
            ["pause"] = 1,
            ["replay"] = false
          }
        },
        {
          id = 70,
          name = "Teleport",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 720,
          width = 64,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["exit"] = "left",
            ["map"] = "space00",
            ["method"] = "door"
          }
        }
      }
    }
  }
}
