return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.3.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 80,
  height = 100,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 14,
  nextobjectid = 162,
  properties = {},
  tilesets = {
    {
      name = "tiles_spaceship",
      firstgid = 1,
      filename = "tiles/tiles_spaceship.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 16,
      image = "tiles/tiles_spaceship.png",
      imagewidth = 256,
      imageheight = 224,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 224,
      tiles = {}
    },
    {
      name = "tiles_ui",
      firstgid = 225,
      filename = "tiles/tiles_ui.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 13,
      image = "tiles/tiles_ui.png",
      imagewidth = 208,
      imageheight = 128,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 104,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      id = 1,
      name = "Background",
      x = 0,
      y = 0,
      width = 80,
      height = 100,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHt0kERAAAMgzC0V/kmJA8McFk1ecAAAwwwwAADDDDAAAMMMMAAAwwwwAADDDDAAAMMMMAAAwwwwAADDDDAAAMMMMAAAwwwwAADDDDAAAMMMMAAAwwwwAADDDDAAAMMMMAAAwwwwAADDDDAAAMMMMAAAwwwwAADDDDAAAMMMMAAAwwwwAADDDDAAAMMMMAAAwwwwAADDDDAAAMMMMAAAwwwwAADDDDAAAMMMMAAA2/gAJyU32I="
    },
    {
      type = "tilelayer",
      id = 2,
      name = "Decoratives (BG)",
      x = 0,
      y = 0,
      width = 80,
      height = 100,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtnYmOHDUQhvPOyxVgN1E4xY1IkII4lnmLvB31w37wUyq73dOeK7MlWWWX7Tr+Lh/dmVVePHny5EWUn6K8fKirXZUQP1JCAJxuQv5BlC9S+TLajInq2VLL78/CY/yv+NaA0PlOKHo/Cn6Am9vfauuQ84kDjt9w5Et87TpE37sR3HtRaGMXLvk5E37D8RuOfImvXYfkmXBXQf/TqH8Y5aMoHz/Ig50t4Tcc3ODIl/jaddjSfxtI3UV5FuV5FNk9Z8q4EBc891ftXQT4e5Rfo/z2UP8j+P1DXXLNc5J+5d33UZS7X0Vx3Z9E+9MHWbCzJfe5WjseH3u8c61DYee4CS/J/jR5hd/r6Jeub6N8F+USyfHLaweciM/Hsn8pj8g9MHsTMvAEy4yf728/xvifLxG88Nkxoc7aEX6SER/94qzvfdch+5tsvIpyqfiRYz1OfC389lmH/oywHTCuIvmjvbN1/16lbM/BjsmaerVXkqcjrlS2Rub5GOnonfs+9ph19ixx9jHO013IJK/2SvJ0xNdZ+PXu3yN+jI6Rv6O53jtPORuIf991yHznORb6vo6Ob6KwzsU5v3QHUmGs78vIonszSddorivnyEHdQcBMuKooF/Gt4tE9hdhXdYf6IYrjBk7ZfrWvzHBGdmblevY5t2f4Kx1g1Movyf1+Kj/yviLZCBHDMXIdWy0+4u/IGMcPDJGJk5/V/ZR9ZRQ/dJ1Dro9gMzIGrIQB+FXrc82537KLLezIJjLxmbne8mG2HP8dv7w+tSeuOfdbPmJLOIEhMnHyc0aut3yYLcd/j0lYqrA+/UzeYh9b/qz2zXWdsb27n5/Dqu+itOYg3xLbMeZW+O2b67q/KG7dU6p7jMs1TqU1B3kMaRI2es+sOXlSB/jNyHXiad39KnlrDvJemD3838REPYNLI/YZOM8HjjzzfeIUPuBcPRvl+6VRxgXc4Lmf9qXFeSh/wUO8Oof83j/rDDxULKfQ6/jdhgN3UZ5FeR4FvKq7UHQ/UiDg+FH3O5dk3PvpF3+kfxAgx3qce/+54Zd95lvXMfdux2RN/RzyL/sLbvDc32rrLvgySqtf8lNR5dMsX7JucIPn/lb7Jhxq/dsKc2b5vAtFugfrHsc7h+5t91GQR/VfYo2xtuTPLCI2OLjBkS/x3vdm5s7yufcOAZ5uC9w8Ju/fUic2ODbgyJd473szc7f46XPJMfH8DsG7hY8nFrj8mUXEJr7m7prXRH4XrnTN8nmtnkP64vitubtWa6KnS32nohzXTF88Zuojd1fWgrhyz9+x0COOLtVPRfhzCF9Yhz1e3V0dv9cBjObzjrUWJ/as6jzdhTLJz5V4Nmt5tafwjrU21t55+iaU6Ux9m0hY5z1F+Ueero1V+JCD+TwVtpf4Ta6Hgecqe4qv/97cx77+O5qw7ZFjP1ofeTfs6er5s09fz1avD1u9Merr0dLcqn/k3bCah0z+UJ/FeaZwzlBfh16XXWjJB8ZVfGlu1T/ybljNQyY/qIvz/qJ9l/31Po3x8VWdZwrnPqJ2S390babKl5a9XVjjXCFOcclbc5C7HTntbccN/Tq3fMxSnWcKBz+1W/rlx1aq/GrZ4+6i85c4hY9Kaw5ytyOfvY2ufNb7elOddyyfS533fTj4qd3SLz+2Evadt+wJJ2GX4yTHxHMfuly/fPb2LtqMw4Y4+IEbmPjcVt3HtvTLj63Usq99mD58EZd86d2Q8czPXD67jBz1vPb1iz5xnQs+t1XXb/n4u5yW/hiymVr2hRMYZv+VF7wbVvMZX/VJJvK+nGduW+OeRsl/F+fzq7qesf4up+pDFt2bSbqWzvrKf94N8cX5WvyW1udt+HgX5VmU51Hc1pZ6qNpMsq94b6Loez/c/cr+K194N/Rx1Nfix3hx5d7S/oCdrTxMbSb5IL859+GVb/5uSM5o3C6K9nudAb7X3Jvc9YX4fznk+LEWevuD61L9lCT78p9zH559zG1illzYOW6cpToDkPv8EP+Nn3JN8rX7g+tS/ZQk+45F9q3V9jnknvia+wv4teLX38W17Lu8Nf8YcvkhLKoccB9z3fHLfUttxSXslvDTPrukS/2nJNkXFvmMWPK7h1+vj3hdfyt+HzNab+k6lFx+fR4F//yM4F5W8V9sDnPhp8RPPhyTiNk5+391nu7COcl9fK5fE37Vs+qdp29igs7UKie501w7fsKHHMznqbDVe6ru2q28u3b8ApqSuFvDt+BXGlghzLa9vULNUYdyt4a7z6qTd/DcT3uG0+iq+Az9h9BR+eoycIN7n9e3+OZ6DlXf4p/mas+D5KPuN/m84Kwghur+7d8BfD669+HYOxbfx8eROTnH8v0bvKrvACP6W2PAreqnbyav7MyQZfzw2e/fklXfCWfYr3Tgw0xe2Zkhq9Y0Oef8VRjL3wFm2K90ZNz4Zq3v+Hm/YexN9LW+e2rMoQj7+/Bj+XQXhvTNWt/xq+ctTLmLwXM8MeQqKMdNW/tJzn/6tAdxF4PTB78K8CJIxfs6iu8dvbpyr8rJPCeGXQUJv9aZRi45Hx17FeBFkKfCT98Dqu9Ul4b7qfDTtxa+qfg3l0f8/snpJRzAL3+nWpp3bv3KP//Nhu91VX3W/rcLu+QdeSh+LGrtHy2/JG/Naf1mozW+wjXLlnAg//Jvd5bmzepv2ec7t/slHFRac3LstNeOZ574uRO5n/cP4STsKnlrjsftdfDLul6Gfh9X1c8dv1n+VbFLpnfgXRQw57mIV/8GkfXEsKumu4ie/PO9QLno/3eBv3f4t4arBi+CVz7xDuzvd7zvVrj52fyI3397nOPC70f4DYlwpl8c+SHw096h/cTXxX20W/JT7iluG3xc5nX6xZWr6jsEOW7sy9pPWnL3EZ+yzNt69ktn42hcrpf7ta9Z1dnvnkadb64fRx1fR22NjnPMuKeRe+L5nuAx4FOWefsmdOhsbMWJjhF/XW91v9azIu9uo34X5VmU51HW2Inhw7SLkWAovHSuibfkHgM+ZZm3+RYMfuQHcaIjTC6S61WdfQ252vk7IP+Gs8bOoiM2oLVOW3J8hUsV9YpzNtIHbnDJRwkdFRd2lKp/jZ1RfzROuab8c7zuO/LsWwz9H345z3JMx9qX5NcxyHFjHW85P6r16ZjfRlDH2JcOjR0xOWYzzg/Wpbhyz3+3gE3xQ+9Lx8JvF4bAcOT8YH3C5afj4vi9jj6N43cLGvu2kGK+iTJr/SrXpLPa3/jdQnS/NaRYR+4W5BPnKHkHFyDSBX55f9O4V1Eu9f/1CddLUsxgoroKWIlr7bmMMZnHsPLewP4GzuKXRMS55v9xqNZevo86HmCCrSV+Sfixd+v8G/0/S6q1J4y4k1T4CJNKXsk09lKItci+pHiQiUs+crfweS1MKnkluxTs5CdYCScwRCZOfnK3qOJFxjzazmXL2726xl4KeczgV+1v3C16cbuuPE54ZFmrfSnYyU+PGfyq/Y27RStmyV1XHndJmKzxlZh9/RJ7dbfI56q3e38f9xdheWy8"
    },
    {
      type = "tilelayer",
      id = 7,
      name = "Walls",
      x = 0,
      y = 0,
      width = 80,
      height = 100,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtnFtyJUcRhrUHBrbgSwADMTZhbnoCjCGAFxakPXgJWGONDbMAnrQJInjyWshUzKf4lJHVXX26pTmMpyIqMqvyz0tl5anq0zoz311cXHz3BD1cvJPtKXKXPt7VRv5+Fwv8ffS/vqHJjzqYPwTmB9GfNRS7fwrZF9H/8oYmP9O34I39Y9jH92PScHPX8PHnGH25sX8e+B9G/1FDsQv9W2DgZ+gW/BbsjO8ZTCznroE9NX/Ul2uqq4FujdR81nnWMrEkrfgt2NQ3ns9R9WF/HR49U2yEi7uGjVPzh37nH1+JqfnIub9H/3X0y+hZy9jq8Fuwqb92rthX8rn+f0T/Kvp19K7dXFzcEidy7OzN31q8o/xdRkz/VlzEU/GZv1ls2pg9V/CX638Z/evoXYv525A/Wv7W4q35yLj92a+f+Yrfgk3ba/tJ3qCZv6ivtkU93kZd3kZ9Plr+1uKt+SDuEd2C77Br+1n9en84y32vw7PPJBo76IPDBrSbx1baWIu3WyO+O7oF32FZD/Endbydzzpnu+YTR1vSsazqW5b8Wrxr+tXeFnyH7e4z36PwvuOWYqg+jspfF2cXU/VfY63jLfgOu/U+rf5zbLvmU0arehWHfDS/du6t6SOvdOSv4nLcYbfep2t2q4+j8rd27hFX9c/8iG7Bd9it92kXh+2aTyyt6lUc8tH8nvrzZ79+5qu/LdiMmfPY95557pWlO8UxmD8yf3vqb8t3ii1Y9jyp123emBFvvPnE06puxSEfzbPP7OfoOaHT3/KdYguWmJPar3ljRrzx5hNPq7oVh3w0j3yNdvrOff0cVfwWrGOxHfPGjHjjzSeeVnUrDvloHvka3aq/Bd9hOS95V5nPe+Z5/luixsNzTj9V/rp1LMWMjHgZL1FjWd/M8x85mKU3C99/19ZJjMS3Vm/IR/fz0vyS7Fksdk2evtee/2ZzBm7m/cuW91/kZ42O7uel+SVZ96674slf1Msh7Xry/cvL8Db7/mstb8h97vuOfiyee+ix/GKfjWGdRzyvY+ucKeeUz9OtZ1Kuj8ZaZ/eL/KN3VDzYM+1se90dv5aL0dlpvzN8zd+MToc5Kp4ttkc+me9sMVfPSsbIZ+lR+cN/pbNxLOGqzdnxkk1yXOmSTicjf0k7+alzrPFUfev5TOm++3MHWVbPF9tLnvgqrbi18WPlb83vqfLuOwa2lmRgoN4T8r+Wc3RNnb9z4B1bxy/laCTr7p+l+6XDj+6oc8iZY+hy5jly5DWSC2TGJ1/POMYVx3jmO9/Nm+9wjv0ceNYwouSoew+IrOrWM45xxTFe+87n73DnkDPHwBpGlBx17wGRVV3qrdKKY7zlO4RjPweeNYwoOfL5z7mPrOpSb5VWHGPb5m7x3Q6ffs+tsYYRHeUo8SNZlw9yPvJT523b/Pchf75runuUOe6hmru6N9+3/G25T7vcLeUP/LnUIfGMqPe+YkayLfdptcnYts0jf9fzF89rbbtu3omSE1PnzDyY1vhbmiSmjnaxgxvJuD+4N/NONc8du3Sn2LZ5fL+lVLVuiamjXezglmSJsdw8+kvUePPotAt5S5PE1NEudnBLssRYbh79JWq8eXRIVY657/lbW97v8Nzx9VmUMfYYVzprHzuVEjsxZmzEhKzqgGUNXk/yM73TTb+1pe+l+/7zkCemfhdiTOyMK521j51KydGW779L66nrnx3HfXT3G+iKZ30vQ9D9DY781bpizHoZVzprHzuVOn+XsQb/Zh9Z1Vl7fqk5WBsvvT9I3+mvu+9fxzz5q3XFmNgZVzprHzuVkiPu1Lw7uTeRVZ3RekJ1c7suzzvVAOur8/+MiX9FJ3+1rhgTO+NKZ+1jp9JRjhI3kpFrP7OY5/lliRoPn/tWW7e+VwH6Jvq30ckfMdkndZA2luRZD26d/Zo3xqMcpXxJVuVrWPxBjTfvdSSfeNZOnjNH8M4RtrfSrfa5P9fuTd+R3MmOzes2b8yIN9585szN+saZN2YPb5vmq816hs6Oqx37MF9x3i+ebbw38KPnF+zZh3nke6ltmq926xk6O6527MN8xeX5MvsbKtde8rZlH+aN2cPbpvlqk8+7z9o1vjtn7MN89Zf5Gz2/ZY7Wnl+wZx/mke+ltml+r92Rvn2Yr/jM300mqmkzzy/Ysw/zyPdS2zS/1+5I3z7MV/xsvWeN12Zb9mHemD28bZrfY3NJ1z7ML+msyc49f6fetV439yn35ug5qHvmsZ2OP/f8nXrXeq1b7lPrzfLOoXVc4+aN2cPbpnnbPKL+ttyn9j3Ln3P+jqq/2ft0NmfGnXP+qL/uTsz7D7nXU/lOt3t+THtVlzFnaJ6d9Zw8JX+2x3cc212TZ1z+zJon5qTUn+fMr8mN3cN372uxd0r+2PdKsZnz+X+6/Cb6b6NfRn8WHXlS58y8MdjPOe8Je2W59Y7mu98r4SNCu2/MJfWazKeMfa8U/Zz/IPqH0T+K/nH0/DcvyNfsg8N+jrsasBydx6A+A+rnPEK7b/btnJlPDPteKfo5/yL6j6P/JPpPo++tv64G8I/ft0FjaffN/p0z84lh3ytFP+efR/9Z9J9H/1X0vfXX1QD+8fvUNJb1oNm/c2Y+Mex7pejn/Ivon0T/NPovou+tP2yb4t9zj8F3Z2/6qc2+nTPziWHfK0U/559H/yz6L6MfUX/YNsW/5x6Dz7Oj+z/OYvpBs2/nzPwDhUceuL6IH5qxWu7Yj+a7szd9nHtzff03/nb4n+jQjN/yo3Nme93Z+/+QP9cXeYNm/JZ7vU/Fv2v153Oe70VQnrmPzO2558/1Rd1Bu/pbelfF365PyZ/3xftw7vnz+UbeoJkHy3O89K5qT/5m799zy+cp9XfTLOJ1zO3N32X5vVLuV23Uqd91c350c8gqBZu1Xmuk82F8xkW3LnUHTYzlOc76q63+dgfbW+js/bt0ftS41sZRB7e5564h1jj6+3StEetevtl/aNqyHNuO61UMvon+bfRqO/F7e5h40JbOjwfAlcHXsdaXb/LX1UjIFn9fyLqqLvPQKqdO+L1OvieFr+9NsLGH1jRk/rrzo+KWxteRt6+i8//UdjXS+XgdRmuNVN261pHc35fMV/29Y+chbXX7x7tu9pGxqWXmc89rjeQe1TY6o6zLuZlnLc8QljsXzpl5Y47gvQ7b63x2c+hYZj7ltUZq/l4FZnRGWbd7hrCcWJI6BvPGHMGTP+9t7i/3oe/VOkcNrMVba6SrcWq2nlHW7b7DW+58OGfmjYFn7XV9Xjs8GNZO/tjHrZQYHKP5lGMTLNQ488irLnnPc4M877GNn/w8fLmxc06H2l1jH7dSYvD6zaccm2ChxplHvqQLZo9tbByRP/YR6r3mnsg9Rw4lBq/ffMordkYHzEh3Te4YzKNnekT+2Edo2udcyM8+n3fkUOJwjOZTXrEzOmBGumtyx2AePdMj8pf7zHvd4K/S/ui+q7jEOkbzKRvVkHHmvbaRLpiR3PbMo2d6RP5yn/leGfx9/i7jOdj/xqfDZSyO0XzKRjVknHmvbaQLZiS3PfPomR6Rv9xH8hf8Xf58Bvq+q7iMxTGaT9meGhnpsv6R3DGYR8/0iPzVuorz7irOvQc9zsOriiMOx2g+5V2N5NnKs1Ser8lzxmJzpLsmn7WNnSPyl/vounoWubqMHr9duYrfsFzFmXcVmOwPcMTgnJlPeVcjOZfn6NLvY6pud5/tsU3sR+Sv1lX8VuDqg1jfh9E/iv5x9Pz9QMURg3NmPuVd/eVcZx97UOt295nl1pmxDf6I/NW6yvp7EWusv1+pOGJwzsynfFQjnX3sQa2b+bss95nl1pmxDZ5znu+QPO92FAz3QYR013If+fwGf5X19zzm6u9XKo4YnDPzKR/VSGcfe1Drss5cF/Fbbp0Z2+ChNW7mTSsmQrlruY/kL/gr6u+TmP80Or9fqThs2675lKdO2HvwrjfnXkSv9rEH7XSR7bVtO8nXuKu8w4TaXct9vIzPRpzpt8Hf199nMe/fr1QcPuzbfMpTJ89OsMw9j7lq3xhwVdeYPbZtJ/kad5V3mFDb1fBh3+Z3GX+v/D4D7zPwPgPvM3D2GfgfGFvJAQ=="
    },
    {
      type = "tilelayer",
      id = 9,
      name = "UI",
      x = 0,
      y = 0,
      width = 80,
      height = 100,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHt19ENgCAMBUB0UkZzFMdxAf8tE5BQkcScSf9s0ctTtBQHAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECKwSuGLhe1LF7GPVfX21btjVfStlRsVsfuO2J79ULvmNZ6+9D/jx625DE/cP+ZM/+esK5E7w/PLLCeS65Y9fTiDXHf/4NTLYvjVer5h95q5ONwECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAj8UeABZJFuTQ=="
    },
    {
      type = "tilelayer",
      id = 4,
      name = "Platforms",
      x = 0,
      y = 0,
      width = 80,
      height = 100,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHt3dtu1DAQBuAtXBQQUgs3gOANoQdesirn9qoC+jAdt3U1qSbNjH9nba/+SFa9Xo/jfHG0u1l7e73ZbE7u00f5y+Q3OBWvt5L+S3rPFDL4Kl5vJCW/A0ncYgKHUp1+MTNdm35aI56nX9xMR9BPa8Tz9Iub6Qj6aY14nn5xMx2h/b7IEy8Lk25zlPyedPSZpOdAh7Uf3z/HIekXN9MR9NMa8Tz94mY6gn5aI56nn9/Meq2mn9/Pqkk/S8VfRj+/lVWTfpaKv4x+fiurJv0sFX8Z/Wwr672KVZN+loq/jH5+K6vmY780bntIVl+jZfn+XjQuUj/7fZYg5P5p6X1XK24/cgCN62a/I+nHsaRXjdNr2f9I93Gzn3S7i220eST0w4YN/eiHCWDRHH/0wwSwaI4/+mECWDTHH/0wASya46+O37U0k9Z/tF738Un6MOLn357Wf3zAhsRWo/P129Pn9tSnUTb6YWeKfvTzCqxxP5/jz6tv16Of7eItpZ9Xyq5HP9vFW0o/r5Rdj362i1WaX7/1ehv6WVL+sl79as4h8WvEa/bo904Oo9bvWKx9L6JHv/goaBdBP8y+xM+aM1VahvW+fXSJX/te99MD+t2di/zeLnpm6BcVm9an39Qj+oh+UbFpffpNPaKP6BcVm9an39Qj+oh+UbFp/ezX0/oP/VnGsxbkhRySjqmV9+w7+/Wy/kOvPxlhLUj206PyTB58k/RT0h/9RDCPttPTnJK5Q7f8LqTyd0m/JKV86Ya2M6rfuYD9kPRb0mUpnsSh7Yzkl+f/9TAHMM9BHGEuYL5+07nu8fef177/Dlxet6Hab6R5n+hx14qnHyZJP/phAlg0xx/99OffJY2a382n7/h34f8vpGuo1bYL1y/9sNFDP/phAlg0xx/md4WFQ9Frv37Umsf3VDst7zGs7Qed3AGC6YedJPrRDxPAojn+6IcJYNEcf/TDBLDoPP5K578s7b3WXJRe2/krAOn/h/Y4/0XPhek5/29mEKHzV2aafSheu/2HHTXKXMh+a8yDmev+2u3P7Xdb5ej8laV+rt3+0v5rPn8D9sp/zQ=="
    },
    {
      type = "tilelayer",
      id = 6,
      name = "Decoratives (MG)",
      x = 0,
      y = 0,
      width = 80,
      height = 100,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtnPtO6zAMhzlw4D94hVOurw/nxniRMR4HW8SSFTVd43R0XT9LkbPGPzv5Wq27ZDs7+7Jf4t4KLYU0u778Y5N6rc51SvO5h/pDdTuZ0KbQppprX/6xub22GysaGedzD/WnrjtyeoRBAAIQgAAEIACBSQjsJMvHJJnWmSTndy0Y7LVjTsSO5141azXP732tEBrWDb8GeCL1/NoyrVMNv7bzDj/4tRFoU3P9tfFDDQEIQAACEIAABCAAAQi0EZjj89A5arZRKqtvykMHG5mj5sEWQ2IIrJTAVtbN9zDxkw+/ODtVwg9+bQTa1Fx/bfxQQwACEIAABCAwDwH9Th+LE1giv2N63Qq/+LWnSvitj1/bilFDAAIQWB4Bvdfx+6P4eYNfnJ0q4Xea/Lq0rI14bTVmGvVdjTAQuxMNz38BcEkCvzi7qNL2Sv2XBNb25bI49WaWxx7jIQABCEBgeQS2MmX2jcXPG/zi7FQJvzZ+qCFwLAT0PcJQGzvPHxJ4ntpFjyiv4UNq3ptorOXyfT3WYjVz8HV+yoPL1K78QGV/X55XyeebT8/vQTwN+hCAwHcRuJVCd6ndVxTN/zu6No//z+Wh/1iumNIsoQ9S9TG1p4oZdBLrPzuvzeO1mguDAAQgcEgC+v0RFicAvzg7VZ4SvzHvV7uEy+716WHRabzF5l7HMAhAAAIQWC6BU7oHLvcsHOfMO5mW3fejM/Q5LJd5HcMgAAEIQAACEIAABCAwFwG/f+RZJvGS2m/xup8k/4zN9p2UvEiKtm9/TFHoBqyuOxTu+rX3JbFa5nMWqtF9J7Yn5Y/0/6b2Lx3P96VYbMmLrGj79scUhW7A6rpD4a5fe18Sq2U+Z9Gn4RgEIHD8BD4Bwf+uDw=="
    },
    {
      type = "tilelayer",
      id = 8,
      name = "Foreground",
      x = 0,
      y = 0,
      width = 80,
      height = 100,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHt3Atqg0AQANDcrJ879ENbWvun979AZyELEthVswYVnzDE1BmrrymdFTqHg43AdgWu4tKvJ17+TeTfTqy5dPrY+1jjtV/axvkJECAwh8BdnOQ+4uEYj3OcdEfneI17fYp4jniJ+IiwjRdIfm8RXcR7BL9AmLB9Ru7XMf83XvlNwIvU74jcQ/7F/s+0ctkECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQGDTAmPnOZzeZP7fvNOve09g7wLn/k7t3c39EyBAgACBNQq0zuRZun5p09aZPEvXr8GvZSZP60yf1vql/Vpn8ixdv7RfmsmT5/CcM5NnznrPH5b+NPj+BAgQINAq4Hlhq+B66k/XeHl+a3o1w3X459Rf46XZrTnMcB22Sxn9NVoX73OY4RoYI7b+Gq+fboZrX6O831/j9bPOWS/267e+P/VvfMv6tqV2686uf38CtZ5L3zX8eSj1XGbnD9uljFLP1cUxfVcSqm+lnitV6bvqdulo6rlK/cXYvqtUr5cY9pdBgAABAvMLDPX2+vu6ea2319/X7dLRWm/fxXH9fVIqb7XePlXp78t26UjpeWquGtvf53yvBAhsT+Af2ltPIg=="
    },
    {
      type = "objectgroup",
      id = 10,
      name = "Text",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 9,
          name = "",
          type = "",
          shape = "text",
          x = 144,
          y = 688,
          width = 384,
          height = 32,
          rotation = 0,
          visible = true,
          text = "Game Controls",
          fontfamily = "Marksman",
          pixelsize = 27,
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "text",
          x = 352,
          y = 720,
          width = 144,
          height = 19,
          rotation = 0,
          visible = true,
          text = "Controller*",
          fontfamily = "Marksman",
          pixelsize = 21,
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "text",
          x = 160,
          y = 720,
          width = 144,
          height = 19,
          rotation = 0,
          visible = true,
          text = "Keyboard",
          fontfamily = "Marksman",
          pixelsize = 21,
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "text",
          x = 160,
          y = 736,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[W,A,S,D]",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "text",
          x = 160,
          y = 752,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[S] ",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "text",
          x = 224,
          y = 752,
          width = 96,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Crouch",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "text",
          x = 224,
          y = 736,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Move/Aim",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "text",
          x = 160,
          y = 768,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[SPACE]",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "text",
          x = 224,
          y = 768,
          width = 96,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Jump",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "text",
          x = 160,
          y = 784,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[K]",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "text",
          x = 224,
          y = 784,
          width = 96,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Shoot Weapon",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "text",
          x = 160,
          y = 800,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[L]",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "text",
          x = 224,
          y = 800,
          width = 96,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Hold for Lock",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "text",
          x = 160,
          y = 848,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[P]",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "text",
          x = 224,
          y = 848,
          width = 112,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Pause/unpause",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "text",
          x = 160,
          y = 832,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[TAB]",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 86,
          name = "",
          type = "",
          shape = "text",
          x = 1024,
          y = 1296,
          width = 192,
          height = 32,
          rotation = 0,
          visible = true,
          text = "Current Quest",
          fontfamily = "Marksman",
          pixelsize = 27,
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {}
        },
        {
          id = 98,
          name = "",
          type = "",
          shape = "text",
          x = 160,
          y = 880,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          text = "[SPACE]",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 99,
          name = "",
          type = "",
          shape = "text",
          x = 224,
          y = 880,
          width = 96,
          height = 35,
          rotation = 0,
          visible = true,
          text = "- Skip Cutscene",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 100,
          name = "",
          type = "",
          shape = "text",
          x = 224,
          y = 832,
          width = 144,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Teleport",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 101,
          name = "",
          type = "",
          shape = "text",
          x = 160,
          y = 864,
          width = 144,
          height = 32,
          rotation = 0,
          visible = true,
          text = "Cutscenes",
          fontfamily = "Marksman",
          pixelsize = 21,
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {}
        },
        {
          id = 104,
          name = "",
          type = "",
          shape = "text",
          x = 416,
          y = 736,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Move/Aim",
          fontfamily = "Marksman",
          pixelsize = 15,
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 105,
          name = "",
          type = "",
          shape = "text",
          x = 352,
          y = 736,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "D-Pad",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 106,
          name = "",
          type = "",
          shape = "text",
          x = 352,
          y = 752,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[Down] ",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 107,
          name = "",
          type = "",
          shape = "text",
          x = 416,
          y = 752,
          width = 96,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Crouch",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 108,
          name = "",
          type = "",
          shape = "text",
          x = 352,
          y = 768,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[B]",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 109,
          name = "",
          type = "",
          shape = "text",
          x = 416,
          y = 768,
          width = 96,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Jump",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 110,
          name = "",
          type = "",
          shape = "text",
          x = 352,
          y = 784,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[A]",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 111,
          name = "",
          type = "",
          shape = "text",
          x = 416,
          y = 784,
          width = 96,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Shoot Weapon",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 112,
          name = "",
          type = "",
          shape = "text",
          x = 352,
          y = 800,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[L-Trigger]",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 113,
          name = "",
          type = "",
          shape = "text",
          x = 416,
          y = 800,
          width = 96,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Hold for Lock",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 114,
          name = "",
          type = "",
          shape = "text",
          x = 352,
          y = 848,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[Start]",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 115,
          name = "",
          type = "",
          shape = "text",
          x = 416,
          y = 848,
          width = 112,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Pause/unpause",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 116,
          name = "",
          type = "",
          shape = "text",
          x = 352,
          y = 832,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[Select]",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 117,
          name = "",
          type = "",
          shape = "text",
          x = 416,
          y = 832,
          width = 112,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Teleport",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 118,
          name = "",
          type = "",
          shape = "text",
          x = 352,
          y = 816,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[R-Trigger]",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 119,
          name = "",
          type = "",
          shape = "text",
          x = 416,
          y = 816,
          width = 96,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Swap Weapons",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 120,
          name = "",
          type = "",
          shape = "text",
          x = 160,
          y = 816,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[1] / [2]",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 121,
          name = "",
          type = "",
          shape = "text",
          x = 224,
          y = 816,
          width = 96,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Swap Weapons",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 122,
          name = "",
          type = "",
          shape = "text",
          x = 352,
          y = 880,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          text = "[A] / [B]",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 123,
          name = "",
          type = "",
          shape = "text",
          x = 416,
          y = 880,
          width = 96,
          height = 35,
          rotation = 0,
          visible = true,
          text = "- Skip Cutscene",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 124,
          name = "",
          type = "",
          shape = "text",
          x = 352,
          y = 864,
          width = 144,
          height = 32,
          rotation = 0,
          visible = true,
          text = "Cutscenes",
          fontfamily = "Marksman",
          pixelsize = 21,
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {}
        },
        {
          id = 151,
          name = "",
          type = "",
          shape = "text",
          x = 48,
          y = 48,
          width = 192,
          height = 32,
          rotation = 0,
          visible = true,
          text = "Congrats!",
          fontfamily = "Marksman",
          pixelsize = 29,
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {}
        },
        {
          id = 153,
          name = "",
          type = "",
          shape = "text",
          x = 48,
          y = 80,
          width = 192,
          height = 48,
          rotation = 0,
          visible = true,
          text = "Your Parkour Skills Truly Impressive.",
          fontfamily = "Marksman",
          pixelsize = 24,
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 3,
      name = "Environment",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 1376,
          width = 416,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 1520,
          width = 1248,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 1184,
          width = 16,
          height = 336,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 1168,
          width = 592,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 1264,
          width = 16,
          height = 112,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 1072,
          width = 608,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 672,
          width = 16,
          height = 400,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 656,
          width = 528,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 432,
          width = 16,
          height = 448,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 1088,
          width = 16,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 32,
          width = 16,
          height = 1488,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 1072,
          width = 368,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 928,
          y = 1264,
          width = 320,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 87,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 864,
          width = 304,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 16,
          width = 1216,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 90,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 944,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1168,
          y = 816,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "",
          type = "",
          shape = "rectangle",
          x = 912,
          y = 720,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 125,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 912,
          width = 304,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 133,
          name = "",
          type = "",
          shape = "rectangle",
          x = 848,
          y = 416,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 134,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1088,
          y = 368,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 139,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1168,
          y = 256,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 140,
          name = "",
          type = "",
          shape = "rectangle",
          x = 976,
          y = 160,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 149,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 432,
          width = 528,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 150,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 32,
          width = 16,
          height = 416,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 154,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 432,
          width = 16,
          height = 448,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 155,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 160,
          width = 224,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 160,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 1264,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 161,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 1088,
          width = 16,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 13,
      name = "Units",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 57,
          name = "Engineer",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 1440,
          width = 80,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["title"] = "Engineer Keith"
          }
        },
        {
          id = 61,
          name = "Engineer",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 992,
          width = 80,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["title"] = "Engineer Pete"
          }
        },
        {
          id = 85,
          name = "Doctor",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 1296,
          width = 80,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 12,
      name = "MovingPlatform",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 1504,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "spaceship"
          }
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 1360,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "spaceship"
          }
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 1248,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "spaceship"
          }
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 1392,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "spaceship"
          }
        },
        {
          id = 76,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 1056,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "spaceship"
          }
        },
        {
          id = 127,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 576,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "half"
          }
        },
        {
          id = 128,
          name = "",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 624,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "half"
          }
        },
        {
          id = 146,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 128,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "half"
          }
        },
        {
          id = 148,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 288,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "half"
          }
        },
        {
          id = 157,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 128,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "half"
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 5,
      name = "Events",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 63,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 1232,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 1184,
            ["Goal.y"] = 1080,
            ["Target"] = 52,
            ["auto"] = true,
            ["delay"] = 1,
            ["delayIn"] = 2,
            ["delayOut"] = 2,
            ["pause"] = 1
          }
        },
        {
          id = 64,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 1344,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 688,
            ["Goal.y"] = 1080,
            ["Target"] = 45,
            ["auto"] = true,
            ["delay"] = 2,
            ["delayIn"] = 2,
            ["delayOut"] = 2,
            ["pause"] = 2
          }
        },
        {
          id = 66,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 1488,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 288,
            ["Goal.y"] = 1384,
            ["Target"] = 10,
            ["auto"] = true,
            ["delay"] = 1,
            ["delayIn"] = 2,
            ["delayOut"] = 2,
            ["pause"] = 1
          }
        },
        {
          id = 68,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 1376,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 864,
            ["Goal.y"] = 1272,
            ["Target"] = 67,
            ["auto"] = true,
            ["delay"] = 1,
            ["delayIn"] = 2,
            ["delayOut"] = 2,
            ["pause"] = 1
          }
        },
        {
          id = 77,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 1040,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 112,
            ["Goal.y"] = 920,
            ["Target"] = 76,
            ["auto"] = true,
            ["delay"] = 2,
            ["delayIn"] = 2,
            ["delayOut"] = 2,
            ["pause"] = 2
          }
        },
        {
          id = 129,
          name = "Teleport",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 816,
          width = 304,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "space01",
            ["method"] = "beam",
            ["onTouch"] = true,
            ["section"] = "A"
          }
        },
        {
          id = 131,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 416,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 792,
            ["Goal.y"] = 760,
            ["Target"] = 127,
            ["auto"] = true,
            ["delay"] = 1,
            ["delayIn"] = 2,
            ["delayOut"] = 2,
            ["pause"] = 1
          }
        },
        {
          id = 132,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 656,
          y = 416,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 680,
            ["Goal.y"] = 456,
            ["Target"] = 128,
            ["auto"] = true,
            ["delay"] = 1,
            ["delayIn"] = 2,
            ["delayOut"] = 2,
            ["pause"] = 1
          }
        },
        {
          id = 138,
          name = "Teleport",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 368,
          width = 544,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "space01",
            ["method"] = "beam",
            ["onTouch"] = true,
            ["section"] = "A"
          }
        },
        {
          id = 143,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 48,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 792,
            ["Goal.y"] = 296,
            ["Target"] = 146,
            ["auto"] = true,
            ["delay"] = 1,
            ["delayIn"] = 1.5,
            ["delayOut"] = 1.5,
            ["pause"] = 1
          }
        },
        {
          id = 144,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 48,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 616,
            ["Goal.y"] = 136,
            ["Target"] = 148,
            ["auto"] = true,
            ["delay"] = 1,
            ["delayIn"] = 1.5,
            ["delayOut"] = 1.5,
            ["pause"] = 1
          }
        },
        {
          id = 156,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 48,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 424,
            ["Goal.y"] = 296,
            ["Target"] = 157,
            ["auto"] = true,
            ["delay"] = 1,
            ["delayIn"] = 1.5,
            ["delayOut"] = 1.5,
            ["pause"] = 1
          }
        },
        {
          id = 158,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 112,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "shells",
            ["value"] = "md"
          }
        },
        {
          id = 159,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 112,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["category"] = "ammo",
            ["name"] = "bullets",
            ["value"] = "md"
          }
        }
      }
    }
  }
}
