return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.3.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 80,
  height = 60,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 14,
  nextobjectid = 71,
  properties = {},
  tilesets = {
    {
      name = "tiles_spaceship",
      firstgid = 1,
      filename = "tiles/tiles_spaceship.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 16,
      image = "tiles/tiles_spaceship.png",
      imagewidth = 256,
      imageheight = 224,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 224,
      tiles = {}
    },
    {
      name = "tiles_ui",
      firstgid = 225,
      filename = "tiles/tiles_ui.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 13,
      image = "tiles/tiles_ui.png",
      imagewidth = 208,
      imageheight = 128,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 104,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      id = 1,
      name = "Background",
      x = 0,
      y = 0,
      width = 80,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztw0ENAAAMA6HTXuVzsRckrJqqqqqqqqqqqqqqqqqqqqqqqqo+PYQqhgg="
    },
    {
      type = "tilelayer",
      id = 2,
      name = "Decoratives (BG)",
      x = 0,
      y = 0,
      width = 80,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztW4lu2zAM1T/vvoes3obuRroBKdod+Yv93SQgBDiGFEkdrq8HEI6NSCKfJYqipRCWg12B7KNcFZbdTcSGVnqUtHsvyuMo74i8d+hdarP2TuF6YPTDcpf83Y/yKJzzNhjL03Z/RrmJcnv6/SvKb6dO8E7hOqDnUv0tUMLfgygP0f2ArgdDedoutuvm9PuPUyd4p3Ad0HOp/haQ9PkQ5WPgx+f+JPDfJ1GeRnkW5bnBVtoutukvstfjH+CdwnVAz6X6W0DS50uUr8E2Pl9EeRnlVZTXip0cf0dkI/QTzJ/XP9D/SvW3gNQ+7l94fKbnidvkVy5JmTdRLgx20na18ev1DzB+LpX6WyDHH3BI9U994lOUz0JZL3+t/QOMH0k/rEctdkGf6zn9v0X5Iejl5c/rH6xjWJMWAL3p/J/TP3H6PbTjz+sfpsgfnf+59kB/bS6s4c/iH3rwUArQm87/ms45jqz8gY/z+ocp8uft+y35kzAn/rxzXC1/eI6VAOvUOfDnneNa9D/Nfu+YuAsuU5tvUft4jsjJdZgmf2NzWKpjad/k+GuRf8nx1zP/oiHpo8XX3nVqIPct8i85/nqu3zRgPnIxNv6flz8pP9KKv575Fw2YDy3G9vCHcQz+/Ejv+lsB86HF2KX8lYyvOY5fTUr58+rTW1oi1ZfiGy0XzMXfOA+Ay9bqM6b0Au1jXI5GygPUIFfHnPkDwfF3uufyAL0wJ/64Mc0JlyfsBWo7+JPkP6R8mxaTjaXrFN4pbQf8SfIfkg/XYrK1QHpXyZ/k8uRaTLYWJFut60zoexYftBZAf7L6EM9ekzVg468OG3912PirQ7IV79lYC39SbvgY+JzTMVNG2rNRk9+eOqTcEuQ58XMQb766Jr89dUi5YbCXe+7NV98K/7fs4V4LJPvTGljyBdx6d638SUhrYGn84j3cUm5z7UgcwBoYr+9gvat9P1w7pJhlH873adJ9dL34k+IBa5wwJjwxH7dPuAckf2KNE6hdVCznm6zAZSC+lvwd9w2nB6T4wRpXULuoWM43WYHr5eLr9K6g33F7qHpAigek517+LOebrOD6Nr2neUC8T7gHeo/f3PmmWv4od3QOGcNXt5g/8H3J+YU5o3X/Kzm/MEeAPa3nj5LzC3ME2OGdP7hvMhJ/9PzCkgCxRavxazm/sCRYYwu6303qf8Bf7nzTkqDFFodwzqUUE3BxA7d3fU4AO2rPTmvfpXFbmswJ4Ltrzk5L+wNz8+9S+AOOas5O03Jr5a/07PTGnz222Pj7Hxx/3rPTVv6WCG78Uv9m3R+WOx/3D0db29w="
    },
    {
      type = "tilelayer",
      id = 7,
      name = "Walls",
      x = 0,
      y = 0,
      width = 80,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztW1tu1DAU9R5K2QIPQQHxENB2vuhQQICEuoBZSpbB50g8W0oXgAQUKEtA4mvWwolmLK5ur+3r2MlkMj7SUdLavk2OT+z4xjWmoGD5mIGPwD3wxeJIz8eLOpvgReE4U5Rr4s8y3UvblP7mM/AN+BZ8x8ofL+psgBeE40xRrom/6vq9Bz8I5fb+Uvynib/q+n0Uyk5MPv+F4q+6fhzH4GeTz3+h+EPS7xA8Aj+R+3sKPmHcJ3F95Zr4q6yfvffn5v+92/P9QDwNtfFzoWv9LF86znMxFD8Xin5pKPqloeiXhqJfGop+aSj6pWFo+mnzL7Suj7SNvc5Xma9Zq2EX+vH8i2v9UdO1jubHmD4Zgn6a/EtN1zqaH7U5saHop8m/UP+51tO2PKZPutCvfh74szBm5b5xyFeuzb9Q/7munfpP2ydd6Ff36za4A+6CI6PP74Xaa/MvMxaX9smYlcf0SRf61f16CbwMXgGvGn1+L9Q+Jr9D4x6YeZ+MzPk8ZEyfdOW/2+A18Dq4ZeL952tfUzO+0rgHc+1Ov4A8D952zq2J/26AN8Fb4EMT7z9fe61+NC6dQ/aFcm3MtrSj+ln/3AHvgvdMM/+52jfxn6a8L/pZ/9wHH5jm/nO1b+I/Tfmy9esbqL/s3GGP1H8urLt+1F9/MW/8Ae2R+s+FddeP+k/Sj/ovdmxYB/1i/Ff0O4/ivzQU/6Vh1fwn5SF5PlJDmrvk72gxuc5V85+Ux0hBvU7la4SYXCdtO1qsfe2xj/5rQz/uvyb5Z9f1r6v/YvPPruvvk//qn6U8EM8HaX5Pc0eS/zg0+Wcpf9on/7n+fug6QnUl/1Fo889S/rQv/uPfKzTzr/VASD/uv5T884jlT3P4z/fO4XuvoPppv7NK+b5Y/8XcI20r5U9z+M/3PkCB8XmCMWaC52Ri+89C+51VyvfF+i/mHruYf33vAxwYpydHgn7cV6Hvrcvwn688VT/pfcCFQ4X/6Ljg+7+jofgvFpL/7NyG86ouc813vN4Q/JeqX92Pdl25SfQbCfMdr1f8N+9Hq4v1lWu+4/X64L8msdv0H8a7ao8R42GVy3+h/TWx/msSm+qHOWGq1Y6uMy24r9CnFZ7dahfcATHmVRtzZvFfaH+N1Na3/6VJbKof3kmmxwoN+TrTgvsKfVqdgt/Bb+DXufey+S+0v0Zq69v/0iQ21Q/vxFPoMj3xaCitMy0k//0CX4M/wR8t+C+0P4a39e1/aRLb0pcz8eVFQv77TfQ7a8F/dH/MllCHt9Xsf4mJ7btmbR2LZfnPtz/G1TZUro2dU7+6z+pnY1vhP1ov1X++/TGutqFybeyc+hUUFBQUFDTBP+2upUs="
    },
    {
      type = "tilelayer",
      id = 4,
      name = "Platforms",
      x = 0,
      y = 0,
      width = 80,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztmstKxEAQRWvnA8HRjYr6hb79SPE56lKdj7GCE8jKdPrYSaW9By4MJJDqAx06NbUys6tOjoPk2vJZjVjjvufLcxgoN55b4G+MNTU17q2ftQtqLcHCfmrLZYw1tTXKXx7yx5A/hvwx5I8hfwz5Y8gfQ/4Y8seQP0Z0f6eW3xc5sf/t78B4f+SocI2R/c0B+WN0/Z17thKzMUWxAen6G9KrLf1emQvavwz5Y8gfQ/4Y8seQP4b8MVp/Zzbs/DxWUs7pmxM+u/V34bn0bAfKjqXtiWYNJeY0Ur4RSI/tzvPgefa8ZlzvI/Wdski8rwTE35vn0fOy/j30eh+1+7v3PHmWnveM633MyV8zKxdt/i+1fxzBX8T5vyHv8Aj+5nr+kz+G/DHkjyF/DOrvt++/Pj5M/sj/zJHn71PR/mXIH0P+GPLHqN0f7Q/30Zwhavb3F3NoUedJati/UyJ/DPljyB9D/hjyx5A/hvwxos+/RE/bP404/zKXfFoepedfaqf0/EvtlJ5/mRPfVPNzkg=="
    },
    {
      type = "tilelayer",
      id = 6,
      name = "Decoratives (MG)",
      x = 0,
      y = 0,
      width = 80,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt2mluwyAQhmG6/muuELpev2uSXqTLcTqWptJoCobaVAn1+0ifogRjY35EYE8IANDOh+Rz34Oo9CZ53/cgHOZvHuZvnp7mDwAAAADQlwvJxiR3DNKiZGeSOwYAAAD/j11L+zXz8P1e8qB5TPQ/khxrThLtm5Bfq09do9es/2vPM9dKstWsEm1PkmfNS6L/qeRMc55o37r4808RQ3n9X3uepRjecx7au9eeMH/z9Dh/a8ml5Epzrb+9mvj2Ett3/Yux9Dh/UXIjudXchZ//3b69xPaNjccLAMBf+N6vtdj7LVHUzxZ7PwAADkXN89yx59FLFyuO2QXWDwAAAOiLrR/x9S1+X1Cqbym1t9Byr2LvfexauZqgga158fUtvk6lVN9Sam8hVTszlb33sWvlaoIA9OkLiUBXOg=="
    },
    {
      type = "tilelayer",
      id = 9,
      name = "UI",
      x = 0,
      y = 0,
      width = 80,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt2sENwyAMhWHaSTNaRmGcLpB7fOzRjm1h4v+TuFXo6UkJFDIGgG5+Mq7gIXOe1XNGZZS5ju9njMhxJfQXnTMqY0J/k/5e319Yxqb9nfRHfw9yarJqfkN/9PckJ/3VyMn6WyRj0/7YPxfpT/5HHzLXjBwy54zI9q/q87sL+vOp+vzugv586M+H/nzozyd6n5WxxwIAAD1ZvtPI+E5kd5Z9crc9sAb9+Rj6a3eGp2HoL+wO8k2q9Of93nDV2ma4J0/tz3ves+rZoL+Q3PSXnzt1/fWeN646X6zS367YP/vQn4/lvcMdBgAAAAAAAACNG2klZvY="
    },
    {
      type = "tilelayer",
      id = 8,
      name = "Foreground",
      x = 0,
      y = 0,
      width = 80,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt2lsKwjAUhOHuzMsevKDi/YL734An6EMoyUnNQ4fo/8FQKARKn2YgXQcAAAAAAAC0ZWFZWlaJrIXf1Yq9ZWPZfrKLnmfhd7Ui/L+D5djLqeP/DXGxXBPvHx3/b4ib5Z54/8y8x9vEMk28n1nm434KAPyFfl//tqOrz6vFfb2mo6vPq8V9vaajq8+rxX29pqOrz6vFfb2mo6vPAwAAjKX13abW+m5Ta323qbW+29TYbUCedw+EvlDWvwcSh75QlrsHEkJfKMvdAwnoC2W5eyABfQEAgP9T2kbsI5+3jdhHZd42CmEf+bxtFLCPfN42CthHwO97AVYMSbA="
    },
    {
      type = "objectgroup",
      id = 10,
      name = "Text",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 9,
          name = "",
          type = "",
          shape = "text",
          x = 224,
          y = 64,
          width = 352,
          height = 19,
          rotation = 0,
          visible = true,
          text = "Game Controls",
          fontfamily = "Marksman",
          pixelsize = 27,
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "text",
          x = 416,
          y = 96,
          width = 144,
          height = 19,
          rotation = 0,
          visible = true,
          text = "Weapons",
          fontfamily = "Marksman",
          pixelsize = 21,
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "text",
          x = 240,
          y = 96,
          width = 144,
          height = 19,
          rotation = 0,
          visible = true,
          text = "Movement",
          fontfamily = "Marksman",
          pixelsize = 21,
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "text",
          x = 240,
          y = 112,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[W,A,S,D]",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "text",
          x = 240,
          y = 128,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[S] ",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "text",
          x = 240,
          y = 144,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[Space]",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "text",
          x = 304,
          y = 128,
          width = 96,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Crouch",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "text",
          x = 304,
          y = 112,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Move/Aim",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "text",
          x = 240,
          y = 144,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[Space]",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "text",
          x = 304,
          y = 144,
          width = 96,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Jump",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "text",
          x = 240,
          y = 160,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[K]",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "text",
          x = 304,
          y = 160,
          width = 96,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Shoot Weapon",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "text",
          x = 240,
          y = 176,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[L]",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "text",
          x = 304,
          y = 176,
          width = 96,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Hold for Lock",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "text",
          x = 240,
          y = 192,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[P]",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "text",
          x = 304,
          y = 192,
          width = 128,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Pause/unpause *",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "text",
          x = 240,
          y = 208,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[ESC]",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "text",
          x = 304,
          y = 208,
          width = 96,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Exit Game",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "text",
          x = 416,
          y = 112,
          width = 32,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[1]",
          fontfamily = "Marksman",
          pixelsize = 19,
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "text",
          x = 448,
          y = 112,
          width = 112,
          height = 19,
          rotation = 0,
          visible = true,
          text = "Pistol",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "text",
          x = 416,
          y = 160,
          width = 32,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[2]",
          fontfamily = "Marksman",
          pixelsize = 19,
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "text",
          x = 448,
          y = 160,
          width = 112,
          height = 19,
          rotation = 0,
          visible = true,
          text = "Shotgun",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "",
          shape = "text",
          x = 448,
          y = 128,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          text = "Weak, Med Range",
          fontfamily = "Marksman",
          pixelsize = 15,
          wrap = true,
          color = { 218, 220, 206 },
          valign = "center",
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "text",
          x = 448,
          y = 176,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          text = "Strong, Short Range",
          fontfamily = "Marksman",
          pixelsize = 15,
          wrap = true,
          color = { 218, 220, 206 },
          valign = "center",
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "text",
          x = 448,
          y = 144,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          text = "Ammo: Bullets",
          fontfamily = "Marksman",
          pixelsize = 15,
          wrap = true,
          color = { 218, 220, 206 },
          valign = "center",
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "text",
          x = 448,
          y = 192,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          text = "Ammo: Shells",
          fontfamily = "Marksman",
          pixelsize = 15,
          wrap = true,
          color = { 218, 220, 206 },
          valign = "center",
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "text",
          x = 256,
          y = 224,
          width = 288,
          height = 48,
          rotation = 0,
          visible = true,
          text = "Note: You are currently in the Pause Screen. Press [P] to go back to the level.",
          fontfamily = "Marksman",
          pixelsize = 15,
          wrap = true,
          color = { 218, 220, 206 },
          halign = "center",
          valign = "center",
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "text",
          x = 896,
          y = 48,
          width = 336,
          height = 35,
          rotation = 0,
          visible = true,
          text = "Credits",
          fontfamily = "Marksman",
          pixelsize = 27,
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "text",
          x = 80,
          y = 592,
          width = 240,
          height = 48,
          rotation = 0,
          visible = true,
          text = "Open doorways will transition you to another part of the level upon contact.",
          fontfamily = "Marksman",
          pixelsize = 19,
          wrap = true,
          color = { 254, 255, 139 },
          valign = "center",
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 3,
      name = "Environment",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 736,
          width = 160,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 880,
          width = 1216,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 544,
          width = 16,
          height = 336,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 528,
          width = 592,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 432,
          width = 32,
          height = 304,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 432,
          width = 592,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 32,
          width = 16,
          height = 400,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 16,
          width = 560,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 32,
          width = 16,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 448,
          width = 16,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 720,
          width = 256,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 32,
          width = 16,
          height = 848,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 784,
          y = 432,
          width = 336,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1008,
          y = 624,
          width = 240,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1008,
          y = 608,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 288,
          width = 176,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 13,
      name = "Units",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 57,
          name = "Doctor",
          type = "",
          shape = "rectangle",
          x = 1088,
          y = 800,
          width = 80,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "Doctor",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 352,
          width = 80,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "Doctor",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 352,
          width = 80,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "Doctor",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 352,
          width = 80,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 12,
      name = "MovingPlatform",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 768,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "spaceship"
          }
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 720,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "spaceship"
          }
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 608,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "spaceship"
          }
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 752,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "spaceship"
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 5,
      name = "Events",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 14,
          name = "Teleport",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 800,
          width = 64,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["exit"] = "left",
            ["map"] = "space00",
            ["method"] = "door"
          }
        },
        {
          id = 63,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 592,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 1184,
            ["Goal.y"] = 440,
            ["Target"] = 52,
            ["auto"] = true,
            ["delay"] = 1.5,
            ["delayIn"] = 2,
            ["delayOut"] = 2,
            ["pause"] = 1.5
          }
        },
        {
          id = 64,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 704,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 688,
            ["Goal.y"] = 440,
            ["Target"] = 45,
            ["auto"] = true,
            ["delay"] = 3,
            ["delayIn"] = 3,
            ["delayOut"] = 3,
            ["pause"] = 3
          }
        },
        {
          id = 66,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 752,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 288,
            ["Goal.y"] = 680,
            ["Target"] = 10,
            ["auto"] = true,
            ["delay"] = 1,
            ["delayIn"] = 2,
            ["delayOut"] = 2,
            ["pause"] = 1.5
          }
        },
        {
          id = 68,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 736,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 864,
            ["Goal.y"] = 584,
            ["Target"] = 67,
            ["auto"] = true,
            ["delay"] = 1,
            ["delayIn"] = 2,
            ["delayOut"] = 2,
            ["pause"] = 1
          }
        }
      }
    }
  }
}
