return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.3.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 80,
  height = 60,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 14,
  nextobjectid = 79,
  properties = {},
  tilesets = {
    {
      name = "tiles_spaceship",
      firstgid = 1,
      filename = "tiles/tiles_spaceship.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 16,
      image = "tiles/tiles_spaceship.png",
      imagewidth = 256,
      imageheight = 224,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 224,
      tiles = {}
    },
    {
      name = "tiles_ui",
      firstgid = 225,
      filename = "tiles/tiles_ui.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 13,
      image = "tiles/tiles_ui.png",
      imagewidth = 208,
      imageheight = 128,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 104,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      id = 1,
      name = "Background",
      x = 0,
      y = 0,
      width = 80,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHt0jERAAAMhDC0v/K66JQBA1xWTR4wwAADDDDAAAMMMMAAAwwwwAADDDDAAAMMMMAAAwwwwAADDDDAAAMMMMAAAwwwwAADDDDAAAMMMMAAAwwwwAADDDDAAAMMMMAAAwwwwAADDDDAAAMMMMAAAww8GTiEKoYI"
    },
    {
      type = "tilelayer",
      id = 2,
      name = "Decoratives (BG)",
      x = 0,
      y = 0,
      width = 80,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtm4tu3EYMRfPP21fa2An6Rt9F4wIt+nD3L/J35U1w2iuC1Eorae1d7wBjDjkcDnnFGY208rNnl1M+jVDm1l9izOsjxjHP2uhhdy5dw4+5c0p/F/WjqF+l+nXwU+yF2iS9KbbQ4ZpCf0u+ZV81bo3C/HPoezHxh1HxCdy+CNkUO/Lb9f4K/o+of0ZV+++o91Fd51CbawrFF/Gd/ehaXA75VfW/H7N+EJU+fBXVdUfe0VAZ6DhuwlHx/pN0OlvIuaZQfBLf2Y+uxYX5M/02LH8XlRwTJc+0RlQZ8zzaH0f9JOoLk9Ofaaj8N1Z9jtmb4InX5/b5sz3xXFMo+Inv7EfX4lL5ItmPUX+K6n7jUx5zE3q3UV9GfRUVnLMefKgM8NsHT4ysX1Hww143P3adum5nX34sLT6ntz2/8EVUcmG7i/pNVB/zWfCfR0Xf+7wdKoNx5Jv2PXD09Ys90Sn7g+bS+sG/zn6oLC4el7eFExhm/5UX30f9IaqPoY0+fKYxbDAu55nPrbFz9weN0TXu/MOfUFlcZEvXlBgqWvn/c4z5NSq+OJ2L36H1mfcHn2tJO9xfXDS/4tV61JkO6n5l/4XxXdS18ANvUeXeof3BfVvSjqkWF/Djvg+t/GJ/E37kTKUHHlWfZCreh74oa2Fsf/Cx2Htr9AH+aH75zX0fmn3MPDFnOfYqOTKFqbZyTXTu/oAdaJh4sCIfxrDAx0zHxoz1yY6KKPi9FRR/uv0h+1IMPZlIvijeKgeyn86PYTTWJxsqwu4QftonfM6uLXsPVeST4s33iM5X5GMYjfVpvAp24N9Jh39dZ2p7aGF7Tn59GRX//B5RnWWQ/W5jGAt9SPzkwykLMa9J5+KnZzU9d/hzwn3wx/oUQwelsz9Q2ohRDJwpyL2OcqaZi5/jVj2/zcUxQ9HZz3pb8PIdPHbR7s7Yrod+F7f89D7H7E30Ea/rzGnLvpfOvuts1Zbf4MHZGppjQg+a++Gzr/sQEKO/f8l6zmOroq6n9jH2s41jefkHHpytodl39KC5Hz77Qr7l9y9Zz3lsVdT11D7GfrZxLC//DuFBDOhBkWd6rC8al21twS/xL4+Vfzrf5HsG9wr8r87f/h7Ax+c55vDMdyo6x7c5ujnHbmLwbVTeQYNX9R5gzjxZF9yyXDx9a9JqnjVkGT989vO3ZNV7wjXmr2zgw5q0mmcNWbWmyTmndzFZfg+wxvyVjYwbv2npPX7eb9A9dCar5llDxvzH0DXmr2xkX9hP9B6/ut7ClLMYNNuo5rlEWY4bXvtJzn/6tAdxFoPSB71ErKqYFO/U50ztL8q9Kid971H7qRTh193TyCWnU3Wv+NXnmit+w8y45t8Qj7ncFb+5iA31hZ9/s+F7XdW+lPXbvRveBx7VOy3JuzHdNxudfoVrlg2v0uPjundLvEf1d1rCQbUbk2OHn6vPONHHXsgxfW8FZuAk7Cp5N8bj9jb4ZVuvw77rVe3Hjt9a/lWxS6Zn4H1UMNe10XUR1W8R3TjkofKky21ET/75XqBc9G+4/bnD3zU8afAieOURz8D+fMfzboWb35uv+P2/Rh0Xvh/hGxLhTL8o8i3w096h/cTXxX3wnZy9BBqqJyvM6fi4zNuOn3JVfVsUx419WftJJ3cf8SnLnNe1P3RvnBqX2+V87WtWbfa759HmneuLaOPr1Lmm6jlmfubo5B4DPmWZ87tw5ND/N0311e1W52tdK/LuJtq637yM+ioqvkZz1bIPa2ClNct5oJN7DPiUZc7zLpg8IT+IExtTgnK7arOvIRef3wPyG86ceab4gk63Tjs5vkJlh3ZFuTfSB25QyacWbFRU2FGr/jnzTPVHet19opNn32TDZTnPckyn2pfk1ylKl2ed3LHimrqsWp/efxNBnWJf2ho7YmLvy8+TnZxxUPlJW5R1Karc8+8WXG/rfSmm3rQQyz5mAasp9w/WJ1ROYkvU8dO5S3p8txDNiymKdRe1W6ed3LFSW0VUuSZa7W98txDdF1MU65SzBfnEfZS8gwoQxy/vb9K7i6rfbS+pKGYwUVsVrES19lyGTqahVp4b2N/AWfScCnEu/d/pfB51PMCEuQ7Rc8KPvVv3v2P/dxqsOJNU+AiTSl7Jzgk/1iL7uuJBJjr1bOHjOkwqeSU7V/zA0PEjPzlbVPEiYxy8U2Hi/Fj7HPFTPOA3drYYi/uK37scGTtbLMHvnPJqqq/kjHKP/AOj6mzBvaKiY/8f9y9HW9vc"
    },
    {
      type = "tilelayer",
      id = 7,
      name = "Walls",
      x = 0,
      y = 0,
      width = 80,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtmmmOHEUQhfsOLFfwItsDGtsyW/9iMwiQEAfwUfoY/ByJzePBPgASYLYjIPGLs/De4M+8jqmsrumqYnqsTikmojIiIyNeRmVV5fRisW97BC4egb8Vwrui90SfPuMpv68+27wierWDW7dJP8S/fYxtxDInrzF6ro9FX4m+Fn0jyvaBLmzzkujlDk6sffoh/u1nbCOWOXmN0XM5v29F31WlrsFvTP0N8X/Z8XvYgd2TwK+vvpx7n974bfJ/2fGr8H2vjseiqepvk/8XCb9jJftIdBL4fST5fqEPde28TX1611+2Lv+XGT9y/0RJghFyYgRW5+VD/SfGY+Tzxnce+xpXjv1MSq5Tpm8sT58p47fGtu01/ubgNaacI3NKOW3GyOkzZXzW2La9xt8cvMaUc2ROKafNGDl9pozPGtu21/ibg9eYco7MKeW0GSOnz5TxWWPb9hp/c/AaU86ROaWcNmPk9JkyPmts217jbw5eY8o5MqeU02aMnD5TxmeNbdtr/M3Ba0w5R+aUctqMkdNnyvissW17jb85eI0p58icUk6bMXL6TDl9clbjM6AWcSbkcfj5POT0N4ecGKZ/Ysm4Uj9WHuK/9R1d+8G578xtbLyt8buMX+ucp/b7m3DTmVsr/7H9u4wfdcY3H9+T5v6WRG/8Np25jcWpNX4b/Lhfck/KfWiT3rEMuX+ps1bs6I3fkDOxlp8x/dvgx7pXThzuf0v0tugd0VLk82r05kPww7/tc01YK/T1TEfmi3rmlnNPKXsuWvrty491r5zx7r8iuiq6Jrou8v9L0Jv3+ccO/77+QuQ1WYrqOWTF71g2j0QnYYvPqbmmeN7Sd19+rHvljHf/oeiG6Kbolmhs/Rm/5WLx9AcR+DE/+yPnbN4fkac4cyOvLq6pnrfU9+FHXVTOePcfiF4TvS56UzS2/sCIZ4fnYn7m7YsZmym5Qlhr6bsvFta9csa7/1B0W3RHdFc0tv7wnZz56euLGZspudJaa+m7LxbWvXLGu/9AdE/0hmiK+sN3cuanry9mbKbkSm2tpe9WLGsDZr7I+uLZAXes6FthZD5zyK15d6U/6+svPTf+FMGNB/pWvHNglj5b8+5KP/XlmMEN7j70jjfzat07aTOF7Hl3uVFfzhXc4O5D7xwSjz1+RuS/+mrht6+/f3Fq/aW+Wvih9/h9/Z1Fkfpq4Yd+V/DjGz3PITlj6epDVzm2/s6nRqiPrjnSHjvzHMu+B0/9ruBXv8Md15jm71RqBFw8x9Czzhy7fPbtC7c/9I4R/+YX9fyYA7+sIefmOYaeddaxiZFl9BJfWPyoEXI3fkPPOutYfMDR7wJ+jokzDs5+fNYBdfV16dLOZ0fUCDl31XjrrDPHsm96r+X8FL26Lrz+yM889w/6u/q6dNWOGsG24nes+VpnnTnW5398+9bzP6kuFL9cW68vz8N8rtY+aqDiXfGjRsCvq8ap2XrWmWO7zk/Rj8GP3Gt+mTsyNuTued1Y5/NyMEnMUrYen9jC0y5l9HUsuHvPAGd8O4ccl/5SThtk3w+t9wH7pT1ZLB48Fp2IqH90rON5OTFkjClbj09s4WmXMvq+sdjg23nQZ57+Uk4bZOPXeh+w32zapx9orzmDH+sIz7XmGeE1Rw8nhowxZeur7ZAx2LTGVr1zpM88Y0g5bZCN30M7GNi0X5/Bj3WE2zf7gu997nf0cGLIGFO2vtoOGYNNa2zVO3X6zDOGlNMG2fidt9X71+vMs03yyr5bz7tqtyneVg1lXimTl3lrLDbonT995ukv5bRBngI/rzPflZKf47d89s0E3l12m+Jt1VDmlTJ5mbfGYoNepheKn9cR/CSf4pd7YD7vqt0m/KgRcoYnZimjN2+NxaalT38pMy75HPWn/W6lfW+NtB+upqo/7628S3l/tcwem7lRX9mXcpd+qG/8GD89E47EBjW9xyy4Hxngdcy60v9qV0uRfruy0m9YVtrzVrIxrdkRQ65xytZ31Yj7vI/2/T6mju16no3xTezGT+8kR3o3OZLY2+p3Jsa1rvRbgdVT0c+in0Q/imQzWf15viuiq6Jrouui+vsE55f11fU8Sz14DPWNvfE7EXZ6Nz5SbR3psrOpRs98Z2JY68r195voS9Gvol9Espm0/g41+Q3RTdEtkeZcewY4v6wv47csz7PUg4f7hvjGnn2eb8j7Gt8ibHgeyPS0ec24fyWvXH9/iMDvd8nur3bEkPdsytZ7TK0t9x2I+H2M8as2dSx5OjfiH+Ob2OE1bvqTVxuFctq8ZuAnefV/1d9tzXtHdFe0qf4yD2THXce571C0yTc+4BUb+pNXG01z2ryOS90b2tOfSu6tv7TDd/pN2fq+Grknfev3Ma2xzNnSe74D0Sbf6cdyjbvqu2w0bFRjjpw75VHO94P3COwR2COwR2DnEfgHfQHecw=="
    },
    {
      type = "tilelayer",
      id = 9,
      name = "UI",
      x = 0,
      y = 0,
      width = 80,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHt2lFuwyAMxnG2k+ZoHIXj7AJ73xcp6gNNJWM70Kz/Sjy0wpn54QBZWwovBBD4zwI/GtxvctM16wyz7Nw9ectu+/4qJbPpmlP8snP35J2dg+ahefLw1Gt27p68s3O4sZ9r3vF7rF2V+ntYeNbzT/Wz7H+WPvi9Pkfgd7JBH2u3xcbS51PrrySdXRv7R2j/wO/1+meqUeovVH/F46dn5k1xe+2mNV2znSz36R8pZ8u+YKq9mc9N6RDOC+LnhDvCkv1c929sBGuj8Yv544dfTCAWTf3F/LLPXrPOXbFRE40AAggggAACdxDQuWJ/NjU19a13GNPMHEfOyeqLXzc5+HUgg28H/Pb/AVN/ne+AX8Wvw9Pbd/Eb2ceU89N+t2pvO/ws33VcWn8D83j6nYvi63N1XP8JfjFj/FL8Tu+J7rcb7cp7ROvXpuvvf8PVFN9iEr7oo/6W+/myXx814FfUt67P+L0ywC82HyPrzqo1JjZCohFAAAEEEEAAAQQQQAABBBBAAAEEEEBgtsAfl11m9g=="
    },
    {
      type = "tilelayer",
      id = 4,
      name = "Platforms",
      x = 0,
      y = 0,
      width = 80,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtWtlOxDAM3DcOIXG8AAK+kJuPRNzHI8fHMJGYFapI7MYbN7tyJKttYsczkyykab5ns9nlHzvCfQ92BRy15RuBHhwSxj3YF+ygI7sGlhtYbfHglDDuwlKu7VqgjeJ20G/CVls8OBGjR66xOhDb2Dj6e3AiRo9c5KW9EpvWf+jnwYkYPXIN+UnPxCb55do9OBGjR64cz1w9seXapXoPTsTokUviO2wntmG99tmDEzF65NLyph+x8Xns1YMTMXrkGsuf2MbG0d+DEzF65CIv7ZXYtP5DPw9OxOiRa8hPeiY2yS/X7sGJGD1y5Xjm6okt1y7Ve3AiRo9cEt9hO7EN67XPHpyI0SOXljf9ErYTWO0eyjFiW7/T96zfPvhb94MO0UfL0rN+LXkvqu/Qz6Zk6Cfrtw6XjYx9oL7X/VOZmY9H6e9wz/vPPurYssTvN/SzKWCLjvkX+tkUsEXH/Av9bArYojn/TtHNGSytE6WSW0u2qF+TwKC9tL61YNLkpn7nwHEB2+zItoBFs3+SOLQ4e6LZe6B+gDAvt7i7hz3BXue142+s/Wj31BIHjc7jGcgR/+n3hrAH2DMs3dcWaz/Lqt8dBHuEvcDea8VDnLWfZdIvnZW7/LXa/d5Fx2n3j9NvaOrfbxrrFn+DPfaPe9FvqjHE0JlK6GeSbxb6hX42BWzRMf+m1a/0/ichW4XvH9b5V/q+Ia0fVuH7h1U/aY6V2lPuZf/+FvqVRlhuC/1kjUoeoV9JHblt1fUrrQ80+8OSgmkNMdW7Zxq71v8/LOsDaf3Ads1esTQONe0e+tXgWpaY0M82UqFf6GdTwBYd8y/0sylgi475F/rZFLBFc/79Pf+ieSegj5Sdfqt65f5pj+dfejqLU8LymZlE1vMrmW7n1a37nyea6OYNeRdxDiYHv3X/ubxe9dbzKxLO1v1L+RfZ/gO+J3Iq"
    },
    {
      type = "tilelayer",
      id = 6,
      name = "Decoratives (MG)",
      x = 0,
      y = 0,
      width = 80,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtmlduwzAMQNP5116h6rx+05lepOM4IQEJYQw1lmQFpZtHgDAjiOv5h4q1WCAQgAAE+hH4llA//cLtNdKnRP/aa4b64PCrZ2Y94Gdp1Ntz4lffHR4QgAAEIAABCEAAAhCAAAQgAAF/BC6kpLeB+qvSb0VBSlsN1G+1VHZoBDz+/zyndwC/aW8LftP44Q2B/0bgSBo6jnqSaW7XPKrzaosM59yWGOrTml99T0XPop7rQqOMxXmXuFZtmkv7o8IOstfOuRWuW1s1zqGIfuf09u1/TuzhN+1teeN3Le3cRL2taO1K9n4YrY1jfTVWqXjjdyeF30d9KG1C9gXRldHaONZXYyEQgAAEIAAB7wTSec2eKb3X7Km+EIuxM4Cn+qgFAhCAAAQg0EIgzQe7fO3soDayIRA25q+WnR3URiAAAQhAAAIQgAAEIOCdgL0/8ijFLqM+yTOdD3r1MHY/piRPz5ps77ncKVd65s5Ueu8k3Ul5Fvsl6qtZF7OLjN2PKUmSai3ZO7bH9p7bm3KlZ+sdnVxs1iAAgb8jsAabpFSA"
    },
    {
      type = "tilelayer",
      id = 8,
      name = "Foreground",
      x = 0,
      y = 0,
      width = 80,
      height = 60,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHt2msKwjAQRtFu0gcqWt+4/w34BRIIsU0tg4xtb2CIbROTHv0xA2kaGgIIIIAAAggggAACCCCAAAIIIIAAAghMUWClTa8VmxjbKb6E456PWnun2CsOiouC9r1A8DspWsVZgZ8QRrSrxt7i+Kd6/Ebgaehd8YhTXtnneIsOAQQQQMBZwJqnes935musear3/H/ws+Sp1jzXOt/bz5qnes/39rPmqd7zvf1YHwEEEEAAAQSWI2Ct+5Yj1f2m1rqv+1uXc3fqdZv3L2Wt+7z3772+te7z3j/rI/BLgTI/SOcgUs95iLp+nh+EMxB5cB6ibhee5vlBq+s8OA8hkIGW5wflUM5DlCKf13l+UD7lPEQpwjUCCCCAAALzFxiqjUKNRH3U/z+o1UacF+93S09qtVGrQdRHSaq7r9VGYQb1UbdbulurjcIY6qMkRY/AfAXeICtFdw=="
    },
    {
      type = "objectgroup",
      id = 10,
      name = "Text",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 9,
          name = "",
          type = "",
          shape = "text",
          x = 144,
          y = 64,
          width = 352,
          height = 19,
          rotation = 0,
          visible = true,
          text = "Game Controls",
          fontfamily = "Marksman",
          pixelsize = 27,
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "text",
          x = 336,
          y = 96,
          width = 144,
          height = 19,
          rotation = 0,
          visible = true,
          text = "Weapons",
          fontfamily = "Marksman",
          pixelsize = 21,
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "text",
          x = 160,
          y = 96,
          width = 144,
          height = 19,
          rotation = 0,
          visible = true,
          text = "Movement",
          fontfamily = "Marksman",
          pixelsize = 21,
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "text",
          x = 160,
          y = 112,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[W,A,S,D]",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "text",
          x = 160,
          y = 128,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[S] ",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "text",
          x = 160,
          y = 144,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[Space]",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "text",
          x = 224,
          y = 128,
          width = 96,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Crouch",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "text",
          x = 224,
          y = 112,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Move/Aim",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "text",
          x = 160,
          y = 144,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[Space]",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "text",
          x = 224,
          y = 144,
          width = 96,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Jump",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "text",
          x = 160,
          y = 160,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[K]",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "text",
          x = 224,
          y = 160,
          width = 96,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Shoot Weapon",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "text",
          x = 160,
          y = 176,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[L]",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "text",
          x = 224,
          y = 176,
          width = 96,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Hold for Lock",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "text",
          x = 160,
          y = 192,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[P]",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "text",
          x = 224,
          y = 192,
          width = 128,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Pause/unpause *",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "text",
          x = 160,
          y = 208,
          width = 64,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[ESC]",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "text",
          x = 224,
          y = 208,
          width = 96,
          height = 19,
          rotation = 0,
          visible = true,
          text = "- Exit Game",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "text",
          x = 336,
          y = 112,
          width = 32,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[1]",
          fontfamily = "Marksman",
          pixelsize = 19,
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "text",
          x = 368,
          y = 112,
          width = 112,
          height = 19,
          rotation = 0,
          visible = true,
          text = "Pistol",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "text",
          x = 336,
          y = 160,
          width = 32,
          height = 19,
          rotation = 0,
          visible = true,
          text = "[2]",
          fontfamily = "Marksman",
          pixelsize = 19,
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "text",
          x = 368,
          y = 160,
          width = 112,
          height = 19,
          rotation = 0,
          visible = true,
          text = "Shotgun",
          fontfamily = "Marksman",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "",
          shape = "text",
          x = 368,
          y = 128,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          text = "Weak, Med Range",
          fontfamily = "Marksman",
          pixelsize = 15,
          wrap = true,
          color = { 218, 220, 206 },
          valign = "center",
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "text",
          x = 368,
          y = 176,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          text = "Strong, Short Range",
          fontfamily = "Marksman",
          pixelsize = 15,
          wrap = true,
          color = { 218, 220, 206 },
          valign = "center",
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "text",
          x = 368,
          y = 144,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          text = "Ammo: Bullets",
          fontfamily = "Marksman",
          pixelsize = 15,
          wrap = true,
          color = { 218, 220, 206 },
          valign = "center",
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "text",
          x = 368,
          y = 192,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          text = "Ammo: Shells",
          fontfamily = "Marksman",
          pixelsize = 15,
          wrap = true,
          color = { 218, 220, 206 },
          valign = "center",
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "text",
          x = 176,
          y = 224,
          width = 288,
          height = 48,
          rotation = 0,
          visible = true,
          text = "Note: You are currently in the Pause Screen. Press [P] to go back to the level.",
          fontfamily = "Marksman",
          pixelsize = 15,
          wrap = true,
          color = { 218, 220, 206 },
          halign = "center",
          valign = "center",
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "text",
          x = 816,
          y = 48,
          width = 336,
          height = 35,
          rotation = 0,
          visible = true,
          text = "Credits",
          fontfamily = "Marksman",
          pixelsize = 27,
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "text",
          x = 0,
          y = 592,
          width = 240,
          height = 48,
          rotation = 0,
          visible = true,
          text = "Open doorways will transition you to another part of the level upon contact.",
          fontfamily = "Marksman",
          pixelsize = 19,
          wrap = true,
          color = { 254, 255, 139 },
          valign = "center",
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 3,
      name = "Environment",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 736,
          width = 160,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 880,
          width = 896,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 544,
          width = 16,
          height = 336,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 528,
          width = 592,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 752,
          y = 432,
          width = 32,
          height = 304,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 432,
          width = 448,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 32,
          width = 16,
          height = 400,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 16,
          width = 560,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 592,
          y = 32,
          width = 16,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 448,
          width = 16,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 720,
          width = 256,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 32,
          width = 16,
          height = 848,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 784,
          y = 432,
          width = 336,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1008,
          y = 624,
          width = 240,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1008,
          y = 608,
          width = 112,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1136,
          y = 288,
          width = 112,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 448,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 432,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 13,
      name = "Units",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 57,
          name = "Doctor",
          type = "",
          shape = "rectangle",
          x = 1088,
          y = 800,
          width = 80,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "Doctor",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 352,
          width = 80,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "Engineer",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 352,
          width = 80,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 12,
      name = "MovingPlatform",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 880,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "spaceship"
          }
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 720,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "spaceship"
          }
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 608,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "spaceship"
          }
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 752,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "spaceship"
          }
        },
        {
          id = 76,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 432,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["area"] = "spaceship"
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 5,
      name = "Events",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 14,
          name = "Teleport",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 800,
          width = 64,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["exit"] = "left",
            ["map"] = "space00",
            ["method"] = "door"
          }
        },
        {
          id = 63,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 592,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 1184,
            ["Goal.y"] = 440,
            ["Target"] = 52,
            ["auto"] = true,
            ["delay"] = 1.5,
            ["delayIn"] = 2,
            ["delayOut"] = 2,
            ["pause"] = 1.5
          }
        },
        {
          id = 64,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 704,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 688,
            ["Goal.y"] = 440,
            ["Target"] = 45,
            ["auto"] = true,
            ["delay"] = 3,
            ["delayIn"] = 3,
            ["delayOut"] = 3,
            ["pause"] = 3
          }
        },
        {
          id = 66,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 864,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 288,
            ["Goal.y"] = 680,
            ["Target"] = 10,
            ["auto"] = true,
            ["delay"] = 1.5,
            ["delayIn"] = 2,
            ["delayOut"] = 2,
            ["pause"] = 1.5
          }
        },
        {
          id = 68,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 736,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 864,
            ["Goal.y"] = 584,
            ["Target"] = 67,
            ["auto"] = true,
            ["delay"] = 1,
            ["delayIn"] = 2,
            ["delayOut"] = 2,
            ["pause"] = 1
          }
        },
        {
          id = 77,
          name = "Boomarang",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 416,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["Goal.x"] = 112,
            ["Goal.y"] = 184,
            ["Target"] = 76,
            ["auto"] = true,
            ["delay"] = 3,
            ["delayIn"] = 3,
            ["delayOut"] = 3,
            ["pause"] = 3
          }
        }
      }
    }
  }
}
