return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.3.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 40,
  height = 30,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 13,
  nextobjectid = 12,
  properties = {},
  tilesets = {
    {
      name = "tiles_spaceship",
      firstgid = 1,
      filename = "tiles/tiles_spaceship.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 16,
      image = "tiles/tiles_spaceship.png",
      imagewidth = 256,
      imageheight = 224,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 224,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      id = 1,
      name = "Background",
      x = 0,
      y = 0,
      width = 40,
      height = 30,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHNl+lqxDAMhPed0/tcem3pXXpA37YzsB8IE2eVxCn9IWTL0mjWNuPsZrVabbZ2L78nOwz+SuP/Yrfisi87CH4Otw/hfMrmYMS9uxMW86z3ntf6d1o76sEcqqlhee9qa0PxoTruCr8VXkM1tV5Taow1VMddoSe5eOIZP6XGuI+yJxl7ZM8++f7Z6H+s8YnsNMRY2+Wn8ntVrzdZ5FXDOlfehexStotPuV7DLPPKedwfMOwdN/dO9iCLddfFPK7VxmDX1mtx84AjGPY/Mu/ps+xFVqvPxsHO5sc8+MX7dbbl9C7/3YjfVC2FX7xfa3Hy/n3JWvDrhGMtjfuSGZsb/Mj3/bqRmR/G2lhPfamlxO3Ri7HYLfLhgZYyj7zm3M0WHI3BOcWzgpd9jLfquTQO/JfsY+2MZxrPtU8voub+Bb9SO32O9O3TC/NHc8lbcv/Ke+U534H0jXrhGJq7BD/eHc4UDvbmhsV4HLsOzV2CH5id+kzR48gVrBibOwYTPZ6DB9YcjLIWTPS4XB8zB2tMza7clpgtseANJtpGfIoHa0ptrQZMtK2Wl4mDlcnN5iyBme2dyWvFj/vh/2J8K8e3L8OlzEHz0Gb7Mic75374v9haBiZvXxYn5qF5YLX47qy9fbFvdlxqns/6F3YCZEk="
    },
    {
      type = "tilelayer",
      id = 3,
      name = "Decoratives (BG)",
      x = 0,
      y = 0,
      width = 40,
      height = 30,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtlEkKwCAQBP3/G7L/Ir9L92FgruaSJtRAox6EstQZg8LAfwxsOsqirIrnu3IoKdW5zGnGMwVOHJ3p1rp4UxCvxlj36zGlypffXXeZwgcHBr404L9Kf35/A72n0J/nPdKf552xAwMYwAAGMJBm4AFonyVJ"
    },
    {
      type = "tilelayer",
      id = 4,
      name = "Walls",
      x = 0,
      y = 0,
      width = 40,
      height = 30,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtlUlOBDEMRfsODJcBesWMgA0H6DuABCy4AEiwZdkS83gAxmI6AhIrzsL70B9ZURV0VfcGUZa+7DiJ/eNyUo1GLf2owDtBBsAgWAQjoNmx7e+HJmQlEb8hMAzE7xW8dWx4thi3BXi3exkTspKIn+uT8oNTC65tAW7iWHlciRybxC/WDx4ZPDJxtb8fuhd+sX5wq/uvRDH/Uv8tfH3bz/6T3Y++07ugOFVF9ZsFev/ch1FrbqZLzId10db+qiJ+48DnTPUkc1rTDXTnvS7a8lUV7V0CV+Aa3IBRMAaaYAo4Z5HW+SaAekI62j4f7kqinP6G8ZvYnma+iJf9Ot8e2AcHIIrPF31lbOdQDdLz++xeU6Tn2HsIjnISm1/R3iK/Q3leOdY7WEavgW5ja+8xUP2iXDLIi+F+cC9Ip7VwnMhvA6ewAlZBjB1jprFcP7Z8yznWBYgxnEvvg/5Tsc/1fnhe2mKfcmyBTZDHTz3mf1+aU3ujnDA4BWcgXat8eg9vwR24BxnQu2Eu0hb7lGMHbIMifk1Ccc+zNGfZ+6X6PYBHsAuewG/1Uw7fWb2nsuPdNQfNRb/PJx3fvGjHNbJVv2dgfi/YP9XPvZXe37y+TXPFceQU7bhGdtn6qbd6eZ+dP3KKtuety9QParXUFagrUFfgX1XgA9QKX1E="
    },
    {
      type = "tilelayer",
      id = 5,
      name = "Platforms",
      x = 0,
      y = 0,
      width = 40,
      height = 30,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtWMsKAjEM3KtefFwUxC/07Rf5NeL7cfTxMU4PA6Hb2kawVmhgSIwTks5mdfVZVdUsIQboNQdoFwbwMma6i+AB9BNhgT5LgLZGsAUOwJlJ4c18LfH62yF0WOF6rdjHaLYDjoBPv1/Ot8Fce+AEXAHbctCPM+WoX9k/Xp04b98fZf/idCPL1q/sH5WJ87Z+ue1fG8cYAvgOiULqz+ce5oKG0Ug9H0aLMu5BmS9Krhqp6FeTRJUo+qnkqpH/Rb8RJh8DjcxwwzwdYAJMgWaGuGMml4WeeVw1Mqep13DZI/Sbjzyf19RruOwXeuYhz+c19Rou+5kz0WTMXMjLGhm76uT7MnZxmftkJ1hrvKZew2UPc453/zmQ5/Oa+hD3BTThlhI="
    },
    {
      type = "tilelayer",
      id = 6,
      name = "Decoratives (FG)",
      x = 0,
      y = 0,
      width = 40,
      height = 30,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtVUkOwjAMNOsNvgBfgRcBH2NfjnyC5TmMK7tKIxL11gjG0tTOeConk0NEGHSADqQceKDxTDUL4Lm/5iW8sHw3qaJW3F9R1/G3m7nh5IqTyP1oOCDPjFdjVvrpKK6Yq4hjDkL5NbABuoglhi4Sg3O9xC+kMw7wfcuY06JVun8tjkBJCwcmgWaLemfYB7xqzoaArkrnNfeAvmGA7D2U4nOci7Wq/xbTgMQ7I3hzKuD9qUM1F0NNWuG85iEwMoyRvYdSfI5zsVb1DDpAB37DgQ8OGC6i"
    },
    {
      type = "tilelayer",
      id = 7,
      name = "Foreground",
      x = 0,
      y = 0,
      width = 40,
      height = 30,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtkFkKgDAMBXtJF1TcF7z/BXwFfyX5MogTGApNaF4nJQoDGMAABjCAAQxgAAMY+JuBQh8uReWgDpDTa2cj2ge6+z6fs3i7cr5BjAaT+hH5Fu1dhVWHBiLybdq7W+HUP51zjqcYwQAGPm7gAj7pEAw="
    },
    {
      type = "objectgroup",
      id = 9,
      name = "Environment",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 352,
          width = 576,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 32,
          width = 16,
          height = 320,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 16,
          width = 416,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 32,
          width = 16,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 208,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 224,
          width = 16,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 11,
      name = "Events",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 10,
          name = "Teleport",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 272,
          width = 64,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["exit"] = "right",
            ["map"] = "space01",
            ["method"] = "door"
          }
        },
        {
          id = 11,
          name = "Pickup",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 272,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["item"] = "bullets_sm",
            ["value"] = 10
          }
        }
      }
    }
  }
}
