return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.3.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 40,
  height = 30,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 11,
  nextobjectid = 10,
  properties = {},
  tilesets = {
    {
      name = "tiles_spaceship",
      firstgid = 1,
      filename = "tiles/tiles_spaceship.tsx",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 16,
      image = "tiles/tiles_spaceship.png",
      imagewidth = 256,
      imageheight = 224,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 224,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      id = 1,
      name = "Background",
      x = 0,
      y = 0,
      width = 40,
      height = 30,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHNl+lqxDAMhPed0/tcem3pXXpA37YzsB8IE2eVxCn9IWTL0mjWNuPsZrVabbZ2L78nOwz+SuP/Yrfisi87CH4Otw/hfMrmYMS9uxMW86z3ntf6d1o76sEcqqlhee9qa0PxoTruCr8VXkM1tV5Taow1VMddoSe5eOIZP6XGuI+yJxl7ZM8++f7Z6H+s8YnsNMRY2+Wn8ntVrzdZ5FXDOlfehexStotPuV7DLPPKedwfMOwdN/dO9iCLddfFPK7VxmDX1mtx84AjGPY/Mu/ps+xFVqvPxsHO5sc8+MX7dbbl9C7/3YjfVC2FX7xfa3Hy/n3JWvDrhGMtjfuSGZsb/Mj3/bqRmR/G2lhPfamlxO3Ri7HYLfLhgZYyj7zm3M0WHI3BOcWzgpd9jLfquTQO/JfsY+2MZxrPtU8voub+Bb9SO32O9O3TC/NHc8lbcv/Ke+U534H0jXrhGJq7BD/eHc4UDvbmhsV4HLsOzV2CH5id+kzR48gVrBibOwYTPZ6DB9YcjLIWTPS4XB8zB2tMza7clpgtseANJtpGfIoHa0ptrQZMtK2Wl4mDlcnN5iyBme2dyWvFj/vh/2J8K8e3L8OlzEHz0Gb7Mic75374v9haBiZvXxYn5qF5YLX47qy9fbFvdlxqns/6F3YCZEk="
    },
    {
      type = "tilelayer",
      id = 3,
      name = "Decorative (BG)",
      x = 0,
      y = 0,
      width = 40,
      height = 30,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtlEkKwCAQBP3/G7L/Ir9L92FgruaSJtRAox6EstQZg8LAfwxsOsqirIrnu3IoKdW5zGnGMwVOHJ3p1rp4UxCvxlj36zGlypffXXeZwgcHBr404L9Kf35/A72n0J/nPdKf552xAwMYwAAGMJBm4AFonyVJ"
    },
    {
      type = "tilelayer",
      id = 4,
      name = "Walls",
      x = 0,
      y = 0,
      width = 40,
      height = 30,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtlUlOAzEQRbkDw2WArJgRsMkBcgeQgAUXAAm2LCMxjwdgbKYjILHiLLzf5KOSlUbpTjaILunJZbdd9V2xnaGh2gZRgU+CDMMIrMA4NDq+xwfRErKSSd8ojIH0vcNHx0dni35boLvdT5+QlUz6XJ9UH5paaG0LtElj5X4lcSySvlg/dGToyKTV44No+9EX64e2+vyVKOZfOn/L379tfv7kD+Lc6V1QnKqm+i2A3j+fw9jq23yPLIV50df6qiZ9U+B9pu0M3zSnF3TnPS/6GqtqWtuEG7iFO5iASWjALDhnUav9TYPOhNroe38MVzLl9G8YfxP7c3wv0uVx7e8ADuEIonl/cayM7xyqQbp/791zitpF1h7DSZfE1le0tmjcofxdOTY7rNJuQK+xtfYUVL9o13S6xfB58FlQq1rEejhO1LfFoFiDdYixY8wYR+tdP9wfu8S7ghjDufQ+6H8qnnO9H8JzcHNzXzl2YBu66Wsy7v++NKfWRjujcw4XkM5VPr2H9/AAj5CB3g1hPbi5ua8ce7ALRfoahOKeZ2nOsvdL9XuCZ9iHF1DthPXg5ua+cvjO6j2VH++uNehbHPd6tfHNi36cI1/1ewXre8P/rX4+W+n99blN4xf1o6bop/PL1k9nq5/32fmjpuj7u9sy9UNabXUF6grUFfhXFfgCdAZaAw=="
    },
    {
      type = "tilelayer",
      id = 5,
      name = "Platforms",
      x = 0,
      y = 0,
      width = 40,
      height = 30,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtV0kOwjAM7BUuLBeQEC9k50V9DWJfjiyPYXwYyUpTGiORFimWRnaNLU+mBtpXlmWLiBhh1hLQdlUXOpZ0H3gCw0hYYc4aoG0Q7IAjcGFSeeHXUde/DqFDjvuVc47otQdOgKud1NTNbwsOB+AM3ADX6uanNdMxedbNL+0f70SYd78faf/CdGOVq1/aPyoT5l39mrZ/XRxjDIT+58f+/RuAGzQMRmx+oBZk3IPEL0iuQlHSryCJKZH0M8lVKP4X/SZgPgVaDcMdfHrADJgD7QbiAU4+q3rm8fXonKXfUssZ8p7y6Z2PdWXe0m+p5byqZx7WlXlLv6WW8+RMNB0zV+V1j459ffpzHftqmftmJ9gr3tJvqeUMOUdT9u8NLmGWEg=="
    },
    {
      type = "tilelayer",
      id = 6,
      name = "Decorative (FG)",
      x = 0,
      y = 0,
      width = 40,
      height = 30,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtVUkOwjAMNOsNvgBfgRcBH2NfjnyC5TmMK7tKIxL11gjG0tTOeConk0NEGHSADqQceKDxTDUL4Lm/5iW8sHw3qaJW3F9R1/G3m7nh5IqTyP1oOCDPjFdjVvrpKK6Yq4hjDkL5NbABuoglhi4Sg3O9xC+kMw7wfcuY06JVun8tjkBJCwcmgWaLemfYB7xqzoaArkrnNfeAvmGA7D2U4nOci7Wq/xbTgMQ7I3hzKuD9qUM1F0NNWuG85iEwMoyRvYdSfI5zsVb1DDpAB37DgQ8OGC6i"
    },
    {
      type = "tilelayer",
      id = 7,
      name = "Foreground",
      x = 0,
      y = 0,
      width = 40,
      height = 30,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eAHtkFkKgDAMBXtJF1TcF7z/BXwFfyX5MogTGApNaF4nJQoDGMAABjCAAQxgAAMY+JuBQh8uReWgDpDTa2cj2ge6+z6fs3i7cr5BjAaT+hH5Fu1dhVWHBiLybdq7W+HUP51zjqcYwQAGPm7gAj7pEAw="
    },
    {
      type = "objectgroup",
      id = 9,
      name = "Environment",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 352,
          width = 576,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 32,
          width = 16,
          height = 320,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 16,
          width = 416,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 32,
          width = 16,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 208,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 224,
          width = 16,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
